File export
PKUHPC/SCOW pull request #1001
Opened 2023-11-24 03:42 UTC by ZihanChen821

2023-12-05 10:54 UTC, ddadaal requested changes

2023-12-05 10:54 UTC, ddadaal commented on protos/server/file.proto
> +service FileService {
换个名字，ExportService和rpc ExportData

2023-12-05 10:54 UTC, ddadaal commented on apps/mis-web/src/pageComponents/common/exportFileModal.tsx
> +    console.log("columns: ", columns);
console.log去掉一下

2023-12-05 10:54 UTC, ddadaal commented on protos/server/file.proto
> +  bytes chunk = 1;
现在这样设计，对API的调用者来说，返回的东西一律不知道是什么，但是实际上返回的也是一个一个的message。可以将整个rpc Export拆分成多个rpc，每个RPC返回一种固定的message，比如

```protobuf
message ExportUsersResponse {
  repeated ExportedUser users = 1;
}

rpc ExportUsers(ExportUsersRequest) returns (stream ExportUsersResponse);
```

这样每个API更清晰，调用的时候也有类型辅助。

2023-12-05 10:54 UTC, ddadaal commented on protos/server/file.proto
> +message ExportAccount {
ExportedAccount

2023-12-06 09:12 UTC, ZihanChen821 commented
还缺少 新增service Export 测试用例，明天补上

2023-12-10 13:39 UTC, ddadaal approved these changes

2023-12-14 03:23 UTC, lyl-available commented
导出中文乱码
![image](https://github.com/PKUHPC/SCOW/assets/125553919/cc65d2af-41e6-4957-bc9a-2805eeb59dd4)

2023-12-14 09:06 UTC, lyl-available commented
导出时若存在翻页，导出文件会少第一条数据
页面显示内容：
![image](https://github.com/PKUHPC/SCOW/assets/125553919/d49d9b4e-cafd-4178-97f5-86683edcca9a)
导出内容：
![image](https://github.com/PKUHPC/SCOW/assets/125553919/391625a1-326f-4627-973f-e367a05cd71a)

2023-12-18 02:00 UTC, ZihanChen821 commented
> 语言为中文时，导出乱码 ![image](https://private-user-images.githubusercontent.com/125553919/290390279-c87b0b9f-ab23-4735-8ba9-f1e177c2be5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjQ1MzQsIm5iZiI6MTcwMjg2NDIzNCwicGF0aCI6Ii8xMjU1NTM5MTkvMjkwMzkwMjc5LWM4N2IwYjlmLWFiMjMtNDczNS04YmE5LWYxZTE3N2MyYmU1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwMTUwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2ZjZjg2MjVmYTRkZjdlZWU1ZjlmZTVhMDEzYmI5NDFlNDQzMmRiMDNkMDM1NzM2NDNmODg5NWUzNGIxYzQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2wGd3dFTZVXDCUjGsvuhDiMTFeSsMzXqFOTWPT6GN-w) ![image](https://private-user-images.githubusercontent.com/125553919/290390186-cc65d2af-41e6-4957-bc9a-2805eeb59dd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjQ1MzQsIm5iZiI6MTcwMjg2NDIzNCwicGF0aCI6Ii8xMjU1NTM5MTkvMjkwMzkwMTg2LWNjNjVkMmFmLTQxZTYtNDk1Ny1iYzlhLTI4MDVlZWI1OWRkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwMTUwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzY4MzFiNDNiMThiZDE5Y2M2MjFkZTU5NzQ3M2MwNjUzNzQ1NDE1MTM0OWYyYjFkOThjMjQyYjViMmYyOTMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ln6PAdfqcpgtpM7lp4CUttF-FoT1XMjaLXhDSr2W6_E)

应该是打开csv格式文件的问题造成的，可以用记事本看看数据源是否正确。

2023-12-18 09:42 UTC, lyl-available commented
租户管理-账户列表，搜索后导出为空：
![image](https://github.com/PKUHPC/SCOW/assets/125553919/2e0163c0-cb40-4b5c-8120-b6cfeedd106a)
![image](https://github.com/PKUHPC/SCOW/assets/125553919/9b86c0d3-efbb-4800-a720-57b716c09d39)

2023-12-19 09:47 UTC, lyl-available commented
除导出时间与页面显示时间有时差外，无其余问题

2023-12-20 03:46 UTC, lyl-available approved these changes

2023-12-27 09:37 UTC, merged