Feat shortcut
PKUHPC/SCOW pull request #1014
Opened 2023-11-28 06:46 UTC by OYX-1

2023-11-28 11:27 UTC, ddadaal requested changes

2023-11-28 11:27 UTC, ddadaal commented on apps/portal-server/src/services/user.ts
> +      fs.mkdir(dirPath, { recursive: true }, (err) => {
用fs.promises下的Promise版本的文件操作

2023-11-28 11:27 UTC, ddadaal commented on apps/portal-server/src/services/user.ts
> +          });
fs.promises

2023-11-28 11:27 UTC, ddadaal commented on apps/portal-web/src/components/Icon.tsx
> +export default Icon;
不要用export default，正常export const Icon就好了

2023-11-28 11:27 UTC, ddadaal commented on apps/cli/src/compose/index.ts
> +        "./quickEntry":"/etc/quickEntry",
quickEntry是scow的配置文件，就应该放在scow的配置下面，/etc/scow/quickEntries

2023-11-28 11:27 UTC, ddadaal commented on apps/portal-server/src/services/user.ts
> +export const userServiceServer = plugin((server) => {
这些API都是用于dashboard的吧，那就改成dashboardServiceServer

2023-11-28 11:27 UTC, ddadaal commented on apps/portal-web/src/apis/api.mock.ts
> +  getQuickEntry:null,
不mock这个的话，dev下dashboard还能正常显示吗？

2023-11-28 11:27 UTC, ddadaal commented on apps/portal-web/src/models/User.ts
> +}
如果只是为了改entryType这个属性的类型，可以用proto生成的类型计算出来：`Omit<QuickEntry, "entryType"> & { entryType: EntryType }`。少写重复代码

2023-11-28 11:27 UTC, ddadaal commented on apps/portal-web/src/pageComponents/dashboard/Sortable.tsx
> +  isFinish: boolean,
isFinish?英语语法

2023-11-28 11:27 UTC, ddadaal commented on protos/portal/user.proto
> +  optional Cluster cluster = 8;
cluster此处不需要名字，只需要cluster的id。这里只需要给`string cluster`即可。

2023-11-28 11:27 UTC, ddadaal commented on protos/portal/user.proto
> +message QuickEntry {
整个QuickEntry应该用discriminated union的模型来设计。

所有的entry都有的属性包括：
```proto
message Entry {
  string id = 1;
  string name = 2;
}
```

有三种QuickEntry，不同的entry需要不同的属性。

到某个页面的entry：

```proto
message PageLinkEntry {
  string path = 1;
  // antd的图标ID
  string icon = 2;
}
```

到某个集群的某个登录节点的shell的快捷方式

```proto
message ShellEntry {
  string cluster = 1;
  string login_node = 2;
}
```

启动一个应用的entry

```proto
message AppEntry {
  string cluster = 1;
  string app = 2;
}
```

通过oneof实现三种类型选一个。所以，整个QuickEntry的定义为：

```proto
message Entry {
  string id = 1;
  string name = 2;

  oneof entry {
    PageLinkEntry page_link = 3;
    ShellEntry shell = 4;
    AppEntry app = 5;
  }
}
```

2023-11-28 11:27 UTC, ddadaal commented on protos/portal/user.proto
> +service UserService {
DashboardService

2023-11-28 11:27 UTC, ddadaal commented on protos/portal/user.proto
> +  rpc GetQuickEntry(GetQuickEntryRequest) returns (GetQuickEntryResponse);
QuickEntries，英语语法

2023-11-28 11:27 UTC, ddadaal commented on apps/portal-web/src/components/Icon.tsx
> +import * as icons from "@ant-design/icons";
不要import *，这样会把整个包里的所有图标全部导入到前端，影响整个前端bundle的大小。此处应该手动import一些常用的icon，并给一个map用于实现string到常用icon的映射。

2023-11-28 11:27 UTC, ddadaal commented on apps/portal-web/src/components/Icon.tsx
> +import * as icons from "@ant-design/icons";
再编写一个高阶函数，接受一个Icon组件，其返回一个组件，并把返回的组件的color修改颜色。

2023-11-28 11:33 UTC, ddadaal requested changes

2023-11-28 11:33 UTC, ddadaal commented on apps/portal-server/src/services/user.ts
> +const quickEntryPath = "/etc/quickEntry";
quickEntry是scow生成的文件，现在所有scow生成的文件都放在用户目录的scow下面，所以也直接这样做就好了，把某个用户的quickEntries相关的文件都放在`~/scow/quickEntries`下面

2023-11-29 06:01 UTC, OYX-1 commented on protos/portal/user.proto
> +  optional Cluster cluster = 8;
有集群的需要展示集群的name呀
![image](https://github.com/PKUHPC/SCOW/assets/74037789/97343793-77e9-469c-8741-5feefdb69f9e)

2023-11-29 09:21 UTC, OYX-1 commented on apps/portal-server/src/services/user.ts
> +const quickEntryPath = "/etc/quickEntry";
![image](https://github.com/PKUHPC/SCOW/assets/74037789/1fae9819-8003-4bf5-aa0c-402f63ef3863)
写这个地址吧，"~/"这个是在集群中用户的加目录吧

2023-11-29 14:09 UTC, ddadaal commented on protos/portal/user.proto
> +  optional Cluster cluster = 8;
集群的名字可以从publicConfig中获取，不需要再传一遍。传数据的时候只传最必要的数据，一个cluster的id已经足够标识是哪个集群这个信息了，不要再传name这种只用于显式、和这个接口业务逻辑无关的信息。

2023-11-29 14:10 UTC, ddadaal commented on apps/portal-server/src/services/user.ts
> +const quickEntryPath = "/etc/quickEntry";
quickEntry目录下面的文件是SCOW生成的，还是用户自己写的？用户自己写的，即配置文件，是放在/etc/scow下面的；SCOW生成的，就放在~/scow下面。这两种文件要分开

2023-12-01 02:21 UTC, OYX-1 commented on apps/portal-web/src/models/dashboard.ts
> +}
之前是用到了enum类型，直接用proto生成的文件会报tls错误。现在已删掉了这个文件，直接用proto生成的文件

2023-12-01 06:13 UTC, OYX-1 commented on protos/portal/dashboard.proto
> +  string name = 2;
shell和apps都是英文的，已加上PageLinkEntry类型的国际化

2023-12-01 06:16 UTC, OYX-1 commented on apps/portal-web/src/pageComponents/dashboard/AddEntryModal.tsx
> +          loginNode:"",
![image](https://github.com/PKUHPC/SCOW/assets/74037789/296bcf10-0c2d-4f99-bd37-af0259169d84)
先确定Entry类型，后面打开选择集群Modal框再确定集群。为“”是clusterId和loginNode的ts类型是string

2023-12-01 06:16 UTC, OYX-1 commented on apps/portal-web/src/pageComponents/dashboard/AddEntryModal.tsx
> +              clusterId:"",
同上，先确定Entry类型，后面打开选择集群Modal框再确定集群。

2023-12-01 10:40 UTC, ddadaal commented
要看隐藏的conversation

2023-12-04 01:48 UTC, OYX-1 commented on apps/portal-web/src/pageComponents/dashboard/AddEntryModal.tsx
> +  });
已改，初始为null

2023-12-04 10:49 UTC, ddadaal commented
![image](https://github.com/PKUHPC/SCOW/assets/8363856/405776ab-7e5c-45a8-aa9b-feb5c6d78ffb)

2023-12-04 11:19 UTC, ddadaal requested changes

2023-12-04 11:19 UTC, ddadaal commented on apps/portal-web/src/utils/dashboard.ts
> +  return "";
再强调一下不要用空字符串代表undefined。空字符串是空字符串，undefined是undefined，表达没有值这个含义的时候用undefined。

2023-12-04 11:19 UTC, ddadaal commented on apps/portal-web/src/pageComponents/dashboard/Sortable.tsx
> +                  getEntryClusterName(x) && ((!(activeId && activeItem) && isEditable) || !isEditable) ? (
按语义，这里应该是**当x的type是shell和app**，才会执行这一块的代码。但是，现在的代码中体现的是，**如果获取x的集群信息返回的不是空字符串**，执行这一块的代码。代码所表示的语义和代码所表示的有区别，会影响代码的可读性。例如说，按现在的代码，为什么获取一个项的集群名有可能返回空字符串呢？所以，这里应该直接写成实际上想要表达的`x.type === "Shell || x.type === "App"`。这会带来另一个好处，在下面使用这个x变量的时候，x变量的类型会更加具体。见下面一个comment

2023-12-05 07:22 UTC, OYX-1 commented on apps/portal-web/src/pageComponents/dashboard/Sortable.tsx
> +          Router.push(join("/shell", item.entry.shell.clusterId, item.entry.shell.loginNode));
Router和useRouter和有什么区别呢？
Router 是更通用的、全局性的路由控制方式，而useRouter 是专为 React 函数组件设计的 Hook

2023-12-05 09:21 UTC, OYX-1 commented on apps/portal-web/src/utils/dashboard.ts
> +
![image](https://github.com/PKUHPC/SCOW/assets/74037789/10bb1fed-9714-48a7-8862-a1b073b7462f)

2023-12-05 09:30 UTC, OYX-1 commented on protos/portal/dashboard.proto
> +}
Entry和AppEntry类似父类子类的关系，用appId作为Entry的id不可以吗？符合Entry的id且易读，不然Entry的id用什么呢

2023-12-05 10:30 UTC, ddadaal commented on protos/portal/dashboard.proto
> +}
不可以，这两个属性的含义不一样。Entry.id的作用只是唯一确定一个项，不应该有业务含义。Entry.id可以是任何值，只要它满足不同的entry id不同就可以。这个ID用于对这个项本身的操作，比如查询、新增、删除、修改一个Entry，那么此时应该用这个Entry.id来代指这个项。而appId是有业务含义的，是指这个App的entry所指示的app的ID。在代码中用这个Entry所对应的应用的时候，就可以用这个appId的属性。

就像是数据库中用户的ID和姓名一样，即使假设所有人的姓名都是不一样的，但是ID和姓名也应该是两个字段，因为ID是用于唯一代指一个项，姓名是有对应的业务含义。

2023-12-05 11:20 UTC, ddadaal requested changes

2023-12-05 11:20 UTC, ddadaal commented on apps/portal-web/src/pageComponents/dashboard/Sortable.tsx
> +                        {getEntryClusterName(x as Entry & {entry: {$case: "app" | "shell"} }) as string}
推出不来就算了，但是现在至少前面的判断逻辑看起来清晰一些。

这里as整个函数调用的返回值隐藏了一个问题，这个getEntryClusterName返回的是I18nStringType，不是string。如果这里的应用名称是一个国际化对象，这里运行时就会报错。这就是为什么要利用好类型系统，因为类型系统可以检查出问题。

再检查一下所有用了类型断言的地方看有没有这种问题

2023-12-05 11:20 UTC, ddadaal commented on apps/portal-web/src/pageComponents/dashboard/Sortable.tsx
> +export default Sortable;
不要用export default

2023-12-05 11:20 UTC, ddadaal commented on apps/portal-web/src/utils/dashboard.ts
> +  return undefined;
实际上这里的if (item.entry)、第二个item.entry.$case === "app"，以及最后的return undefined都可以不写，因为ts知道item只有$case是app和shell两种情况。

```ts
export const getEntryClusterName = (item: Entry & { entry: {$case: "app" | "shell"} }) => {
  const clusters = publicConfig.CLUSTERS;

  if (item.entry.$case === "shell") {
    const clusterId = item.entry.shell.clusterId;
    return clusters.find((x) => x.id === clusterId)?.name;
  }

  const clusterId = item.entry.app.clusterId;
  return clusters.find((x) => x.id === clusterId)?.name;
};

```

2023-12-05 11:20 UTC, ddadaal commented on apps/portal-web/src/pageComponents/dashboard/SelectClusterModal.tsx
> +  IncompleteEntryInfo: IncompleteEntryInfo | null;
属性名首字母小写

2023-12-05 11:20 UTC, ddadaal commented on apps/portal-web/src/pageComponents/dashboard/AddEntryModal.tsx
> +  const [IncompleteEntryInfo, setIncompleteEntryInfo] = useState<IncompleteEntryInfo | null>(null);
局部变量首字母小写

2023-12-06 14:29 UTC, ddadaal approved these changes

2023-12-06 14:29 UTC, ddadaal commented on apps/cli/src/compose/index.ts
> +        "portal_data":"var/lib/scow/portal",
/var/lib/scow/portal

2023-12-25 04:04 UTC, lyl-available commented
di点击选择集群后页面报错
![image](https://github.com/PKUHPC/SCOW/assets/125553919/754e4368-6233-4ac1-8cdd-93b3f3b7cc82)
![image](https://github.com/PKUHPC/SCOW/assets/125553919/0777f728-dab2-4527-9488-423f945eac4a)

2023-12-25 09:25 UTC, lyl-available approved these changes

2023-12-27 08:12 UTC, OYX-1 commented
@ddadaal 这个代码合一下哈

2023-12-28 14:48 UTC, merged