feat(ai): scow ai
PKUHPC/SCOW pull request #1017
Opened 2023-12-01 07:41 UTC by tongchong

2024-01-09 03:24 UTC, Miracle575 commented on apps/ai/src/server/trpc/route/algorithm/algorithm.ts
> +      populate: ["versions", "versions.sharedStatus", "versions.privatePath"],
versions.sharedStatus, versions.privatePath 是不是可以去掉？

2024-01-09 03:27 UTC, Miracle575 commented on apps/ai/src/server/trpc/route/algorithm/algorithm.ts
> +        message: ErrorCode.ALGORITHM_NAME_ALREADY_EXIST,
在 message 里面需要抛出实际的某个算法名称已存在

2024-01-09 05:57 UTC, Miracle575 commented on apps/ai/src/server/trpc/route/dataset/dataset.ts
> +      populate: ["versions", "versions.sharedStatus", "versions.privatePath"],
这里应该也不需要 "versions.sharedStatus", "versions.privatePath"

2024-01-31 12:28 UTC, ddadaal requested changes

2024-01-31 12:28 UTC, ddadaal commented on docs/docs/deploy/config/ai/intro.md
> +hpcOnly: false
所以`hpcOnly`是true的话，ai服务就不管这个集群了吗？因为SCOW到目前为止的主力功能一直是portal，目前主要的用户群体是HPC，AI是附加功能，所以这里建议改成`enableInAI`，默认为false。另外，如果之后还有新的类似AI的功能，这样设计也能让用户可以选择在哪些系统中开启这个集群，而原来的`hpcOnly`在这个方面扩展起来就比较麻烦一点。

2024-01-31 12:28 UTC, ddadaal commented on docs/docs/deploy/config/ai/apps/apps/vscode/index.md
> +### VSCode扩展安装
这个部分和HPC的部分是相同的吧？把这个部分的内容移动到门户系统的vscode部分，在这里可以给一个链接过去。

2024-01-31 12:28 UTC, ddadaal commented on docs/docs/deploy/config/ai/apps/configure-web-app.md
> +大多数配置与门户系统的交互式应用中的[web类应用配置](../../../../deploy/config/portal/apps/configure-web-app.md)一致, 以下为两者之间的不同
所以这里和门户系统有什么区别？看起来多了一个`image`和`startCommand`，但是这里又没有说`image`是干什么用的。对各个配置应该在文档中详细介绍，而不是只在一份示例配置文件中提到。

这里应该像HPC的配置一样，逐个介绍每个配置项。和HPC的交互式应用相同的配置可以给个链接过去而不再重复，但是不可以一点都不提。新的配置项应详细介绍；和HPC名字相同但是作用不同的配置应该先介绍作业，再介绍和HPC的同名配置项的区别。

2024-01-31 12:46 UTC, ddadaal requested changes

2024-01-31 12:46 UTC, ddadaal commented on docs/docs/deploy/config/ai/intro.md
> +本节介绍如何配置 **AI 系统（beta）**。
要部署AI系统，对集群和系统有什么要求吗？比如是不是需要先部署一个harbor？跑AI应用的集群是否需要安装一些什么软件？这些东西要在这里一开始就提。

2024-02-01 02:40 UTC, Miracle575 commented on docs/docs/deploy/config/ai/intro.md
> +hpcOnly: false
改为如下配置确实是比较合适的
```
enableIn:
  ai: true
  hpc: true
```
但是这样的改动会影响到 getClusterConfig 这个函数，hpc 这边调用这个函数的地方特别多，改动会比较大。所以看能不能在 beta 版本中展示不考虑 ai 系统过滤集群的问题。这个后续单独做一个 issue 来优化。

2024-02-01 10:04 UTC, piccaSun commented on docs/docs/deploy/config/ai/intro.md
> +本节介绍如何配置 **AI 系统（beta）**。
已修改 请确认

2024-02-01 15:33 UTC, ddadaal approved these changes

2024-02-01 15:34 UTC, merged