feat(portal): 优化从文件系统直接提交脚本任务
PKUHPC/SCOW pull request #1024
Opened 2023-12-06 05:52 UTC by piccaSun

### 问题

如果共享目录中挂载了用户工作目录时，提交文件脚本没有特殊指定工作目录的情况下会默认将用户家目录作为脚本作业的工作目录
但是如果共享目录中没有挂载用户工作目录时，会将执行脚本文件的适配器所在路径作为工作目录，这样会导致脚本可以作为作业提交，但是已提交的作业在**进入目录**下进入对用户来说并不在同一节点的适配器目录
![img_v3_025q_7f94aa52-ac40-4ced-8158-4a78897e497g](https://github.com/PKUHPC/SCOW/assets/43978285/406b2fd5-b17f-4b9b-b0f8-51ff2c35376e)

### 修改

// TODO 适配器分支暂时指定为适配器新增分支，与适配器联调结束后修改

此pr做出以下修改
在调度器适配器接口参数增新增脚本文件所在绝对路径
在点击提交文件时的提交确认对话框中新增文字提示
![1701841771512](https://github.com/PKUHPC/SCOW/assets/43978285/0cb4ecac-3dbb-47a5-b831-108dbf8562f3)
![1701841771524](https://github.com/PKUHPC/SCOW/assets/43978285/f5bbe856-92ff-456c-b129-3a7447eef790)

2023-12-21 13:29 UTC, ddadaal requested changes
这是feat还是fix？changeset里是patch

2023-12-21 13:29 UTC, ddadaal commented on apps/ai/next-env.d.ts
这个文件别放进来

2023-12-21 13:29 UTC, ddadaal commented on apps/portal-server/src/services/job.ts
> +      // const minRequiredApiVersion: ApiVersion = { major: 1, minor: 5, patch: 0 };
要调到1.5.0吗？似乎1.5.0还没有发布？

2023-12-22 01:38 UTC, piccaSun commented
> 这是feat还是fix？changeset里是patch

是一个patch的feat。。不影响现有功能的小的优化

2023-12-22 01:38 UTC, piccaSun commented on apps/ai/next-env.d.ts
已删除，请确认

2023-12-22 01:40 UTC, piccaSun commented on apps/portal-server/src/services/job.ts
> +      // const minRequiredApiVersion: ApiVersion = { major: 1, minor: 5, patch: 0 };
是的，如果代码没有其他的问题，请帮忙发布https://github.com/PKUHPC/scow-scheduler-adapter-interface
的1.5.0，然后我更改这边的最低版本和scow-scheduler-adapter-interface标签

2023-12-22 15:18 UTC, ddadaal requested changes

2023-12-22 15:18 UTC, ddadaal commented on libs/protos/scheduler-adapter/package.json
> +    "generate": "rimraf generated && buf generate --template buf.gen.yaml https://github.com/PKUHPC/scow-scheduler-adapter-interface.git",
1.5.0发布了，记得改一下

2023-12-25 01:36 UTC, piccaSun commented on libs/protos/scheduler-adapter/package.json
> +    "generate": "rimraf generated && buf generate --template buf.gen.yaml https://github.com/PKUHPC/scow-scheduler-adapter-interface.git",
已通知适配器更新至1.5.0，修改本pr内接口最低版本要求到1.5.0，修改适配器接口仓库到1.5.0

2023-12-25 12:05 UTC, ddadaal commented
这个功能要把提交作业功能对适配器接口的要求从1.2.0提交到1.5.0，版本要求变化有点大，我认为需要一个minor版本。我先去确认一下

2023-12-25 13:32 UTC, ddadaal commented
根据最新的提交提交一下changeset文件

2023-12-25 13:33 UTC, ddadaal requested changes
根据最新的changeset要求提交changeset文件

2023-12-26 09:51 UTC, piccaSun commented
> 根据最新的changeset要求提交changeset文件

已修改changeset文件，请确认

2023-12-27 09:18 UTC, ddadaal approved these changes

2023-12-27 09:18 UTC, merged