feat(mis-web): 管理系统新增集群监控功能
PKUHPC/SCOW pull request #1044
Opened 2023-12-22 02:55 UTC by Miracle575

2023-12-27 09:36 UTC, ddadaal requested changes
编写文档介绍此功能

2023-12-27 09:36 UTC, ddadaal commented on apps/mis-web/src/pages/admin/monitor/alarmLog.tsx
> +                { value: "", label: t(p("selectAll")) },
可以用undefined代替""吗？

2023-12-27 09:36 UTC, ddadaal commented on apps/mis-web/src/pages/api/admin/monitor/getResourceStatus/[[...path]].ts
> +    + req.url!.replace("/api/admin/monitor/getResourceStatus", "");
1. req.query.path可以拿到匹配到的path参数
2. 有个`joinWithUrl`（@scow/utils）函数专门用于这种把URL和其他的参数合并的场景，处理了很多边界条件
3. proxy.web无法处理websocket，请确认是否确定不需要websocket。如果需要websocket，可以要求grafana可以公开访问+使用iframe的方案解决

2023-12-27 09:36 UTC, ddadaal commented on apps/mis-web/config.js
> +    CLUSTER_MONITOR_GRAFANA_URL: misConfig.clusterMonitor.grafanaUrl,
runtime config可以嵌套。此处建议使用`CLUSTER_MONITOR: { enabled: false, grafanaUrl: string }`，这样可以重用config里的类型定义，减少重复定义

2023-12-28 07:14 UTC, Miracle575 commented on apps/mis-web/src/pages/admin/monitor/alarmLog.tsx
> +                { value: "", label: t(p("selectAll")) },
不可以使用 undefined，value 为 undefined 时，选择框无法选择该项

2023-12-28 08:34 UTC, Miracle575 commented on apps/mis-web/src/pages/api/admin/monitor/getResourceStatus/[[...path]].ts
> +    + req.url!.replace("/api/admin/monitor/getResourceStatus", "");
1. req.query.path 可以拿到 path，但是不能拿到 query 参数。想拼接 query 参数还得做额外处理
3. grafana 本身是开启的 websocket 的实时更新功能，但目前不需要使用实时更新数据，普通数据获取不走 ws。此外很多集群不愿意公开 grafana

2023-12-28 09:14 UTC, Miracle575 commented
> 编写文档介绍此功能

https://pkuhpc.github.io/SCOW/pr-preview/pr-1044/docs/deploy/config/mis/cluster-monitor

2023-12-28 14:45 UTC, ddadaal requested changes

2023-12-28 14:45 UTC, ddadaal commented on docs/docs/deploy/config/mis/cluster-monitor/index.md
文档中应将grafana的配置和在此scow中配置此功能的部分分开。grafana本身的配置和SCOW本身没有关系。

文档应拆分为两部分：

一部分为和此功能有关的grafana的配置和SCOW如何启用本功能的配置，放在此位置。此部分介绍此功能对grafana有哪些要求，需要哪些数据，以及如何在SCOW配置文件中打开此功能，以及相关的注意事项，例如grafana的url有什么要求等。

另一部分为grafana本身的配置方法。此部分文档只是示例作业，放在`slurm集群部署实践`下。第一部分可以给一个链接到此部分文档。

2023-12-28 14:45 UTC, ddadaal commented on apps/mis-web/src/pages/api/admin/monitor/getResourceStatus/[[...path]].ts
> +  const target = joinWithUrl(publicConfig.CLUSTER_MONITOR.grafanaUrl ?? "",
如果此功能没有启用，此API应该返回404。

2023-12-28 14:47 UTC, ddadaal commented on apps/mis-web/src/pages/api/admin/monitor/getResourceStatus/[[...path]].ts
> +    + req.url!.replace("/api/admin/monitor/getResourceStatus", "");
```ts
const { path, ...rest } = req.query;
```

rest就是其他的参数。

现在这样的问题是path的开头这部分（/api/admin/monitor/getResourceStatus）被重复了一次，看看能不能去掉这个重复。

如果这样不行的话，起码也可以使用req.url!.slice("/api/admin/monitor/getResourceStatus".length)，以更好地表达去除前缀这个含义。

2024-01-02 15:37 UTC, ddadaal approved these changes

2024-01-02 15:38 UTC, merged