fix(portal): 修复部分集群无法获取集群运行信息时导致仪表板无法展示其他正常信息
PKUHPC/SCOW pull request #1061
Opened 2024-01-11 06:48 UTC by OYX-1

2024-01-15 10:48 UTC, ddadaal requested changes

2024-01-15 11:01 UTC, ddadaal requested changes

2024-01-15 11:01 UTC, ddadaal commented on apps/portal-web/src/pageComponents/dashboard/OverviewTable.tsx
> +  partitionStatus?: PartitionInfo_PartitionStatus;
TableProps只有两种可能，要么获取成功的集群全部都有，要么获取失败的集群全部都没有。所以，定义TableProps为 `{ clusterId: string; clusterName: string; info?: { 其他属性 }}`，把从API获取到的信息都转换为这个格式，逻辑更简单。

2024-01-17 11:53 UTC, ddadaal requested changes
其他没问题

2024-01-17 11:53 UTC, ddadaal commented on protos/portal/config.proto
> +  // GetClusterInfo中不包含获取失败的集群的信息。
没用的注释删了

2024-01-18 02:03 UTC, OYX-1 commented on protos/portal/config.proto
> +  // GetClusterInfo中不包含获取失败的集群的信息。
OK

2024-01-18 13:36 UTC, ddadaal approved these changes

2024-01-18 13:36 UTC, merged