feat(mis): 管理系统创建用户增加配置项控制账户管理员是否允许创建用户
PKUHPC/SCOW pull request #1073
Opened 2024-01-18 07:21 UTC by ZihanChen821

// TODO

2024-01-19 09:40 UTC, ddadaal requested changes

2024-01-19 09:40 UTC, ddadaal commented on apps/cli/assets/init-full/config/mis.yaml
> +  enableAccountAdminUserCreation: true
这个场景挺具体的，所以描述也可以更具体一点。这个功能似乎不是只有账户管理员能用吧？租户和平台管理员应该都可以，名字修改为`createUserIfNotExistWhenAddUserToAccount`

2024-01-22 02:43 UTC, ZihanChen821 commented on apps/cli/assets/init-full/config/mis.yaml
> +  enableAccountAdminUserCreation: true
确认了下需求，现在是需要控制账户管理员是否能使用该功能，该开关不涉及租户管理员和平台管理员。 加了一下前端页面的逻辑判断。  在这个场景下，是否不需要改名了呢

2024-01-22 10:45 UTC, ddadaal requested changes
所以现在的逻辑是：添加用户到账户时，如果用户不存在，如果是账户管理员操作的，就不创建；如果是租户和平台管理员操作的，就创建？那如果是作为租户/平台管理员进入账户管理界面，然后添加不存在的用户呢？能不能添加用户的判断标准是用户自己的身份（只有账户管理员的身份或者是租户/平台管理员），还是从哪个界面操作？

名字是另外一回事，这么具体的需求就应该对应具体的名字。`enableAccountAdminUserCreation`这个光看名字会以为是如果设置成`false`，那么账户管理员就不能创建用户。但是账户管理员什么时候会创建用户呢？这个光看名字看不出的。

如果账户管理员不行，改名`createUserIfNotExistWhenAddingUserToAccountAsAccountAdmin`；如果是不能从账户管理界面中添加不存在的用户，改名`createUserIfNotExistWhenAddingUserToAccountFromAccountAdminPage`。确实有点长，但是这是最直观的。

2024-01-22 10:45 UTC, ddadaal commented on apps/mis-web/src/pageComponents/users/AddUserButton.tsx
> +  isfromAccount?: boolean
如果是否能创建用户是根据UI入口判断的，则这样写没问题；如果是根据用户的身份判断的，则在组件中使用用户身份判断。

2024-01-23 08:06 UTC, ZihanChen821 commented
经过和若淼老师讨论，需要将此功能做成三级
1. 账户管理员不允许添加用户
2. 账户管理员允许添加添加用户，但是不允许添加不存在的用户时创建用户
3. 账户管理员可以添加用户，同时在添加不存在的用户时可以创建用户

2024-01-24 12:33 UTC, ddadaal approved these changes
等待下个版本

2024-01-26 14:10 UTC, merged