feat(mis): 账户增加封锁阈值
PKUHPC/SCOW pull request #1101
Opened 2024-01-30 09:11 UTC by ZihanChen821

2024-02-18 14:21 UTC, ddadaal requested changes

2024-02-18 14:21 UTC, ddadaal commented on apps/mis-web/src/i18n/zh_cn.ts
> +        useDefaultBlockThresholdAmount: "使用默认封锁阈值",
使用租户默认封锁阈值。记得改英文版本

顺便，有专门的API查询租户的默认封锁阈值吗？如果有的话，这里可以顺便显示一下当前租户的封锁阈值

2024-02-18 14:21 UTC, ddadaal commented on .changeset/mighty-countries-march.md
> +"@scow/ai": minor
确认一下变更版本

2024-02-18 14:25 UTC, ddadaal requested changes
列旁边可以加个tooltip，显示为?，内容为解释一下“封锁阈值”是指“当余额小于此封锁阈值时，账户将会被封锁”。

2024-02-18 14:25 UTC, ddadaal commented on apps/mis-server/src/bl/charging.ts
> +  account.blockThresholdAmount ?? account.tenant.getProperty("defaultAccountBlockThreshold");
getProperty是在运行时检查关联entity是否加载，而account本身已经使用`Loaded`来在编译时确保进入的entity已经加载所需要的关联关系，后者安全性强于前者，所以这里没有必要用getProperty，直接用`.$.defaultAccount`就可以了。

2024-02-19 02:37 UTC, ZihanChen821 commented on .changeset/mighty-countries-march.md
> +"@scow/ai": minor
已和若淼老师确认是minor

2024-02-19 03:25 UTC, ZihanChen821 commented on apps/mis-web/src/i18n/zh_cn.ts
> +        useDefaultBlockThresholdAmount: "使用默认封锁阈值",
![image](https://github.com/PKUHPC/SCOW/assets/130351655/9c3aea58-dc3e-415e-bdd4-0ec977806ae9)

2024-02-19 13:24 UTC, ddadaal requested changes
/pr:request e2e

2024-02-28 02:34 UTC, lyl-available approved these changes

2024-02-28 12:28 UTC, ddadaal approved these changes

2024-02-28 12:31 UTC, merged