fix: touch error
PKUHPC/SCOW pull request #1103
Opened 2024-01-31 01:59 UTC by Miracle575

2024-02-01 15:07 UTC, ddadaal requested changes

2024-02-01 15:07 UTC, ddadaal commented on apps/portal-server/src/services/file.ts
> +            });
这里可以不异步吗？异步出了错不好调试。错误是因为filePaths太多，但是这里每次touch 1000个已经可以解决这个问题了，异步不异步并不影响解决此bug。

2024-02-02 02:56 UTC, Miracle575 commented on apps/portal-server/src/services/file.ts
> +            });
此处改为异步是考虑到当文件特别多时，会一定程度影响获取目录内容的速度。如果忽略对加载速度的影响的话可以不使用异步。

2024-02-02 14:36 UTC, ddadaal commented on apps/portal-server/src/services/file.ts
> +            });
测试一下在各种常见情况下的此操作执行的速度。

另外，为什么必须要进行一次这个操作？刷新文件系统缓存的工作不应该由SCOW关心。

2024-02-04 02:36 UTC, Miracle575 commented on apps/portal-server/src/services/file.ts
> +            });
分别测试一个目录下文件数量为 1000、5000 和 10000 的情况，该接口 10 次测试的平均值分别为 687ms、1365ms 和 2285ms

刷新文件系统缓存为跨文件传输功能的需要，这一块目前正在打算优化，看如何不在获取文件目录时执行刷新缓存操作。

2024-02-04 12:19 UTC, ddadaal commented on apps/portal-server/src/services/file.ts
> +            });
看起来，有没有完成刷新不影响此接口返回的结果的正确性？如果需要等待这些操作完成返回的结果才正确，需要等待刷新完成再返回结果，否则可以异步调用。

2024-02-05 01:35 UTC, Miracle575 commented on apps/portal-server/src/services/file.ts
> +            });
是的，不影响。所以此处可以使用异步

2024-02-05 12:22 UTC, ddadaal approved these changes

2024-02-05 12:22 UTC, merged