fix: 使用外部认证系统时，外部系统未实现的功能在用户使用时提示用户功能未实现
PKUHPC/SCOW pull request #1135
Opened 2024-02-22 07:36 UTC by OYX-1

## 使用外部认证系统时，外部系统未实现的功能在用户使用时提示用户功能未实现
### 主要是增加了修改密码、修改邮箱、新增用户的提示

2024-02-22 08:24 UTC, Miracle575 commented on apps/mis-web/src/pages/api/profile/changeEmail.ts
> +    return { 501: null };
在 mis-server 中有判断 是否具有修改邮箱的能力的逻辑，是否收敛到一个位置比较合适，不要 mis-web 有这个逻辑，然后 mis-server 也有这个逻辑。类似的问题都可以看看

2024-02-22 08:38 UTC, OYX-1 commented on apps/mis-web/src/pages/api/profile/changeEmail.ts
> +    return { 501: null };
在web-server层判断是去auth调修改邮箱函数之前（不知道外部认证是否实现了该函数），server层的逻辑是直接去auth调修改邮箱函数(外部认证实现了该函数，但任然可能返回不支持修改邮箱)

2024-02-22 08:42 UTC, OYX-1 commented on apps/mis-web/src/pages/api/profile/changeEmail.ts
> +    return { 501: null };
还有现在有几个修改密码直接调auth的函数，没有经过server

2024-02-22 08:43 UTC, Miracle575 commented on apps/mis-web/src/pages/api/profile/changeEmail.ts
> +    return { 501: null };
没有太理解，mis-server 也是调用了 getCapabilities 知道的 auth 有无对应能力，你在 mis-web api 也是调用的 getCapabilities。

2024-02-22 14:35 UTC, ddadaal requested changes

2024-02-22 14:35 UTC, ddadaal commented on apps/mis-web/src/pages/admin/tenants/create.tsx
> +                message.error(userIdRule?.message);
message是否有可能也是国际化的？

2024-02-23 01:42 UTC, OYX-1 commented on apps/mis-web/src/pages/admin/tenants/create.tsx
> +                message.error(userIdRule?.message);
![image](https://github.com/PKUHPC/SCOW/assets/74037789/a2d7cecc-d6e0-4268-830d-5dc8b33dc18c)
这个就是string，下图是它的来源
![image](https://github.com/PKUHPC/SCOW/assets/74037789/dc7df6b3-30d2-45c1-846d-e153cdbaf699)

2024-02-23 15:45 UTC, ddadaal approved these changes

2024-02-23 15:45 UTC, merged