fix(mis): 消费记录、充值记录搜索功能优化
PKUHPC/SCOW pull request #1152
Opened 2024-03-04 08:09 UTC by OYX-1

## 消费记录类型选择框修改
账户管理->消费记录、租户管理->账户消费记录，平台管理->账户消费记录：
1、类型改为多选
2、类型选择下拉框不隐藏文字信息
### 改进前
![1713859929246](https://github.com/PKUHPC/SCOW/assets/78541912/d4ded0f4-490d-4901-b825-17ee53b3682e)
### 改进后
![1713860086118](https://github.com/PKUHPC/SCOW/assets/78541912/0324498f-2e89-4fce-85dc-be48d573beb5)
![1713860050066](https://github.com/PKUHPC/SCOW/assets/78541912/58d553eb-f26c-4ce4-aaaa-c92ad011df44)
## 充值记录类型选择框修改
账户管理->充值记录，租户管理->账户充值记录，租户管理->租户充值记录，平台管理->充值记录：
1、增加充值类型搜索
2、类型搜索框进行trim
### 改进前
![1713860486279](https://github.com/PKUHPC/SCOW/assets/78541912/2c151376-f85e-40e8-963a-c595daa6706a)
### 改进后
![1713860541548](https://github.com/PKUHPC/SCOW/assets/78541912/67de633f-924a-46e9-af51-4fe82f5afa22)
![1713862788038](https://github.com/PKUHPC/SCOW/assets/78541912/6bf70036-9bc4-4973-beb6-e72598d44373)
## 账户搜索框修改
租户管理->账户消费记录，租户管理->账户充值记录，平台管理->账户消费记录：
1、账户搜索框改为可以输入多个
2、账户搜索框，允许直接输入内容后，不用再点击搜索结果也可以进行搜索
### 改进前
![修改前](https://github.com/PKUHPC/SCOW/assets/78541912/d19b6b22-6cb7-4de5-90d5-11a39b889343)
### 改进后
![修改后](https://github.com/PKUHPC/SCOW/assets/78541912/c371f0f7-11b1-49c2-afab-bc877de8b613)
## 其他
1、导出功能根据类型从string->string[]同步更新
2、mis、audit中测试用例随着账户名和类型可多选，string->string[]，随之修改和增加
3、mis、audit中日志相关随string->string[]进行一定修改
连锁i修改，操作日志，体现单选、多选、全选，并兼容过去记录：
![微信截图_20240507114137](https://github.com/PKUHPC/SCOW/assets/78541912/ccdcb7b1-51fe-4b61-8682-3e75827738da)

2024-04-24 12:33 UTC, ddadaal requested changes
所有修改SCOW API的变化需要确保兼容性！仔细阅读开发文档里的版本控制 -> Protobuf接口版本兼容性方案

2024-04-24 12:33 UTC, ddadaal commented on protos/audit/operation_log.proto
> -    AccountOfTenantTarget account_of_tenant = 1;
保证API的向后兼容性，不要删除原来的API。原来API放着不用即可。如果需要删除原来的API，需要根据流程，先让这个API deprecate，然后在下个破坏性版本删除。

2024-04-24 12:33 UTC, ddadaal commented on protos/server/export.proto
> +  repeated string user_ids = 11;
修改已经存在的字段的序数是**破坏性更新**。给新的字段用新的序号，给`AccountsTarget accounts`给11。

2024-04-24 12:33 UTC, ddadaal commented on protos/server/export.proto
> -    AccountOfTenantTarget account_of_tenant = 4;
保留删除原来的API。

2024-04-24 12:33 UTC, ddadaal commented on protos/server/charging.proto
> +    AccountsTarget accounts = 9;
新字段使用新的序号，不要修改原来的序号

2024-04-24 12:33 UTC, ddadaal commented on apps/mis-web/src/pages/api/finance/getChargeRecordsTotalCount.ts
> +    accountName: Type.Optional(Type.Array(Type.String())),
HTTP API可以随便改，如果现在这个变成了多个值，顺便改名为`accountNames`

2024-04-24 12:33 UTC, ddadaal commented on protos/server/export.proto
> +  repeated string type = 4;
虽然在grpc层面上这个变化是不breaking的（意思是，用老版本grpc api写的代码，调用实现了新版本grpc api的实现（也就是新版SCOW），这个数据可以正确解析），但是会已有代码使用新的grpc api编译的时候会出现编译错误（因为在编程语言中这个字段的类型变了）。为了保持兼容性，应该新增一个`repeated string types`属性，并在后端代码中同时处理这两个字段，也就是说，如果types有值，就以types的值为准；否则，以type的值为准。可以deprecate掉type，但是不可以直接删除！

2024-04-26 08:48 UTC, cuvalign commented
根据review意见修改Proto保证兼容性，后端增加type兼容。从grpc兼容性与review意见出发，前端http接口accountName部分改为accountNames，type部分改为types。

2024-04-27 06:44 UTC, ddadaal requested changes

2024-04-27 06:44 UTC, ddadaal commented on protos/server/charging.proto
> +  repeated string types = 13;
这种作用相同的字段需要写个注释，说明最终具体如何取值，也就是说，当types设置时，以types为准，否则以type为准。

2024-04-27 06:44 UTC, ddadaal commented on apps/mis-web/src/pages/api/admin/finance/payments.ts
> +    type:Type.Optional(Type.Array(Type.String())),
可能是多个取值的参数的名字用复数

2024-04-27 06:44 UTC, ddadaal commented on apps/mis-web/src/pageComponents/common/PaymentTable.tsx
> +  accountName?: string[];
accountNames

2024-04-27 06:44 UTC, ddadaal commented on apps/mis-server/src/services/export.ts
> +      }
不要把`[""]`当成一个特殊条件，而只需要区分数组和字符串两种形式。如果在用户在UI那边啥都没输入使得前端获得的值为`""`，应该在前端就预处理掉这些值，让空字符串这类的值不要传到后端。因为后端代码主要负责业务逻辑，在业务逻辑中穿插对这些特殊值的处理影响代码的可读性。

2024-04-27 06:44 UTC, ddadaal commented on apps/mis-server/src/utils/array.ts
> +  return types.size > 0 ? Array.from(types) : [""];
为什么以`[""]`作为默认值，用空字符串是不是同样的含义？

2024-04-28 11:47 UTC, cuvalign commented on apps/mis-web/src/pages/api/admin/finance/payments.ts
> +    type:Type.Optional(Type.Array(Type.String())),
### 疑问
改为types后，容易和"src/entities/PayRecord"的payrecord类产生冲突，可能需要修改该类。但是正常一个payrecord实例确实是type。此处待考虑

2024-04-28 12:59 UTC, ddadaal requested changes

2024-04-28 12:59 UTC, ddadaal commented on apps/mis-server/src/services/charging.ts
> +      const searchType = getChargesSearchType(types ?? type);
types不会是undefined的，如果没有传任何值，types将会是空数组。应该判断如果types是空数组就使用type.

2024-04-28 12:59 UTC, ddadaal commented on apps/mis-server/src/utils/array.ts
> +  return types.size > 0 ? Array.from(types) : [];
`Array.from(new Set())`不是返回`[]`？

2024-04-28 12:59 UTC, ddadaal commented on apps/mis-web/src/pages/api/admin/finance/payments.ts
> +    type:Type.Optional(Type.Array(Type.String())),
没太看懂，这里是http api，表示的是一个参数，到数据库有一大堆流程要走，怎么直接和实体类产生关系的？

2024-04-28 12:59 UTC, ddadaal commented on apps/mis-web/src/pages/api/admin/finance/payments.ts
> +    type:Type.Optional(Type.Array(Type.String())),
querystring能否正常解析数组类型的参数确实可以尝试一下，但是如果参数本来是由URLSearchParams处理的话，这里应该没有问题。

2024-04-28 12:59 UTC, ddadaal commented on apps/mis-web/src/pageComponents/file/apis.ts
> +      },
可以使用URLSearchParams类处理参数，尽量不要自己处理querystring参数

2024-04-28 12:59 UTC, ddadaal commented on apps/mis-web/src/pageComponents/finance/AccountSelector.tsx
> +  onChange?: (value: string[]) => void;
value要保留的，value和onChange是antd Form组件默认传的属性，这个组件不应该记录自己的value，而是应该用antd的value作为当前的值

2024-04-28 12:59 UTC, ddadaal commented on apps/mis-web/src/pageComponents/finance/AccountSelector.tsx
> +  onChange?: (value: string[]) => void;
如果将单选和多选AccountSelector做在一个组件里不好做，就分开做，原来的不变，重新做一个多选的AccountSelector

2024-04-29 09:06 UTC, cuvalign commented on apps/mis-web/src/pages/api/admin/finance/payments.ts
> +    type:Type.Optional(Type.Array(Type.String())),
可能昨天弄乱了，已解决

2024-04-29 14:35 UTC, ddadaal requested changes

2024-04-29 14:35 UTC, ddadaal commented on apps/mis-web/src/pageComponents/finance/AccountMultiSelector.tsx
> +  onChange?: (value: string[]) => void;
需要增加value: string[]作为当前值

2024-04-29 14:35 UTC, ddadaal commented on apps/mis-web/src/pageComponents/finance/AccountMultiSelector.tsx
> +  const [selectedValues, setSelectedValues] = useState<string[]>([]);
并且不要自己维护自己的值，自己的值从props.value获取。

2024-04-29 14:35 UTC, ddadaal commented on apps/mis-web/src/pageComponents/finance/AccountSelector.tsx
> +export const AccountMultiSelector: React.FC<Props> = ({
原来的AccountSelector怎么给改名了？

2024-04-29 14:35 UTC, ddadaal commented on apps/mis-web/src/pageComponents/finance/ChargeTable.tsx
> +  accountName?: string [];
复数 accountNames

2024-04-29 14:35 UTC, ddadaal commented on protos/audit/operation_log.proto
> +    SpecificAccountsOfTenantTarget specific_accounts_of_tenant = 5;
我刚意识到一个问题，这个`SpecificAccountsOfTenant`有点拗口，实际上可以直接重用原来的`AccountsOfTenantTarget`，给里面增加一个`repeated string accountNames`属性，如果这个属性为空数组则行为不变，为整个tenant的全部账户，否则为选择的账户。proto里给message增加`repeated`字段不是breaking的，这样做没有问题。顺便把代码中其他地方也改成这样，修改原来的`accountsOfTenant`而不是新加一个

2024-04-29 14:35 UTC, ddadaal commented on protos/server/export.proto
> +    AccountOfTenantTarget account_of_tenant = 4 [deprecated=true];
这样的话原来的取一个account的API也可以留着，没必要deprecate。

2024-04-30 01:43 UTC, cuvalign commented on apps/mis-web/src/pageComponents/finance/AccountSelector.tsx
> +export const AccountMultiSelector: React.FC<Props> = ({
改晕了，已改回

2024-04-30 07:42 UTC, cuvalign commented on apps/mis-web/src/pageComponents/finance/AccountMultiSelector.tsx
> +  const [selectedValues, setSelectedValues] = useState<string[]>([]);
这里保留了inputValue，仅用于增强组件的交互性（搜索功能），不直接影响选中账户。感觉删除的话会降低组件的封装性和实用性。

2024-04-30 18:13 UTC, cuvalign commented
7dd42ae是不合并前较完善版本，后续为中间版本。请检查4d809b6（自测导出平台日志没有输入操作行为时会报错）和62dee63（本地pnpm test有问题，但单独测报错文件又没报错），在合并SpecificAccountsOfTenant到AccountsOfTenantTarget后，日志思路不大确定。日志的AccountsOfTenant是否需要accountNames或者部分保留SpecificAccountsOfTenant？目前UI中mis没有涉及，但未来AI或后续也有相关？总之可能涉及不同方向。希望先确认一下思路。

2024-04-30 18:14 UTC, cuvalign commented on protos/audit/operation_log.proto
> +    SpecificAccountsOfTenantTarget specific_accounts_of_tenant = 5;
这里比较纠结，修改量还是挺大的，具体写在后续讨论里，需要确定一下日志这块涉及的思路

2024-05-05 14:41 UTC, ddadaal approved these changes
改一下就行

2024-05-05 14:41 UTC, ddadaal commented on .changeset/slow-candles-rush.md
> +"@scow/grpc-api": patch
根据规则，修改了API，但是兼容当前的API，则需要提高minor版本。

2024-05-05 14:45 UTC, ddadaal requested changes

2024-05-05 14:45 UTC, ddadaal commented on protos/server/charging.proto
> +    AccountsTarget accounts = 10;
这个target是否可以使用AccountsOfAllTenantsTarget代替？因为虽然实际上账户名是全局唯一的，但是这是因为底层是用的slurm，slurm保证的账户名全局唯一，但是SCOW这一层并不要求账户名必须全局唯一，而只保证租户中账户名唯一，SCOW的API也要和SCOW的设计一致。

2024-05-05 14:48 UTC, ddadaal commented on protos/server/charging.proto
> +    AccountsTarget accounts = 10;
日志部分同样考虑下这个问题，并且仍然合并到AccountsOfTenant里去

2024-05-07 03:58 UTC, cuvalign commented
已经合并了AccountsTarget进入AccountsOfAllTenantsTarget，日志进行同步修改，并且兼容了先前没有accountNames的情况。连锁修改，日志的消费和充值记录中，能体现单选、多选、全选。

2024-05-09 13:09 UTC, ddadaal approved these changes

2024-05-09 13:10 UTC, merged