feat(web): 优化适配器无法启动时的页面错误信息展示
PKUHPC/SCOW pull request #1182
Opened 2024-03-29 10:19 UTC by piccaSun

2024-04-03 11:24 UTC, ddadaal requested changes

2024-04-03 11:24 UTC, ddadaal commented on apps/portal-web/src/pages/api/app/getAppSessions.ts
> +    503: Type.Object({
不要在前端用503表示后端错误，503一般用于HTTP前后端之间不通的情况，混用有可能无法区分到底是哪一层不通。集群联不通用500就好了，代码设置为CLUSTER_UNAVAILABLE

2024-04-03 11:24 UTC, ddadaal commented on apps/portal-web/src/pages/api/app/getAppSessions.ts
> +    [status.CANCELLED]: (err) => ({ 503: { code: "SERVICE_UNAVAILABLE", message: err.details } } as const),
同样的，CANCELLED也有可能是grpc前后端不通，之前测试前后端之间用TLS双向加密的时候，如果证书有问题就回出CANCELLED。这里可以用error的metadata来区分不同类型的grpc错误。

2024-04-03 11:24 UTC, ddadaal commented on apps/mis-server/src/plugins/clusters.ts
>            details: reason,
这里可以把出错的每个集群的id以及错误放在metadata里作为一个数组一起传到前端，这样前端就能够获得足够多的信息进行进一步处理。尽量避免在后端做面向用户的数据或者错误展示（这里的reason是返回给前端的，最终可能会给用户看，所以应该进可能保留信息。打到log的时候，就应该后端负责把错误信息渲染出字符串给开发者看了，但是也要注意尽可能保留信息）

2024-04-03 11:24 UTC, ddadaal commented on apps/mis-web/src/utils/route.ts
> +        const clusterId = e.metadata.get("clusterId")[0] ?? undefined;
在通用的函数里对一些常见的错误进行处理是可以的，但是也要考虑到可扩展性。这里是特殊处理了后端有clusterId这个字段的情况，也就是当后端scow error code是`ADAPTER_CALL_ON_ONE_ERROR`；那同样的道理，这里也可以同时处理多个集群操作失败，也就是错误码`CLUSTEROPS_ERROR_CODE`的情况，而这种情况下metadata所函数的数据又不一样。所以这里的代码也需要考虑可扩展性。

最终这里的数据都会给前端，让前端读取code和数据来渲染正确的错误信息。所以这里应该做的事情，是根据不同的code把对应的code的metadata里存的信息都放到返回的500错误里，使得前端直接读取到code和metadata，并直接做进一步处理（比如把错误给用户展示出来）

2024-04-03 11:24 UTC, ddadaal commented on apps/portal-web/src/utils/getClusterConnError.tsx
> +export const getClusterConnError =
不用缩写，名字长无所谓，方便理解，getClusterConnectionError

2024-04-03 11:24 UTC, ddadaal commented on apps/mis-web/src/utils/route.ts
> +        const clusterId = e.metadata.get("clusterId")[0] ?? undefined;
另外这个返回在500错误里的clusterId在哪里用到了吗？我似乎没有找到

2024-04-03 13:06 UTC, piccaSun commented on apps/mis-web/src/utils/route.ts
> +        const clusterId = e.metadata.get("clusterId")[0] ?? undefined;
这里单独传clusterId是为了实现全局错误处理的集群名字的国际化
适配器无法连接的时候考虑直接提示 **xxx集群无法连接**
如果写在500的metadata里，那么就不考虑将集群名字进行国际化展示了？

在入口文件_app.tsx下全局错误处理判断ADAPTER_CALL_ON_ONE_ERROR时使用
```
 if (e.data?.code === "ADAPTER_CALL_ON_ONE_ERROR") {
        const clusterName = e.data.clusterId ?
          (publicConfig.CLUSTERS[e.data.clusterId]?.name ?? e.data.clusterId) : undefined;

        message.error(`${tArgs("page._app.adapterConnErrorContent",
          [getI18nConfigCurrentText(clusterName, languageId)])}(${
          e.data.details
        })`);
        return;
      }
```

2024-04-03 13:15 UTC, piccaSun commented on apps/mis-server/src/plugins/clusters.ts
>            details: reason,
这个地方是之前有需求故意把错误的详细信息暴露出来 #823 
我再确认一下，确认之后把相关的详细的details都修改为从后端日志打印

2024-04-07 11:51 UTC, piccaSun commented on apps/portal-web/src/pages/api/app/getAppSessions.ts
> +    503: Type.Object({
门户利用callOnOne扔出了全局错误，判断方法暂时同Mis一样,不再单独判断HTTP STATUS，请确认

2024-04-07 11:56 UTC, piccaSun commented on apps/mis-web/src/utils/route.ts
> +        const clusterId = e.metadata.get("clusterId")[0] ?? undefined;
修改为将错误集群信息以数组形式传入metadata到前端再处理
但是因为metadata的ts校验类型主要为MetadataValue| MetadataValue[], 数组类型校验不好通过。 考虑到错误信息不涉及到数组排序，暂时通过序列化反序列化处理后端和前端，请确认

2024-04-08 13:51 UTC, ddadaal approved these changes

2024-04-08 13:51 UTC, ddadaal commented on apps/portal-server/src/utils/clusters.ts
> +export const callOnOne: CallOnOne = async (cluster, logger, call) => {
这个函数很好

2024-04-11 08:09 UTC, lyl-available approved these changes

2024-04-11 12:47 UTC, merged