feat: 接入 scowd
PKUHPC/SCOW pull request #1193
Opened 2024-04-02 01:40 UTC by Miracle575

2024-04-18 14:08 UTC, ddadaal requested changes

2024-04-18 14:08 UTC, ddadaal commented on apps/portal-server/src/config/env.ts
> +  SCOWD_ENABLED: bool({ desc: "是否开启 SCOWD", default: false }),
现在实际上调用的grpc service是多态的，是否启用scowd影响不同的service，但是更好的方式应该是抽象在clusterops部分，apps/portal-server/src/clusterops这里已经为job和app定义了接口，job和app部分的grpc service会调用clusterops部分的逻辑，不同的cluster可以用不同的clusterops逻辑。这样可以支持有的cluster启用了scowd，有的没有的场景

2024-04-18 14:08 UTC, ddadaal commented on libs/config/src/cluster.ts
> +  });
address和scowdUrl是互斥的吗？如果是的话，应该设计设计一个type用于区分具体的类型：

```yaml
name: 名字
connectionType: ssh #或者scowd，默认值为ssh，以兼容原来的配置
address: # 不变，以兼容原来的配置。如果是type是ssh则必填
scowd: # 如果connectionType是scowd必填
    url: # scowd配置 必填
```

2024-04-22 03:03 UTC, Miracle575 commented on apps/portal-server/src/utils/scowd.ts
> +export function convertCodeToGrpcStatus(code: Code): status {
这个翻了一下文档，只看到 转为 http 的 status code 的，没找到转为 grpc 的

2024-04-25 07:58 UTC, Miracle575 commented on libs/config/src/cluster.ts
> +  });
将配置改为集群级别
```
scowd:
  enabled: true
  
loginNodes:
  - name: login
    address:  address
    scowd:
      port: 9999
```

2024-04-25 11:12 UTC, ddadaal requested changes
写scowd相关的配置文档，可以先写在飞书里看看

2024-04-25 11:12 UTC, ddadaal commented on apps/portal-server/src/clusterops/api/file.ts
> +  Exists(req: ExistsRequest, logger: Logger): Promise<ExistsReply>;
js命名规范是camelCase

2024-04-25 11:12 UTC, ddadaal commented on apps/portal-server/src/clusterops/file/scowdFile.ts
> +      await client.file.copy({ fromPath, toPath }, { headers: { IdentityId: userId } });
userId是参数，直接加在request里就行了，加在header有什么好处吗？

2024-04-25 11:12 UTC, ddadaal commented on apps/portal-server/src/utils/scowd.ts
> +export function convertCodeToGrpcStatus(code: Code): status {
可以去对比一下，connect的code和grpc的code定义是一模一样的，不需要转换

2024-04-25 11:12 UTC, ddadaal commented on apps/portal-server/src/clusterops/desktop/scowdDesktop.ts
> +    }
这种没有进一步逻辑的错误处理不需要了。grpc server的错误处理逻辑是：如果throw了，拿到throw的东西，将throw的东西的`code`属性作为grpc状态码，`details`作为grpc的`details`。而ConnectError完全符合这个规则：有code而且connect的code定义和grpc一模一样，有details、有message，所以完全不需要处理逻辑，throw了grpc server自然就正确处理错误了。

2024-04-27 06:55 UTC, ddadaal requested changes

2024-04-27 06:55 UTC, ddadaal commented on apps/portal-server/src/utils/scowd.ts
> +};
如果所有getScowdClient的调用都会在返回undefined的时候报错，可以把异常直接写在这个函数里，即使不是，也需要显式指定返回值为可能是undefined的，以免调用者忘记处理undefined的情况。

2024-04-27 06:55 UTC, ddadaal commented on libs/scowd/src/ssl.ts
> +      rejectUnauthorized: false,
这个参数如果设置成了false会禁用客户端对服务器端（scowd）的身份验证，整个过程实际上就不是双向认证（客户端和服务器端互相验证对方的身份），而只有服务器端验证客户端的身份了。应该设置为true，检查一下签证书的过程是不是有问题。

2024-04-28 02:03 UTC, Miracle575 commented on libs/scowd/src/ssl.ts
> +      rejectUnauthorized: false,
翻了一下源码，对于 rejectUnauthorized 这个配置说明如下
```
/**
 * If true the server will reject any connection which is not
 * authorized with the list of supplied CAs. This option only has an
 * effect if requestCert is true.
 * @default true
*/
rejectUnauthorized?: boolean | undefined;
/**
 * If true the server will request a certificate from clients that
 * connect and attempt to verify that certificate. Defaults to
 * false.
 */
requestCert?: boolean | undefined;
```
由于 requestCert 默认为 false, 我在此处并未配置 requestCert，所以 rejectUnauthorized 的配置并没有起作用。
测试了一下，如果 scowd 关闭 ssl 或者配置错误的证书 scow 是验证不通过的。说明 scow ssl 验证已正常开启。目前，我已将这个  rejectUnauthorized 参数删除

2024-04-28 02:03 UTC, Miracle575 commented on apps/portal-server/src/utils/scowd.ts
> +};
考虑直接从这个函数中抛出异常

2024-06-12 23:40 UTC, ddadaal approved these changes

2024-06-14 03:47 UTC, lyl-available approved these changes

2024-06-18 13:29 UTC, merged