feat(mis-web):账户白名单、账户消费记录下都支持以用户ID和姓名搜索
PKUHPC/SCOW pull request #1195
Opened 2024-04-02 08:16 UTC by usaveh

# 做了什么：
![image](https://github.com/PKUHPC/SCOW/assets/72734623/c66fe0d6-8b1c-4ec7-889d-66af36afd3e1)
支持以用户名和用ID搜索

_
![image](https://github.com/PKUHPC/SCOW/assets/72734623/972c6651-6d2c-4494-9409-dd21cf2a5489)
支持用户名和用户ID搜索

2024-04-02 09:12 UTC, ddadaal requested changes
changeset

2024-04-10 11:10 UTC, ddadaal commented
这个功能后面还要改吗？不改了request review

2024-04-11 01:48 UTC, usaveh commented
不改了

2024-04-11 12:47 UTC, ddadaal requested changes

2024-04-12 11:00 UTC, ddadaal approved these changes

2024-04-12 13:32 UTC, merged