faet(mis) : 管理系统平台数据统计作业提交用户前十数横坐标改为userName
PKUHPC/SCOW pull request #1206
Opened 2024-04-11 05:56 UTC by usaveh

### 做了什么
1.管理系统->平台数据统计->用户提交TOP10，横坐标改为userName
![368260221c753d5de6ce002ca3bafd1](https://github.com/PKUHPC/SCOW/assets/72734623/b0e80829-fb2f-4526-bba0-ac3ce778920e)
![ad2ee8bb6ccb1897dcd277e3bc29692](https://github.com/PKUHPC/SCOW/assets/72734623/c8081f48-3ff6-4c1f-a436-b3295c69fe91)

2024-04-11 12:57 UTC, ddadaal requested changes

2024-04-11 12:57 UTC, ddadaal commented on .changeset/great-carrots-refuse.md
> +"@scow/grpc-api": major
默认patch，使用minor会造成SCOW的出现1.5.0->1.6.0的变化，要此变化需要找李老师确认。

2024-04-11 12:57 UTC, ddadaal commented on apps/mis-server/src/services/job.ts
> +      }
使用join在一条SQL语句里查询到所有信息

2024-04-11 12:57 UTC, ddadaal commented on apps/mis-server/src/services/job.ts
> +      const { startTime, endTime, topRank = 10 } = ensureNotUndefined(request, ["startTime", "endTime"]);
topRank应该给予一定限制，不能无限制查询，可以设置最高查10

2024-04-11 12:57 UTC, ddadaal commented on protos/server/job.proto
> +  rpc GetTopSubmitJobUserName(GetTopSubmitJobUserNameRequest) returns (GetTopSubmitJobUserNameResponse);
API改名：`GetUsersWithMostJobSubmissions`

2024-04-11 12:57 UTC, ddadaal commented on protos/server/job.proto
> +    uint32 count = 2;
把user_id也传回来

2024-04-11 12:57 UTC, ddadaal commented on protos/server/job.proto
> +  message SubmitJobUser {
UserInfo即可，因为这个message是包括在Response里面的，无需考虑名字撞车问题

2024-04-11 12:57 UTC, ddadaal commented on protos/server/job.proto
> +  optional uint32 top_rank = 3;
top_n_users

2024-04-12 10:46 UTC, usaveh commented on apps/mis-server/src/services/job.ts
> +      }
这两个表没有关联，只通过string关联＞︿＜

2024-04-15 03:04 UTC, usaveh commented on .changeset/great-carrots-refuse.md
> +"@scow/grpc-api": major
已向李老师确认，patch

2024-04-15 03:05 UTC, usaveh commented on apps/mis-server/src/services/job.ts
> +      }
优化了一下逻辑，使用find，减少阻塞次数

2024-04-15 03:05 UTC, usaveh commented on apps/mis-server/src/services/job.ts
> +      const { startTime, endTime, topRank = 10 } = ensureNotUndefined(request, ["startTime", "endTime"]);
已修改

2024-04-15 03:05 UTC, usaveh commented on protos/server/job.proto
> +  rpc GetTopSubmitJobUserName(GetTopSubmitJobUserNameRequest) returns (GetTopSubmitJobUserNameResponse);
已修改

2024-04-15 03:05 UTC, usaveh commented on protos/server/job.proto
> +    uint32 count = 2;
已修改

2024-04-15 03:06 UTC, usaveh commented on protos/server/job.proto
> +  message SubmitJobUser {
已修改

2024-04-15 03:06 UTC, usaveh commented on protos/server/job.proto
> +  optional uint32 top_rank = 3;
已修改

2024-04-15 11:24 UTC, ddadaal requested changes

2024-04-15 11:24 UTC, ddadaal commented on apps/mis-server/src/services/job.ts
> +      const users = await em.find(User, { userId: { $in: userIds } });
使用数据库的Join在一个SQL查询出最终结果。可以参考copilot的结果：

![image](https://github.com/PKUHPC/SCOW/assets/8363856/f207909c-f2ea-4ebd-8c44-de030f716895)

2024-04-16 09:31 UTC, usaveh commented on apps/mis-server/src/services/job.ts
> +      const users = await em.find(User, { userId: { $in: userIds } });
已解决

2024-04-16 09:31 UTC, usaveh commented on apps/mis-web/src/pages/admin/statistic.tsx
> +  useAsync({ promiseFn: getUsersWithMostJobSubmissionsFn });
已解决

2024-04-17 08:14 UTC, usaveh commented on apps/mis-server/src/services/job.ts
> +      const { startTime, endTime, topNUsers = 10 } = ensureNotUndefined(request, ["startTime", "endTime"]);
已解决

2024-04-17 08:14 UTC, usaveh commented on apps/mis-web/src/pages/api/admin/getUsersWithMostJobSubmissions.ts
> +    topNUsers: Type.Optional(Type.Number()),
已解决

2024-04-17 08:14 UTC, usaveh commented on apps/mis-server/src/services/job.ts
> +        .limit(Math.max(topNUsers, 10));
ok

2024-04-17 08:22 UTC, usaveh commented on apps/mis-server/src/services/job.ts
> +      const results: {userName: string, userId: string, count: number}[] = await knex("job_info as j")
和同事讨论了试了蛮久，整不出来

2024-04-17 11:01 UTC, ddadaal approved these changes

2024-04-17 11:01 UTC, ddadaal commented on apps/mis-server/src/services/job.ts
> +        throw new Error("INVALID_ARGUMENT: 'topNUsers' must be lower than 10.");
grpc错误有专门的抛出方式，参考apps/mis-server/src/plugins/clusters.ts

```ts
import { ServiceError } from "@ddadaal/tsgrpc-common";

throw new ServiceError({ code: status.INVALID_ARGUMENT, message: "" });`
```

2024-04-17 11:01 UTC, ddadaal commented on apps/mis-server/src/services/job.ts
> +      const results: {userName: string, userId: string, count: number}[] = await knex("job_info as j")
那算了

2024-04-17 11:02 UTC, ddadaal requested changes

2024-04-17 11:02 UTC, ddadaal commented on apps/mis-server/src/services/job.ts
> +      }
grpc错误有专门的抛出方式：

```ts
// apps/mis-server/src/plugins/clusters.ts
import { ServiceError } from "@ddadaal/tsgrpc-common";
import { status } from "@grpc/grpc-js";

throw new ServiceError({ code: status.INVALID_ARGUMENT, message: ""});
```

2024-04-18 12:27 UTC, ddadaal approved these changes

2024-04-18 12:27 UTC, merged