fix(ai):  修复 trpc openapi 将 boolean params 全部转为 string 的问题
PKUHPC/SCOW pull request #1220
Opened 2024-04-24 03:02 UTC by ZihanChen821

参照： https://github.com/jlalmes/trpc-openapi/pull/219

将 input 里的z.boolean() -> z.corece.boolean()既可以让trpc-openapi处理boolean参数

2024-04-24 12:17 UTC, ddadaal requested changes

2024-04-24 12:17 UTC, ddadaal commented on apps/ai/src/server/trpc/route/algorithm/algorithm.ts
> +    isPublic:z.coerce.boolean().optional(),
根据文档 （ https://zod.dev/?id=coercion-for-primitives ），boolean coerce的结果是根据js值是否truthy来确定的，比如`"false"`也是true，这应该不是预期结果。这样的话，为了避免歧义所有querystring中使用boolean值的地方应使用`z.union([z.literal("true"), z.literal("false")])`的方式定义，只让传`"true"`或者`"false"`。按如下方式定义一个`booleanQueryParam`函数并使用

```ts
const booleanQueryParam = () => z.union([z.literal("true"), z.literal("false")]);

isPublic: booleanQueryParam(),
```

2024-04-25 08:43 UTC, ZihanChen821 commented on apps/ai/src/server/trpc/route/algorithm/algorithm.ts
> +    isPublic:z.coerce.boolean().optional(),
已改， 并且加了transform 保证server端逻辑不受影响。

2024-04-25 10:58 UTC, ddadaal approved these changes

2024-04-25 10:58 UTC, merged