Feat ai re submit job
PKUHPC/SCOW pull request #1225
Opened 2024-04-25 02:14 UTC by ZihanChen821

2024-05-13 21:23 UTC, ddadaal requested changes
描述里加一个gif或者截图演示一下功能

2024-05-13 21:23 UTC, ddadaal commented on apps/ai/src/app/(auth)/jobs/[clusterId]/AppSessionsTable.tsx
> +                  `?jobId=${record.jobId}&jobName=${record.sessionId}`));
之后最好不要自己处理querystring哈，用URLSearchParams类

2024-05-13 21:23 UTC, ddadaal commented on apps/ai/src/server/trpc/route/jobs/jobs.ts
> +        // 确保所有映射到容器的路径都不重复s
s?

2024-05-13 21:24 UTC, ddadaal requested changes

2024-05-13 21:24 UTC, ddadaal commented on apps/ai/src/server/trpc/route/jobs/apps.ts
> +        path: "/appSessions/{jobId}/params",
params -> submissionParamaters

2024-05-14 06:31 UTC, ZihanChen821 commented on apps/ai/src/app/(auth)/jobs/[clusterId]/AppSessionsTable.tsx
> +                  `?jobId=${record.jobId}&jobName=${record.sessionId}`));
已修改

2024-05-14 21:09 UTC, ddadaal requested changes
changeset

2024-05-15 20:34 UTC, ddadaal approved these changes

2024-05-15 20:35 UTC, ddadaal commented
看你还没有request review，所以我先不合并，如果决定没有后续的修改的话可以直接合并

2024-05-16 00:54 UTC, merged