style(mis): 计费调整精确到分
PKUHPC/SCOW pull request #1236
Opened 2024-05-01 01:19 UTC by cuvalign

涉及到金额的显示页面，全部只展示到分，涉及到金额的输入页面，全部限制为只允许输入精确到分。涉及到金额的导出，也全部只展示到分。
1. 仪表盘：
  a. 账户信息：“可用余额”；
2. 用户空间：
  a. 已结束的作业： “作业计费合计”、“作业计费”、“详情-作业计费”；
  b. 集群和分区信息：“单价”；
  c. 操作日志中，操作内容相关；
3. 账户管理：
  a. 账户信息：“账户余额”、“封锁阈值”；
  b. 已结束的作业： “作业计费合计”、“作业计费”、“详情-作业计费”；
  c. 用户管理：“已用额度/用户限额”、“限额管理-当前已使用/总限额”、“限额管理-修改限额至”；
  d. 充值记录：“合计”、“交费金额”；
  e. 消费记录：“合计”、“扣费金额”；
4. 租户管理
  a. 租户信息：“租户余额”、“默认账户封锁阈值”、“设置默认账户封锁阈值”；
  b. 作业价格表： “单价（元）”、“设置计费价格-单价（元）”；
  c. 已结束的作业：“租户计费"、"平台计费”、详情中的“租户计费"、"平台计费”、“租户计费合计”、“平台计费合计”；
  d. 账户列表中所有金额相关；
  e. 白名单账户列表所有金额相关；
  f. 账户充值限制只能充值金额精确到分；
  g. 账户充值记录、租户充值记录、账户消费记录、操作日志所有金额相关；
5. 平台管理：
  a. 作业计费价格表、租户列表、账户列表所有金额相关；
  b. 充值记录、账户消费记录、操作日志所有金额相关；
  c. 平台数据统计：消费列，金额显示精确到分：消费/充值金额，可视图表金额显示精确到分，坐标轴动态tick动态精确到分。

2024-05-05 14:31 UTC, ddadaal requested changes
style是用于代码风格、不涉及功能的，这个就是一个正常的fix

2024-05-05 14:31 UTC, ddadaal commented on apps/mis-web/src/pageComponents/admin/DataBarChart.tsx
> +  const tickFormatter = (value) => {
限制value类型

2024-05-05 14:31 UTC, ddadaal commented on apps/mis-web/src/pageComponents/admin/DataBarChart.tsx
> +  };
不判断现在的位数，直接toFixed(2)可以吗？

2024-05-06 02:25 UTC, cuvalign commented on apps/mis-web/src/pageComponents/admin/DataBarChart.tsx
> +  };
会造成如下问题：
<img width="824" alt="5b0fc41ea6d342e359af273d00a2524" src="https://github.com/PKUHPC/SCOW/assets/78541912/30bfce79-9f17-4f37-b1a7-9617f5ef0bc8">

2024-05-06 02:31 UTC, cuvalign commented on apps/mis-web/src/pageComponents/admin/DataBarChart.tsx
> +  };
这里改写：  const tickFormatter = (value: number) => {
    const roundedValue = Number.isInteger(value) ? value : parseFloat(value.toFixed(2));
    return roundedValue.toString();
  };
number限制value类型，整数返回整数，两位小数以上限制两位小数，一位小数如0.30通过parseFloat限制为0.3

2024-05-06 15:39 UTC, ddadaal commented on apps/mis-web/src/pageComponents/admin/DataBarChart.tsx
> +  };
这样好

2024-05-06 15:39 UTC, ddadaal approved these changes

2024-05-06 15:40 UTC, merged