fix(mis&portal): 表格新增对列进行排序，修改了部分UI的样式
PKUHPC/SCOW pull request #1238
Opened 2024-05-06 02:20 UTC by usaveh

修改了部分UI的样式
![image](https://github.com/PKUHPC/SCOW/assets/72734623/e458f864-ac5a-4a20-a1dc-f52999ec5990)
HPC->超算平台

![image](https://github.com/PKUHPC/SCOW/assets/72734623/464f3303-3588-4f82-87a1-5ac1ebfda5d4)
使用率的文字颜色会根据数字大小变换，并且改为两位小数

新增了portal、mis中大部分表格的列排序功能

2024-05-06 15:46 UTC, ddadaal requested changes

2024-05-06 15:46 UTC, ddadaal commented on apps/ai/src/app/(auth)/layout.tsx
> +            linkText="超算平台"
这个如果要用中文的话，就得用国际化。原来SCOW HPC本来就是英文可以接受。另外也可以直接用HPC，更简单一点。

2024-05-06 15:46 UTC, ddadaal commented on protos/audit/operation_log.proto
> +  optional string sort_order = 5;
这个选项应该不是什么值都可以填的，而是一个enum吧？

2024-05-06 15:46 UTC, ddadaal commented on apps/mis-web/src/pages/api/finance/charges.ts
> +    sortOrder:Type.Optional(Type.String()),
这里也限制取值

2024-05-06 15:46 UTC, ddadaal commented on apps/mis-web/src/i18n/en.ts
> +      navLinkTextPortal: "Supercomputer Platform",
这个太长了，HPC就行

2024-05-06 15:46 UTC, ddadaal commented on .changeset/great-eyes-hammer.md
> +"@scow/grpc-api": patch
API单独写一个changeset，介绍改了什么地方，目前是用户直接看changelog就知道哪些API怎么改了。另外现在的API只要有实际上的变化都至少是minor

2024-05-07 07:25 UTC, usaveh commented on apps/ai/src/app/(auth)/layout.tsx
> +            linkText="超算平台"
这部分的改动迁移至另一个PR中

2024-05-09 13:04 UTC, ddadaal requested changes
pr的description也改一下，只包含这个PR里的内容

2024-05-10 10:16 UTC, ddadaal requested changes

2024-05-10 10:16 UTC, ddadaal commented on protos/server/charging.proto
> +    UNKNOW = 0;
UNKNOWN

2024-05-10 10:16 UTC, ddadaal commented on protos/common/sort_order.proto
> +  DEFAULT = 2;
那DEFAULT的排序是什么意思？和ascent和descend有啥区别？

2024-05-10 15:37 UTC, usaveh commented on protos/common/sort_order.proto
> +  DEFAULT = 2;
Default 是不排序，按照数据库中原本的顺序导出

2024-05-13 21:33 UTC, ddadaal commented on protos/common/sort_order.proto
> +  DEFAULT = 2;
如果写了SortBy了但是不写SortOrder，那默认就是ASCEND了；但是如果只写了SortOrder，没写SortBy，那SortOrder也不管写什么都没有意义。所以default这个选项没有意义，直接删掉，ASCEND就是默认值

2024-05-13 21:35 UTC, ddadaal requested changes

2024-05-13 21:35 UTC, ddadaal commented on apps/audit-server/src/services/operationLog.ts
> +        break;
这种switch case写成map，orderby也是

```ts
const sorterMap = {
   [GetOperationLogsRequest_SortBy.ID]: "id",
};

const sorter = sorterMap[sortBy];
```

2024-05-15 20:33 UTC, ddadaal approved these changes

2024-05-15 20:33 UTC, merged