fix(mis): 在管理系统修改用户密码时配置的正则不生效
PKUHPC/SCOW pull request #1253
Opened 2024-05-13 06:49 UTC by piccaSun

**背景**

使用`typebox`时会沿用之前的特殊注释以优化为可进行后端校验
但是由于更改用户密码时` passwordPattern`是可配置的，`@pattern`注释应为默认值而不是真正的校验值
在转化为`typebox`类型时被执行进代码，导致`common.yml`中即使更改了配置，在页面也可以正常显示，但是无法通过接口参数校验
此PR优化`@pattern`注释的描述，删除`typebox`中的`pattern`属性定义

**修复前**

```
common.yml

passwordPattern:
  # 正则表达式。下面为默认值
  regex: ^(?=.*[a-zA-Z])(?=.*[`~!@#\$%^&*()_+\-[\];',./{}|:"<>?]).{8,}$

  # 出错时的消息。下面为默认值
  errorMessage: 必须包含数字和符号，长度大于等于8位
```

页面显示正常
![image](https://github.com/PKUHPC/SCOW/assets/43978285/a0eb580d-3d88-4ea9-8c98-e31c80ec6ab4)
但是接口请求参数校验失败，提示正则不满足包含数字
![image](https://github.com/PKUHPC/SCOW/assets/43978285/7ff9f87e-d75c-4810-a7ac-8475b8550eb8)

**修复后**
可正常修改密码

2024-05-13 21:10 UTC, ddadaal requested changes

2024-05-13 21:10 UTC, ddadaal commented on apps/mis-web/src/pages/api/admin/changePassword.ts
> -    }),
这里删了验证后，那整个修改密码的pattern就没地方用到了？要么在这里使用配置中的配置，要么在handler里手动根据配置验证

2024-05-14 01:39 UTC, piccaSun commented on apps/mis-web/src/pages/api/admin/changePassword.ts
> -    }),
pattern实际用在了前端校验，看了整个scow涉及到common.yaml配置文件中的PASSWORD_PATTERN，全部是前端验证，只有这两个地方前期增加了@pattern的注释，在不使用typebox之前，@pattern其实也不会写入代码进行验证，只能作为一个注释提示

正则逻辑实际来源于commonConfig,最好还是把涉及到password_pattern的相关接口都追加一下400的错误处理吗？

2024-05-14 21:10 UTC, ddadaal commented on apps/mis-web/src/pages/api/admin/changePassword.ts
> -    }),
对的，前端校验是不够的，正好PR发现了这个问题就顺便解决一下，在web后端和server都根据配置中的格式检查一下输入

2024-05-18 13:55 UTC, ddadaal approved these changes

2024-05-18 13:56 UTC, merged