feat(ai): AI增加多机多卡 分布式训练
PKUHPC/SCOW pull request #1261
Opened 2024-05-22 02:39 UTC by ZihanChen821

2024-07-12 13:06 UTC, ddadaal requested changes

2024-07-12 13:06 UTC, ddadaal commented on libs/protos/scheduler-adapter/package.json
> +    "generate": "rimraf generated && buf generate --template buf.gen.yaml https://github.com/PKUHPC/scow-scheduler-adapter-interface.git#branch=feat-ai-release",
这个功能准备好了吗？如果准备好了，适配器接口需要发布一个新的版本，并且这个功能需要检查集群的适配器的版本是否是已经实现了新的接口的新版本。

2024-07-16 02:51 UTC, OYX-1 commented on libs/protos/scheduler-adapter/package.json
> +    "generate": "rimraf generated && buf generate --template buf.gen.yaml https://github.com/PKUHPC/scow-scheduler-adapter-interface.git#branch=feat-ai-release",
现在scow的master上就是feat-ai-release这个分支，不是版本号。
要在adapter-interface仓库里把feat-ai-release合到master中才能继续之前的检查适配器版本操作。
当时好像是说ai模块还是beta版就先不合

2024-07-18 09:03 UTC, ddadaal commented on libs/protos/scheduler-adapter/package.json
> +    "generate": "rimraf generated && buf generate --template buf.gen.yaml https://github.com/PKUHPC/scow-scheduler-adapter-interface.git#branch=feat-ai-release",
https://github.com/PKUHPC/SCOW/pull/1361 已经合并了，这个PR的proto修改是只对AI的吧？那就

1. 在接口项目中，发起一个PR，把这个功能所用到的修改合并到ai的分支里
2. 当接口合并到AI的分支后，SCOW项目的本分支合并master，然后在ai项目用的proto项目里用ai的分支

2024-07-18 11:45 UTC, OYX-1 approved these changes

2024-07-22 14:08 UTC, ddadaal requested changes
https://github.com/PKUHPC/scow-scheduler-adapter-interface/pull/25#discussion_r1686618467

2024-07-25 01:39 UTC, merged

2024-07-25 01:39 UTC, ddadaal approved these changes