feat(portal): 门户系统部分UI更新
PKUHPC/SCOW pull request #1277
Opened 2024-05-31 07:24 UTC by usaveh

2024-05-31 09:07 UTC, ddadaal requested changes
1. 黑暗模式下用户信息部分颜色看不清，能否也改回红色？

![image](https://github.com/PKUHPC/SCOW/assets/8363856/bbe70056-3607-4848-aab8-06939cba64cf)

2. 到MIS出现了两个图标，只保留左边那个就行
![image](https://github.com/PKUHPC/SCOW/assets/8363856/b76f75d1-0d63-426f-a916-bb552796ab4d)

3. 首页快速链接的那几个图标的主题色能不能和系统的主题色统一？

2024-06-03 02:52 UTC, usaveh commented
> 1. 黑暗模式下用户信息部分颜色看不清，能否也改回红色？
> 
> ![image](https://private-user-images.githubusercontent.com/8363856/335513465-bbe70056-3607-4848-aab8-06939cba64cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODMyODksIm5iZiI6MTcxNzM4Mjk4OSwicGF0aCI6Ii84MzYzODU2LzMzNTUxMzQ2NS1iYmU3MDA1Ni0zNjA3LTQ4NDgtYWFiOC0wNjkzOWNiYTY0Y2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDNUMDI0OTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTgxNWRjOWY3YTdiNTRlYzZmNDE5ZDFjNDE0MzEyNThhMDAxYTBhMTc0ZDcwYTNmYjViMWU2NTkwYTZmOTExZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pqzrftu6QSXY4KGQ8UcLImMviaeyxtl_AjUoxJo82tU)
> 
> 2. 到MIS出现了两个图标，只保留左边那个就行
>    ![image](https://private-user-images.githubusercontent.com/8363856/335513547-b76f75d1-0d63-426f-a916-bb552796ab4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODMyODksIm5iZiI6MTcxNzM4Mjk4OSwicGF0aCI6Ii84MzYzODU2LzMzNTUxMzU0Ny1iNzZmNzVkMS0wZDYzLTQyNmYtYTkxNi1iYjU1Mjc5NmFiNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDNUMDI0OTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWVkMmQyNDAxM2ExY2RjYTk3N2ZlNTIyZTgzZWIzODEwMDk5NmU3NzJmNTg2NzA0ZDQwYzE5YjdlMjgzN2VmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9guGY1GCCOkcpqnc3-HNIBXDj3jRkSZYqlHsM7caLoM)
> 3. 首页快速链接的那几个图标的主题色能不能和系统的主题色统一？
 
1：okk
2，3：目前设计稿是这样的，和若淼老师确认过。

2024-06-03 05:54 UTC, vanstriker commented
2、我感觉也可以去掉右边那个；
3、主题色这个是指什么，咱们自己设计的图标应该是和主题色一致的吧

2024-06-12 23:39 UTC, ddadaal requested changes
SCOW是可以改主题色的，图中的主题色就是默认的红色 ：https://pkuhpc.github.io/SCOW/docs/deploy/config/customization/webui#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%BB%E9%A2%98%E8%89%B2%E5%92%8Cfooter%E6%96%87%E6%9C%AC 。

理论上来说，通过修改svg的部分区域的颜色可以做到让SVG的颜色和主题色相统一，可以试试看这样做起来是不是比较复杂。如果比较复杂，或者效果不好，需要重新设计图标，使得图标和主题色无关，也就是图标在任何主题色都不会显得违和

2024-06-19 09:18 UTC, usaveh commented
> SCOW是可以改主题色的，图中的主题色就是默认的红色 ：https://pkuhpc.github.io/SCOW/docs/deploy/config/customization/webui#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%BB%E9%A2%98%E8%89%B2%E5%92%8Cfooter%E6%96%87%E6%9C%AC 。
> 
> 理论上来说，通过修改svg的部分区域的颜色可以做到让SVG的颜色和主题色相统一，可以试试看这样做起来是不是比较复杂。如果比较复杂，或者效果不好，需要重新设计图标，使得图标和主题色无关，也就是图标在任何主题色都不会显得违和

已针对上述问题修改为主题色

2024-06-19 12:14 UTC, ddadaal approved these changes

2024-06-19 12:56 UTC, merged