fix(docs): 添加SCOW部署流程文档
PKUHPC/SCOW pull request #1294
Opened 2024-06-12 07:20 UTC by huangjun0210

2024-06-17 11:58 UTC, ddadaal requested changes

2024-06-17 11:58 UTC, ddadaal commented on docs/blog/2024-06-17-scow-deploy-process.md
博客一般用于介绍**后续不会继续修改**的**事件**，比如发布一个版本的时候介绍新版本的新功能，开了一次交流会之后介绍交流会提到的东西。而这篇文档不是描述一个事件，而是一个部署和运维的总览性质的文章，后续可能会一直更新，所以不适合发布为一篇博客，而可以作为一篇文档，放在如下位置，取名为**部署和运维指引**，并进行一些修改：

![image](https://github.com/PKUHPC/SCOW/assets/8363856/1dc3af66-6bd6-4e6f-8b78-a95c358ebc1d)

2024-06-17 11:58 UTC, ddadaal commented on docs/blog/2024-06-17-scow-deploy-process.md
> +5. 登录节点安装桌面，例如Xfce、KDE、MATE等。
1. 准备集群环境

2024-06-17 11:58 UTC, ddadaal commented on docs/blog/2024-06-17-scow-deploy-process.md
> +- 与slurm集群各节点网络可达，或者至少与slurm集群登录节点和管理节点网络可达([代理网关方案](/docs/deploy/config/portal/proxy-gateway))。
2. 准备SCOW部署节点

2024-06-17 11:58 UTC, ddadaal commented on docs/blog/2024-06-17-scow-deploy-process.md
> +## 1.2 编译和部署适配器
3. 编译和部署适配器

2024-06-17 11:58 UTC, ddadaal commented on docs/blog/2024-06-17-scow-deploy-process.md
> +## 1.3 配置SCOW
4. 安装和配置SCOW

2024-06-17 11:58 UTC, ddadaal commented on docs/blog/2024-06-17-scow-deploy-process.md
> +## 1.3 配置SCOW
并在此部分增加至现有安装相关文档的链接：

> 点击此处 docs/category/安装 了解更多安装相关信息

2024-06-17 11:58 UTC, ddadaal commented on docs/blog/2024-06-17-scow-deploy-process.md
> +## 1.3 配置SCOW
[安装部分的文档](https://pkuhpc.github.io/SCOW/docs/deploy/install)重复的内容可以删掉，比如集群要求、安装docker、调度器适配器部分

2024-06-17 11:58 UTC, ddadaal commented on docs/blog/2024-06-17-scow-deploy-process.md
> +# 2. 运维
5. 运维

2024-06-17 11:58 UTC, ddadaal commented on docs/blog/2024-06-17-scow-deploy-process.md
> +- [自定义系统语言](/docs/deploy/config/customization/custom-system-language)
列得有点多，就列10个左右最常用的就行，其他的让用户看左边的文档就行

2024-06-17 11:59 UTC, ddadaal commented on docs/blog/2024-06-17-scow-deploy-process.md
> +- [自定义系统语言](/docs/deploy/config/customization/custom-system-language)
可能需要后续整理一下现有的配置相关的文档

2024-06-18 00:09 UTC, huangjun0210 commented on docs/blog/2024-06-17-scow-deploy-process.md
写这篇文档的目的是给用户提供一个清单(不写具体操作细节)，用户拿着这个清单就知道部署SCOW需要做哪些事。从技术交流群中的提问感觉到，很多用户可能没有耐心把咱们的文档从头到尾读完，导致漏掉某个环节。

2024-06-18 00:10 UTC, huangjun0210 commented on docs/blog/2024-06-17-scow-deploy-process.md
> +5. 登录节点安装桌面，例如Xfce、KDE、MATE等。
这里是想把scow和slurm区分开。发现很多用户在部署scow的时候其实并不了解slurm，认为slurm、ldap等这些就是scow的一部分。

2024-06-18 00:24 UTC, huangjun0210 commented on docs/blog/2024-06-17-scow-deploy-process.md
> +## 1.3 配置SCOW
这里有些重复了。我想了下，是不是把这个文档的内容完善下就好了，不用新起一个文档？

2024-06-18 00:25 UTC, huangjun0210 commented on docs/blog/2024-06-17-scow-deploy-process.md
> +# 2. 运维
就写安装相关的，把运维去掉？

2024-06-18 00:26 UTC, huangjun0210 commented on docs/blog/2024-06-17-scow-deploy-process.md
> +## 1.3 配置SCOW
只写安装部分的，把运维去掉？

2024-06-18 12:53 UTC, ddadaal commented on docs/blog/2024-06-17-scow-deploy-process.md
对的，这个清单确实很重要。但是清单也是会后续更新的，所以最好也放在文档里。博客是描述一个事情的。

2024-06-18 12:55 UTC, ddadaal commented on docs/blog/2024-06-17-scow-deploy-process.md
> +5. 登录节点安装桌面，例如Xfce、KDE、MATE等。
也行，也可以把这个部分理解成前提条件

2024-06-18 12:59 UTC, ddadaal commented on docs/blog/2024-06-17-scow-deploy-process.md
> +## 1.3 配置SCOW
“这里有些重复了”“这个文档的内容”的这里和这个指的删除哪一篇，保留和完善哪一篇？我其实觉得直接完善[现有的安装文档](https://pkuhpc.github.io/SCOW/docs/deploy/install)就好了，内容确实差不多，这篇博客就不要了

2024-06-19 01:34 UTC, huangjun0210 commented on docs/blog/2024-06-17-scow-deploy-process.md
> +## 1.3 配置SCOW
是的，那就保留现有的安装文档，在这个上面改

2024-06-19 08:33 UTC, huangjun0210 commented on docs/blog/2024-06-17-scow-deploy-process.md
已移到安装文档

2024-06-19 08:33 UTC, huangjun0210 commented on docs/blog/2024-06-17-scow-deploy-process.md
> +## 1.3 配置SCOW
完善了安装文档

2024-06-19 08:34 UTC, huangjun0210 commented on docs/blog/2024-06-17-scow-deploy-process.md
> +- [自定义系统语言](/docs/deploy/config/customization/custom-system-language)
删除了一些

2024-06-19 10:36 UTC, ddadaal approved these changes

2024-06-19 10:36 UTC, merged