fix(portal): 作业提交页面修复并优化模板时间应用
PKUHPC/SCOW pull request #1302
Opened 2024-06-18 09:19 UTC by cuvalign

![image](https://github.com/PKUHPC/SCOW/assets/78541912/8b9ac8ed-6020-4a6c-8526-47b8d1296073)
### 要修复问题
1.从模板值中获取到的时间无法填入
2.因为新增了时间单位，模板文件中保存的只有分钟所以无法换算回分钟以外的单位
<img width="302" alt="1d0a79840fb94fee37610e85dc107bc" src="https://github.com/PKUHPC/SCOW/assets/78541912/0f47fec2-a763-4c91-81a1-dbbe1d67a4ce">
3.最长运行时间为空时，提示不随中英文切换变动
### 修复方法
1.增加最长运行时间的时间单位
<img width="302" alt="1d0a79840fb94fee37610e85dc107bc" src="https://github.com/PKUHPC/SCOW/assets/78541912/841fcc67-487c-45f3-88ec-68ce0ee85b62">
2.最长运行时间为空时，提示随中英文切换变动
![image](https://github.com/PKUHPC/SCOW/assets/78541912/f8759e42-d30e-4074-b690-939821dc91ee)

2024-06-18 12:50 UTC, ddadaal requested changes

2024-06-18 12:50 UTC, ddadaal commented on protos/portal/job.proto
> +  optional string max_time_unit=19;
max_time已经规定是了minute了，那调用者负责把max_time转换为分钟后再调用API，不用再加这个字段。

另外max_time字段不符合规范哈，应该叫max_time_minutes。这个可以这次改掉，是一个breaking change但是没办法

2024-06-18 12:50 UTC, ddadaal commented on apps/portal-web/src/pages/api/job/getJobTemplate.ts
> +  maxTimeUnit:Type.Optional(Type.String()),
由前端转换成分钟后传给后端

2024-06-20 12:43 UTC, ddadaal approved these changes

2024-06-20 12:53 UTC, piccaSun approved these changes

2024-06-20 13:02 UTC, ddadaal approved these changes
改完注释直接合并

2024-06-20 13:19 UTC, merged