feat(portal): breakpoint upload
PKUHPC/SCOW pull request #1346
Opened 2024-07-09 02:52 UTC by Miracle575

2024-07-15 11:40 UTC, Miracle575 commented
code review 后需 @lyl-available 进行测试

2024-07-17 09:43 UTC, Miracle575 commented
暂时不合入 master，修复 scowd 的一个 bug，等待1.6.3再合入

2024-08-08 13:53 UTC, ddadaal requested changes

2024-08-08 13:53 UTC, ddadaal commented on apps/portal-server/src/services/file.ts
> +      }
message可以写清晰一点，这个接口必须配置scowd才能使用，而不是mergeFileChunks没有实现。另外一般来说，这种简单的检查逻辑应该写在主要业务逻辑上面，这样主要的业务逻辑的缩进层数会少一级。

```ts
if (scowd没有配置) { 
    报错
}

正常逻辑
```

2024-08-08 13:53 UTC, ddadaal commented on protos/portal/file.proto
> +  uint64 chunk_size = 2;
单位，chunk_size_byte

2024-08-08 13:53 UTC, ddadaal commented on protos/portal/file.proto
> +  uint64 size = 5;
单位

2024-08-08 13:53 UTC, ddadaal commented on protos/portal/file.proto
> +  rpc InitMultipartUpload(InitMultipartUploadRequest) returns (InitMultipartUploadResponse);
这两个新接口写一下注释，简单介绍一下是做什么的，以及要调用这两个接口需要什么条件

2024-08-09 08:01 UTC, Miracle575 commented
scowd 已同步修改，cr 完成后需邀请测试介入

2024-08-09 13:54 UTC, ddadaal approved these changes

2024-08-13 09:07 UTC, merged