fix:  ai和hpc在提交作业和应用前检查一下是否重名
PKUHPC/SCOW pull request #1375
Opened 2024-07-24 09:24 UTC by OYX-1

2024-08-04 13:44 UTC, ddadaal approved these changes

2024-08-04 13:50 UTC, ddadaal requested changes

2024-08-04 13:50 UTC, ddadaal commented on apps/ai/src/server/trpc/route/jobs/apps.ts
> +        users: [userId], accounts: [],states: [],jobName:appJobName,
jobName是1.6.0适配器接口新增的字段，在1.6.0以下版本的适配器中直接相当于不存在，那么这个查询在1.6.0以下版本的适配器中会直接返回userId用户的所有作业，使得返回的作业列表不为0，所以只要这个用户有作业，用户就无法继续提交作业。这不太对吧？

应该根据适配器的版本选择应该传入的参数：当适配器版本大于1.6.0时，进行这个检查，否则就不进行。

2024-08-04 13:50 UTC, ddadaal commented on apps/ai/src/server/trpc/route/jobs/apps.ts
> +        users: [userId], accounts: [],states: [],jobName:appJobName,
另外注意一下英语语法，没有`existed`什么的说法，都是`existingXXX`

2024-08-04 13:50 UTC, ddadaal commented on apps/portal-server/src/clusterops/app.ts
> +            await checkSchedulerApiVersion(client, minRequiredApiVersion);
那么不升级适配器的集群就无法使用了吗？应该只是不升级就跳过检查更合理？

2024-08-05 02:39 UTC, OYX-1 commented on apps/ai/src/server/trpc/route/jobs/apps.ts
> +        users: [userId], accounts: [],states: [],jobName:appJobName,
> jobName是1.6.0适配器接口新增的字段，在1.6.0以下版本的适配器中直接相当于不存在，那么这个查询在1.6.0以下版本的适配器中会直接返回userId用户的所有作业，使得返回的作业列表不为0，所以只要这个用户有作业，用户就无法继续提交作业。这不太对吧？
> 
> 应该根据适配器的版本选择应该传入的参数：当适配器版本大于1.6.0时，进行这个检查，否则就不进行。

加了trycatch，如果适配器版本小于1.6.0会报错，catch里返回空数组，实际上就是跳过检查了

2024-08-05 13:18 UTC, ddadaal requested changes

2024-08-05 13:18 UTC, ddadaal commented on apps/portal-server/src/clusterops/app.ts
> +            await checkSchedulerApiVersion(client, minRequiredApiVersion);
asyncClientCall在try catch里，所以这样写的实际语义时：当适配器版本<1.6 **或者 调用getJobs时出任何错（不仅是未实现接口的错**，都会跳过检查，这也不太对吧？这忽略了**适配器版本>=1.6 但是 调用getJobs时出错**的情况，这种情况正确行为应该是报错。

另外，`getJobs`这个RPC本身是老版本也有的，只是`jobName`这个参数是老版本没有的。老版本会直接忽略这个参数，那么这里的`getJobs`调用仍然会返回`userId`用户的所有作业。

这些针对不同版本有不同逻辑的业务逻辑，最直接实现方法就是：先获取一下要操作的集群的版本，然后根据集群的版本选择要执行的逻辑，一个简单的if else就行。对于这个例子，那么逻辑就是：

```
const version = 获取client的接口版本;

if (version >= 1.6.0) {
    执行判断，该报错就报错
} else {
    不执行判断，打个log说版本太低不执行
}
```

2024-08-08 13:00 UTC, ddadaal requested changes

2024-08-08 13:00 UTC, ddadaal commented on apps/ai/src/server/trpc/route/jobs/jobs.ts
> +      }
ai部分没改？

2024-08-09 01:43 UTC, OYX-1 commented on apps/ai/src/server/trpc/route/jobs/jobs.ts
> +      }
ai还没有正式发版，现在只有一个适配器版本，并且支持所有功能

2024-08-12 13:24 UTC, ddadaal requested changes

2024-08-12 13:24 UTC, ddadaal commented on libs/server/src/scheduleAdapter.ts
> +}
也没必要这样包装，返回一个true false就好了，外面直接if else……

```ts
schedulerVersionSatisties(client, minVersion): boolean
```

2024-08-12 13:24 UTC, ddadaal commented on apps/portal-server/src/services/job.ts
> +      };
我的意思是直接把**整个检查作业重名的逻辑**全给提出去

2024-08-13 13:08 UTC, ddadaal approved these changes

2024-08-13 14:47 UTC, merged