feat(mis): 增加可配置消费记录精度、可配置最小消费金额的功能，默认最小消费金额为0.01
PKUHPC/SCOW pull request #1388
Opened 2024-08-08 10:57 UTC by tongchong

2024-08-09 13:53 UTC, ddadaal requested changes

2024-08-09 13:53 UTC, ddadaal commented on apps/mis-web/src/pages/admin/statistic.tsx
> +                    y: Number(d.count.toFixed(publicConfig.CHARGE_PRECISION)),
把金额number转换为string的逻辑提成一个函数 `moneyNumberToString(number: number): string`

2024-08-09 13:53 UTC, ddadaal commented on docs/docs/deploy/config/mis/charge-precision/index.md
> +- 建议最小消费金额数值与消费记录精度一致。例如消费记录精度为2时，最小消费金额为0.01，如果此时您将最小消费金额设置为0.001，该金额在计算时将会被舍去。
这种要求在读取配置的时候检查，如果精度不一定直接报错退出，简化SCOW的处理逻辑。

2024-08-09 13:53 UTC, ddadaal commented on libs/config/src/mis.ts
> +  }),
由于这样改了默认值之后计费的结果将会改变，对于这种用户什么都没动但是结果变了的情况，需要在changeset里明确提示用户。

单独写一个config的changeset，介绍config中新的配置，并且明确提示：之后计算作业价格时的精度会改变为精确到2位小数，可能会影响作业结果，如果用户需要保持以前的计算精度，需要怎么修改配置

2024-08-09 13:53 UTC, ddadaal commented on libs/config/src/mis.ts
> +  }),
另外，属性名称改为`jobChargeDecimalPrecision`和`jobMinCharge`

2024-08-09 13:53 UTC, ddadaal commented on apps/mis-server/src/bl/jobPrice.ts
> +      return new Decimal(misConfig.minChargeAmount).decimalPlaces(misConfig.chargePrecision, Decimal.ROUND_HALF_CEIL);
这种逻辑可以不出现了，直接从根源防止用户乱写配置，计算逻辑也简单一些

2024-08-12 06:41 UTC, tongchong commented on libs/config/src/mis.ts
> +  }),
由于计费精度对于充值也有影响，jobChargeDecimalPrecision 是否需改成chargeDecimalPrecision

2024-08-12 10:38 UTC, ddadaal commented on libs/config/src/mis.ts
> +  }),
这个PR对充值的精度有什么样的影响？

2024-08-12 10:57 UTC, tongchong commented on libs/config/src/mis.ts
> +  }),
充值的展示列表也统一按照精度的小数位来展示，对接口充值暂时未限制

2024-08-12 11:08 UTC, tongchong commented on libs/config/src/mis.ts
> +  }),
如果说消费只到角，那么页面上充值到分似乎是没有意义的

2024-08-12 13:05 UTC, ddadaal commented on libs/config/src/mis.ts
> +  }),
现在只是作业计费到角，但是从SCOW API调用仍然是可以调用到4位小数的。充值相关的小数点精度另加一个配置。

2024-08-12 13:10 UTC, tongchong commented on libs/config/src/mis.ts
> +  }),
嗯嗯，好的，就像现在这样，先把作业计费精度关联，如果充值有要求再说，暂时先保证以后默认生成的账单到分，防止和外界财务系统无法对帐的问题出现。

2024-08-12 13:26 UTC, ddadaal requested changes

2024-08-12 13:26 UTC, ddadaal commented on docs/docs/deploy/config/mis/charge-precision/index.md
> +作业消费记录精度配置及作业最小消费金额配置在scow v1.6.2以后的版本中生效，如果您想保持v1.6.2之前的版本中的计费逻辑：作业消费记录精度为3，作业最小消费金额为0，您只需要在mis.yaml文件中配置如下即可：
下一个版本应该是1.6.3。标题写清楚为“恢复1.6.2及以前版本的作业计费逻辑"，新配置在1.6.3中生效

2024-08-12 13:26 UTC, ddadaal commented on libs/config/src/mis.ts
> +  }),
要检查这个配置最大为4，如果这里不能检查，在getMisConfig里检查

2024-08-12 13:47 UTC, tongchong commented on libs/config/src/mis.ts
> +  }),
getMisConfig中新增检查必须为0、1、2、3、4

2024-08-13 14:46 UTC, ddadaal requested changes
增加了在新的默认配置下的测试用例，发现了逻辑实现的需要，需要修改逻辑以及对应的新的测试数据

2024-08-13 14:46 UTC, ddadaal commented on apps/mis-server/src/bl/jobPrice.ts
> +    }
这里只体现了在最后价格取整的时候取到对应的精度，但是最低费用在哪里体现的？

2024-08-13 14:46 UTC, ddadaal commented on apps/mis-server/tests/job/testData-precision3.json
> +  },
对于这个用例，它对应的计费项不是0，elapsedTime==1，那么因为有最低价格的配置，所以最后的价格应该大于>0？

2024-08-14 01:58 UTC, tongchong commented on apps/mis-server/tests/job/testData-precision3.json
> +  },
如果使用默认的jobChargeDecimalPrecision:2, jobMinCharge:0.01，价格应该大于0；如果使用jobChargeDecimalPrecision: 3，jobMinCharge: 0，则应该等于0

2024-08-14 11:53 UTC, ddadaal approved these changes

2024-08-14 11:53 UTC, merged