after new user created connect to login node via ssh as the user
PKUHPC/SCOW pull request #226
Opened 2022-10-19 06:34 UTC by WZD09

2022-11-03 02:23 UTC, WZD09 commented
![image](https://user-images.githubusercontent.com/102740885/199636236-2321718f-e677-41b8-a9a2-09673c96572c.png)
创建用户后 系统创建用户的家目录成功,bash相关的配置写入成功，prompt可以正确地显示。
![image](https://user-images.githubusercontent.com/102740885/199636613-e989f14d-652e-4e8b-acc0-ed087cc4a850.png)

2022-11-03 12:48 UTC, ddadaal requested changes

2022-11-03 12:48 UTC, ddadaal commented on libs/ssh/src/ssh.ts
> +    await ssh.connect({ host, port: port ? +port : undefined, username, password: pwd });
不要直接使用ssh.connect，有一个sshConnect方法（看上面），可以自动处理运行结束时释放连接的逻辑，直接去掉try catch块

2022-11-03 12:48 UTC, ddadaal commented on libs/ssh/src/ssh.ts
> +      logger.error("User %s home directory %s is not exits", username, userHomeDir);
1. is not exits？写一个完整的英文句子 ：Home directory %s of user %s does not exist
2. 如果是错误，logger.error之后，还应该throw new Error，throw一个错误出去，防止继续往下执行

2022-11-03 12:48 UTC, ddadaal commented on libs/ssh/src/ssh.ts
> + * If fails, return the error
改注释

2022-11-03 12:48 UTC, ddadaal commented on libs/ssh/src/ssh.ts
> +export async function userSshFirstLogin(
函数名取名为这个函数做的事情。这个事情时“用户第一次SSH登录”吗？不是，是以用户身份登录并配置免密登录，取名为`insertKeyAsUser`。之前那个`insertKey`也顺便修改为`insertKeyAsRoot`

2022-11-05 08:02 UTC, WZD09 commented on libs/ssh/src/ssh.ts
> +    await ssh.connect({ host, port: port ? +port : undefined, username, password: pwd });
`sshConnect`是用公钥登录，这里需要用密码登录，不能直接使用。
如果直接重载`sshConnect` 其他部分的代码涉及到比较多的修改，所以参考`sshConnect`增加了用密码登录的方法`sshConnectByPassword`

2022-11-05 08:44 UTC, ddadaal approved these changes

2022-11-05 08:45 UTC, merged