add proxys and increase  websocket connnections timeout
PKUHPC/SCOW pull request #241
Opened 2022-10-27 11:58 UTC by WZD09

2022-10-27 15:44 UTC, ddadaal requested changes

2022-10-27 15:44 UTC, ddadaal commented on apps/portal-server/config/apps/vscode.yml
> +proxy_type: rproxy
`proxy_type` -> `proxyType`，其他的配置都是camelCase的

取值取更加易懂的值，比如`rproxy` -> `relative`、`proxy` -> `absolute`, `wsproxy` -> `websocket`

2022-10-27 15:44 UTC, ddadaal commented on apps/portal-web/src/pages/api/app/connectToApp.ts
> +    200: { host: string; port: number; password: string; proxyType: string } & (
用literal type确定好proxyType的所有取值：`string` -> `"rproxy" | "wsproxy" | "proxy"`

2022-10-27 15:44 UTC, ddadaal commented on libs/config/src/appConfig/app.ts
> +  proxy_type: Type.String({ description: "proxy 类型" }),
和上面一样，`string`类型太宽泛，用Enum或者`Type.Union([Type.Literal("rproxy"]...])`定死所有可能取值

2022-10-27 15:44 UTC, ddadaal commented on protos/portal/app.proto
> +  string proxyType = 6;
用`proto`的`enum`定死所有取值

2022-11-02 08:46 UTC, WZD09 commented
![image](https://user-images.githubusercontent.com/102740885/199439420-4f091404-df3c-4f1d-bdb5-0d5a6f20fc4a.png)
vscode连接成功

![image](https://user-images.githubusercontent.com/102740885/199441463-06c75995-2e38-423c-843e-4562a6f3d1c3.png)
jupyter连接成功

![image](https://user-images.githubusercontent.com/102740885/199441746-9ded97f1-0839-4309-8150-245b610dc988.png)
docs增加jupyter配置

2022-11-02 09:02 UTC, ddadaal commented
文档结构：

![image](https://user-images.githubusercontent.com/8363856/199447771-07cc24fd-0055-45a5-a178-9a837bd03948.png)

2022-11-02 15:01 UTC, ddadaal requested changes

2022-11-02 15:01 UTC, ddadaal commented on docs/docs/portal/apps/examples/configure-jupyter-app.md
> +
这部分内容在configure-web-app.md中已经解释过了，这里不需要再解释。这篇文档中的内容应该全都是jupyter相关的

2022-11-02 15:01 UTC, ddadaal commented on docs/docs/portal/apps/examples/index.md
> +以VScode和Jupyter为例，讲解如何配置交互式应用。
可以不要有首页，直接让用户需要什么应用就看哪一页就可以了

2022-11-02 15:02 UTC, ddadaal commented on docs/docs/portal/apps/examples/configure-jupyter-app.md
> +title: 样例：Jupyter配置
直接取名jupyter就可以了，用户要部署jupyter直接来这里看

2022-11-03 08:38 UTC, WZD09 commented
![image](https://user-images.githubusercontent.com/102740885/199677545-6edb9b77-1406-4999-8be7-f07d62a03655.png)
现在的文档结构

2022-11-05 10:15 UTC, ddadaal approved these changes

2022-11-07 07:28 UTC, ddadaal approved these changes

2022-11-07 07:28 UTC, merged