Show all tenant
PKUHPC/SCOW pull request #245
Opened 2022-10-30 16:59 UTC by coovy

See if it can pass CI

2022-10-31 01:30 UTC, ddadaal requested changes

2022-10-31 01:30 UTC, ddadaal commented on apps/mis-server/src/services/tenant.ts
> +          }))),
这里用了await吗？没有用await就把async删了，也不需要Promise.all

2022-10-31 01:30 UTC, ddadaal commented on apps/mis-server/src/services/tenant.ts
> +      const [tenants, tenantCount] = await em.findAndCount(Tenant, {});
这里不需要做分页，就不需要findAndCount。find拿到所有数据，然后tenants.length就拿到数量了。findAndCount本质上执行了两次sql

2022-10-31 01:30 UTC, ddadaal commented on apps/mis-server/src/services/tenant.ts
> +      const tenantName = await em.findOne(Tenant, { name: name });
拿到的是tenant对象，不是tenant的名字，变量名改为tenant

2022-10-31 01:30 UTC, ddadaal commented on apps/mis-web/config.js
> +    ENABLE_CREATE_USER: capabilities.createTenant,
这里没有报错？相同的config key。而且capabilities是认证系统的API，根本没有createTenant这个字段 https://pkuhpc.github.io/SCOW/docs/common/auth/custom#get-capabilities

2022-10-31 01:30 UTC, ddadaal commented on apps/mis-web/src/pageComponents/tenant/CreateTenantForm.tsx
> +      <Form.Item label="姓名" name="name" rules={[{ required: true }]}>
姓名 -> 租户名

2022-10-31 01:30 UTC, ddadaal commented on apps/mis-web/src/pageComponents/tenant/CreateTenantModal.tsx
> +      .httpError(409, () => { message.error("此租户ID已经存在！"); })
租户ID -> 租户名

2022-10-31 01:30 UTC, ddadaal commented on apps/mis-web/src/pageComponents/tenant/CreateTenantModal.tsx
> +      <p>租户不存在，请输入租户名称以创建租户。</p>
删掉

2022-10-31 01:30 UTC, ddadaal commented on apps/mis-web/src/pages/api/tenant/create.ts
> +     * @pattern ^[a-z1-9_]+$
不限制

2022-11-04 09:29 UTC, coovy commented
![image](https://user-images.githubusercontent.com/96867690/199939293-57df171c-7205-4567-abff-f909b8cef80e.png)

2022-11-04 09:34 UTC, merged