fix(mis): fix a bug of set/unset roles of init
PKUHPC/SCOW pull request #249
Opened 2022-11-04 02:11 UTC by tulvgengenr

I just want to use github to build the image and test if the api call at system initialization has been modified

2022-11-07 08:20 UTC, ddadaal requested changes

2022-11-07 08:20 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitUsersAndAccountsTable.tsx
> +  roletype: "platform" | "tenant";
roleType

2022-11-07 08:20 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitUsersAndAccountsTable.tsx
> +  userid: string;
userId

2022-11-07 08:20 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitUsersAndAccountsTable.tsx
> +  reloadfunction: () => void;
reload

2022-11-07 08:20 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitUsersAndAccountsTable.tsx
> +const SelectWithLoading: React.FC<SelectProps> = ({ roletype, role, userid, reloadfunction }) => {
这里的抽象有点问题，用两个组件清晰一点：TenantRoleSelector和PlatformRoleSelector，分别负责租户角色和平台角色，并且把在外面的children也直接写在组件里面。这样， 所有和某种角色相关的操作和组件都在一个组件里。

2022-11-08 03:16 UTC, ddadaal requested changes

2022-11-08 03:16 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitUsersAndAccountsTable.tsx
> +
用map 把Object.values(PlatformRole)映射成Select.Option组件，直接写到return的那个组件里，不需要单独写个变量。另外注意命名规则，局部变量为camelCase。还有，这里为什么要判断value的类型？

2022-11-08 03:16 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitUsersAndAccountsTable.tsx
> +  });
同上

2022-11-08 03:23 UTC, tulvgengenr commented on apps/mis-web/src/pageComponents/init/InitUsersAndAccountsTable.tsx
> +
判断value类型是因为，遍历enum类型的时候，会输出两次结果。一次key是string，value是number；另一次key为number，value是string。
我用map改一下。

2022-11-08 06:44 UTC, ddadaal approved these changes

2022-11-08 06:58 UTC, merged