Show all tenant
PKUHPC/SCOW pull request #250
Opened 2022-11-04 11:02 UTC by coovy

![image](https://user-images.githubusercontent.com/96867690/199957518-bfb610ae-55eb-4748-802a-3e4e6f9ff6ac.png)
添加租户时，要求租户名不能重复

2022-11-04 11:50 UTC, ddadaal requested changes

2022-11-04 11:50 UTC, ddadaal commented on apps/mis-server/src/services/tenant.ts
> +            userCount: userCount.find((t) => t.tenant_id === x.id)?.count ?? 0,
1. 在什么情况下，count将会是undefined？是sql写错了、sql执行结果中没有count这一列的时候。如果发现查出来的结果没有这个租户，说明SQL写错了。与其给一个默认值，掩盖这个SQL的错误，不如抛出一个错误，错误早发现早解决。暴露错误优于掩盖错误
2. find的实现为遍历数组，找到其中满足这个函数条件的元素，复杂度是O(n)。这里需要对每个租户查找一次tenant_id等于当前租户id的userCount的项，那么这里的复杂度为O(n^2)。有没有O(n)的做法？

2022-11-04 11:50 UTC, ddadaal commented on apps/mis-server/src/services/tenant.ts
> +        .execute("select tenant_id, count(*) as count from user group by tenant_id");
不推荐直接执行裸sql语句。这里语句里写死了表名（user）、列名（tenant_id）。参考https://mikro-orm.io/docs/virtual-entities 的第二个示例来学习如何使用query builder API写group by

2022-11-05 13:42 UTC, coovy commented on apps/mis-server/src/services/tenant.ts
> +            userCount: userCount.find((t) => t.tenant_id === x.id)?.count ?? 0,
关于1，不是很理解.不过我的思路是：查租户表获取了所有租户对象数组tanants，查user表获取了userCount包含每个user属于哪个租户id,以及相同租户id的count。返回值对所有租户tenants进行map遍历。但是对所有租户遍历时，由于刚创建租户时，租户里没有user和account, 所以这时在userCount里find时，找不到满足“对应新租户id的用户”，也就userCount.find()返回了undefine，这时我就用了？.和？？以便显示新创建的租户时，能够显示用户数和租户数为0的情况。所以并不是查出来结果中没有这个租户，而是新创建的租户里没有没有账户和用户。所以是我哪里理解错了吗？

2022-11-05 14:10 UTC, ddadaal commented on apps/mis-server/src/services/tenant.ts
> +            userCount: userCount.find((t) => t.tenant_id === x.id)?.count ?? 0,
你说得对，之前是我理解错了。没有user的tenant不会出现在userCount里

2022-11-05 14:41 UTC, ddadaal requested changes

2022-11-05 14:41 UTC, ddadaal commented on apps/mis-server/src/services/tenant.ts
> +            accountCount: accountCount[i++]?.tCount ?? 0,
如果不存在id为2的tenant，userCount数组还一定满足`userCount[i].id == i+1`吗？
提示：
```ts
// 把
const userCount = [{ tId: 1, tCount: 10}, {tId: 2, tCount: 20}]

// 转换为
const userCountMap = { "1": 10, "2": 20 };

// 以下调用复杂度为O(1)
const userCountOfTenant1 = userCountMap[1]; // 10

// 以下调用返回undefined
const userCountOfTenant3 = userCountMap[3]; // undefined
```

2022-11-06 00:55 UTC, ddadaal approved these changes

2022-11-06 00:56 UTC, merged