feat(portal-web): 门户系统上传文件时显示进度条
PKUHPC/SCOW pull request #252
Opened 2022-11-05 04:24 UTC by qhqhqhq

显示进度条

2022-11-05 04:25 UTC, ddadaal commented
不使用axios

2022-11-05 04:34 UTC, ddadaal requested changes

2022-11-05 04:34 UTC, ddadaal commented on apps/portal-web/package.json
> +    "axios": "^1.1.3",
去除^，定死版本为1.1.3

2022-11-05 04:57 UTC, qhqhqhq commented on apps/portal-web/package.json
> +    "axios": "^1.1.3",
好的。不过现在我只是想试一试这个包

2022-11-29 08:49 UTC, ddadaal commented
暂时做不了，之后再说

2022-11-29 08:49 UTC, closed without merging