feat(mis):  在租户管理和平台管理下的用户界面，实现修改密码功能
PKUHPC/SCOW pull request #269
Opened 2022-11-11 07:35 UTC by tulvgengenr

创建镜像，集群测试使用

2022-11-11 07:55 UTC, ddadaal requested changes

2022-11-11 07:55 UTC, ddadaal commented on apps/mis-web/src/apis/api.ts
> +  changePasswordForTenantAdmin: fromApi<ChangePasswordForTenantAdminSchema>("PATCH", join(process.env.NEXT_PUBLIC_BASE_PATH || "", "/api/tenant/changePassword")),
for -> as，不是给Platform/TenantAdmin改密码，而是作为这两个用户改密码

2022-11-11 07:55 UTC, ddadaal commented on apps/mis-web/src/pageComponents/tenant/AdminUserTable.tsx
> +              message="只有租户管理员才能修改密码"
不需要判断，这个组件只有租户管理员能用

2022-11-11 07:55 UTC, ddadaal commented on apps/mis-web/src/pageComponents/admin/AllUsersTable.tsx
> +              onClick={() => {
不需要判断，这个组件只有平台管理员能用

2022-11-11 08:26 UTC, ddadaal requested changes

2022-11-11 08:26 UTC, ddadaal commented on apps/mis-web/src/pageComponents/admin/AllUsersTable.tsx
> +  const [form] = Form.useForm<FormProps>();
这样写，整个Table里的每个Modal都使用了相同的form对象，虽然可能用起来没什么问题，但是总之是一种抽象不完全的设计，整个AllUsersTable维护了过多状态（这个Table本身并不需要知道Form的状态），也不利于表单逻辑的重用。

推荐：将修改密码的Modal单独抽成一个组件放到一个单独的文件里，提供一个onConfirm的prop代表确认修改密码时的回调。使用apps/portal-web/src/components/ModalLink.tsx（mis-web中不存在，可以复制一份过去）的ModalLink HOC包装这个Modal，然后在这里渲染这个ModalLink

2022-11-11 08:32 UTC, tulvgengenr commented on apps/mis-web/src/pageComponents/admin/AllUsersTable.tsx
> +  const [form] = Form.useForm<FormProps>();
好的，我当时写的时候也感觉这样确实维护了过多状态。

2022-11-15 02:37 UTC, ddadaal requested changes
两个ChangePasswordModal的UI是一致的，只是点击完成时的逻辑不一样。所以应该使用同一个组件，给组件加一个onComplete的回调，在组件内当点击完成时调用这个回调，在不同的地方传入不同的回调

2022-11-15 02:37 UTC, ddadaal commented on apps/mis-web/src/pages/api/admin/changePassword.ts
> +export interface changePasswordAsPlatformAdminSchema {
首字母大写

2022-11-15 02:37 UTC, ddadaal commented on apps/mis-web/src/pages/api/tenant/changePassword.ts
> +export interface changePasswordAsTenantAdminSchema {
首字母大写

2022-11-15 02:37 UTC, ddadaal commented on apps/mis-web/src/pageComponents/admin/changePasswordModal.tsx
> +const changePasswordModal: React.FC<Props> = ({ name, userId, reload, onClose, visible }) => {
React组件的首字母大写，同时还要改文件名

2022-11-15 03:22 UTC, tulvgengenr commented on apps/mis-web/src/pageComponents/admin/changePasswordModal.tsx
> +const changePasswordModal: React.FC<Props> = ({ name, userId, reload, onClose, visible }) => {
由于不同的回调方法在调用api时都需要获取form中的内容（oldpassword, newpassword）作为参数，但是这个form是子组件ChangePasswordModal维护的。将回调方法传给子组件的时候，有什么方法可以获取到子组件的form吗？

2022-11-15 03:23 UTC, tulvgengenr commented
由于不同的回调方法在调用api时都需要获取form中的内容（oldpassword, newpassword）作为参数，但是这个form是子组件ChangePasswordModal维护的。将回调方法传给子组件的时候，有什么方法可以获取到子组件的form吗？

2022-11-15 07:45 UTC, ddadaal requested changes

2022-11-15 07:45 UTC, ddadaal commented on apps/mis-web/src/components/ChangePasswordModal.tsx
> +    onComplete: (oldPassword:string, newPassword:string) => Promise<Boolean>;
为什么需要返回值呢？`Promise<void>`就可以了

2022-11-15 07:45 UTC, ddadaal commented on apps/mis-web/src/components/ChangePasswordModal.tsx
> +    setLoading(false);
这里不需要boolean就可以做到根据结果不同分别处理。Promise resolve了就说明成功，reject了说明失败。这里不需要单独处理失败的情况，但是无论是否成功，都需要把loading状态改回来(finally)，所以：

```ts
onComplete().then(() => { message.success("修改成功"); }).finally(() => setLoading(false));
```

`setLoading(false)`这种无论是否操作是否成功都需要进行的操作一般都出现在finally里。

2022-11-15 07:45 UTC, ddadaal commented on apps/mis-web/src/pageComponents/admin/AllUsersTable.tsx
> +                onComplete={async (oldPassword: string, newPassword: string): Promise<Boolean> => {
这里应该时不需要手动写类型的，应该能自动推断出来的吧？

2022-11-15 07:45 UTC, ddadaal commented on apps/mis-web/src/pageComponents/admin/AllUsersTable.tsx
> +                    .then(() => { message.success("修改成功"); resultReturn = true; });
不需要单独保存和处理结果。另外，确认一下到底是父组件（这里）还是子组件（ChangePasswordModal）来弹修改成功的message

2022-11-15 07:45 UTC, ddadaal commented on apps/mis-web/src/pages/api/admin/changePassword.ts
>    "changePasswordAsPlatformAdminSchema", async (req, res) => {
这里的schema name没有改

2022-11-15 07:45 UTC, ddadaal commented on apps/mis-web/src/pages/api/tenant/changePassword.ts
>    "changePasswordAsTenantAdminSchema", async (req, res) => {
schema name没有改

2022-11-15 07:48 UTC, tulvgengenr commented on apps/mis-web/src/components/ChangePasswordModal.tsx
> +    onComplete: (oldPassword:string, newPassword:string) => Promise<Boolean>;
我想的是应该是执行成功的时候，将form中的内容重置为""

2022-11-15 07:49 UTC, ddadaal commented on apps/mis-web/src/components/ChangePasswordModal.tsx
> +    onComplete: (oldPassword:string, newPassword:string) => Promise<Boolean>;
看下面，使用then, catch和finally处理执行成功、失败和无论成功失败的逻辑

2022-11-18 07:48 UTC, ddadaal requested changes

2022-11-18 07:48 UTC, ddadaal commented on apps/mis-web/src/components/ChangePasswordModal.tsx
> +        form.setFieldsValue({ oldPassword: "", newPassword: "", confirm: "" });
有一个`form.resetFields()`方法可以重置表单内容

2022-11-18 07:48 UTC, ddadaal commented on apps/mis-web/src/components/ChangePasswordModal.tsx
> +        reload();
reload是父组件在执行完某个操作后应该做的事情，但是这个子组件并不关心父组件在完成之后应该做什么。万一父组件执行结束后不是reload呢？去掉reload这个prop

2022-11-18 07:48 UTC, ddadaal commented on apps/mis-web/src/components/ChangePasswordModal.tsx
> +      title={`确认要修改用户${name}（ID：${userId}）的密码？`}
修改用户${name}（ID：${userId}）的密码就可以了，不需要是疑问句。疑问句一般是写在确认框这种地方的。这个Modal是有交互的。

2022-11-18 07:48 UTC, ddadaal commented on apps/mis-web/src/pageComponents/admin/AllUsersTable.tsx
> +                    .then(() => { message.success("修改成功"); })
如果父组件需要在执行完成后reload，那么应该在这里调用reload，而不是把reload传给子组件来调用

2022-11-18 08:20 UTC, ddadaal commented on apps/mis-web/src/components/ChangePasswordModal.tsx
> +      width={"70%"}
没有必要手动设置width吧？看现在的UI图，Modal太宽了，也不好看

2022-11-18 09:13 UTC, ddadaal approved these changes

2022-11-18 13:43 UTC, merged