refactor(mis-server和libs/auth): 把mis-server中创建用户的逻辑独立出来，把调用http在auth中创建用户的部分也独立出来
PKUHPC/SCOW pull request #273
Opened 2022-11-13 12:08 UTC by coovy

2022-11-13 14:29 UTC, ddadaal commented
这是两个工作，拆成两个PR。首先是后面的独立调用auth的HTTP接口创建用户的逻辑，然后是前面独立mis-server中创建用户的逻辑

2022-11-14 00:24 UTC, ddadaal requested changes
逻辑是独立出来了，之前调用这个逻辑的地方也得改成调用这个函数，不然独立出来有什么意义呢？同时，还要定义这个函数成功执行时的返回值类型。

2022-11-14 02:52 UTC, ddadaal requested changes
dockerfile没改，仔细看文档

2022-11-14 03:55 UTC, coovy commented
> dockerfile没改，仔细看文档

我查看了Dockerfile.mis-server文件，关于我在添加的包@scow/lib-auth,在docker文件中似乎是之前添加过，
![image](https://user-images.githubusercontent.com/96867690/201571294-82e326dc-d98d-4b80-afa1-bd071dfeb5fb.png)
另外包@scow/lib-auth包并没有依赖其他包
![image](https://user-images.githubusercontent.com/96867690/201571581-88bfc090-a560-471c-8344-47ad1690d97a.png)
刚才ci失败我看是运行RUN apk update && apk add libc6-compat python3 make gcc g++这条命令失败，我把失败的镜像重新运行了一下就通过了

2022-11-14 03:56 UTC, ddadaal approved these changes

2022-11-14 03:56 UTC, merged