fix(portal): 为交互式应用添加用户可自定义选项
PKUHPC/SCOW pull request #283
Opened 2022-11-16 14:51 UTC by WZD09

2022-11-17 01:43 UTC, ddadaal requested changes

2022-11-17 01:43 UTC, ddadaal commented on apps/portal-server/config/apps/vscode.yml
> +  - widget: number_field
1. `widget: number_field` -> `type: number 或 string 或 select`
2. 目前所有配置项中的短语（即多个单词组成的短语）都是用的`camelCase`格式命名（`numberField`），不是使用下划线的方式
3. 区分label和key。label是UI中显示的，key是编程时用的。

举例比如版本字段，应该设计为：

```yaml
- type: string
  key: version
  label: 版本
```

2022-11-17 01:43 UTC, ddadaal commented on apps/portal-server/src/services/app.ts
> +      const attributes:AppCustomAttribute[] = app.attributes ? app.attributes : [];
1. `app.attributes ?? []`
2. 如果appId不存在呢？这里app如果是undefined的话，throw一个NOT_FOUND的error，记得增加message

2022-11-17 01:43 UTC, ddadaal commented on apps/portal-web/src/pageComponents/app/LaunchAppForm.tsx
> +          label={item.label}
key和label要分开。

这样添加的Form.Item，可以从form.validateFields()的返回值中通过Form.Item的key读到用户的值

2022-11-17 01:43 UTC, ddadaal commented on apps/portal-web/src/pageComponents/app/LaunchAppForm.tsx
> +          </Select>
具体选项应该也从配置文件中读出来

2022-11-17 01:43 UTC, ddadaal commented on apps/portal-web/src/pages/api/app/getAppAttributes.ts
> +  }
如果appId不存在，定义404的response

2022-11-17 01:43 UTC, ddadaal commented on libs/config/src/app.ts
> +  )),
具体有哪些表单类型要使用enum确定，对于select类型的字段，具体有哪些选项也应该要求用户确定，选项的key和value也要区分。

举例

```yaml
- type: select
   label: 版本
   select:
      - key: 10
        value: v10
      - key: 11
         value: v11
```

2022-11-17 01:43 UTC, ddadaal commented on protos/portal/app.proto
>        returns (CreateAppSessionResponse);
创建作业的时候，如何把用户自己的字段也提交到后端？这段逻辑是不是没写？推荐：`CreateAppSessionRequest`里增加一个`map<string, string> customAttributes`字段，key为attribute的key，value是用户的输入（如果是select，是用户选择项的key，不是label），这样后台就能读到用户的选项了

2022-11-23 04:11 UTC, ddadaal requested changes

2022-11-23 04:11 UTC, ddadaal commented on apps/portal-server/src/clusterops/slurm/app.ts
> +            beforeScript = beforeScript + "export " + key + "=" + customAttributes[key] + "\n";
1. 是否考虑值包括空格、特殊字符等情况？
2. 使用格式化字符串，更直观

```ts
`export ${key}=${customAttributes[key]}`
```

2022-11-23 04:11 UTC, ddadaal commented on apps/portal-server/src/services/app.ts
> +                ? AppCustomAttribute_AttributeType.select : AppCustomAttribute_AttributeType.text,
webAppProps_ProxyTypeFromJSON

2022-11-23 04:11 UTC, ddadaal commented on apps/portal-web/src/pageComponents/app/LaunchAppForm.tsx
> +  });
大量重复代码。这三种组件只有内部的具体组件和rules不一样，可以简化

InputNumber的rules可以分成两个写，更好重用重复代码：`{ required: true }, { type: "integer" }`

2022-11-23 04:11 UTC, ddadaal commented on apps/portal-web/src/pages/api/app/getAppAttributes.ts
> +            ? "select" : "text",
AppCustomAttribute_AttributeTypeToJson方法，可以把enum值转换成string

2022-11-23 04:11 UTC, ddadaal commented on libs/config/src/app.ts
> +        }), { description:"表单选项", default: []},
1. 应该是Type.Optional，而不是给[]的默认值，因为其他两种attribute是不需要select的值的
2. 在getAppConfigs获取应用配置时，需要检查type为select的字段的select属性是否有没有设置。如果没有设置需要报错

2022-11-23 04:11 UTC, ddadaal commented on libs/config/src/app.ts
> +      name: Type.String({ description: "表单name" }),
表单字段名

2022-11-23 06:04 UTC, fuzhenxin commented on apps/portal-server/config/apps/vscode.yml
> +        value: v10
是有必要的，比如用户端看到的是简单的Rstudio3.0、但是实际上对应的script里module load 后面是 rstudio/4.0。这就需要显示给用户和实际代码处理的值不一致。

2022-11-24 00:52 UTC, ddadaal requested changes

2022-11-24 00:52 UTC, ddadaal commented on apps/portal-server/src/clusterops/slurm/app.ts
> +            }
是否有必要不允许全空的值？`export VAR=`有时候也是清除一个已存在环境变量的方法

2022-11-24 00:52 UTC, ddadaal commented on apps/portal-server/src/clusterops/slurm/app.ts
> +            }
1. 是否有必要不允许全空的值？`export VAR=`有时候也是清除一个已存在环境变量的方法
2. 值里存在双引号确实会影响代码，但是直接禁止也不是一个好的办法

推荐方法：项目中应该已经安装了[shell-quote](https://www.npmjs.com/package/shell-quote)这个包，使用这个包的`quote`方法给值加上引号就可以了。

2022-11-24 00:52 UTC, ddadaal commented on docs/docs/portal/apps/configure-web-app.md
> +| `type`   | "number", "text" 或者 "select" | 是    | 在HTML表单元素中输入的内容的类型             |
" -> \`

2022-11-24 02:16 UTC, ddadaal requested changes

2022-11-24 11:20 UTC, WZD09 commented on apps/portal-server/src/clusterops/slurm/app.ts
> +            }
修改为允许空值，只用shell-quote加上引号对包括空格的字符串进行处理

2022-11-24 13:20 UTC, WZD09 commented
![image](https://user-images.githubusercontent.com/102740885/203793606-b36b47fc-38dc-4882-a59f-c42aa581cc08.png)

现在用户可以在自定义表单输入包含空格的字符串。

2022-11-24 13:47 UTC, ddadaal requested changes

2022-11-24 13:47 UTC, ddadaal commented on apps/portal-server/config/apps/vscode.yml
> +        value: v10
这里的key是编程里用的，value是显示的吗？这里的命名规则和上面的不一样。上面的是用label表示显示的。这里建议改成显示的仍然用label，编程里用的为value。

2022-11-24 15:11 UTC, WZD09 commented on apps/portal-server/config/apps/vscode.yml
> +        value: v10
变成用的key -> value
显示给用户的value -> label

2022-11-24 15:12 UTC, ddadaal commented on apps/portal-server/config/apps/vscode.yml
> +        value: v10
是这意思

2022-11-25 00:35 UTC, ddadaal approved these changes

2022-11-25 00:40 UTC, ddadaal requested changes

2022-11-25 00:40 UTC, ddadaal commented on apps/portal-server/src/services/app.ts
> +      const { account, appId, cluster, coreCount, maxTime, partition, qos, userId, customAttributes } = request;
在这里需要再次验证一次用户的输入是否符合配置文件里的规定，比如select类型的属性的取值是不是属于配置文件中的规定的，number类型的取值是不是number，如果输入不符合要求需要抛出一个INVALID_ARGUMENT错误，message里写清楚什么问题。因为用户可能直接通过HTTP请求访问的后端，没有经过UI。

2022-11-25 03:18 UTC, WZD09 commented on apps/portal-server/src/services/app.ts
> +      const { account, appId, cluster, coreCount, maxTime, partition, qos, userId, customAttributes } = request;
portal-web的CreateAppSession这个api 400的code好像没有用到，我把它定义成`INVALID_INPUT`处理这个gRPC的`NVALID_ARGUMENT`error可以吗

2022-11-25 03:47 UTC, ddadaal commented on apps/portal-server/src/services/app.ts
> +      const { account, appId, cluster, coreCount, maxTime, partition, qos, userId, customAttributes } = request;
可以的

2022-11-25 12:40 UTC, ddadaal requested changes

2022-11-25 13:31 UTC, ddadaal approved these changes

2022-11-26 01:28 UTC, merged