enhancement(portal-web, mis-web): 在header上添加默认集群选择框
PKUHPC/SCOW pull request #296
Opened 2022-11-21 12:27 UTC by qhqhqhq

-  mis
![image](https://user-images.githubusercontent.com/98016770/203054907-3692151a-423c-4d25-a24b-3da24f8d323c.png)
![image](https://user-images.githubusercontent.com/98016770/203055114-9f78d8fc-f0ea-4e01-ab58-3d713fb0f3c5.png)

2022-11-21 12:29 UTC, qhqhqhq commented
多集群操作默认选择全部集群

![d3b6b7851322aa17c9c7e7ffb2dbc85](https://user-images.githubusercontent.com/98016770/203055442-fd435e9c-0e95-4a57-b254-9aa13ae6a5cc.png)

![35b5a0e84dfb2c59d6db512ded74ca4](https://user-images.githubusercontent.com/98016770/203055471-618c3d42-2c3e-430b-9aac-ee8175a0dc66.png)

2022-11-24 05:20 UTC, qhqhqhq commented
已解决冲突

2022-11-24 07:21 UTC, ddadaal requested changes

2022-11-24 07:21 UTC, ddadaal commented on apps/portal-web/src/layouts/base/BaseLayout.tsx
> +  const allRoutes = useMemo(() => userRoutes(), [defaultClusterStore.cluster]);
为什么默认cluster会影响userRoutes的结果？

2022-11-24 07:30 UTC, qhqhqhq commented on apps/portal-web/src/layouts/base/BaseLayout.tsx
> +  const allRoutes = useMemo(() => userRoutes(), [defaultClusterStore.cluster]);
因为需要实现点击header上的`shell`或`文件管理`就跳转到默认集群.  userRoutes中我修改了clicktopath这个属性, 使它的值等于当前默认集群的路径, 但是切换默认集群的时候allRoutes不会自动改变, 所以这里加了一个`defaultClusterStore.cluster`表示当默认集群改变时, 重新生成一下allRoutes

2022-11-24 07:34 UTC, ddadaal commented on apps/portal-web/src/layouts/base/BaseLayout.tsx
> +  const allRoutes = useMemo(() => userRoutes(), [defaultClusterStore.cluster]);
现在的写法里，userRoutes里使用了useStore这个hook，那么userRoutes本身就变成了一个hook。先不说hook的命名规则（useXXX），在memo里使用hook也是不符合规则的。

修改：userRoutes增加一个默认集群参数，通过defaultClusterStore.cluster把默认集群以参数形式传进去，在这里的dep数组中加入这个

2022-11-24 08:47 UTC, ddadaal requested changes

2022-11-24 08:47 UTC, ddadaal commented on apps/mis-web/src/layouts/base/header/index.tsx
> +      />
1. 只是一个单独的SingleClusterSelector，用户可能不知道这是个什么东西。给SingleClusterSelector加一个可选的prop `label`，类型为string。如果用户设置了这个Prop，给SingleClusterSelector加一个item放在第一个，这个item为disabled的状态，label为用户的label。这个label可以起到提示用户这是什么的效果，效果如下

![image](https://user-images.githubusercontent.com/8363856/203735191-3f702cbf-9a1b-4c72-8cf2-cfad2a353ddb.png)

2. 这个选择框是一个有自己逻辑的组件，和header的关系没那么大，应该拆分成一个单独的`DefaultClusterSelector`的组件。useStore、设置Label等逻辑均应该放在单独的组件内。

2022-11-24 09:24 UTC, qhqhqhq commented on apps/mis-web/src/layouts/base/header/index.tsx
> +      />
![image](https://user-images.githubusercontent.com/98016770/203746380-16f2308c-2699-4e31-978d-186a8f329ac9.png)

2022-11-24 15:13 UTC, ddadaal approved these changes

2022-11-24 15:13 UTC, merged