fix(mis-web,mis-server): 初始化时，支持创建ladp中不存在的用户
PKUHPC/SCOW pull request #303
Opened 2022-11-25 07:10 UTC by coovy

2022-11-25 07:21 UTC, ddadaal requested changes
截个图

2022-11-25 07:21 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +    isUserExist: async ({ request, em }) => {
英语语法错。`userExists`就行。下面所有`isUserExists`全部改成`userExists`

2022-11-25 07:21 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +      };
底层不一定是LDAP，另外英语语法错。取名`existsInScow`, `existsInAuth`

另外这里为什么要用对象？直接两个let变量不可以吗？

2022-11-25 07:21 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +        isExist["isExistInScow"] = true;
existsInScow这个变量没有存在的意义。在返回的时候直接`existsInScow: !!user`就可以

2022-11-25 07:21 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +      }));
并不需要在所有集群中检查用户是否存在，因为SCOW要求所有集群的认证系统相同。所以只需要选第一个集群，ssh登录一下看能不能登录就可以知道用户是否在认证系统中存在了。

2022-11-25 07:21 UTC, ddadaal commented on apps/mis-server/src/utils/newUserInDatabaseAndAuth.ts
> +  }
这是在数据库中创建用户，下面是在认证系统中创建用户，这是两个逻辑。而且，在其他地方确实有用到这块在数据库中创建用户的逻辑的，所以这里应该把这个拆分为两个方法。一个是`createUserInDb`，在数据库中创建用户；一个是`createUserInAuth`，在认证系统中创建用户。只需要在数据库中的创建的地方，只调用第一个；同时需要在数据库和认证系统中创建的，调用两个。

另外这个文件应该直接改成`createUser.ts`就可以。

2022-11-25 15:23 UTC, coovy commented
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/96867690/204015388-5400ff8f-2b3c-42a2-831a-4a4b2b08d4cd.png">

2022-11-26 05:38 UTC, ddadaal requested changes

2022-11-26 05:38 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +      }
这里有简化的写法。

```ts
const existsInAuth = await sshRawConnectByPassword(node, name, password, server.logger).then(() => true).catch(() => false);
```

2022-11-26 05:38 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +        await createUserInDatabase(user, server.logger, em);
写到数据库是一定会发生的逻辑，所以应该放到if的外面。

2022-11-26 05:38 UTC, ddadaal commented on apps/mis-server/tests/admin/user.test.ts
>  }));
出现了大量重复逻辑，应该提取为函数。这里虽然和其他的不一样，但是实际上任何对`@scow/lib-auth`的调用都需要mock，那么应该把整个对`@scow/lib-auth`的mock都提取到`data/lib-auth.ts`中，在需要mock的文件中调用。

2022-11-26 05:38 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +        }
这些逻辑是在认证系统中创建用户。我上一次评论说的是抽象一个`createUserInAuth`，为什么没有抽象呢？只有这一个地方用到了在认证系统创建用户吗？user.ts中的createUser的逻辑没有用到相同的逻辑吗？出现了重复逻辑，就应该考虑到把重复逻辑抽象成一个函数，然后调用这个函数。

2022-11-26 05:38 UTC, ddadaal commented on apps/mis-server/tests/init/init.test.ts
> +  const isExistResult = await asyncClientCall(client, "userExists", {
isExist？result就可以了

2022-11-26 05:38 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitAdminForm.tsx
> +      await api.userExists({ body: { email, identityId, name, password } }).then((isExist) => {
isExist -> result或者exists，或者直接解构结果

`then(({ existsInScow, existsInAuth })`

2022-11-26 05:38 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitAdminForm.tsx
> +    publicConfig.ENABLE_CREATE_USER ?
从这里开始逻辑较为复杂，用三元运算符（`?`, `:`）可读性不佳，建议改为if语句

```tsx
if (publicConfig.ENABLE_CREATE_USER) {
const { existsInScow, existsInAuth } = await api...
if (existsInScow) {
}
} else {
}
}
```

2022-11-26 05:38 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitAdminForm.tsx
> +            title: "请确认",
此标题没有意义，建议改为“用户已经存在”

2022-11-26 05:38 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitAdminForm.tsx
> +    publicConfig.ENABLE_CREATE_USER ?
建议重新梳理一下这里的逻辑，减少重复代码。

2022-11-26 05:38 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitAdminForm.tsx
>              type="warning"
type可以根据是否允许创建用户选择不同的type。不支持为warning，支持为success

2022-11-26 05:38 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitAdminForm.tsx
> +              : "当前认证系统不支持创建用户，请确认要添加的用户必须已经存在于认证系统，且用户的ID必须和认证系统中的用户ID保持一致"}
您可以选择加入一个已存在的用户 -> 您可以选择加入一个已存在于认证系统的用户

2022-11-27 13:02 UTC, coovy commented on apps/mis-server/src/services/init.ts
> +        }
啊，这个我当时理解错了，现在想通了

2022-11-27 13:02 UTC, coovy commented on apps/mis-server/tests/admin/user.test.ts
>  }));
这个我发现是在mis-server的plugin里添加了getCapabilities之后，mis-server的测试都需要mock掉这个函数，然后我看到mis-server的测试里有个全局文件，本来是想的从那里怎么一次性导入。但是我把这个mock直接放到全局文件里是不生效的，请问有办法直接全局导入吗？

2022-11-27 13:07 UTC, coovy commented on apps/mis-server/src/services/init.ts
> +        await createUserInDatabase(user, server.logger, em);
这个我的思路是：写到数据库在系统不支持创建用户且用户不存在于认证系统里是不会发生的。     我的想法是：if(用户存在于Auth) createUserInDatabase; else if (系统支持创建用户）{ createUserInDatabase; createUserInAuth;}           如果我将写到数据库放到外面，那么就会有情况：系统不支持创建用户的情况下，这个用户也不存在于认证系统，但是我却要写到数据库。     如果确实写到外面的话，那我要if(不支持创建用户&&不存在于认证系统)  return;else, 好像就写就没这样简洁。 这样想有理解的对吗?

2022-11-27 14:57 UTC, ddadaal requested changes

2022-11-27 14:57 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +        await createUserInDatabase(user, server.logger, em);
为了减少代码缩进层次，确实应该先把短的逻辑放到一开头。这里确实应该是先判断不支持创建用户以及不存在于认证系统的情况。先把这个分支给完成，然后后面的所有逻辑的缩进层次都能少一层。

2022-11-27 14:57 UTC, ddadaal commented on apps/mis-server/tests/admin/user.test.ts
>  }));
你这里想到了在全局文件中一次性导入非常好。你说的全局文件是`global.d.ts`吧。这个文件其实只是提供了一些类型定义，在运行时执行的时候不会被import（所以对global.d.ts的import其实都是引入的类型，但是在运行时这种只引入类型的import将会被删掉），所以这个文件的内容不会被执行。

jest提供了全局配置的功能 https://jestjs.io/docs/configuration#globalsetup-string ，可以参考官方文档以及这个stackoverflow问题 https://stackoverflow.com/questions/63138016/how-to-use-jest-global-setup-and-teardown-in-a-nodejs-project

2022-11-29 08:45 UTC, ddadaal requested changes

2022-11-29 08:45 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +      }
这一块应该直接提到整个逻辑最上面，因为这种情况完全不需要任何处理，直接`return [{ createdResult: false }]`就可以了，省下了上面那一堆逻辑的运行时间，也能减少下面else块的缩进层级。

2022-11-29 08:45 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +          result = true;
如果你看过某些教科书讲一个函数应该只有一个return语句，把它忘了。我们应该让函数尽快return。在这里直接`return [{ createdResult: true }]`就可以了，减少下面缩进层次。

2022-11-29 08:45 UTC, ddadaal commented on apps/mis-server/tests/init/init.test.ts
> +it("Test a user exists scow", async () => {
这个测试是在测什么？名字写清楚。

2022-11-29 08:45 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitAdminForm.tsx
>      setLoading(true);
setLoading放到validateFields()后面，因为validateFields是异步方法，理论上来说可能失败，如果失败了是没有逻辑把loading改回false的。

2022-11-29 08:45 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitAdminForm.tsx
> +    await api.userExists({ body: { identityId } }).then((result) => {
这里是写在线性的逻辑，都用await了，为什么还在用then？


这样代码是不是更清晰一点，下面代码缩进更小一格？
```ts
const result = await api.userExists();

if (result)
...
```

2022-11-29 08:45 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitAdminForm.tsx
> +      else if (!result.existsInAuth && result.getUserCapability && !publicConfig.ENABLE_CREATE_USER) {
}和else放在一行。

2022-11-29 08:45 UTC, ddadaal commented
多写一条评论，详细讲一下在不同情况下可能出现的UI界面。

2022-11-29 10:22 UTC, ddadaal requested changes

2022-11-29 10:22 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +        getUserCapability: false,
既然existsInAuth的取值已经可以判断到底系统支不支持查询用户了，那么这里的getUserCapability就不需要了

2022-11-29 10:22 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +      } else {
这里的else已经没有存在的必要了。

是不是没有理解什么叫缩进层次？

```ts
// 以这里为基础，缩进层次为0
if (a) {
    // 缩进层次为1
} else {
    // 缩进层次为1
    if (b) {
         // 缩进层次为2
    }
}
```

缩进层次越小，代码可读性越好。

现在的代码里，else里面的代码缩进层次为1，但是实际上可以直接删掉else，后面的缩进层次为0。

2022-11-29 10:22 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitAdminForm.tsx
> +    } else {
这里同样可以降低缩进层次。每个if块里最后一个语句加入return结束整个函数，那么后面的本来在else块中的语句（层次为1）就可以从else中提取出来，降低一个缩进层次。

2022-11-29 10:22 UTC, ddadaal commented on protos/server/init.proto
> +  bool createdResult = 1;
proto文件字段的命名规则为下划线`created_result`。另外，result没有必要，这个字段就是表示到底有没有创建，那么直接`created`就可以了

2022-11-29 10:22 UTC, ddadaal commented on protos/server/init.proto
> +  bool getUserCapability = 3;
下划线命名规则

2022-11-29 12:36 UTC, coovy commented
在初始化创建初始管理员功能中，影响UI的因素有：
1. SCOW数据库中是否已经存在此用户2.当前认证系统是否支持创建用户，3. 当前认证系统是否支持查询用户，4.创建用户结果、


这部分展示的界面可能为
1.初始界面：当前认证系统支持创建用户（左）与不支持创建用户（右）的界面：
  

2.添加一个已经存在于SCOW数据库的用户：此时“取消”与“确认”按钮均不会进行操作：
 

接下来都是添加的用户不存在于SCOW的情况下的UI

2.当前认证系统支持创建用户，认证系统支持查询时，添加一个不存在于认证系统的用户:
 

3.所有添加成功的提示信息都是如下：会把输入字段清空，并提示添加成功
 

4. 当前认证系统支持创建用户，认证系统支持查询时，添加一个已经存在于认证系统的用户:
 

5．当前系统不支持创建用户，认证系统支持查询，添加一个不存在于认证系统的用户：
 

6. 当前认证系统支持创建用户，认证系统不支持查询时，添加一个用户：

 
7. 当前认证系统不支持创建用户，认证系统不支持查询时，添加一个用户：
 

8.创建失败情况：此时不会清空字段

2022-11-30 01:55 UTC, ddadaal requested changes

2022-11-30 01:55 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +      }];
一般来说是把短的逻辑先处理，这样缩进层次高的代码块比较短。比如这里应该是

```ts
if (!server.ext.capabilities.getUser) { 
return
}

// ... 
```

2022-11-30 01:55 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +          throw <ServiceError> { code: Status.INTERNAL, message: `Error creating user ${user.id} in auth.` };
这里逻辑没有必要地混乱。这一块的逻辑是这样的：

```ts
if (不是409) { 处理1；} else { 处理2; return; }  处理3;
```

为什么不能写成这样？

```ts
if (是409) { 处理2；return; } 处理1; 处理3; 
```

2022-11-30 01:55 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitAdminForm.tsx
> +      Modal.confirm({
确认弹窗是需要用户确认是否进行**下一步**操作。但是在用户已经存在的条件下，没有**下一步操作**可以进行。所以这里直接modal.error。

另外，弹出Modal应该使用`useModal` hook获取一个modal对象，然后通过这个modal对象调用，不要直接使用Modal静态方法调用。

2022-11-30 01:55 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitAdminForm.tsx
> +      Modal.confirm({
confirm -> error

2022-11-30 01:55 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +      let errorType: string | undefined;
为什么需要这两个变量？这两个变量只会在冲突和出错的时候赋值，但是赋值之后会抛出错误，用户也取不到这两个变量呀？

2022-11-30 01:55 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitAdminForm.tsx
> +                }); }
createdResult永远是true。处理出错情况是通过httpError（处理非200的HTTP响应）或者catch来处理

2022-11-30 01:55 UTC, ddadaal commented on apps/mis-web/src/pages/api/init/createInitAdmin.ts
>    });
通过`handlegRPCError`处理grpc错误，将grpc错误映射为非200的HTTP响应。

2022-11-30 01:55 UTC, ddadaal commented on apps/mis-web/src/pages/api/init/createInitAdmin.ts
> +      errorType: string | undefined,
这两个值没有意义

2022-11-30 02:27 UTC, ddadaal requested changes

2022-11-30 02:27 UTC, ddadaal commented on apps/mis-web/src/pages/api/init/userExists.ts
> +export interface userExistsSchema {
类型首字母大写

2022-11-30 15:05 UTC, coovy commented on apps/mis-web/src/pageComponents/init/InitAdminForm.tsx
> +                }); }
好的，在createdInitAdmin里我去掉了返回created,异常结果全由异常机制来处理

2022-11-30 15:06 UTC, coovy commented on apps/mis-web/src/pages/api/init/createInitAdmin.ts
>    });
好的，不过这里原来也是判断了是否已经初始化，所以我保留了已经初始化过的返回，写成了：
409: { code: "ALREADY_EXISTS_IN_AUTH" | "ALREADY_EXISTS_IN_SCOW" | "ALREADY_INITIALIZED" }；
另外我考虑了一下，还是把userExist调用的结果不从前端传到后端了，而是在这里重新调用一次，因为这些参数从前端传过来可能不可靠？感觉后端api能够有一套自己完整的判断机制比较好？

2022-11-30 15:10 UTC, ddadaal commented on apps/mis-web/src/pages/api/init/createInitAdmin.ts
>    });
你说的是对的，不把userExists的结果传给createInitAdmin，不仅是因为不可靠，而且是因为调用userExists和createInitAdmin之间有时间差，这时间差之间可能会有用户直接创建了这个用户，使得userExists在调用createInitAdmin实际上并不可信，所以一个正确的createInitAdmin实现实际上仍然需要自己检查用户是否存在，**而且**即使检查了用户是否存在，在实际创建用户的时候还需要处理创建用户API返回的已经存在的错误。所以实际上传过来的这个参数是没有意义的。

2022-11-30 17:55 UTC, coovy commented on apps/mis-web/src/pages/api/init/createInitAdmin.ts
>    });
明白了！这点感觉太重要了

2022-12-02 06:35 UTC, ddadaal requested changes

2022-12-02 06:35 UTC, ddadaal commented on protos/server/init.proto
> +message userExistsRequest {
首字母大写

2022-12-02 06:35 UTC, ddadaal commented on protos/server/init.proto
> +  rpc userExists(userExistsRequest) returns (userExistsReply);
rpc首字母大写

2022-12-02 06:35 UTC, ddadaal commented on apps/mis-server/src/utils/createUser.ts
> +    });
createUserInDatabase已经处理租户不存在和用户已经存在的问题了，这里可以不再处理了。这里不处理的错误自然就扔出去了

2022-12-02 06:35 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +          if (e.code === 6) {
处理grpc错误的时候不要直接出现数字，而是使用`@grpc/grpc-js`里的status对象里的具体值，比如这里是`status.ALREADY_EXISTS`，以提高代码可读性

2022-12-02 06:35 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +          throw <ServiceError> { code: Status.INTERNAL, message: `Error creating user ${user.id} in database.` };
这里没有必要单独再处理一遍错误，因为createUserInDatabase出现错误的时候会自动扔出去，这里不处理就继续往上扔。这里单独处理一遍没有意义

2022-12-02 06:35 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +        });
这里确实需要处理错误，但是需要回滚数据库的操作。目前的这两个只是catch一下已有错误，生成一个新的错误，没有意义。

2022-12-02 06:35 UTC, ddadaal commented on apps/mis-server/src/utils/createUser.ts
> +export async function createUserInAuth(
这个函数不需要管数据库的事情。它只负责在认证系统中创建用户，不用管创建失败了回滚数据库的事情。同样，在数据库中创建用户也不需要管认证系统的事情。如果调用者同时需要在数据库和认证系统中创建，那么由调用者负责处理认证系统中创建出错了干什么。

2022-12-02 07:50 UTC, coovy commented on apps/mis-server/src/services/init.ts
> +        });
好的，我把回滚数据库操作从createUserInAuth中提出了，作为catch异常的单独处理，在这里我放在了第二个if Status.INTERNAL 的处理中

2022-12-02 08:02 UTC, ddadaal requested changes

2022-12-02 08:02 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +            };
这里有个设计问题。用户在认证系统中存在、但是在SCOW中不存在，实际上并不造成整个流程的失败：确实创建了一个初始管理员。所以，应该给`CreateInitAdminReply`中增加字段：`bool created_in_auth = 1`，表示这个用户是不是在认证系统中创建了，那么在这里就不应该是throw一个错误，而是返回一个created_in_auth为true的Reply。

2022-12-02 08:02 UTC, ddadaal commented on protos/server/init.proto
> +  bool exists_in_scow= 1;
安装这个VSCode插件 https://marketplace.visualstudio.com/items?itemName=zxh404.vscode-proto3 格式化一下你的proto文件

2022-12-02 08:05 UTC, coovy commented on apps/mis-server/src/utils/setAsAdmin.ts
> +export async function setAsInitAdmin(userId: string, em: SqlEntityManager<MySqlDriver>) {
是的，那我修改一下直接在createIninAdmin加几步操作设置管理员

2022-12-02 08:08 UTC, coovy commented on apps/mis-server/src/services/init.ts
> +          if (e.code === Status.INTERNAL) {
这个是因为我看之前user.ts创建用户的操作里，insertKeyAsUser操作如果失败会报错，但是也似乎是认为创建成功了，并没有回滚数据库，如果不用if, insertKeyAsUser失败也需要回滚数据库吗？

2022-12-02 08:10 UTC, coovy commented on protos/server/init.proto
> +  bool exists_in_scow= 1;
好的

2022-12-02 08:15 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +          if (e.code === Status.INTERNAL) {
在这里如果调用认证系统创建用户的API出错了，那么在认证系统中肯定没有创建出这个用户，如果在这里不删除SCOW中的用户的话，就会出现数据库和认证系统数据不一致的问题。

insertKeyAsUser失败没有回滚这个设计确实可能有问题，目前的想法是尽量保证数据的一致性，不单独处理SSH相关操作操作失败的情况。运行到insertKey的时候，用户已经创建好了，已经不存在数据不一致的问题了。这个之后可能会再想想。

2022-12-02 08:58 UTC, coovy commented on apps/mis-server/src/services/init.ts
> +          if (e.code === Status.INTERNAL) {
有点不是很理解，目前createUserInAuth可能会报三个错误，依次是1.调用认证系统创建用户api可能报的409已存在用户，2.调用认证系统创建用户api时其他失败未创建错误， 3.insertKeyAsUser过程报的错误。

可是目前insertKey操作是放在createUserInAuth里的。如果执行到insertKey报错，那说明此时认证系统用户已经存在。如果insertKey失败不需要回滚数据库，那用if解决调用认证系统创建用户api时其他非409失败错误就已经保证了数据一致。 如果放到外面的话，会使得insertKey失败了也回滚数据库，数据就不一致了。

如果我确实要放到外面，那我在createUserInAuth里把insertKeyAsUser的错误catch掉，不让上报？

2022-12-02 09:05 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +          if (e.code === Status.INTERNAL) {
不好意思我之前没有看到`createUserInAuth`里还有`insertKeyAsUser`过程。

实际上创建一个用户有三个过程：在数据库里创建、在认证系统里创建和给新用户插入key。目前的createUserInAuth实际上包含了后面两个过程，这是不合理的。我们应该把后面两个流程拆开，新的`createUserInAuth`只包括在在认证系统里创建，然后给新用户插入key应该再拆成一个函数`insertKeyToNewUser`。考虑到新的`createUserInAuth`的逻辑完全等于`@scow/lib-auth`中引入的`createUser`，所以就无需再有createUserInAuth，需要在认证系统里创建的时候直接调用`@scow/lib-auth`里的`createUser`。

这样拆分后，是不是错误处理会简单一些？在调用认证系统的`createUser`的时候出现错误，就回滚数据库；如果是后面`insertKeyToNewUser`出错，就不回滚。

2022-12-02 09:08 UTC, coovy commented on apps/mis-server/src/services/init.ts
> +          if (e.code === Status.INTERNAL) {
好的，明白了，谢谢学长

2022-12-03 01:36 UTC, ddadaal requested changes
逻辑都很清晰了，非常好。

另外，还需要把mis-server里已经有的user.ts里的createUser的逻辑用你这次提取出来这几个函数改写。

2022-12-03 01:36 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +            createdInAuth = true;
没有return，整个await仍然会抛出异常。

2022-12-03 01:36 UTC, ddadaal commented on apps/mis-server/src/services/init.ts
> +        });
尽量不要使用let，尽量使用const。这里可以写成

```ts
const createdInAuth = await createUser(...)
     .then(() => true)
     .catch(async (e) => {
         if (e.status === 409) { 
             server.logger.warn("User exists in auth.");    
             return false;
           }
         server.logger.error(e, "Error..);
         throw ...
      });
```

2022-12-04 08:21 UTC, coovy commented
> 逻辑都很清晰了，非常好。
> 
> 1. 还需要把mis-server里已经有的user.ts里的createUser的逻辑用你这次提取出来这几个函数改写。
> 2. 还需要增加这个createInitAdmin的测试。

关于2，测试里是有createInitAdmin的测试的，是之前存在的测试，它测试了创建用户是否成功以及角色是否正确106#L, it("creates an init admin user", async()=> ......;

另外还有个地方存在疑问，看之前user.ts中createUser代码，发现insertKeyAsUser函数中需要的username参数，传入的是user.name而不是userId，考虑到userId名称才是唯一的，所以这里有疑问

2022-12-04 08:24 UTC, ddadaal commented
这里传错了，应该传userId。怪不得之前创建用户后仍然没有自动配置免密登录，原来是这里的问题。

2022-12-04 08:28 UTC, coovy commented
> 这里传错了，应该传userId。怪不得之前创建用户后仍然没有自动配置免密登录，原来是这里的问题。

那我改一下

2022-12-04 09:03 UTC, ddadaal approved these changes
非常好。这个功能对空集群的初始化非常重要。这个功能逻辑比较复杂，中途也一起改了很多地方，非常不容易。如果你没有更多地方要改了，让它ready for review。

2022-12-04 10:15 UTC, coovy commented
> 非常好。这个功能对空集群的初始化非常重要。这个功能逻辑比较复杂，中途也一起改了很多地方，非常不容易。如果你没有更多地方要改了，让它ready for review。

确认了一遍，删除了一个多余的console.log，应该暂时没了，但是还没有实际集群测试过，但我的集群可能需要我重新搞一下，可能得过两天，另外关于认证系统是否支持查询的情况，是否支持创建的情况，可以在实际集群进行配置选择吗？

2022-12-04 11:41 UTC, ddadaal commented
认证系统是否支持查询是通过capability的getUser拿到。你现在也是这么写的。实际集群是部署的认证系统自己通过`GET /capabilities`接口报告的。你的”在实际集群中进行配置选择“是什么意思？

2022-12-15 04:05 UTC, coovy commented
> 认证系统是否支持查询是通过capability的getUser拿到。你现在也是这么写的。实际集群是部署的认证系统自己通过`GET /capabilities`接口报告的。你的”在实际集群中进行配置选择“是什么意思？

当时是我理解错了，我想的测试不同认证系统能力的情况下的功能是否正常。

刚刚我在ssh和ldap认证系统下测试，数据库中已有用户，认证系统中已存在用户，认证系统不存在用户情况下功能均正常

2022-12-15 07:18 UTC, ddadaal requested changes

2022-12-15 07:18 UTC, ddadaal commented on apps/mis-server/src/plugins/fetch.ts
> +  f.addExtension("capabilities", capabilities);
这个文件是用来放获取作业相关的业务逻辑的，和获取认证系统的能力无关。获取认证系统的能力的API应该放在单独的plugin中，比如`authPlugin`

2022-12-15 07:18 UTC, ddadaal commented on apps/mis-web/src/pages/api/init/createInitAdmin.ts
> +      [Status.INTERNAL]: () => ({ 500: null }),
如果某个grpc不需要特定的处理，就不需要单独写错误处理，这一行INTERNAL的错误处理直接删掉就行

2022-12-15 13:08 UTC, ddadaal commented
太棒了

2022-12-15 13:09 UTC, merged