fix(portal): 已创建交互式应用列表增加刷新按钮
PKUHPC/SCOW pull request #323
Opened 2022-11-29 09:30 UTC by WZD09

2022-11-29 16:06 UTC, WZD09 commented
![image](https://user-images.githubusercontent.com/102740885/204580658-f86e9c02-c23d-4d38-899d-c6a38dc9d6bf.png)
创建的应用页面增加刷新按钮。新建应用后，状态为`PENDING`，手动刷新后作业状态为`RUNNING`，出现连接按钮。增加用户需要刷新的提示。

2022-11-30 01:59 UTC, ddadaal commented
为什么要给这个Alert？创建作业后切换回来的时候刷新了一次，这时是显示的当前最新的状态。如果用户后续还需要最新的状态，直接点刷新就可以了。

2022-12-04 06:50 UTC, ddadaal submitted a review, later dismissed

2022-12-04 06:51 UTC, ddadaal commented
这一页有自动刷新，是不是给用户一个提示比较好？或者给一个是否自动刷新的checkbox。

2022-12-05 06:31 UTC, WZD09 commented
> 


> 这一页有自动刷新，是不是给用户一个提示比较好？或者给一个是否自动刷新的checkbox。

现在添加了这样的是否选择自动刷新checkbox可以吗，默认是勾选的 自动进行10s的自动刷新，如果取消勾选 不再自动刷新。
![image](https://user-images.githubusercontent.com/102740885/205564617-5456b98a-235b-41bb-a7c0-4b6ff239cf5b.png)

2022-12-05 06:31 UTC, ddadaal requested changes

2022-12-05 06:31 UTC, ddadaal commented on apps/portal-web/src/pageComponents/app/AppSessionsTable.tsx
> +            自动刷新
10s自动刷新

2022-12-05 06:41 UTC, ddadaal approved these changes

2022-12-05 06:56 UTC, merged