feat(mis): 修改多集群操作错误处理方式
PKUHPC/SCOW pull request #343
Opened 2022-12-05 07:20 UTC by qhqhqhq

2022-12-05 07:24 UTC, ddadaal requested changes

2022-12-05 07:24 UTC, ddadaal commented on apps/mis-server/src/plugins/clusters.ts
> +          metadata: scowErrorMetadata(CLUSTEROPS_ERROR_CODE),
用这个错误方式，更详细的错误信息（在这里就是具体哪些集群出错了）应该放在metadata里，不是放在details里。`scowErrorMetadata`函数的extra参数就是接受更多的错误信息。

```ts
{
     "SCOW_CLUSTEROPS_FAILED_CLUSTERS": failed,
}
```

2022-12-05 07:24 UTC, ddadaal commented on apps/mis-server/src/utils/error.ts
> +export const scowErrorMetadata = (code: string, extra?: Record<string, MetadataValue>) => {
这个extra的value的类型应该可以接受数组。试试把它改成`Record<string, MetadataValue | MetadataValue[]>`

2022-12-05 09:15 UTC, qhqhqhq commented on apps/mis-server/src/plugins/clusters.ts
> +          metadata: scowErrorMetadata(CLUSTEROPS_ERROR_CODE),
extra的内容会以键值对的形式保存在metadata里, 那么在route函数中该以什么形式把这些额外的参数传递到前端? 我现在的想法是把下面的details替换成一个叫extra的对象, 存储额外数据
```typescript
export const route: typeof rawRoute = (schemaName, handler) => {
  return rawRoute(schemaName, async (req, res) => {
    const response = handler(req, res);
    if (response instanceof Promise) {
      return response.catch((e) => {
        if (!(e.metadata instanceof Metadata)) { throw e; }

        const SCOW_ERROR = e.metadata.get("IS_SCOW_ERROR");
        if (!SCOW_ERROR) { throw e; }
        const code = e.metadata.get("SCOW_ERROR_CODE")[0].toString();
        const details = e.details;
        return { 500: { code, details } };
      });
    }
  });
};
```

2022-12-05 09:18 UTC, ddadaal commented on apps/mis-server/src/plugins/clusters.ts
> +          metadata: scowErrorMetadata(CLUSTEROPS_ERROR_CODE),
你说的有道理，放在metadata里的话就不能直接传到前端去了。可以先这样试试，把错误信息放在details里。

2022-12-08 13:23 UTC, ddadaal approved these changes

2022-12-08 13:23 UTC, merged