fix(portal): webl类应用配置文件的formData项可以使用before脚本的环境变量
PKUHPC/SCOW pull request #352
Opened 2022-12-07 14:41 UTC by WZD09

2022-12-07 14:48 UTC, ddadaal commented on apps/portal-server/src/clusterops/slurm/app.ts
> +          const sessionInfo = `echo -e "{${customForm}}" >$SERVER_SESSION_INFO`;
这里的逻辑较为复杂，不容易理解也容易出错。建议抽出一个函数，然后在单元测试里写测试用例

2022-12-09 09:05 UTC, WZD09 commented on apps/portal-server/src/clusterops/slurm/app.ts
> +const SERVER_SESSION_INFO = "server_session_info.json";
为了保存和读取更多变量，把SERVER_SESSION_INFO 这个文件改成了json格式的server_session_info.json，内容是`{"HOST":"login01","PORT":50588,"PASSWORD":"3Vet45EaVQvH","TEST_USER":"bob"}`这种格式。

2022-12-09 09:08 UTC, WZD09 commented
为了保存和读取更多变量，把SERVER_SESSION_INFO 这个文件改成了json格式的server_session_info.json，内容是{"HOST":"login01","PORT":50588,"PASSWORD":"3Vet45EaVQvH","TEST_USER":"bob"}这种格式。

2022-12-09 10:05 UTC, ddadaal requested changes

2022-12-09 10:09 UTC, WZD09 commented on apps/portal-server/src/clusterops/slurm/app.ts
> +  [key: string]: string | number;
是的 只有port是number，那我都改成string 然后把port转换成number吧

2022-12-09 10:12 UTC, WZD09 commented on apps/portal-server/src/clusterops/slurm/app.ts
> +  password: string;
实际上是 `{"HOST":"login01","PORT":50588,"PASSWORD":"3Vet45EaVQvH","TEST_USER":"bob"}` 那我把这里改成大写的

2022-12-09 10:16 UTC, WZD09 commented on apps/portal-server/src/clusterops/slurm/app.ts
> +  [key: string]: string | number;
只有port是number，但是如果这里不写number类型 port跟Index signature不兼容了

2022-12-09 10:22 UTC, ddadaal commented on apps/portal-server/src/clusterops/slurm/app.ts
> +  [key: string]: string | number;
ok，那在这里备注一下，其他key均为string

2022-12-09 10:27 UTC, ddadaal commented
这个PR实装后，之前版本创建的交互式应用（也就是不是json格式的session文件）还能正常显示吗？

2022-12-09 10:30 UTC, WZD09 commented
> 

是不兼容之前创建的app的，因为这个连接应用的时候会去读的文件不存在

2022-12-09 10:42 UTC, ddadaal commented
那这个PR就这样把，因为还没有发1.0，所以破坏性更新是可以接受的。发了1.0之后需要想办法兼容之前的逻辑。

2022-12-09 10:43 UTC, ddadaal approved these changes

2022-12-09 11:22 UTC, merged