feat(mis): 优化平台管理的全部租户列表
PKUHPC/SCOW pull request #423
Opened 2023-01-16 12:53 UTC by qhqhqhq

2023-01-16 15:09 UTC, ddadaal requested changes

2023-01-16 15:09 UTC, ddadaal commented on apps/mis-server/src/entities/Tenant.ts
> +  @Property({ columnType: DATETIME_TYPE, defaultRaw: "CURRENT_TIMESTAMP(6)" })
这里(6)不必要

2023-01-17 02:25 UTC, ddadaal commented on apps/mis-server/src/entities/Tenant.ts
> +  @Property({ columnType: DATETIME_TYPE, defaultRaw: "CURRENT_TIMESTAMP" })
我搞错了，这里是需要这个(6)的……

2023-01-17 02:26 UTC, ddadaal commented on apps/mis-server/src/entities/Tenant.ts
> +  @Property({ columnType: DATETIME_TYPE, defaultRaw: "CURRENT_TIMESTAMP" })
可以把这个CURRENT_TIMESTAMP(6)提取成一个常量CURRENT_TIMESTAMP放在DATETIME_TYPE那个文件里，然后所有使用DATETIME_TYPE类型的地方的defaultRaw值都改成这个常量，这样就不会犯错了

2023-01-17 07:08 UTC, qhqhqhq commented on apps/mis-server/src/migrations/.snapshot-scow_server.json
> +          "default": "current_timestamp(0)",
运行migration命令默认生成的default值是`current_timestamp(0)`, sql语句是`alter table `tenant` add `create_time` DATETIME(6) not null default current_timestamp(0);`, 这个语句跑不通, 要改成`current_timestamp(6)`.  那么这个文件也要改吗?

2023-01-17 07:25 UTC, ddadaal commented on apps/mis-server/src/migrations/.snapshot-scow_server.json
> +          "default": "current_timestamp(0)",
要改。把代码里的defaultRaw改成current_timestamp(6)之后，这个生成的还是(0)吗？

2023-01-17 07:56 UTC, qhqhqhq commented on apps/mis-server/src/migrations/.snapshot-scow_server.json
> +          "default": "current_timestamp(0)",
是的

2023-01-17 08:05 UTC, qhqhqhq commented on apps/mis-server/src/migrations/.snapshot-scow_server.json
> +          "default": "current_timestamp(0)",
```
 "create_time": {
          "name": "create_time",
          "type": "DATETIME(6)",
          "unsigned": false,
          "autoincrement": false,
          "primary": false,
          "nullable": false,
          "length": 0,
          "default": "current_timestamp(0)",
          "mappedType": "datetime"
        },
```
user表create_time的这一项也是(0), 但是在数据库中是(6)
<img width="590" alt="image" src="https://user-images.githubusercontent.com/98016770/212842451-9dcd5026-b3d8-4ebd-a671-9b94d08aac20.png">

2023-01-17 10:28 UTC, ddadaal commented
加一下changeset文件。给mis-web和mis-server MINOR的版本更新

2023-01-18 00:21 UTC, ddadaal approved these changes

2023-01-18 00:21 UTC, merged