feat(mis): 平台管理部分，计费价格模块优化
PKUHPC/SCOW pull request #431
Opened 2023-01-20 01:43 UTC by qhqhqhq

2023-01-20 01:44 UTC, qhqhqhq commented
![image](https://user-images.githubusercontent.com/98016770/213600153-70ec8496-38a4-43ba-b98b-1786d8a9cd0a.png)
现在页面大致这样, 先测下功能的正确性

2023-01-20 08:15 UTC, qhqhqhq commented
changeset 设置为什么?

2023-01-21 03:00 UTC, ddadaal commented
changeset作用：
1. 记录每个版本号之间的变化，自动生成changelog
2. 让changelog自动确定版本如何提升

2023-01-21 03:07 UTC, ddadaal requested changes

2023-01-21 03:07 UTC, ddadaal commented on apps/mis-web/src/models/job.ts
> +};
AmountStrategyDescribe -> AmountStrategyDescriptions
AmountStrategyAlgorithm -> AmountStrategyAlgorithmDescriptions

2023-01-21 03:07 UTC, ddadaal commented on apps/mis-web/src/pageComponents/job/ManageJobBillingTable.tsx
> +                  <a href="https://icode.pku.edu.cn/SCOW/docs/info/mis/business/billing">{"细节请查阅文档"}</a>
文档地址之后会提成一个常量，现在先用github pages的地址。

2023-01-21 03:07 UTC, ddadaal commented on apps/mis-web/src/pages/admin/jobBilling.tsx
> +            />
不选择管理平台计费项确实有点奇怪。试试设计成一个单选组，一个选择是平台，另一个选择是租户，租户的单选项里还有个租户Select，选择其中一个的时候把另一个disable掉。

把这个单选组提取为一个单独的组件。

2023-01-21 03:08 UTC, ddadaal commented on apps/mis-web/src/pageComponents/job/ManageJobBillingTable.tsx
> +          >
历史计费项按时间顺序倒序排列直观一点。

2023-01-21 03:09 UTC, ddadaal commented on apps/mis-web/src/pageComponents/job/ManageJobBillingTable.tsx
> +    return tenant + " " + (nums.length === 0 ? 1 : Math.max(...nums) + 1);
计费项ID中，租户和数字之间加个下划线吧，加空格看起来不像是一个单独的ID

2023-01-29 07:35 UTC, ddadaal requested changes

2023-01-29 07:35 UTC, ddadaal commented on apps/mis-web/src/pageComponents/job/PlatformOrTenantRadio.tsx
> +  onChange: (value: string) => void;
1. 如果选择了平台，onChange将会以`undefined`为参数调用，在函数签名这里没有体现undefined这个值
2. 一般来说null值表示“这个属性有值，但是这个值是空“，undefined代表”这个属性没有取值“。这里应采用null表示选择为平台的情况，并增加对应的注释解释当值为null时是什么意思
3. 目前value和onChange都是required的property，使得这个组件不能被用于FormItem。应把这两个属性修改为optional的。文档：https://ant.design/components/form-cn#formitem

2023-01-29 07:35 UTC, ddadaal commented on apps/mis-web/src/pageComponents/job/ManageJobBillingTable.tsx
> +            pagination={false}
当数据量太大时应该有分页。参考文档：[如何在没有数据或只有一页数据时隐藏分页栏](https://ant.design/components/table-cn#%E5%A6%82%E4%BD%95%E5%9C%A8%E6%B2%A1%E6%9C%89%E6%95%B0%E6%8D%AE%E6%88%96%E5%8F%AA%E6%9C%89%E4%B8%80%E9%A1%B5%E6%95%B0%E6%8D%AE%E6%97%B6%E9%9A%90%E8%97%8F%E5%88%86%E9%A1%B5%E6%A0%8F)

2023-01-29 10:49 UTC, ddadaal commented on apps/mis-web/src/pageComponents/job/PlatformOrTenantRadio.tsx
> +  onChange?: (value: string) => void;
value: string => value: string | null。要体现所有可能的取值

2023-01-29 10:49 UTC, ddadaal commented on apps/mis-web/src/pageComponents/job/PlatformOrTenantRadio.tsx
> +  const [select, setSelect] = useState(value);
这个状态是没有必要的，这个组件的状态就是prop传进来的状态（react的思想：UI=组件(状态)，组件就是这个函数，状态就是参数）并且，按目前的方案，如果外部value值改变了，这个组件的值不会跟随变化，因为这个组件是用的自己的状态。

2023-01-29 11:21 UTC, qhqhqhq commented on apps/mis-web/src/pageComponents/job/PlatformOrTenantRadio.tsx
> +  onChange?: (value: string) => void;
这里是什么意思? 不是已经是`string | null`了吗

2023-01-29 11:25 UTC, ddadaal commented on apps/mis-web/src/pageComponents/job/PlatformOrTenantRadio.tsx
> +  onChange?: (value: string) => void;
onChange函数的参数。否则onChange函数不知道value还可能取值为null。

2023-01-29 11:38 UTC, ddadaal commented on apps/mis-web/src/pageComponents/job/PlatformOrTenantRadio.tsx
> +  const [tenant, setTenant] = useState(value || "");
这个状态也不应该存在。

需要意识到这里有两个状态：Radio.Group的状态和TenantSelector的状态。

当value是null时，Radio.Group选择平台；当value不是null时，Radio.Group选择租户。所以，Radio.Group有两个可能取值，这个值是从value的值衍生的，所以直接用一个bool的局部常量表示
```tsx
// isPlatform的取值决定Radio.Group的值。
const isPlatform = value === null || value === undefined;

<Radio.Group
  onChange={(e) => {
    // 这里的val就是Radio.Group的状态，其类型为boolean
    const isPlatform = e.target.value;
    // 这个函数被调用，说明用户选择了平台或者租户
    // 如果用户选择了平台，则应该使用null参数调用上层的事件处理函数onChange。
    // 否则，则是选择租户。应该给一个租户的默认值，即所有租户的第一项
    // 需要从外部传入所有租户数组tenants
    onChange?.(isPlatform ? null : tenants[0]);
  }}
  value={isPlatform}
>
// ...
</Radio.Group>
```

接下来，当value不为空时，value的值决定了TenantSelector的状态，所以把value和onChange传给下一层的TenantSelector即可，让TenantSelector负责显示UI和响应事件。

2023-01-29 11:40 UTC, ddadaal commented on apps/mis-web/src/pageComponents/job/PlatformOrTenantRadio.tsx
> +  const [tenant, setTenant] = useState(value || "");
https://ant.design/components/radio-cn#components-radio-demo-radiogroup-more 看这个例子，如何把一个其他组件包括在Radio里，不需要像这个例子一样当不选择的时候隐藏TenantSelector，正常显示就可以了。

2023-01-29 11:49 UTC, ddadaal commented on apps/mis-web/src/pageComponents/job/PlatformOrTenantRadio.tsx
> +  const [tenant, setTenant] = useState(value || "");
哦，租户是在TenantSelector中获取的，这个组件是不知道有哪些租户的，还是我自己来改下这块把。

2023-01-29 13:34 UTC, ddadaal commented on apps/mis-web/src/pages/admin/jobBilling.tsx
> +};
这段逻辑是mis-server有的吧。最好还是不要有重复逻辑。

这里可以修改gRPC API，给返回的JobBillingItem message增加一个active属性，这样前端就可以直接根据active的值确定哪些是active的、哪些是历史的

2023-01-29 14:46 UTC, qhqhqhq commented on apps/mis-web/src/pages/admin/jobBilling.tsx
> +};
我最开始就是写成这样的逻辑, 但是发现这样改非常麻烦
首先是`mis-server/tests/job/billingItems.test.ts`这个文件里面的所有测试都需要修改, mock文件也得修改; 
而且api.getbillingitems和api.getbillingtable这两个http接口都是调用这个grpc接口, 这样修改可能连带着其它地方的代码出现问题; 
还有就是如果增加active这个属性, 那么activeonly这个属性就会比较奇怪, 当activeonly为true时返回的items的active就全都是true, 含义就重复了

2023-01-30 01:25 UTC, ddadaal approved these changes

2023-01-30 01:25 UTC, merged