feat(mis): 在初始化界面的编辑作业价格表tab中使用新的管理计费表组件
PKUHPC/SCOW pull request #466
Opened 2023-02-18 05:25 UTC by qhqhqhq

2023-02-18 10:44 UTC, ddadaal requested changes
现在的设计是，如果一个计费项没有对应的价格，那么后端会返回一个id和其他属性为空的计费价格。是这样的吗？

这样设计的问题和java等传统面向对象中对象引用类型变量可以为null的问题是一样的。类型限制了一个变量的取值范围，如果一个对象属于一个类型，那么它是有意义的，它确实指向这个变量的合法取值范围中的一个元素。但是这里的id为空的对象就打破了这一约束：这个变量确实属于这个类型，但是它实际上并不合法，它没有代表任何一个实际的价格项。这就像给一个对象引用类型给null一样，函数以为自己拿到了一个合法的这个类型的对象，而根据代码的定义，所有这个类型的对象都具有某个方法，所以这个兴奋地直接在这个对象上调方法，结果这个对象是个null，直接NullPointerException。新的编程语言引入可空类型也就是为了解决这个问题，在类型层面上将语义表达得更加精确。

看一下这样设计带来的问题：

1. amount_strategy变成了optional。一个合法的计费项的amount_strategy一定不是optional的，但是为了兼容这样的设计，只能把这个proto改成这样。这样，这个proto message就不能精确地表示一个计费项对象的属性的性质。
2. 表中增加了大量根据计费项对象中的某个属性的值是否为空来显示不同组件的逻辑。表中某一行是因为**这个属性为空**所以应该这么显示，还是因为**这一个对象为空**所以应该这么显示呢？应该是后者。目前的逻辑，只是为了特殊处理一个不合法的对象的取值，而没有体现具体的业务逻辑。

这里我们应该这样考虑：价格表这个组件才是这些数据的最终消费者。价格仍然是getBillingItems API获取的价格，但是之前价格表组件假设所有计费项都能在这些价格中找到对应的价格，所以仅根据所有计费价格的数据就可以算出整个表的结构。但是现在有的价格项找不到对应的数据了，所以需要从其他地方获取数据来算出整个表的架构，价格数据只是为了显示一个计费项是否有价格而已。整个集群的所有价格项可以在后端拿`runtimeConfig.CLUSTERS_CONFIG`算出来。逻辑可以参考apps/mis-web/src/pages/api/job/getBillingTable.ts。

2023-02-18 14:32 UTC, ddadaal commented on apps/mis-web/src/pageComponents/init/InitJobBillingTable.tsx
> +          您可以在这里设置默认作业价格表。未设置的将会以0元计费。
诶，这里发现一个小问题。目前的逻辑是未设置的将会报错。所以这里的文字改为：

> 您可以在这里设置默认作业价格表。您必须全部设置完全部价格才能完成初始化。

2023-02-20 15:07 UTC, ddadaal requested changes

2023-02-20 15:07 UTC, ddadaal commented on protos/server/job.proto
>    repeated JobBillingItem items = 1;
所以有了history_items之后，这个就变成active_items了吗？变量的含义变了，最好从名字上表现出来

2023-02-21 04:18 UTC, qhqhqhq commented on apps/mis-web/src/pages/api/job/getBillingTable.ts
> +        const path = [cluster, partition.name, qos].filter((x) => x).join(".");
顺便改了下这里

2023-02-21 06:31 UTC, ddadaal approved these changes

2023-02-21 06:31 UTC, merged