fix(portal): 修复home目录下创建文件夹失败的问题
PKUHPC/SCOW pull request #483
Opened 2023-03-01 07:42 UTC by tongchong

home目录下创建文件夹失败后返回失败的原因，并于页面展示
<img width="456" alt="屏幕截图_20230228_213501" src="https://user-images.githubusercontent.com/25954437/222074688-ebecbb81-2342-4556-890e-38cbed9222ac.png">

2023-03-01 08:57 UTC, ddadaal commented on .changeset/late-doors-happen.md
> +"@scow/portal-web": minor
这是个bugfix，给patch的版本就可以了

2023-03-01 09:10 UTC, tongchong commented on .changeset/late-doors-happen.md
> +"@scow/portal-web": minor
好的

2023-03-02 02:44 UTC, ddadaal commented
目前只是个临时处理。打算通过这个PR让所有SFTP错误都能直接显示在前端，可能还需要一段时间。可以测试的时候我通知一下。

2023-03-03 15:19 UTC, ddadaal commented
现在这样改了之后，报错的信息和PR描述中的图不一样的了吧？截一张最新的图放在PR描述里。

2023-03-04 02:59 UTC, tongchong commented
> 现在这样改了之后，报错的信息和PR描述中的图不一样的了吧？截一张最新的图放在PR描述里。

好的，换图了

2023-03-04 04:14 UTC, ddadaal approved these changes

2023-03-04 04:19 UTC, ddadaal requested changes

2023-03-04 04:19 UTC, ddadaal commented on libs/ssh/tests/sftp.test.ts
> +  }
同样的代码格式出现过很多次，考虑提取出公共函数。

```ts
async function expectSftpError(fn: () => Promise<unknown>) {
    // 怎么实现？
}

await expectSftpError(async () => {
    await sftpRename(testServer.sftp)(filePath, "/data/home/testNew");
});
```

2023-03-04 04:19 UTC, ddadaal commented on apps/portal-server/src/utils/ssh.ts
> +    } else if (e instanceof SftpError) {
上一个if里直接throw掉了，这里应直接把if放到全新的一行，减少这一行的代码缩进。对比：
```ts
if (e instanceof SshConnectError) {
   throw ???
}

if (e instanceof SftpError) {
  throw ??;
}
```

2023-03-04 04:19 UTC, ddadaal commented on libs/ssh/tests/ssh.test.ts
> +    await sshRmrf(ssh, filePath);
有没有考虑为什么其他测试还写了一行`expect("").fail()`呢？因为如果这一行并没有抛出错误，整个测试仍然会成功。

2023-03-05 08:33 UTC, tongchong commented on libs/ssh/tests/sftp.test.ts
> +  }
好的，我改了一下，之前因为是测试案例，就放松了点

2023-03-05 08:34 UTC, tongchong commented on libs/ssh/tests/ssh.test.ts
> +    await sshRmrf(ssh, filePath);
实际上没抛出错误就是没测到位

2023-03-05 08:36 UTC, tongchong commented on apps/portal-server/src/utils/ssh.ts
> +    } else if (e instanceof SftpError) {
好的，这里之前还真没想到。其实throw了，这个else没有必要

2023-03-05 08:38 UTC, ddadaal commented on libs/ssh/tests/sftp.test.ts
> +});
这样设计好多了，但是还有一点小问题：

1. sftpErrorCase -> sftpErrorCases
2. Function这个定义一般不要用，因为不够具体。它的参数是什么，返回值是什么？另外在这里，sftpErrorCases是一个常量，ts是可以推断出类型的，不需要自己再加一个类型。
3. jest自己有it.each可以定义参数化测试用例，和原生forEach的对比可以参考：https://stackoverflow.com/questions/57171579/using-jests-test-each-vs-looping-with-foreach 。目前我们还是偏向用it.each方案

2023-03-05 08:57 UTC, tongchong commented on libs/ssh/tests/sftp.test.ts
> +});
好的，那我这边再改一下

2023-03-05 13:20 UTC, tongchong commented on libs/ssh/tests/sftp.test.ts
> +});
我发现我这边如果使用it.each，代码复杂度会比使用原生的forEach高，那还有必要改为jest的it.each吗？如下：
`interface SftpTestCase {
  name: string;
  func: (sftp: SFTPWrapper ) => (...args: any[]) => Promise<unknown>;
  args: (string|number|Buffer)[];
}
const sftpErrorCases: SftpTestCase[] = [
  { name: "sftpWriteFile", func: sftpWriteFile, args: ["/data/home/newfile", Buffer.alloc(0)] },
  { name: "sftpReadFile", func: sftpReadFile, args: ["/data/home/demo_admin"] },
  { name: "sftpReaddir", func: sftpReaddir, args: ["/data/home/test"] },
  { name: "sftpChmod", func: sftpChmod, args: ["/data/home/test", "555"] },
  { name: "sftpChown", func: sftpChown, args: ["/data/home/test", 512, 555] },
  { name: "sftpRealPath", func: sftpRealPath, args: ["/data/home/test"] },
  { name: "sftpStat", func: sftpStat, args: ["/data/home"] },
  { name: "sftpUnlink", func: sftpUnlink, args: ["/data/home/test"] },
  { name: "sftpRmdir", func: sftpRmdir, args: ["/data/home/test"] },
  { name: "sftpRename", func: sftpRename, args: ["/data/home/test", "/data/home/testNew"] },
  { name: "sftpMkdir", func: sftpMkdir, args: ["/data/home/test"] },
];

sftpErrorCases.forEach(item=>{
  item.toString=()=>{return item.name};
})

it.each(sftpErrorCases)("%s should catch error and throw SftpError ", async ({ name, func, args }) => {
  try {
    await func(testServer.sftp)(...args);
    fail("should not reach here");
  } catch (e) {
    expect(e).toBeInstanceOf(SftpError);
  }
});`

2023-03-05 13:38 UTC, ddadaal commented on libs/ssh/tests/sftp.test.ts
> +});
为什么要自己定义类型呢？`it.each`中的类型ts会自动推断。函数的名字可以从函数这个对象的`name`属性中获取，所以也不用自己写。唯一的问题是ts无法自动推断每个测试用例中的args的类型为`Parameters<typeof fn>`，所以得手动把args as成any[]。

```ts
it.each([
  { fn: sftpWriteFile, args: ["/data/home/newfile", Buffer.alloc(0)]},
  { fn: sftpReadFile, args: ["/data/home/demo_admin"]},
  { fn: sftpReaddir, args: ["/data/home/test"]},
  { fn: sftpChmod, args: ["/data/home/test", "555"]},
  { fn: sftpChown, args: ["/data/home/test", 512, 555]},
  { fn: sftpRealPath, args: ["/data/home/test"]},
  { fn: sftpStat, args: ["/data/home"]},
  { fn: sftpUnlink, args: ["/data/home/test"]},
  { fn: sftpRmdir, args: ["/data/home/test"]},
  { fn: sftpRename, args: ["/data/home/test", "/data/home/testNew"]},
  { fn: sftpMkdir, args: ["/data/home/test"]},
])("$fn.name should catch error and throw SftpError ", async ({ fn, args }) => {

  try {
    await fn(testServer.sftp)(...args as any[]);
    expect("").fail("should not reach here");
  } catch (e) {
    expect(e).toBeInstanceOf(SftpError);
  }

});
```
![image](https://user-images.githubusercontent.com/8363856/222963876-f4070581-bbba-4a14-80ca-6256025626e1.png)

2023-03-05 13:48 UTC, tongchong commented on libs/ssh/tests/sftp.test.ts
> +});
谢谢，因为没有设置类型的话，...args 会报错，但我没想到可以直接用断言 as any[] 来解决这个问题

2023-03-05 14:03 UTC, ddadaal commented on libs/ssh/tests/sftp.test.ts
> +});
用`as any[]`确实不好，应尽可能少用。但是可以发现这里在定义测试用例数组的时候就已经无法确保类型安全了（无法确保args属性的类型是同一个对象中的fn属性的参数），所以这里用`as any[]`并没有进一步破坏类型安全。你最开始的版本也使用了Array<any>定义args的类型。

2023-03-05 14:04 UTC, ddadaal commented on libs/ssh/tests/sftp.test.ts
> +});
为什么把之前你的设计删掉？你之前做的设计可以留着，以便以后作为自己和其他人的参考。

2023-03-06 00:00 UTC, tongchong commented on libs/ssh/tests/sftp.test.ts
> +});
只是想合并部分commit，以后这种更改都留着作为参考

2023-03-06 00:05 UTC, tongchong commented on libs/ssh/tests/sftp.test.ts
> +});
最初直接使用Array、Function，都是为了解决fn属性的参数校验，这里用as any[]是更优解

2023-03-06 03:17 UTC, ddadaal commented
合并最新的master

2023-03-06 06:34 UTC, ddadaal approved these changes

2023-03-06 07:19 UTC, lyl-available approved these changes

2023-03-06 07:27 UTC, merged