fix(mis, portal): 修复用户退出登录，token未删除问题
PKUHPC/SCOW pull request #493
Opened 2023-03-04 09:59 UTC by coovy

原问题：原问题，由于用户推出后，执行的操作是先清除cookie，再从redis删除token, 但由于cookie已被删除，导致从cookie中解析不到要在redis中删除的token

2023-03-04 12:54 UTC, ddadaal requested changes

2023-03-04 12:54 UTC, ddadaal commented on apps/mis-web/src/pages/api/auth/logout.ts
> -  method: "DELETE";
为什么要修改API层的Logout的API的HTTP method？

2023-03-04 12:54 UTC, ddadaal commented on apps/portal-web/src/pages/api/auth/logout.ts
> +    deleteToken(token, runtimeConfig.AUTH_INTERNAL_URL)
同上

2023-03-04 12:54 UTC, ddadaal commented on libs/auth/src/deleteToken.ts
> +  await fetch(authUrl + "/token", {
增加return，把响应也返回去。

2023-03-04 12:54 UTC, ddadaal commented on apps/mis-web/src/pages/api/auth/logout.ts
>        .then(() => ({ 204: null }));
return await ，而且这里不处理错误，就可以写成线性流程：

```ts
await deleteToken(..);
return { 204: null }
```

2023-03-05 06:00 UTC, ddadaal requested changes

2023-03-05 06:00 UTC, ddadaal commented on apps/auth/src/routes/logout.ts
> +    Body: Static<typeof BodySchema>
https://pkuhpc.github.io/SCOW/docs/deploy/config/auth/impl-custom-auth#delete-token 认证系统的API定义的是token放在query里，这里为什么要改成到Body里去？如果要修改到body里去，那么这是对API的一个破坏性修改，需要同时修改文档，已有的系统也需要重新实现。这里不需要改到body里，保留原来的实现。

fetch中传递querystring的方式可以使用query的参数初始化`URLSearchParams`对象，把这个对象的toString()方法的返回值添加到URL+"?"后面去

2023-03-05 10:21 UTC, ddadaal approved these changes

2023-03-06 07:06 UTC, lyl-available approved these changes

2023-03-06 07:26 UTC, merged