feat(portal): 添加跨集群文件传输功能
PKUHPC/SCOW pull request #510
Opened 2023-03-13 03:48 UTC by tulvgengenr

for test in muti-cluster

2023-03-14 08:01 UTC, ddadaal commented on apps/mis-server/src/plugins/clusters.ts
> +      const node = typeof loginNode === "string" ? loginNode : (loginNode.address + ":" + loginNode.port.toString());
获取登录节点的逻辑全部统一到getClusterLoginNode函数中去。

2023-03-14 09:26 UTC, tulvgengenr commented on apps/portal-server/src/utils/ssh.ts
> +}
好，当时是考虑到保留getClusterLoginNode的返回值，因为引用它的地方太多了，现在我把引用它的地方都改了

2023-03-14 09:30 UTC, ddadaal commented on apps/portal-server/src/utils/ssh.ts
> +}
如果这一个问题就会改很多地方，那把这个改loginNode的schema单独作为一个PR提出来。这本来也是一个独立的功能。

2023-03-14 09:30 UTC, tulvgengenr commented on apps/mis-server/src/plugins/clusters.ts
> +      const node = typeof loginNode === "string" ? loginNode : (loginNode.address + ":" + loginNode.port.toString());
但是getClusterLoginNode实际上是在portal-server端的utils中定义的，如果都要用的话，最好放在全局的lib/utils中。不过我现在在auth、mis-server中都加了utils/ssh.ts，里面照搬了getClusterLoginNode方法，感觉暂时可以先这样把。

2023-03-22 07:29 UTC, ddadaal commented on apps/portal-web/src/pages/api/file/queryTransferFiles.ts
HTTP响应流只适合文件下载这种直接获取纯二进制的方式，因为每次前端获取的chunk不一定对应你后台发的某一次chunk。HTTP里所有数据都是**二进制**流。举个例子，比如后端发了两次请求，一次内容是"123"，一次内容是"4"，但是前端有可能第一次获取的chunk是"12"，第二次是"34"。你要这么做，那你需要自己实现把流按某种方式分割，然后分块解析，太过复杂了。

而且HTTP本质上是请求响应，很多网关会设置一次HTTP请求的最长时间，一旦HTTP时间过长整个连接就断开了。

所以这种需求还是老老实实开websocket来交换数据。

2023-03-31 02:26 UTC, tulvgengenr commented on apps/auth/src/utils/ssh.ts
> +export function getClusterLoginNode(cluster: string): ClusterLoginNode {
关于loginNode配置文件增加port和privateKeyPath这个需求，经过昨天讨论，决定删去。
昨天讨论的跨集群传输的架构，需要每个集群增加一个只有公网地址的transferNode只用于文件传输。具体内容可以看我提出的[issue232](https://github.com/PKUHPC/scow-internal-dev/issues/232)、[issue233](https://github.com/PKUHPC/scow-internal-dev/issues/233)、[issue234](https://github.com/PKUHPC/scow-internal-dev/issues/234).
本pr的代码，实现了基于**各集群loginNode之间可以免密登录**的文件传输。
目前CI没有通过的原因在于，对于grpc后端queryTransferFiles这个api的test的没有通过，其中startTransferFiles的test我还没有实现，而queryTransferFiles的test需要在ssh-server这个容器中安装scow-sync软件才可以通过。
所以想问一下达哥：①startTransferFiles的test是否需要实现。②queryTransferFiles的test是舍弃，还是在ssh-server中安装scow-sync然后保留。

2023-03-31 02:28 UTC, tulvgengenr commented on apps/portal-web/src/pages/api/file/queryTransferFiles.ts
目前采用了轮询的方式实现，有时间我会去再研究下websocket或者Transfer-Encoding: chunked的方式。

2023-03-31 03:14 UTC, ddadaal commented on apps/auth/src/utils/ssh.ts
> +export function getClusterLoginNode(cluster: string): ClusterLoginNode {
测试是需要写的，但是可以在功能实现完后再写。

你需要仔细考虑这两个测试的期望行为是什么。目前你的query的测试写死了希望获得的输入，但是每一次运行都是这样的输出吗？对于每一次开始传输，什么事情是一定会发生的？对每次查询，输出的具体结果（比如传输速度、大小）肯定不一样，但是有什么条件是一定要满足的吗？测试是写这些一定会发生的事情。

目前你可以先写`it.skip("...")`把已经有的测试跳过。

2023-03-31 06:07 UTC, tulvgengenr commented on apps/auth/src/utils/ssh.ts
> +export function getClusterLoginNode(cluster: string): ClusterLoginNode {
好的，因为这个pr现在已经实现了基于loginNode免密的文件传输，之后我补充一下文档先把这部分合进去，还是等[issue232](https://github.com/PKUHPC/scow-internal-dev/issues/232)、[issue233](https://github.com/PKUHPC/scow-internal-dev/issues/233)、[issue234](https://github.com/PKUHPC/scow-internal-dev/issues/234)三个issue实现完一起合。

2023-04-06 10:07 UTC, tulvgengenr commented
# 测试er请看这里
目前由于我们多集群环境上没有配备带有公网的传输节点，我在58集群上通过端口转发的方式实现了hpc01和hpc02登录节点的免密，因此将登录节点作为了传输节点。集群配置文件我已修改，测试er可直接拉取镜像进行测试。

2023-04-06 12:41 UTC, ddadaal commented on apps/portal-server/config/clusters/hpc01.yaml
> +transferCrossCluster:
crossClusterFileTransfer

2023-04-06 12:41 UTC, ddadaal commented on apps/portal-server/src/services/file.ts
> +    startTransferFiles: async ({ request, logger }) => {
startFileTransfer

2023-04-06 12:43 UTC, ddadaal commented on apps/portal-server/src/services/file.ts
> +      // 检查fromTransferNode -> toTransferNode是否已经免密
这两个节点之间要免密是scow-sync的要求吧？把检查这两个节点是否已经免密的代码放在scow-sync代码里去做。毕竟已经有了一个单独的scow-sync项目了，相关逻辑尽量放在那个项目里去。scow应该做的只是准备好scow-sync需要的参数，尽量简化相关逻辑。

2023-04-07 03:29 UTC, lyl-available commented
> # 测试er请看这里
> @lyl-available 目前由于我们多集群环境上没有配备带有公网的传输节点，我在58集群上通过端口转发的方式将登录节点作为了暴露出来的传输节点。集群配置文件我已修改，测试er可直接拉取镜像在58集群上进行测试。

ok，junda approve了再开始测试哈

2023-04-12 07:04 UTC, ddadaal commented on apps/portal-server/src/services/file.ts
> +      const toTransferNode = getClusterTransferNode(toCluster);
仍然应该改成string，如果这个功能没有打开，但是却用到了需要获取transferNode的功能，这种情况应该报错。

2023-04-12 07:04 UTC, ddadaal commented on apps/portal-web/src/pageComponents/filemanager/ClusterFileTable.tsx
ok，但是尽量把公共代码往外提。

2023-04-12 07:10 UTC, ddadaal commented on apps/portal-web/src/pages/files/fileTransfer.tsx
> +  const [clusterRight, setClusterRight] = useState<Cluster>();
状态要么有默认值，要么单独处理undefined的情况。大量使用!不好。

2023-04-12 07:11 UTC, ddadaal commented on docs/docs/deploy/config/cluster-config.md
> +crossClusterFilesTransfer:
单独加一个布尔值enabled配置，和系统中其他可选功能的配置对齐。

2023-04-12 07:11 UTC, ddadaal commented on docs/docs/deploy/config/portal/transfer-cross-clusters.md
> +每个集群需要有一个专门用来做文件传输的节点TransferNode，该TransferNode要求只拥有**公网地址**。该TransferNode可以是登录节点LoginNode，但同样要求具有公网地址。
公网地址详细解释一下。是要求互联网公网地址？还是要求平台之间能互相连接的地址？

2023-04-19 06:44 UTC, ddadaal requested changes

2023-04-19 06:44 UTC, ddadaal commented on apps/portal-server/src/services/file.ts
> +
可以写成

```ts
const publicKey = await sshConnect(..., async (ssh) => { 
    // ...
    return fileData.toString();
});
```

2023-04-19 06:44 UTC, ddadaal commented on apps/portal-server/src/services/file.ts
> +        privateKeyPath = `${keyDir}/id_rsa`;
这里也是一样的，sshConnect可以返回结果，尽可能减少这种函数给外部变量赋值的代码。

2023-04-19 06:44 UTC, ddadaal commented on apps/portal-web/src/pageComponents/filemanager/SingleCrossClusterTransferSelector.tsx
> +  }, []);
获取数据用`useAsync`，获取作业的逻辑用`promiseFn`参数

2023-04-19 06:44 UTC, ddadaal commented on apps/portal-web/src/pageComponents/filemanager/TransferInfoTable.tsx
> +      return newTransferData;
可以用Promise.all同时发起多个http请求。

2023-04-19 06:44 UTC, ddadaal commented on apps/portal-web/src/pageComponents/filemanager/TransferInfoTable.tsx
> +      return newTransferData;
可以加一个HTTP API来获取开启了跨集群文件传输的集群列表，减少HTTP请求的数量

2023-04-19 06:44 UTC, ddadaal commented on protos/portal/file.proto
> +  string left_time = 6;
这些数据都是直接从scow-sync读的吗？parse一下。例如，transfer_size最好改成一个数字类型（比如uint64），以b或者kb为单位。speed也是。progress是百分比吗？如果是的话，也用uint32这种来表示，值为0-100，如果有小数的话用浮点数。left_time也改成一个比如remaining_time_seconds，其值为秒单位的时间。

2023-04-19 09:54 UTC, tulvgengenr commented on protos/portal/file.proto
> +  string left_time = 6;
想了一下，这些数据都是直接从scow-sync读的。
speed会根据传输的速度，自适应选择量纲，格式为“21.94MB/s”。left_time的格式是“01:02:03”。这两个不用parse直接展示在前端就可以吧。
 progress的格式为"30%"，可以parse一下。
transfer_size的量纲是bytes，也可以parse为KB为量纲。

2023-04-19 10:28 UTC, ddadaal commented on protos/portal/file.proto
> +  string left_time = 6;
要parse。因为如果你之后如果不用rsync实现了呢？这些输出还会是这样的吗？

2023-04-20 12:03 UTC, ddadaal requested changes

2023-04-20 12:03 UTC, ddadaal commented on apps/portal-web/src/layouts/routes.tsx
>      }] : []),
如果只有一个集群或者没有集群开启了fileTransfer，则不显示这两个选项卡。要不要开启这个功能可以在next.config.js里判断，通过publicConfig给一个`CROSS_CLUSTER_FILE_TRANSFER_ENABLED`的boolean变量到应用中。

2023-04-20 12:03 UTC, ddadaal commented on apps/portal-server/src/services/file.ts
> +        toTransferNode.split(":")[0] : toTransferNode;
getClusterTransferNode和try...那个函数应该直接返回解析好的`host`和`port`，而不是让调用者再解析一次。

2023-04-20 12:11 UTC, tulvgengenr commented on protos/portal/file.proto
> +  uint64 transfer_size_k_bs = 3;
如果写成kbs的话，编译出来是Kbs，这样会误解成是bit。

2023-04-20 12:14 UTC, tulvgengenr commented on docs/docs/deploy/config/portal/transfer-cross-clusters.md
> +每个集群需要有一个专门用来做文件传输的节点TransferNode，该TransferNode要求只拥有**互联网公网地址**。该TransferNode可以是登录节点LoginNode，但同样要求具有公网地址。
这个我再找付老师确认一下，上次说的是只有互联网公网地址，不要有内网地址，但是也可以用LoginNode做TransferNode，这样其实既有互联网公网地址又有内网地址了

2023-04-20 12:16 UTC, tulvgengenr commented on apps/portal-server/src/services/file.ts
> +        toTransferNode.split(":")[0] : toTransferNode;
这个感觉之后提出来一个新的issue比较好，如果要将getClusterTransferNode和getClusterLoginNode的返回值改为[host, port]。要改很多个地方，并且在这个pr没有合进去之前，每次新加入的用到getClusterLoginNode的代码都要改

2023-04-20 12:19 UTC, ddadaal commented on apps/portal-server/src/services/file.ts
> +        toTransferNode.split(":")[0] : toTransferNode;
getClusterTransferNode是这个PR新加的，可以先改了。

2023-04-20 12:20 UTC, ddadaal commented on protos/portal/file.proto
> +  uint64 transfer_size_k_bs = 3;
但现在这样也会……一般都是用的byte，bit用得比较少。加个注释吧。

2023-04-20 12:20 UTC, ddadaal commented on protos/portal/file.proto
> +  string recv_cluster = 1;
或者to_cluster，和其他的to_path这些名字一样。

2023-04-20 12:29 UTC, tulvgengenr commented on protos/portal/file.proto
> +  uint64 transfer_size_k_bs = 3;
我的意思是，proto文件编译之后。在前后端import的时候，实际上`transfer_size_k_bs`会编译成`transferSizeKBs`，但是`transfer_size_kbs`会编译成`transferSizeKbs`。而量纲是缩写的时候，代码风格应该是全部大写。

2023-04-20 12:38 UTC, ddadaal commented on protos/portal/file.proto
> +  uint64 transfer_size_k_bs = 3;
这个编译出来的形式是按照编程语言决定的，js因为代码风格是camelCase命名变量名，所以编译出来是KBs，但是如果换成python，那编译出来就是transfer_size_k_bs了。这个具体怎么编译到代码无法确定。另外，变量名这么要求是为了可读，读proto文件的时候，上下文只能局限在proto文件，而不应该考虑具体编译出来是怎么样的。所以在proto中的命名，就应该只考虑读proto文件时是否易懂。proto用的下划线命名，就要求所有命名都是小写，这是命名法要求的，无法改变，所以就只能用kbps，然后加注释来进一步说明具体的单位。

2023-04-20 12:38 UTC, ddadaal commented on docs/docs/deploy/config/portal/transfer-cross-clusters.md
> +每个集群需要有一个专门用来做文件传输的节点TransferNode，该TransferNode要求只拥有**互联网公网地址**。该TransferNode可以是登录节点LoginNode，但同样要求具有公网地址。
一般来说有互联网公网地址的要求是高于有内网地址的要求吧。如果只有各个集群都可以访问的地址，但是这个地址不能公网访问，可以吗？

2023-04-20 13:17 UTC, tulvgengenr commented on docs/docs/deploy/config/portal/transfer-cross-clusters.md
> +每个集群需要有一个专门用来做文件传输的节点TransferNode，该TransferNode要求只拥有**互联网公网地址**。该TransferNode可以是登录节点LoginNode，但同样要求具有公网地址。
是可以的，需要在TransferNode上进行防火墙配置，实现IP过滤。

为了在公网传输，TransferNode肯定要给公网地址。现在要讨论的是①只给公网地址 or ②既给公网地址，又给子网地址。因为想要将TransferNode**只用来**做文件传输，所以不希望TransferNode被LoginNode和ComputeNode访问到。

如果①，那么可以就需要在网关，也就是SCOW节点上进行防火墙配置，限制从LoginNode到TransferNode的访问，因为LoginNode节点访问公网需要过网关。
如果②，那么不光要在网关进行配置，还要在TransferNode上对LoginNode进行IP过滤。

2023-04-20 13:24 UTC, ddadaal commented on docs/docs/deploy/config/portal/transfer-cross-clusters.md
> +每个集群需要有一个专门用来做文件传输的节点TransferNode，该TransferNode要求只拥有**互联网公网地址**。该TransferNode可以是登录节点LoginNode，但同样要求具有公网地址。
我们要定义这个“公网”是什么意思。互联网的公网地址和”两个集群能够互相访问的网络中的地址“这两个，应该是后者更容易获取吧？如果只是要在两个集群之间传文件，那么这两个节点只要能在一个”两个集群能够互相访问的网络“中就可以了吧？建议在文档里详细定义各个涉及到的网络。

2023-04-26 01:59 UTC, tulvgengenr commented on apps/portal-web/src/layouts/routes.tsx
>      }] : []),
请问是将CROSS_CLUSTER_FILE_TRANSFER_ENABLED作为环境变量吗

2023-04-26 02:02 UTC, ddadaal commented on apps/portal-web/src/layouts/routes.tsx
>      }] : []),
看文档 项目设计->配置

2023-04-26 02:09 UTC, tulvgengenr commented on apps/portal-web/src/layouts/routes.tsx
>      }] : []),
应该是修改config.js吧，不是next.config.js

2023-04-26 02:10 UTC, ddadaal commented on apps/portal-web/src/layouts/routes.tsx
>      }] : []),
对的

2023-04-26 02:37 UTC, tulvgengenr commented on apps/portal-web/src/layouts/routes.tsx
>      }] : []),
虽然选项卡不展示，但是可以直接输入URL跳转到对应界面，这个要不要限制一下

2023-04-26 02:38 UTC, ddadaal commented on apps/portal-web/src/layouts/routes.tsx
>      }] : []),
可以

2023-04-26 06:27 UTC, ddadaal submitted a review, later dismissed

2023-07-03 06:51 UTC, lyl-available commented
发现漏了个古早的PR，这个可以测了吗？ @ddadaal @tulvgengenr

2023-07-03 14:23 UTC, ddadaal commented
不用，这个功能目前还没有考虑要进主分支

2023-09-22 08:29 UTC, closed without merging