feat(mis): 修复租户、账户已结束作业列表，可搜索出非本租户、账户下的作业的问题
PKUHPC/SCOW pull request #533
Opened 2023-03-28 14:32 UTC by tongchong

1、搜索不到无权限账户的数据
![image](https://user-images.githubusercontent.com/25954437/228271177-accf78b7-de0a-4093-a2db-cf659cda23d8.png)

2、搜索不到无权限用户的数据
![image](https://user-images.githubusercontent.com/25954437/228271742-d6571a67-8f10-445b-9dec-5a70852eba09.png)

3、精确搜索搜不到无权限的数据
![image](https://user-images.githubusercontent.com/25954437/228272004-d9654529-548d-4432-9ddb-8db03af14262.png)

4、账户管理下搜不到其它账户的数据
![image](https://user-images.githubusercontent.com/25954437/228272282-82ec1da7-fb71-44fe-a5c0-6630abbed1ae.png)

2023-03-28 15:02 UTC, ddadaal commented on apps/mis-server/src/services/job.ts
> +      }
有权限问题的话，filterJobs直接就往外扔了错误，调用者就应该收到错误。为什么这里要掩盖这个错误，反而返回一个没有数据的结果？

2023-03-28 15:08 UTC, ddadaal requested changes

2023-03-28 15:08 UTC, ddadaal commented on apps/mis-server/src/services/job.ts
> +  const permissionAccounts = (await em.find(Account, { tenant: { name: tenantName } }, { fields: ["accountName"]}))
`allowedAccounts`

2023-03-28 23:55 UTC, ddadaal commented on apps/mis-server/src/services/job.ts
> +  const permissionAccounts = (await em.find(Account, { tenant: { name: tenantName } }, { fields: ["accountName"]}))
从数据库中取出所有数据作为中间结果的写法一般都有问题。在这里`permissionAccounts`的用处是限制作业只能在指定的租户里， 实际上无需把所有账户名都取出来。

在检查账户是否可以被查询时，可以写成：
```ts
// 如果指定了accountName，但是在数据库中找不到账户为accountName、租户名为tenantName的账户
if (accountName && !(await em.findOne(Account, { tenant: { name: tenantName }, accountName })) { 
    throw ...;
}
```

在后面生成查询条件时，把租户名作为查询条件即可

```ts
{ tenant: tenantName }
```

2023-03-29 01:25 UTC, tongchong commented on apps/mis-server/src/services/job.ts
> +      }
不一定是权限问题，可能是没有这条数据，或者没有这个用户、没有这个租户

2023-03-29 01:30 UTC, ddadaal commented on apps/mis-server/src/services/job.ts
> +  const permissionAccounts = (await em.find(Account, { tenant: { name: tenantName } }, { fields: ["accountName"]}))
如果这里只需要限制在指定的租户里，是否就完全没有必要加这一段判断？直接无脑在返回的返回条件里加上租户名的查询条件是否就可以做到？

2023-03-29 01:52 UTC, tongchong commented on apps/mis-server/src/services/job.ts
> +  const permissionAccounts = (await em.find(Account, { tenant: { name: tenantName } }, { fields: ["accountName"]}))
似乎是可以的，我加上去看一下各场景效果

2023-03-31 03:47 UTC, lyl-available approved these changes

2023-04-03 03:57 UTC, merged