feat(auth): 增加了otp功能
PKUHPC/SCOW pull request #540
Opened 2023-04-02 09:04 UTC by coovy

登录界面添加了输入otp码的input框和绑定otp的按钮
<img width="492" alt="image" src="https://user-images.githubusercontent.com/96867690/229342685-f0aeaba5-7f6a-4782-9ce5-b538c171a37a.png">

如果otp为启动并为本地状态，点击绑定otp之后转到绑定UI(远程状态会跳转到otp.remote.redirectUrl:):
<img width="428" alt="image" src="https://user-images.githubusercontent.com/96867690/229342778-64f3521a-f39b-47f2-8440-f5b661a9dcdd.png">

用户名密码验证通过会转到获取邮箱绑定链接的UI（需在10分钟内绑定）:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/96867690/229342942-99eae8a2-39c2-4233-b50d-a8c50035207d.png">

邮箱收到链接：
<img width="377" alt="image" src="https://user-images.githubusercontent.com/96867690/229343023-d57635ee-fd95-4687-96bf-908325cd6a0a.png">

邮箱确定之后二维码UI：

用户信息过期：
<img width="433" alt="image" src="https://user-images.githubusercontent.com/96867690/229343201-21e01a8e-d099-4b8f-adc1-a6cd8dd22841.png">

2023-04-04 07:01 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +    password: string,
不要把用户密码也给保存到redis中

2023-04-04 07:01 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  f.redis.set(OTPSessionToken, JSON.stringify(userInfo), "EX", 600);
await

2023-04-04 07:01 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  const redisUserInfoObject = JSON.parse(redisUserJSON);
这是什么类型？

2023-04-04 07:02 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +export async function getAbsoluteUTCTimestamp() {
为什么这个函数是async？

2023-04-04 07:02 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  if (redisUserInfoObject["senEmailTimestamp"] !== undefined) {
senEmailTimestamp -> sendEmailTimestamp

2023-04-04 07:03 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  console.log("发邮件了");
要打log的话，用logger对象，不要直接打到console.log上，并且log内容用英文写

2023-04-04 07:04 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  transporter.sendMail(mailOptions, (e) => {
这是个async方法吧？await呢？尽量用async/await，不要用回调函数

2023-04-04 07:08 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  }
这个函数和下面的`extractEmailAddressFromEntry`基本是一样的，只有extractAttr的第二个参数不一样，是重复代码。实际上可以直接用extractUserInfoFromEntry。让extractUserInfoFromEntry多返回email和secret就可以了

2023-04-04 07:17 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  console.log("jjjj", authConfig.otp.status);
删除没有意义的log

2023-04-04 07:19 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +export async function searchOneAttributeValueFromLdap(
这个函数是在查找某个dn对应的entry把？根据条件搜索entry已经有函数了（searchOne），直接用dn相等为条件先搜索到整个entry，然后从entry取对应的attribute就可以，不需要重新再定义一个和searchOne基本上一致的函数。

2023-04-04 07:20 UTC, ddadaal commented on apps/auth/src/auth/otp/index.ts
> +    validateUserNameAndPassword(f, ldapConfig);
这个函数是在绑定route，不是在验证账户密码，把函数名改一下。下面的也是

2023-04-04 07:23 UTC, ddadaal commented on docs/docs/deploy/config/auth/config.md
> +  5. 如果您的密钥要自己存储在某个地方（即otp.status为remote），那么您需要提供一个验证otp码的接口，返回验证的结果。返回结果用string类型false或者true字符串即可。scow会使用fetch向config/auth.yml中的otp.remote.url发起请求。
返回结果还是用json比较好。要求接口返回`{"result": true| false }`

2023-04-04 07:24 UTC, ddadaal commented on docs/docs/deploy/config/auth/config.md
> +  | body  | OTPCode, userId                   |
body的这两个参数是什么意思？类型是什么？camelCase命名：`OTPCode` -> `otpCode`

2023-04-04 13:36 UTC, coovy commented on apps/auth/src/auth/otp/aesUtils.ts
> +let key: Buffer = Buffer.alloc(32);
这个加密和解密之间auth重启了我确实没考虑到。不过我准备把otpSessionToken改成cookie传输似乎更加合理一些，但是由于这个otpSessionToken本身存在时间我默认就10分钟，redis服务器应该也有设置用户不能拿着key去查询？所以这里有必要对otpSessionToken加密吗？有必要的话我把iv和key存到环境变量？

2023-04-04 14:44 UTC, ddadaal commented on apps/auth/src/auth/otp/aesUtils.ts
> +let key: Buffer = Buffer.alloc(32);
redis实际上可以当作一个数据库用，iv和key可以存放在redis中，认证系统启动的时候先检查一下，如果已经有了iv和key就直接用，没有就生成。这样，即使auth重启，iv和key仍然可以用，只是redis重启之后，已有的绑定OTP的请求就不能用了，但这是可以接受的。

> redis服务器应该也有设置用户不能拿着key去查询？

用户不能直接访问redis。但是你可以在往redis里存otpSessionToken的时候给token加一个前缀（比如`otpSessionToken`）来指定这个是一个token。

> 不过我准备把otpSessionToken改成cookie传输似乎更加合理一些

什么意思？otpSessionToken目前是要放在email的链接里一起发过去吧？用户发起OTP绑定的浏览器和点击email链接的浏览器可能不是一次浏览器，在点击email时很可能无法获取之前的cookie，所以这个token不能放在cookie里。

2023-04-04 15:02 UTC, coovy commented on apps/auth/src/auth/otp/aesUtils.ts
> +let key: Buffer = Buffer.alloc(32);
> 什么意思？otpSessionToken目前是要放在email的链接里一起发过去吧？用户发起OTP绑定的浏览器和点击email链接的浏览器可能不是一次浏览器，在点击email时很可能无法获取之前的cookie，所以这个token不能放在cookie里。

对对，学长说的对。我的意思是说是在给用户发送email链接之前的otpSessionToken在各个路由之间的传递，这个我改成cookie比较好，过期时间也可以设置成和绑定时限一样。给用户邮件发的otpSessionToken我还是放到query参数里

2023-04-04 15:06 UTC, coovy commented on apps/auth/src/auth/otp/aesUtils.ts
> +let key: Buffer = Buffer.alloc(32);
> redis实际上可以当作一个数据库用，iv和key可以存放在redis中，认证系统启动的时候先检查一下，如果已经有了iv和key就直接用，没有就生成。这样，即使auth重启，iv和key仍然可以用，只是redis重启之后，已有的绑定OTP的请求就不能用了，但这是可以接受的。
> 但是把aes的iv和key存放在redis中的话，存放这两个数据的redis的key该怎么保存呢？
> > redis服务器应该也有设置用户不能拿着key去查询？
> 
> 用户不能直接访问redis。但是你可以在往redis里存otpSessionToken的时候给token加一个前缀（比如`otpSessionToken`）来指定这个是一个token。
> 
> > 不过我准备把otpSessionToken改成cookie传输似乎更加合理一些
> 
> 什么意思？otpSessionToken目前是要放在email的链接里一起发过去吧？用户发起OTP绑定的浏览器和点击email链接的浏览器可能不是一次浏览器，在点击email时很可能无法获取之前的cookie，所以这个token不能放在cookie里。

对对，学长说的对。我的意思是说是在给用户发送email链接之前的otpSessionToken在各个路由之间的传递，这个我改成cookie比较好，过期时间也可以设置成和绑定时限一样。给用户邮件发的otpSessionToken我还是放到query参数里

2023-04-04 15:06 UTC, coovy commented on apps/auth/src/auth/otp/aesUtils.ts
> +let key: Buffer = Buffer.alloc(32);
> 什么意思？otpSessionToken目前是要放在email的链接里一起发过去吧？用户发起OTP绑定的浏览器和点击email链接的浏览器可能不是一次浏览器，在点击email时很可能无法获取之前的cookie，所以这个token不能放在cookie里。
对对，学长说的对。我的意思是说是在给用户发送email链接之前的otpSessionToken在各个路由之间的传递，这个我改成cookie比较好，过期时间也可以设置成和绑定时限一样。给用户邮件发的otpSessionToken我还是放到query参数里

2023-04-04 15:07 UTC, coovy commented on apps/auth/src/auth/otp/aesUtils.ts
> +let key: Buffer = Buffer.alloc(32);
> 什么意思？otpSessionToken目前是要放在email的链接里一起发过去吧？用户发起OTP绑定的浏览器和点击email链接的浏览器可能不是一次浏览器，在点击email时很可能无法获取之前的cookie，所以这个token不能放在cookie里。

对对，学长说的对。我的意思是说是在给用户发送email链接之前的otpSessionToken在各个路由之间的传递，这个我改成cookie比较好，过期时间也可以设置成和绑定时限一样。给用户邮件发的otpSessionToken我还是放到query参数里

2023-04-04 15:32 UTC, ddadaal commented on apps/auth/src/auth/otp/aesUtils.ts
> +let key: Buffer = Buffer.alloc(32);
把iv和key分别base64编码，然后选一个base64编码后不会出现的字符作为分隔符把两个字符串拼接起来，然后放到redis里

2023-04-04 15:42 UTC, coovy commented on apps/auth/src/auth/otp/aesUtils.ts
> +let key: Buffer = Buffer.alloc(32);
> 把iv和key分别base64编码，然后选一个base64编码后不会出现的字符作为分隔符把两个字符串拼接起来，然后放到redis里

好，学长这个思路太好了。但是在redis中存储这个value的key该怎么确定并保存呢，这个有点想不通

2023-04-04 15:51 UTC, ddadaal commented on apps/auth/src/auth/otp/aesUtils.ts
> +let key: Buffer = Buffer.alloc(32);
key定成常量就可以了。

另外，otpSessionToken也可以不用cookie传，用query传挺方便的，也没啥坏处

2023-04-04 15:54 UTC, coovy commented on apps/auth/src/auth/otp/aesUtils.ts
> +let key: Buffer = Buffer.alloc(32);
> key定成常量就可以了。
> 
> 另外，otpSessionToken也可以不用cookie传，用query传挺方便的，也没啥坏处

好

2023-04-06 13:11 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  const redisUserInfoObject = JSON.parse(redisUserJSON) as Object;
这个JSON的具体格式是怎样的？使用同一个数据结构的代码应该写在一起。

```ts
// 保存在redis里的信息的类型 
interface OtpSessionInfo {}

// 将要绑定OTP的用户信息保存在redis里，返回这个信息对应的token
async function saveOptSession(info: OtpSessionInfo): Promise<string> {}

// 根据token获取保存在redis里的用户类型
async function getOptSession(token: string): Promise<OtpSessionInfo | undefined> {}
```

之后所有需要操作session的代码都从这两个函数和这个类型里获取，这样就不会相关代码到处都有了

2023-04-06 13:11 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  }) + "\">{{labelText}}</a>";
这里定义模板可以直接使用liquid。可以新建一个liquid模板，然后这里直接渲染liquid模板，就和渲染HTML一样。

2023-04-06 13:11 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  let success = true;
为什么要有这个变量？

```ts
const emailSent = await transporter.sendMail().then(() => true).catch((e) => {
logger.error(e);
return false;
});
```
```

2023-04-06 13:11 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +    }
这里是在检查配置文件格式，放在读取配置文件格式并检查的函数里去。

2023-04-06 13:11 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +      return (await JSON.parse(await res.text()).result) as boolean;
`await res.json()`直接获取body并转换为json。

2023-04-06 13:11 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +        logger.error(`error in verify otp code in remote status, error ${e}`);
logger.error(e, "error when verifying otp code in remote");

2023-04-06 13:11 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +    logger.info("fail to find otp secret");
错误的日志用logger.error

2023-04-06 13:11 UTC, ddadaal commented on apps/auth/src/auth/otp/routeHandles.ts
> +    action: Type.String(),
action有几种可能取值？用enum写死

2023-04-06 13:11 UTC, ddadaal commented on apps/auth/src/auth/otp/routeHandles.ts
> +            { sendEmailUI: true, redisUserInfoExpiration: true, backToLoginUrl: backToLoginUrl });
redisUserInfoExpiration 这个参数是指token没有找到吗？那就是直接`tokenNotFound`

2023-04-06 13:11 UTC, ddadaal commented on apps/auth/src/auth/otp/routeHandles.ts
> +          <input type="hidden" name="backToLoginUrl" value="${backToLoginUrl}"></div> `;
html都用liquid定义

2023-04-06 13:11 UTC, ddadaal commented on apps/auth/src/config/auth.ts
> +export enum otpAlgorithm {
enum首字母大写

2023-04-06 15:35 UTC, coovy commented on apps/auth/src/config/auth.ts
> +export enum otpAlgorithm {
这个定义枚举的enum确实是小写的，学长之前的代码也是小写的。

2023-04-07 01:14 UTC, ddadaal commented on apps/auth/src/config/auth.ts
> +export enum otpAlgorithm {
我指的是enum名：otpAlgorithm -> OtpAlgorithm

2023-04-07 01:21 UTC, ddadaal commented on apps/auth/src/auth/otp/aesUtils.ts
> +export async function GetIvAndKeyWhenEncrypt(f: FastifyInstance) {
只是这个区别可以调用者区分，或者将加密的逻辑写在解密的逻辑之上：

```ts
async function encrypt() {
   const ivKey = await decrypt();
   if (!ivKey) { // 生成密钥并保存 }
}
```

2023-04-07 18:40 UTC, coovy commented on apps/auth/src/auth/otp/routeHandles.ts
> +          <input type="hidden" name="backToLoginUrl" value="${backToLoginUrl}"></div> `;
我新建了个文件，用来存放邮邮箱链接liquid模板和二维码liquid模板

2023-04-11 14:18 UTC, ddadaal commented on apps/auth/src/auth/otp/aesUtils.ts
> +  }
这里修改各个语句的顺序，可以去掉let定义：

```ts
const result = await f.redis.get(REDIS_KEY);
if (!result) { return undefined; }
const ivAndKey = decodeIvKeyFromBase64(result);
```

2023-04-11 14:22 UTC, ddadaal commented on apps/auth/src/auth/otp/aesUtils.ts
这个文件叫aesUtils.ts，那么这个函数就应该只包含aes加解密的代码，不应该涉及redis的读写。

2023-04-11 14:22 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +}
从redis读和写到redis同一种数据的代码应该放在同一个文件中。

2023-04-11 14:26 UTC, ddadaal commented on apps/auth/src/config/auth.ts
> +    status: Type.Enum(OtpStatusOptions, { description: "otp功能状态", default: "disabled" }),
这里我觉得还是把这个配置拆成两个配置比较好。一个是enabled，表示OTP功能是不是启用；另一个配置是`type`，有`ldap`和`remote`两个值，如果enabled了那么type就必填。因为一般来说可选功能都需要有一个单独用来标志整个功能是否启用的选项，启用了，再有下面的更具体地配置（type）。

2023-04-14 11:43 UTC, ddadaal commented on apps/auth/config/auth.yml
> +    scowHost: http://localhost:5000
SCOW有base path的话，这里写什么？

2023-04-14 11:43 UTC, ddadaal commented on apps/auth/config/auth.yml
> +        contentText: "Please click on the following link to bind your OTP"
邮件内容可以是HTML吗？

2023-04-14 11:43 UTC, ddadaal commented on apps/auth/src/auth/otp/aesUtils.ts
> +// 解密时，如果redis服务器重启, 返回undefined,通知上层函数
这个注释已经过期了吧？删掉

2023-04-14 11:43 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +    await f.redis.set(AES_ENCRYPTION_IV_KEY_REDIS_KEY, encryptedIvKey);
encode iv和key的过程也提取为一个函数，这样的话，所有和存取iv和key的逻辑都为单独的函数，把iv和key encode只是存取iv和key的一个过程而已。

2023-04-14 11:43 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  const timeLimitMinutes = authConfig.otp!.ldap!.timeLimitMinutes;
authConfig.otp.ldap这个对象的值应该从参数传入（就像ldapConfig一样），这样可以要求调用者手动去验证这个对象是不是不是undefined

2023-04-14 11:43 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  const otpLdap = authConfig.otp!.ldap!;
authConfig.otp.ldap这个对象的值应该从参数传入（就像ldapConfig一样），这样可以要求调用者手动去验证这个对象是不是不是undefined，调用者也不需要每次都要!

2023-04-14 11:43 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  if (otpSession["sendEmaililTimestamp"] !== undefined) {
这个是在访问已知类型的对象的已知属性，用.操作符访问对象的属性

2023-04-14 11:43 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  const href = hrefWithoutBackToLoginUrlParam + `&backToLoginUrl=${encodeURIComponent(backToLoginUrl)}`;
这个后面添加的backToLoginUrl也是一个search params，为啥要单独写出来，在上面拼接URL的时候一切拼了就可以

2023-04-14 11:43 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  const href = hrefWithoutBackToLoginUrlParam + `&backToLoginUrl=${encodeURIComponent(backToLoginUrl)}`;
这个拼接URL的做法是在哪里找的资料吗？给我一个链接我看看。

2023-04-14 11:43 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  const otpLdap = authConfig.otp.ldap!;
otp.type是不是ldap应该去检查otp.type，而不是看otp.ldap有没有配置。因为用户有可能otp.type不是ldap但是配置了otp.ldap。

2023-04-14 11:43 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  }
必须增加这个验证吗？可以直接报错吗？

2023-04-14 11:43 UTC, ddadaal commented on apps/auth/src/auth/otp/views/email.liquid
> +<p>{{ contentText }}</p>
contentText可以是HTML吗？

2023-04-14 11:43 UTC, ddadaal commented on apps/auth/src/auth/ssh/postHandler.ts
> +    otpCode: Type.Optional(Type.String()),
实际这个otpCode是不是必须有可以在运行时检查配置文件得出。如果运行时检查配置文件发现配置了OTP，那么就给这个Schema增加一个otpCode: Type.String()，否则就不要有：

```ts
...authConfig.otp.enabled ? { otpCode: Type.String() } : undefined,
```

但是得看一下这样写法下面用这个req的时候ts编译器能不能推出有一个otpCode属性。

2023-04-17 06:42 UTC, ddadaal commented on apps/auth/src/auth/ldap/postHandler.ts
> +    ...(authConfig.otp?.type === OtpStatusOptions.ldap || authConfig.otp?.type === OtpStatusOptions.remote)
如果之后有其他类型的OTP验证类型，这里又要加？可以发现，只要OTP功能打开了（也就是不是disabled），那么这里就需要一个otpCode，所以这里的判断条件应该为otp.type !== disabled

2023-04-17 06:42 UTC, ddadaal commented on apps/auth/src/auth/loginHtml.ts
> +  const enableTotp = authConfig.otp?.type !== OtpStatusOptions.disabled && authConfig.otp?.type !== undefined;
按目前的schema，otp.type这个配置项是有默认值的，所以只要otp不是undefined，otp.type就不会是默认值，所以检查条件应该是：authConfig.otp && authConfig.otp.type !== disabled

2023-04-17 06:42 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +    const timeDiff = Math.floor(currentTimestamp / 1000 - otpSession["sendEmaililTimestamp"]);
otpSession["sendEmaililTimestamp"]：otpSession.sendEmailTimestamp

sendEmaililTimestamp 注意拼写

2023-04-17 06:42 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +    const validatePreOtpCode = speakeasy.totp.verify({
变量名注意，表达的是是不是上一个otp码的检查结果，可以取名为`isPreOtpCode`。`validatePreOtpCode`看起来像是个函数的名字，表达的是一个行为而不是一个结果。

2023-04-17 06:42 UTC, ddadaal commented on apps/auth/src/auth/otp/index.ts
> +  if (authConfig.otp?.type === OtpStatusOptions.disabled || !authConfig.otp?.type) {
很多地方都用到了检查otp是否打开，可以考虑增加一个函数`otpEnabled`来做这个检查

2023-04-17 06:42 UTC, ddadaal commented on apps/auth/src/auth/otp/routeHandles.ts
> +      const otp = authConfig.otp!;
这个和其他用到otp配置的地方也是一样的，otp这个参数对象应该从整个外层函数的参数传进来，这样可以让外层函数检查otp是不是undefined，同时自己用的时候也不需要加!。检查一下其他用到!的地方是不是都可以用这个方法去掉!。

2023-04-17 06:42 UTC, ddadaal commented on apps/auth/config/auth.yml
> +    scowHost: http://localhost:5000
这里明确解释一下提到如果scow有base path怎么办

2023-04-17 13:13 UTC, ddadaal reviewed
差不多了

2023-04-17 13:13 UTC, ddadaal commented on docs/docs/deploy/config/auth/config.md
> +#### 一、如果您配置otp将密钥存在ldap中(即otp.type为ldap):
3级标题，3个#，而且标题的内容一般不用完整的句子，而是直接简短的语句，比如：将OTP密钥保存在LDAP中

2023-04-17 13:13 UTC, ddadaal commented on apps/auth/config/auth.yml
> +    #限制绑定otp要在多久时间内完成，需要整数，默认10
yaml的注释的#和主要内容之间加个空格

2023-04-17 13:13 UTC, ddadaal commented on apps/auth/src/auth/otp/helper.ts
> +  const mailAttributeName = ldapConfig.attrs.mail || "mail";
如果没有配置attrs.mail应该报错，不要乱改人家的LDAP。在读取配置的时候就检查需要mail的attr但是没有配attrs.mail就报错

2023-04-17 15:13 UTC, ddadaal requested changes

2023-04-18 01:21 UTC, ddadaal approved these changes

2023-04-19 06:06 UTC, ddadaal approved these changes

2023-04-19 10:27 UTC, ddadaal submitted a review, later dismissed

2023-04-19 11:13 UTC, ddadaal approved these changes

2023-04-25 02:48 UTC, ddadaal submitted a review, later dismissed

2023-04-25 07:24 UTC, coovy commented
> 这个是不是也要修改auth.yml文件才会显示opt的输入框？

对，这个也是可配置是否启动的功能。在这个代码的SCOW/docs/docs/deploy/config/auth/config.md里的otp部分有详细的配置说明

2023-05-08 07:20 UTC, lyl-available commented
我有一个问题哈，remote的验证方式需要运行一段ts代码还需要手动把验证码放到用户家目录底下，那到时候用户用的时候也是要安装ts运行环境，再一个用户一个用户的放验证码吗？

2023-05-08 07:34 UTC, coovy commented
> 我有一个问题哈，remote的验证方式需要运行一段ts代码还需要手动把验证码放到用户家目录底下，那到时候用户用的时候也是要安装ts运行环境，再一个用户一个用户的放验证码吗？

不是这样的。scow的remote时，实现的是携带userId和用户输入的otp验证码向某个接口发起请求，再由那个接口告诉scow验证是否通过。我给的ts代码仅仅是个直接可以使用的接口示例，仅仅对于是一种情况，是把用户的otp密钥放在用户家目录下（别的部署scow用这种情况的话，那他们手动复制每个用户的密钥到用户家目录，还是他们实现自动化这个过程，这个咱们不管。就是他们怎么让每个用户绑定otp咱们不管，由他们自己保管otp密钥），然后那段示例代码是取这个密钥，再进行验证，返回验证结果的true或者false。

2023-05-08 07:34 UTC, coovy commented
> 我有一个问题哈，remote的验证方式需要运行一段ts代码还需要手动把验证码放到用户家目录底下，那到时候用户用的时候也是要安装ts运行环境，再一个用户一个用户的放验证码吗？

复制的不是验证码，是otp密钥。

2023-05-08 07:36 UTC, coovy commented
> > 我有一个问题哈，remote的验证方式需要运行一段ts代码还需要手动把验证码放到用户家目录底下，那到时候用户用的时候也是要安装ts运行环境，再一个用户一个用户的放验证码吗？
> 
> 不是这样的。scow的remote时，实现的是携带userId和用户输入的otp验证码向某个接口发起请求，再由那个接口告诉scow验证是否通过。我给的ts代码仅仅是个直接可以使用的接口示例，仅仅对于是一种情况，是把用户的otp密钥放在用户家目录下（别的部署scow用这种情况的话，那他们手动复制每个用户的密钥到用户家目录，还是他们实现自动化这个过程，这个咱们不管。就是他们怎么让每个用户绑定otp咱们不管，由他们自己保管otp密钥），然后那段示例代码是取这个密钥，再进行验证，返回验证结果的true或者false。

至于如果他们想省事直接用我写的代码也行，但是他们怎么运行是他们的事。

2023-05-08 08:18 UTC, lyl-available commented
> > > 我有一个问题哈，remote的验证方式需要运行一段ts代码还需要手动把验证码放到用户家目录底下，那到时候用户用的时候也是要安装ts运行环境，再一个用户一个用户的放验证码吗？
> > 
> > 
> > 不是这样的。scow的remote时，实现的是携带userId和用户输入的otp验证码向某个接口发起请求，再由那个接口告诉scow验证是否通过。我给的ts代码仅仅是个直接可以使用的接口示例，仅仅对于是一种情况，是把用户的otp密钥放在用户家目录下（别的部署scow用这种情况的话，那他们手动复制每个用户的密钥到用户家目录，还是他们实现自动化这个过程，这个咱们不管。就是他们怎么让每个用户绑定otp咱们不管，由他们自己保管otp密钥），然后那段示例代码是取这个密钥，再进行验证，返回验证结果的true或者false。
> 
> 至于如果他们想省事直接用我写的代码也行，但是他们怎么运行是他们的事。

所以接口的代码是用户自己写，scow这边只是调接口，再通过接口的返回确认验证码是否通过？那密钥和验证码之间的转换也是接口做吗？

2023-05-08 08:21 UTC, coovy commented
> 密钥和验证

对，是这样的。只不过现在他们那边的情况就是我的示例代码写的情况。我们是给他们直接提供了这段代码让他们可以直接使用。

2023-05-09 10:00 UTC, lyl-available commented
有一个小问题哈https://github.com/orgs/PKUHPC/projects/1/views/30?pane=issue&itemId=27668001
里面还有2个我感觉是不是可以优化的地方

2023-05-11 02:52 UTC, coovy commented
@lyl-available 
这个commit修复了绑定链接发送失败前端显示问题，增加了再次发送绑定链接动态倒计时，补充了文档中二维码上方文字配置说明。
二维码文字配置选项为otp.ldap.qrcodeDescription,支持字符串和html标签。例如：
```
otp:
  ldap:
    qrcodeDescription: "<p>此二维码仅出现一次</p><p>请不要泄露此二维码</p><p>请使用authenticator扫描此二维码绑定</p>"
```
显示效果为：
<img width="361" alt="image" src="https://github.com/PKUHPC/SCOW/assets/96867690/8bc89a48-b8b8-452d-803d-9f3a2c65de8a">

2023-05-11 07:02 UTC, lyl-available commented
![image](https://github.com/PKUHPC/SCOW/assets/125553919/dd659043-41e8-42f9-bcc9-6175f1c3ecca)

发送失败变成这样了

2023-05-11 08:04 UTC, coovy commented
> ![image](https://user-images.githubusercontent.com/125553919/237600012-dd659043-41e8-42f9-bcc9-6175f1c3ecca.png)
> 
> 发送失败变成这样了

谢谢，这里我之前少考虑了，现在这个commit这个问题已修复
<img width="413" alt="image" src="https://github.com/PKUHPC/SCOW/assets/96867690/fef59e7e-68bb-4ece-b471-3739220818d4">

2023-05-11 08:50 UTC, lyl-available approved these changes

2023-05-11 11:24 UTC, ddadaal commented
终于

2023-05-11 11:24 UTC, merged