fix(portal): 修复使用模板时所有下拉列表项无法应用的问题
PKUHPC/SCOW pull request #557
Opened 2023-04-12 08:46 UTC by tongchong

![VbkPTlj8tK](https://user-images.githubusercontent.com/25954437/231403868-111836cc-6968-43a9-9857-af583e29803f.jpg)

2023-04-12 10:20 UTC, ddadaal reviewed
整个模板和SubmitJobForm应该重构一下，但是目前还是先能用就好

2023-04-12 10:20 UTC, ddadaal commented on apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
> +        const setTemple = initial.partition &&
setTemple -> setValueFromTemplate，命名不要偷懒

2023-04-12 12:52 UTC, tongchong commented
> 整个模板和SubmitJobForm应该重构一下，但是目前还是先能用就好

SubmitJobForm重构的话，需要了解更多普通用户的实际需求和痛点，包括但不限于拓展slurm等调度器的功能，动作不小。可以考虑在部分页面增加我们的GitHub地址，获得更多来自用户的issue

2023-04-12 15:12 UTC, ddadaal commented
我想的不是功能上的，功能上的大改动还是让产品去操心吧。我想的主要是代码设计上的。现在进入提交作业页面之后还有一堆逻辑要逻辑，各个表单之间的联动也很复杂，加载模板在这种代码上打补丁感觉也很难。这个之后再说吧

2023-04-12 15:18 UTC, ddadaal requested changes

2023-04-12 15:18 UTC, ddadaal commented on apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
>      },
每次切换集群后都会刷新新集群的信息，每次获取集群后就会执行这个回调。模板应该只是在第一次加载的时候应用，加载了之后用户如果切换集群，就和模板无关了。设置模板的值不应该在这里。

2023-04-12 15:18 UTC, ddadaal commented on apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
>    }, [currentPartitionInfo]);
这个也是，每次切换了分区信息都会执行这个effect，只要用户切换了分区信息都会运行这里，但是模板应该也只是第一次进入的时候会加载，后面用户自己再手动改就和模板没有关系了。

2023-04-12 15:18 UTC, ddadaal commented on apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
>      },
Form有isFieldTouch方法来确认一个字段是不是被用户修改过。如果用户修改过，就不要根据模板改值了。

2023-04-13 01:43 UTC, tongchong commented on apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
>      },
每次切换集群后都会刷新新集群的信息，而后就会执行这个回调，但获取模版的值又在此之前，所以之前会有这个bug，因为获取到集群后更新的覆盖了initial。如果用户决定使用模版，他大概率是想使用模版中的选项的，如果模板中的partitions及qos值在该集群中，那么与其切换为我们默认的第一个选项，不如设置为用户使用模版中的值。

2023-04-13 01:57 UTC, ddadaal commented on apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
>      },
这样考虑似乎也可以

2023-04-13 01:58 UTC, ddadaal approved these changes

2023-04-13 03:22 UTC, tongchong commented on apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
>      },
嗯嗯，那先这样，后续需求变动再改

2023-04-13 03:24 UTC, tongchong commented on apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
>    }, [currentPartitionInfo]);
同上，加载模板时若切换partition ，取模板值设为默认值

2023-04-17 03:35 UTC, lyl-available commented
![image](https://user-images.githubusercontent.com/125553919/232371914-f3d22c5b-7e37-4895-b715-8ad182ef77b8.png)

使用模板时，目录名是用的原模板的，作业名是用的随机生成的，建议统一一下

2023-04-17 06:28 UTC, ddadaal commented on apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
>          form.setFieldValue("workingDirectory", calculateWorkingDirectory(data.clusterInfo.submitJobDirTemplate));
如果已经有了用来更新workingDirectory的effect了，这里就不要再手动设置一次workingDirectory了

2023-04-17 07:03 UTC, tongchong commented on apps/portal-web/src/pageComponents/job/SubmitJobForm.tsx
>          form.setFieldValue("workingDirectory", calculateWorkingDirectory(data.clusterInfo.submitJobDirTemplate));
好的，effect那边我再监听clusterInfoQuery.data，因为要等它出来才能设置workingDirectory

2023-04-18 07:58 UTC, lyl-available approved these changes

2023-04-18 11:04 UTC, merged