feat(portal-web): 交互式应用显示pending或者terminated状态作业的未启动原因
PKUHPC/SCOW pull request #598
Opened 2023-04-26 05:53 UTC by WZD09

![image](https://user-images.githubusercontent.com/102740885/234525370-79683fcb-a507-4930-8abc-1c4890334019.png)

2023-04-26 06:55 UTC, ddadaal requested changes

2023-04-26 06:55 UTC, ddadaal commented on apps/portal-web/src/pageComponents/app/AppSessionsTable.tsx
> +          "NODE_FAIL", "PREEMPTED", "SPECIAL_EXIT", "TIMEOUT"]
我觉得是不是只要reason不是空就可以显示，用户有更多的信息更好

2023-04-26 10:40 UTC, ddadaal approved these changes

2023-04-28 08:25 UTC, lyl-available approved these changes

2023-04-28 08:49 UTC, merged