feat(portal-web): portal web 文件管理页面展示文件大小按照单位展示最多三位有效数字，实际文件大小鼠标悬浮展示
PKUHPC/SCOW pull request #599
Opened 2023-04-26 05:56 UTC by ZihanChen821

文件管理页面下的文件大小按照单位进行展示，规则如下
文件大小显示三位数字，如0.10、11.0、110。单位根据大小调整如下：
0-999KB：KB;
1000KB-999MB： MB;
1000MB-999GB：GB；
最多展示三位有效数字， 当文件在该单位下大于等于1000时，比如1000kb，需要转为下一位单位展示并保持三位有效数字（四舍五入规则），如图所示
![image](https://user-images.githubusercontent.com/130351655/234481782-1aad1e96-a2a4-419f-9ae3-9dda74f2274d.png)
同时鼠标移至数字上会显示实际文件大小（单位为KB）
![image](https://user-images.githubusercontent.com/130351655/234481954-9456936e-4c31-4fae-a07b-cc6720a2d5c1.png)

测试时建议每个单位的文件都跑一遍 （KB,MB,GB,TB）, 当前设计下大于1024TB不展示大小， 测试每个单位时建议数字一个为1000以内，一个为1000到1024。验证展示是否符合预期。

2023-04-26 06:50 UTC, ddadaal requested changes

2023-04-26 06:50 UTC, ddadaal commented on apps/portal-web/src/pageComponents/filemanager/FileManager.tsx
> +const formateFileSize = (size: number): string => {
formate -> format

2023-04-26 06:50 UTC, ddadaal commented on apps/portal-web/src/pageComponents/filemanager/FileManager.tsx
> +  const MAX_SIZE = 1125899906842624;
这是怎么算出来的？直接写算式：1024*1024*1024*1024*1024。这种常量在编译时会被计算出来。

2023-04-26 06:50 UTC, ddadaal commented on apps/portal-web/src/pageComponents/filemanager/FileManager.tsx
> +  return `${decimalSize.toFixed(0)} ${unitMap[carryCount]}`;
@scow/lib-decimal的代码（不包括类型）不要在前端用，因为这样会使得`bignumber.js`这个npm包被打包到前端，加大前端的打包大小。直接用js的数字类型计算。

2023-04-26 07:58 UTC, ddadaal submitted a review, later dismissed

2023-05-04 02:45 UTC, lyl-available commented
有个issue哈 https://github.com/orgs/PKUHPC/projects/1/views/30?pane=issue&itemId=27300443

2023-05-04 02:56 UTC, ZihanChen821 commented
> 有个issue哈 https://github.com/orgs/PKUHPC/projects/1/views/30?pane=issue&itemId=27300443

这个是取整方向问题导致的，统一都向下取整展示吧

2023-05-04 03:00 UTC, lyl-available commented
> > 有个issue哈 https://github.com/orgs/PKUHPC/projects/1/views/30?pane=issue&itemId=27300443
> 
> 这个是取整方向问题导致的，统一都向下取整展示吧

这边前端展示都只展示整数吗？

2023-05-04 04:39 UTC, ZihanChen821 commented
> > > 有个issue哈 https://github.com/orgs/PKUHPC/projects/1/views/30?pane=issue&itemId=27300443
> > 
> > 
> > 这个是取整方向问题导致的，统一都向下取整展示吧
> 
> 这边前端展示都只展示整数吗？

刚看了下产品的方案， 应该1.11-9.99，10.1 - 99.9都需要展示小数，我这里需要改一下

改完后，KB还是四舍五入取整，其他单位无论是展示整数，还是一位小数或者两位小数，最后一位也还是四舍五入取吧， 比如1.119 -> 1.12，11.89  -> 11.9,  99.96 -> 100。保持一定是三位有效数字的同时，悬浮展示的KB数也是一致的。

这里有个特殊处理
![image](https://user-images.githubusercontent.com/130351655/236113443-3740b174-8eca-4410-bf58-4da8b0908539.png)
当最后的数字决定是取几位小数时，会遇到toFixed()函数的四舍五入进位问题导致实际需要的有效数字展示不准确，比如99.98, 由于小于100所以预期应该是保留一位小数来维持三位有效数字，可此时的0.08会进位，导致展示为100.0。 为了符合预期，需要考虑toFixed()的进位问题所以做了9.996和99.95的特殊处理

2023-05-04 05:12 UTC, ddadaal approved these changes

2023-05-05 03:28 UTC, lyl-available approved these changes

2023-05-05 05:54 UTC, merged