feat(mis,portal): mis.yaml和portal.yaml中支持增加导航链接
PKUHPC/SCOW pull request #652
Opened 2023-05-17 10:15 UTC by piccaSun

2023-05-18 01:20 UTC, ddadaal requested changes
单独写一篇文档介绍自定义导航链接功能，放在 https://pkuhpc.github.io/SCOW/docs/deploy/config/customization/customNavLinks 。

需要覆盖以下内容：

- 如何配置
- 默认能用的图标ID如何查看
- 如何自定义图标链接

2023-05-18 01:20 UTC, ddadaal commented on apps/cli/assets/config/mis.yaml
> +    # errorMessage: ""
这个是什么？

2023-05-18 01:20 UTC, ddadaal commented on apps/cli/assets/config/portal.yaml
> +# iconScirptUrls: []
- Scirpt -> Script
- iconfontScriptUrls

2023-05-18 01:20 UTC, ddadaal commented on apps/mis-web/src/layouts/routes.tsx
> +export const AddedNavLinksRoutes = (navLinkItems: NavItemProps[]): NavItemProps[] => {
这是个函数吧？`customNavLinkRoutes`

2023-05-18 01:20 UTC, ddadaal commented on apps/mis-web/src/layouts/routes.tsx
> +export const CreateUserCurrentRoleMap = (user: User | undefined): Map<string, number> => {
函数名camelCase

2023-05-18 01:20 UTC, ddadaal commented on apps/mis-web/src/layouts/routes.tsx
> +  const roleMap = new Map<string, number>();
这个roleMap是为了表示这个用户是哪些用户？没必要用roleMap，用一个写死的object就好了：

```ts
const roles = {
    user: true,
    accountAdmin: true,
}
```

然后在下面的代表依次判断每个值是不是，分别赋值true和false。这样简单多了，而且更直观，还能享受到类型检查。

2023-05-18 09:48 UTC, piccaSun commented on apps/cli/assets/config/mis.yaml
> +    # errorMessage: ""
解决master的conflict的时候重复了，已删除。

2023-05-18 09:52 UTC, piccaSun commented
> 单独写一篇文档介绍自定义导航链接功能，放在 https://pkuhpc.github.io/SCOW/docs/deploy/config/customization/customNavLinks 。
> 
> 需要覆盖以下内容：
> 
> * 配置好后的效果
> * 如何配置
> * 各个角色的解释
> * 默认能用的图标ID如何查看
> * 如何自定义图标链接

已追加。
另外 https://github.com/PKUHPC/scow-internal-dev/issues/257 这个用户角色多写了一个tenantOwner,已删除。
如果是后期有计划追加的角色，我再改回来。请确认~

2023-05-18 10:44 UTC, ddadaal requested changes

2023-05-18 10:44 UTC, ddadaal commented on apps/mis-web/src/layouts/routes.tsx
> +const getCurrentUserRoles = (user: User | undefined): typeof roles => {
不要可修改的全局变量。getCurrentUserRoles应每次返回一个新的对象

2023-05-18 10:44 UTC, ddadaal commented on docs/docs/deploy/config/customization/customNavLinks.md
> +当您点击导航链接时，我们会在当前链接后面加入查询参数`?token={用来跟踪登录用户的状态的token}`，以此来保证您后续链接的安全验证。
以此来保证您后续链接的安全验证：您可以通过token查询当前操作用户。

2023-05-18 10:44 UTC, ddadaal commented on docs/docs/deploy/config/customization/customNavLinks.md
> +| `accountOwner`     | 在账户中的角色：账户管理员      |
user：在所有账户中均为普通用户
accountAdmin: 在某个账户中为账户管理员
accountOwner: 在某个账户中为账户拥有者

2023-05-18 10:44 UTC, ddadaal commented on libs/web/src/layouts/IconFont.tsx
> +  const defaultScriptUrl = "//at.alicdn.com/t/c/font_4071713_6zxyzqrl1yb.js"; // Ant Design 3.0 全新线性图标体系
这种不变常量可放到外部，并用全大写命名

2023-05-18 10:44 UTC, ddadaal commented on docs/docs/deploy/config/customization/customNavLinks.md
> +#### 1 默认图标仓库
不需要有1、2

2023-05-19 02:18 UTC, ddadaal requested changes

2023-05-19 02:18 UTC, ddadaal commented on docs/docs/deploy/config/customization/customNavLinks.md
> +title: 自定义导航链接功能
标题要简洁。去掉“功能"二字

2023-05-19 02:18 UTC, ddadaal commented on docs/docs/deploy/config/customization/customNavLinks.md
> +系统支持自定义门户系统和管理系统的导航链接功能。点击发生跳转。
您可以增加门户和管理系统的导航链接，点击这些链接会跳转到您指定的URL。

2023-05-19 02:18 UTC, ddadaal commented on docs/docs/deploy/config/customization/customNavLinks.md
> +同时支持自定义导航链接图标，并支持用户通过自己在[iconfont.cn](https://www.iconfont.cn/)上的项目中的图标仓库来灵活管理导航链接图标。
支持自定义图标只是功能的一部分，不需要在文档一开始介绍。删掉这一句话。

2023-05-19 02:18 UTC, ddadaal commented on docs/docs/deploy/config/customization/customNavLinks.md
> +当您点击导航链接时，我们会在当前链接后面加入查询参数`?token={用来跟踪登录用户的状态的token}`，以此来保证您后续链接的安全验证：您可以通过token查询当前操作用户。
是指删掉`以此来保证您后续链接的安全验证`

2023-05-19 02:18 UTC, ddadaal commented on docs/docs/deploy/config/customization/customNavLinks.md
> +```
yaml title="config/mis.yaml"

2023-05-19 02:18 UTC, ddadaal commented on docs/docs/deploy/config/customization/customNavLinks.md
> +```
yaml title="config/portal.yaml"

2023-05-19 02:18 UTC, ddadaal commented on docs/docs/deploy/config/customization/customNavLinks.md
> +| `allowedRoles`            |  用户角色字符串列表    | `mis`             |否           |管理系统指定可以看到该导航链接的角色列表，用户角色类型包括  `user`, `accountAdmin`, `accountOwner`, `tenantFinance`, `tenantAdmin`, `platformAdmin`, `
这不是必填的，解释里解释如果不填会发生什么行为

2023-05-19 02:18 UTC, ddadaal commented on docs/docs/deploy/config/customization/customNavLinks.md
> +| `user`             | 在所有账户中均为普通用户，或者未加入账户 |
把`user`拆分为`accountUser`和`user`。`accountUser`加入了账户但是都是普通用户，`user`是没有加入任何账户的用户。这两种用户还是拆分一下比较好。

2023-05-19 02:42 UTC, piccaSun commented on docs/docs/deploy/config/customization/customNavLinks.md
> +| `user`             | 在所有账户中均为普通用户，或者未加入账户 |
> 把`user`拆分为`accountUser`和`user`。`accountUser`加入了账户但是都是普通用户，`user`是没有加入任何账户的用户。这两种用户还是拆分一下比较好。

是说用户在allowedRoles里面可以填写[user, accountUser]两种字符串，显示导航栏角色判定的时候追加user为所有对象的判定吗？就是allowedRoles: [user]的时候同allowedRoles:[]的情况一样对吗？

2023-05-19 02:55 UTC, ddadaal commented on docs/docs/deploy/config/customization/customNavLinks.md
> +| `user`             | 在所有账户中均为普通用户，或者未加入账户 |
不是，user只包括没有加入任何账户的用户。accountUser只包括加入了账户，但是在所有账户中都是普通用户的用户。

另外现在allowedRoles: []的时候是所有用户均可用？看起来是比较奇怪的，按逻辑来说空数组应该是谁都不能用。如果是谁都能用，应该是不设置allowedRoles。

2023-05-19 03:01 UTC, piccaSun commented on docs/docs/deploy/config/customization/customNavLinks.md
> +| `user`             | 在所有账户中均为普通用户，或者未加入账户 |
对，现在空数组的时候是没做限定的，那我再修改一下

2023-05-19 04:58 UTC, piccaSun commented
@ddadaal 
上面comment已修改完成，请确认。
根据修改后的allowedRoles:[]的逻辑，我还想再跟您确认一下图标脚本地址 iconfontScriptUrls: []的逻辑
`| `iconfontScriptUrls`       |  字符串列表           | `portal`，`mis`   | 否         | [iconfont.cn](https://www.iconfont.cn/)下的项目图标库的脚本地址，支持复数添加。如果没有填入或者值为空，则按默认图标库下的图标进行查找。如果填入且不为空，则替换默认图标库，在您自己管理的[iconfont.cn](https://www.iconfont.cn/)的项目图标库下查找图标。    |`
自己预想的防止用户误配置为空，所以为空时也按默认图标库里查询，是不是也应该统一成如果为空，则无法显示图标？

2023-05-19 06:22 UTC, ddadaal commented
> @ddadaal 上面comment已修改完成，请确认。 根据修改后的allowedRoles:[]的逻辑，我还想再跟您确认一下图标脚本地址 iconfontScriptUrls: []的逻辑
> 
> > | `iconfontScriptUrls`       |  字符串列表           | `portal`，`mis`   | 否         | [iconfont.cn](https://www.iconfont.cn/)下的项目图标库的脚本地址，支持复数添加。如果没有填入或者值为空，则按默认图标库下的图标进行查找。如果填入且不为空，则替换默认图标库，在您自己管理的[iconfont.cn](https://www.iconfont.cn/)的项目图标库下查找图标。    |
> 
> 自己预想的防止用户误配置为空，所以为空时也按默认图标库里查询，是不是也应该统一成如果为空，则无法显示图标？

iconfontScriptUrls这样设计没有问题。因为iconfontScriptUrls是用来**覆盖已有配置**，为空或者为null的含义都是没有东西可以覆盖，那就是应该保留原来的设置。但是allowedRoles是设置，不是覆盖，没有默认值，所以就应该以用户输入的为准。

2023-05-19 06:22 UTC, ddadaal submitted a review, later dismissed

2023-05-22 09:06 UTC, piccaSun commented
@ddadaal  @lyl-available 
已删除与icon有关的配置，默认显示图标为LinkOutlined，请确认
![portal-custom-navlinks](https://github.com/PKUHPC/SCOW/assets/43978285/a0ab92a1-1ef1-4317-9a82-aac66646050f)

2023-05-23 03:03 UTC, ddadaal commented
使用 #662 实现自定义图标。

用户可以把图标文件放到`public`目录下，然后通过链接配置中的`iconPath`配置图标的链接。链接的图标通过`join(publicConfig.BASE_PATH, "/api/public", iconPath)`读取。web应确保用户无论输入什么大小的图片，都能把图片缩放到能正确显示的图标的大小。

2023-05-25 10:20 UTC, piccaSun commented
@ddadaal  不好意思有一个问题还请继续帮忙确认一下
考虑到用户上传自定义图标文件可能为`.svg, .png, .jpg`等，目前是利用了原生`img`的tag来做展示，因为在img下比较难做到按图片文本进行颜色填充，现在主题色的切换是通过反色`filter: dark ? "invert(100%)" : "none",`来做的
这样黑白图片没什么影响，彩色和其他颜色的反色稍微有一些违和
![image](https://github.com/PKUHPC/SCOW/assets/43978285/55ce0eea-7b88-47c2-92fa-0afb64fcc167)
![image](https://github.com/PKUHPC/SCOW/assets/43978285/fb424323-c144-4999-b2e4-5801bee11d18)
请确认是否需要更改？或者限制用户图标文件为.svg？

2023-05-25 13:58 UTC, ddadaal commented on apps/mis-web/src/layouts/routes.tsx
> +            src={publicConfig.PUBLIC_PATH ?
PUBLIC_PATH应该不会是undefined的，如果这里是空，那应该是PUBLIC_PATH的定义有错，自己修改一下

2023-05-25 13:59 UTC, ddadaal commented on docs/docs/deploy/config/customization/customNavLinks.md
文档中介绍如何配置自定义图标，iconPath是什么意思

2023-05-26 02:01 UTC, ddadaal approved these changes

2023-06-06 09:29 UTC, lyl-available commented
@ddadaal 目前如果一个用户只有二级导航权限，没有一级权限，这样整个导航栏都是不可见的，需不需要改成只要有二级权限，一级也会显示？不然如果要显示二级导航就必须在一级配一个一样的权限

2023-06-06 09:51 UTC, ddadaal commented
不用改，本来导航就要先能看到一级，才能看到二级。举例，如果一个用户要想能添加用户（二级功能），那他首先得能进行用户管理（一级功能）才行。

2023-06-07 03:52 UTC, lyl-available commented
accountUser的权限有问题哈，麻烦 @piccaSun 看一下

2023-06-07 07:32 UTC, lyl-available commented
demo_user是一个租户管理员且不属于任何账户，按配置它只能看见‘一级导航a’，但现在它还能看见底下的‘二级导航b’
![image](https://github.com/PKUHPC/SCOW/assets/125553919/6264a570-8303-42fa-bbed-1526106406dd)

![image](https://github.com/PKUHPC/SCOW/assets/125553919/d618ba98-66c0-437a-9255-24a8dae271d0)

2023-06-07 11:36 UTC, piccaSun commented
@lyl-available 
[ ].every判断永远返回true导致了没有账户时accountUser判断为true
已修改，请确认😭

2023-06-08 06:31 UTC, lyl-available approved these changes

2023-06-08 07:02 UTC, merged