fix(mis-server): 修改从白名单移除账户时封锁条件为余额小于等于0元
PKUHPC/SCOW pull request #659
Opened 2023-05-19 03:19 UTC by piccaSun

在原有逻辑 移除白名单时当账户余额小于0后追加等于0的情况

白名单中余额为0元的账户
<img width="754" alt="image" src="https://github.com/PKUHPC/SCOW/assets/43978285/ac756e3c-b8e3-4e67-8e3a-245f50b2c512">
<img width="743" alt="image" src="https://github.com/PKUHPC/SCOW/assets/43978285/67e2c4e6-c6a2-4b7a-9c31-46916364649f">
移除白名单后状态变为封锁
<img width="737" alt="image" src="https://github.com/PKUHPC/SCOW/assets/43978285/ecb89eec-1364-4462-96c5-8827a9c87881">

2023-05-19 03:43 UTC, ddadaal requested changes
不只是这里，还需要修改扣费时的逻辑，现在扣费时也是小于0才封锁，应同时改成小于等于0封锁

2023-05-19 03:43 UTC, ddadaal commented on apps/mis-server/src/services/account.ts
> +      if (account.balance.isNegative() || account.balance.isZero()) {
isLessThanOrEqualTo

2023-05-19 04:17 UTC, piccaSun commented
> 不只是这里，还需要修改扣费时的逻辑，现在扣费时也是小于0才封锁，应同时改成小于等于0封锁

![image](https://github.com/PKUHPC/SCOW/assets/43978285/bb3d2caa-611f-4a36-8e12-5163d1fe9a1c)
充值和扣费的逻辑我看原本就判断了0，全局搜了一下好像只有这里写到了

2023-05-19 05:55 UTC, ddadaal approved these changes

2023-05-19 05:56 UTC, ddadaal commented
link一下issue

2023-05-22 03:13 UTC, lyl-available approved these changes

2023-05-22 04:46 UTC, merged