Refactor http api
PKUHPC/SCOW pull request #684
Opened 2023-06-07 06:09 UTC by piccaSun

[修改HTTP API定义方式，去除生成api-routes-schemas.json步骤](https://github.com/PKUHPC/scow-internal-dev/issues/315)

2023-06-07 10:39 UTC, piccaSun commented
@ddadaal 
因为改动的地方比较多，有两个细节单独说明一下麻烦注意

1.在测试接口时，有一些接口比如提交作业，创建交互式应用，管理系统的导入用户等出现了类型识别失败的问题
经检查是因为比如对下面的qos进行类型转换时转换为A的typebox形式在调用api时无法正确识别，所以对于几个出现这样的问题的接口采用了B的类型转换方式，经测试没有问题。

_SubmitJobSchema_：`qos: string | undefined;`
A: `qos: Type.Union([Type.String(), Type.Undefined()]),`
B: `qos: Type.Optional(Type.String()),`
因为a: string | undefined 和 a? :string还是有一点点微妙的差别，所以目前只对出现问题的接口单独进行了这种转换。请进一步确认。


2.有一些schema因为用类型重新定义，返回值需要断言as any的情况，在表单中也出现了大量的这种情况，为了避免过多的使用as any，对于出现这些问题的地方的response整体又用了Type.Object()进行外包。

_GetJobTemplateSchema_
  ```
responses: {
    200: {
      template: JobTemplate;
    }
    400: {
      message: string;
    }
    404: { code: "TEMPLATE_NOT_FOUND" };
   }
```
类型转换为
  ```
responses: Type.Object({
    200: Type.Object({
      template: JobTemplate,
    }),
    400: Type.Object({
      message: Type.String(),
    }),
    404: Type.Object({ code: Type.Literal("TEMPLATE_NOT_FOUND") }),
  }),
```
经测试没有问题，还是请再确认一下

2023-06-07 11:20 UTC, ddadaal requested changes
1. Type.Union([Type.String(), Type.Undefined()])和Type.Optional区别不大，且更建议用后面一种形式
2. responses不应该用Type.Object包裹

2023-06-07 11:20 UTC, ddadaal commented on apps/mis-web/src/pageComponents/admin/AllTenantsTable.tsx
> +  data: typeof GetAllTenantsSchema["responses"]["200"] | undefined;
data实际推出来是any。如果你想从Schema中获得一个其中的类型，应该使用`Static<typeof GetAllTenantSchema["responses"]["200"]`

2023-06-07 11:20 UTC, ddadaal commented on apps/mis-web/src/pages/api/admin/changeJobPrice.ts
> +    price: Type.Number({}),
原来的注释里的@minimum这些会体现在生成的schema里。改用typebox定义在，已有的注释里的限制也应该定义到typebox的schema里。例如这里应该写`Type.Number({ minimum: 0 })`

2023-06-08 10:37 UTC, ddadaal commented
改动太大了，没法一行一行看。自测一下主要功能，如果没有问题就合并。

2023-06-09 00:05 UTC, piccaSun commented
> 改动太大了，没法一行一行看。自测一下主要功能，如果没有问题就合并。

好的，本地测过了我再拉镜像测下其他集群下有没有问题

2023-06-13 11:06 UTC, piccaSun commented
@ddadaal  关于周会上提到的重构后门户系统偶然会无法打开的问题
**本地复刻条件是**切换到refactor-http-api分支时，之前在其他分支没有正常退出门户系统
其他情况不会报错可以正常登陆门户系统
**原因是**因为首次切换到refactor-http-api分支时，旧版本的token没有被废弃，但是userInfo也没有取到，所以门户系统的apps在获取时为null，与extra.apps匹配时可能发生了类型校验的错误
![image](https://github.com/PKUHPC/SCOW/assets/43978285/e42108ad-bdd5-4267-a206-ee21e4d5ffc7)
![image](https://github.com/PKUHPC/SCOW/assets/43978285/c6bee946-629e-42e5-8581-518f7e174a57)
![image](https://github.com/PKUHPC/SCOW/assets/43978285/aee238ff-6aa8-4855-9829-234751bdce01)

ListAvailableApps的返回值如下
![image](https://github.com/PKUHPC/SCOW/assets/43978285/fa4dabba-ca16-4306-a8a4-05857b863a48)
_app.tsx中的extra.apps定义如下
```
const extra: ExtraProps = {
    userInfo: undefined,
    footerText: "",
    primaryColor: "",
    apps: [],
    darkModeCookieValue: getDarkModeCookieValue(appContext.ctx.req),
  };
```

我想问一下，这个问题如果新版本发布的时候是会强制用户废弃旧版本重新登录一次吗？如果这样的话可能不需要更改

如果要修改，通过给listAvailableApps catch一个空数组的返回值经测试可以避免这个问题
`const apps = await api.listAvailableApps({ query: { token } }).then((x) => x.apps).catch(()=>[]);`
请进一步确认如何更改，是否还有其他更好的办法

2023-06-14 01:30 UTC, ddadaal commented
把listAvailableApps移动到`if (userInfo) {`块里面就可以了，只有登录了之后才能获取可用的应用。之前就是这样的。应该是我上次改的时候这里改错了。

也同时在调用`api.listAvailableApps`时加一个`.catch(()=>[])`吧，这样如果获取应用出错了也不会造成整个应用完全不可用。

2023-06-14 02:35 UTC, piccaSun commented
@ddadaal 
我这边自测结束了，没什么其他问题的话麻烦后续合并

2023-06-15 01:17 UTC, merged