feat(portal): 通过代理网关节点解析主机名连接交互式应用，以及刷新vnc密码
PKUHPC/SCOW pull request #688
Opened 2023-06-12 06:30 UTC by ZihanChen821

### 现状
1. 代理网关的Nginx代理交互式应用连接时，Nginx无法解析类似于运行交互式应用的计算节点的IP地址，所以配置代理网关节点后无法连接
2. VNC连接刷新密码时，scow节点需要在计算节点上使用当前用户刷新密码，加入代理网关节点后，scow无法直接连接计算节点，故无法实现密码刷新以及后续连接

### 改动
如果在配置代理网关的情况下：
1. 用户点击连接交互式应用时，由scow节点连接到代理网关节点，使用`ping -c 1 -W 1 compute node `命令获取计算节点IP后再发送请求至代理网关节点。
2. 用户连接VNC应用时，由scow节点连接到代理网关节点后，以root身份从代理网关节点连接至计算节点，并以当前用户运行刷新密码命令，同时在代理网关节点使用`ping -c 1 -W 1 compute node `获取计算节点IP。如果是连接VNC应用时，连接app将略过第一步，获取IP将在刷新密码时一并获取。

### 要求
1. 各个集群的登陆节点对于scow节点公开，且主机名，IP不能一样。
2. scow配置root免密登录至各集群代理网关节点，且各代理网关节点可免密root登录集群内部的所有计算节点

### 文档修改

![image](https://github.com/PKUHPC/SCOW/assets/130351655/4bfe3d58-0fcb-4f7e-a540-2244e66e89ed)

![image](https://github.com/PKUHPC/SCOW/assets/130351655/976e8716-2fab-4a7b-9aa2-e69773387bd0)

2023-06-12 06:56 UTC, ddadaal commented on apps/portal-server/src/utils/proxy.ts
> +      }, {}) as Hosts;
如果要自己parse hosts的话，把parse hosts文件的代码提取为单独的函数，单独放在一个文件中，并写完整的测试。注意hosts文件的格式。建议不要自己写parse，看看网上有没有已经有的npm包。

2023-06-12 07:01 UTC, ZihanChen821 commented on apps/portal-server/src/utils/proxy.ts
> +      }, {}) as Hosts;
好的，现在是准备在有代理网关的58集群上测试一下是否可行，之后会修改。

2023-06-16 11:13 UTC, ddadaal requested changes

2023-06-16 11:13 UTC, ddadaal commented on apps/portal-web/src/utils/config.ts
> +  ENABLE_CHANGE_PASSWORD: boolean | undefined;
之前有个PR把这个改成了boolean，为什么这里又要改成 | undefined？

2023-06-16 11:13 UTC, ddadaal commented on docs/docs/deploy/config/portal/proxy-gateway/index.md
> +- 如果您配置了代理网关节点，那么需要确保在配置各集群登录节点时，其域名和IP地址必须是不一样的。否则，代理网关节点将无法区分不同的登录节点。
登录节点的域名或者IP地址在所有集群中都是不重复的。

2023-06-16 11:13 UTC, ddadaal commented on apps/portal-server/src/utils/turbovnc.ts
> +  const cmd = `ssh ${computeNode} sudo`;
computeNode和sudo也放在params里去

2023-06-16 11:13 UTC, ddadaal commented on apps/portal-server/src/services/app.ts
> +      const ip = app.type === AppType.web ? await getIpFromProxyGateway(cluster, reply.host, logger) : undefined;
web类的应用在这里解析的IP，vnc类的应用在clusterops/slurm/app.ts解析的，太分散了。把web类应用解析host到IP也放在clusterops/slurm/app.ts里。

2023-06-19 01:28 UTC, ZihanChen821 commented on apps/portal-web/src/utils/config.ts
> +  ENABLE_CHANGE_PASSWORD: boolean | undefined;
现在master是加了 | undefined， 这个分支落后于master所以我加了这个，我把master同步一下。

2023-06-19 01:34 UTC, ddadaal requested changes

2023-06-19 01:34 UTC, ddadaal commented on apps/portal-server/src/utils/turbovnc.ts
> +      loggedExec(proxyGatewaySsh, logger, true, "sudo", [...params]),
执行的命令应该是`ssh computeNode sudo -u ...`，这个执行的是`sudo ssh computeNode -u`

2023-06-19 01:34 UTC, ddadaal commented on docs/docs/deploy/config/portal/proxy-gateway/index.md
> +- 如果您配置了代理网关节点，那么需要确保在配置各集群登录节点时，登陆节点的域名或者IP地址在所有集群中都是不重复的。否则，代理网关节点将无法区分不同的登录节点。
登陆节点->登录节点

2023-06-19 02:25 UTC, ddadaal approved these changes

2023-06-19 02:25 UTC, ddadaal commented
有在实际的集群上测试过吗？

2023-06-19 02:36 UTC, ZihanChen821 commented
> 

已部署在58集群的scow-test节点上进行自测： http://10.129.227.58:8090/apps/sessions

2023-06-19 06:54 UTC, merged