fix(cli): 暴露 gateway 的环境变量 extra
PKUHPC/SCOW pull request #698
Opened 2023-06-19 09:30 UTC by tongchong

修改了什么：
暴露 gateway 的环境变量 extra，方便用户增加 nginx 的 location 块等 server 配置。

具体操作：
修改项目部署目录下install.yml文件中的gateway的extra参数即可。

```sh

# 网关配置
gateway:
   # 更多nginx配置
   # 可接受的格式为nginx的server可接受的属性配置，例如可增加在当前系统nginx默认端口的服务
   extra: "location /extra {
            proxy_pass http://extra-web:3000;
            include includes/headers;
            include includes/websocket;
         }"

```

您配置后，可以在使用`./cli compose up -d`启动项目后，使用 ` ./cli compose exec gateway sh` 进入gateway服务，在 `/etc/nginx/http.d` 目录下的 default.conf 文件最下方查看到您添加的配置。如果gateway启动失败，说明您的配置不符合规范，请保证其正确性。

2023-06-19 15:04 UTC, ddadaal requested changes
增加文档：docs/deploy/config/gateway，介绍网关的配置项。标题为网关，目前只需要包含extra配置的简介即可。

2023-06-19 15:04 UTC, ddadaal commented on apps/cli/assets/install.yaml
> +#          }"
yaml支持多行字符串：https://stackoverflow.com/a/3790497

2023-06-20 02:29 UTC, ddadaal commented on docs/docs/deploy/config/gateway/config/index.md
> +您增加`extra`配置后，可以在使用`./cli compose up -d`启动scow后，使用 ` docker exec -it scow-deployment-gateway-1 /bin/sh` 进入gateway服务，在 `/etc/nginx/http.d` 目录下的 `default.conf` 文件最下方查看到您添加的配置。
容器名字不一定。推荐使用`./cli compose exec gateway sh`命令进容器

2023-06-20 02:36 UTC, tongchong commented on docs/docs/deploy/config/gateway/config/index.md
> +您增加`extra`配置后，可以在使用`./cli compose up -d`启动scow后，使用 ` docker exec -it scow-deployment-gateway-1 /bin/sh` 进入gateway服务，在 `/etc/nginx/http.d` 目录下的 `default.conf` 文件最下方查看到您添加的配置。
本意是想让用户可以无脑复制，如果改的话，我换成`gateway_container_name`吧

2023-06-20 02:59 UTC, ddadaal commented on docs/docs/deploy/config/gateway/config/index.md
> +您增加`extra`配置后，可以在使用`./cli compose up -d`启动scow后，使用 ` docker exec -it scow-deployment-gateway-1 /bin/sh` 进入gateway服务，在 `/etc/nginx/http.d` 目录下的 `default.conf` 文件最下方查看到您添加的配置。
容器名字本来就不一定。`./cli compose exec gateway sh`这个才可以无脑复制。

2023-06-20 03:01 UTC, tongchong commented on docs/docs/deploy/config/gateway/config/index.md
> +您增加`extra`配置后，可以在使用`./cli compose up -d`启动scow后，使用 ` docker exec -it scow-deployment-gateway-1 /bin/sh` 进入gateway服务，在 `/etc/nginx/http.d` 目录下的 `default.conf` 文件最下方查看到您添加的配置。
抱歉，是我刚刚看错了

2023-06-20 03:11 UTC, ddadaal submitted a review, later dismissed

2023-06-20 06:18 UTC, merged