feat(config): 集群配置登录节点新增节点展示名
PKUHPC/SCOW pull request #709
Opened 2023-06-29 04:50 UTC by ZihanChen821

TODO

2023-07-03 14:27 UTC, ddadaal requested changes

2023-07-03 14:27 UTC, ddadaal commented on libs/config/src/cluster.ts
> +    )),
需要兼容原来的配置文件格式，不然所有用户都需要修改配置才能更新到这个版本。

如果用户的`loginNodes`填的是字符串，就把它认为是name也是这个字符串。

2023-07-04 08:01 UTC, ddadaal requested changes

2023-07-04 08:01 UTC, ddadaal commented on libs/config/src/cluster.ts
> +  };
最好不要在读配置的时候，修改读进去的配置。之前确实也有这么做的，这会使得定义配置的文件过于复杂。这个处理不同类型的配置格式的代码最好写到业务逻辑里去。例如：

```ts
// 配置格式定义中，使用一个类型定义登录节点配置的类型
type LoginNodeConfigSchema = Type.Union([Type.String(), Type.Object({ ... }));

// 增加一个专门的读取登录节点信息的函数，所有需要获取登录节点的地方都使用此函数
function getLoginNode(loginNode: LoginNodeConfigSchema) {
    return typeof loginNode === "string" ? { name: loginNode, address: loginNode } : loginNode;
}
```

2023-07-04 08:33 UTC, ZihanChen821 commented on libs/config/src/cluster.ts
> +  };
请问这个函数是不是放在这里比较合适？ 看起来 auth，mis-server, portal-server，portal-web都会使用到
![image](https://github.com/PKUHPC/SCOW/assets/130351655/77235124-1a47-4244-aafd-5599053b931b)

2023-07-04 08:36 UTC, ddadaal commented on libs/config/src/cluster.ts
> +  };
utils应该不依赖config项目。这个函数可以直接放在定义这个配置的文件里。

2023-07-04 11:31 UTC, ddadaal approved these changes

2023-07-06 06:10 UTC, lyl-available approved these changes

2023-07-06 15:25 UTC, merged