refactor(portal): 实现各交互式应用在每个集群中单独配置
PKUHPC/SCOW pull request #715
Opened 2023-07-03 03:22 UTC by piccaSun

2023-07-03 14:35 UTC, ddadaal requested changes

2023-07-03 14:35 UTC, ddadaal commented on apps/portal-server/src/utils/app.ts
> +  }
先添加公共的`apps`，再添加集群独有的`clusterAppsConfigs`，就可以省去这里的if判断。

2023-07-03 14:35 UTC, ddadaal commented on apps/portal-server/src/utils/app.ts
> +  const clusterAppsConfigs = getAppConfigs(join(DEFAULT_CONFIG_BASE_PATH, "clusters/", cluster));
变量名可以取得清晰一点：`commonApps`和`clusterApps`

2023-07-03 14:35 UTC, ddadaal commented on .changeset/strange-countries-sleep.md
> +为了实现按集群读取 AppConfigs 以及创建应用时填写应用名等功能，修改了交互式应用部分 proto
介绍修改了哪些grpc api，列出名字即可。

2023-07-03 14:35 UTC, ddadaal commented on apps/portal-server/src/clusterops/api/app.ts
> +  appName: string | undefined;
为何是undefined？应该所有应用都有名字

2023-07-03 14:35 UTC, ddadaal commented on protos/portal/app.proto
> +  optional string app_name = 5;
这里为什么是optional的？

2023-07-03 14:35 UTC, ddadaal commented on apps/portal-server/src/utils/app.ts
> +  return { apps, clusterApps };
最终返回这个集群能用的所有应用即可，无需区分是公共的还是集群专属的

2023-07-03 14:35 UTC, ddadaal commented on apps/portal-web/src/pages/api/app/listAvailableApps.ts
> +      clusterApps: Type.Array(App),
最终返回这个集群能用的所有应用即可，无需区分是公共的还是集群专属的

2023-07-04 01:13 UTC, piccaSun commented on protos/portal/app.proto
> +  optional string app_name = 5;
这个地方本地测试读取的时候会出现已有的appId不在现存的apps中的情况，因为也可以展示到已创建应用中，所以这个地方给了个后端undefined逻辑，在前端处理成如果undefined就直接显示appId
![image](https://github.com/PKUHPC/SCOW/assets/43978285/9594d6c3-5a05-4a1c-b95e-542d05159efd)
另外也担心之前有保存过的地方，新加了之后跟前面不兼容，但是好像没有存过，
那我直接改成不可以undefined在后端给一个找不到就set appId的逻辑

2023-07-04 01:19 UTC, ddadaal commented on protos/portal/app.proto
> +  optional string app_name = 5;
OK，这个情况确实需要单独考虑。那就先保持可以undefined的情况，具体显示成什么由前端处理。在proto里给这个字段加个注释，解释什么情况下这个字段会是undefined。

2023-07-04 03:45 UTC, piccaSun commented on apps/portal-web/src/pages/api/app/listAvailableApps.ts
> +      clusterApps: Type.Array(App),
上述问题已修改，请确认~

2023-07-04 03:58 UTC, ddadaal submitted a review, later dismissed

2023-07-04 09:53 UTC, lyl-available commented
1、此处为搜索作业名，不是应用名
![image](https://github.com/PKUHPC/SCOW/assets/125553919/e333172f-39c9-4909-ad7a-d434f276ccd1)

2、在集群一搜索时，返回的还是集群二的作业列表，且同时发了2次一样请求
![image](https://github.com/PKUHPC/SCOW/assets/125553919/a5c77b5f-b56a-4dc9-8bfa-8badd9872fc8)

2023-07-05 03:46 UTC, piccaSun commented
> 1、此处为搜索作业名，不是应用名 
> 
> 2、在集群二搜索后，跳转到集群一进行搜索，返回的还是集群二的作业列表，且同时发了2次一样请求
> 
> 3、点击集群二应用列表，再跳转至集群一应用列表，此时前端并未调用集群一的接口，返回的还是集群二的应用列表 


2是因为在搜索动作结束的onFinish()和useEffect()中重复调用了reload，所以搜索动作每次发了2次请求
但是这个逻辑其实跟刷新按键有冲突，空值搜索和刷新是同样的动作了，所以修改了搜索逻辑，在点击搜索时不再请求api只在获取到的已创建应用列表中进行过滤，点击刷新按键时可以带着搜索内容一起重新过滤搜索结果
@ddadaal 麻烦确认这个地方的逻辑变更

3.是因为xxxx/[clusterid]/xxxx的同一页面组件互相切换时，路径发生了变更，但是组件内容读取缓存没有重新刷新，增加了对路径中获取的集群参数的监听
上述1，2，3问题已修改，感谢，请确认

2023-07-05 08:08 UTC, ddadaal requested changes
更新文档，介绍如何配置各个集群均可使用的应用以及只有特定集群可以使用的应用。以及编写一篇blog，介绍此版本中交互式应用相关配置的变化。

2023-07-05 09:04 UTC, lyl-available submitted a review, later dismissed

2023-07-05 12:14 UTC, piccaSun commented
文档及博客更新，请确认 @ddadaal

2023-07-08 01:56 UTC, ddadaal approved these changes

2023-07-10 01:46 UTC, lyl-available approved these changes

2023-07-10 02:49 UTC, merged