feat(portal): 门户系统桌面页面新增桌面信息，包括桌面名，桌面类型，创建时间等
PKUHPC/SCOW pull request #718
Opened 2023-07-05 09:31 UTC by ZihanChen821

TODO

2023-07-17 02:29 UTC, ddadaal requested changes

2023-07-17 02:29 UTC, ddadaal commented on docs/docs/deploy/config/portal/intro.md
> +# desktopsDir
补充完整，并且放到loginDesktop下

2023-07-17 02:41 UTC, ZihanChen821 commented on docs/docs/deploy/config/portal/intro.md
> +# desktopsDir
请问desktopDir也需要分集群配置吗？

2023-07-17 02:44 UTC, ddadaal commented on docs/docs/deploy/config/portal/intro.md
> +# desktopsDir
是的，因为其他桌面相关的可以分集群配置，这个不可以，看着也比较奇怪

2023-07-17 03:43 UTC, ddadaal commented
冲突

2023-07-17 05:07 UTC, ZihanChen821 commented
> 冲突

已解决

2023-07-17 09:14 UTC, ddadaal approved these changes

2023-07-20 07:14 UTC, lyl-available commented
地址切换未生效

2023-07-20 07:38 UTC, lyl-available commented
集群二只存在2个桌面
![image](https://github.com/PKUHPC/SCOW/assets/125553919/6a04daad-3541-4c9a-a394-ba6e46f9fdce)
切换到集群一后，再切回集群二，会显示集群一其中一个桌面，接口返回是正确的
![image](https://github.com/PKUHPC/SCOW/assets/125553919/4d570fbb-a096-46c8-b773-c807cd847f40)
![image](https://github.com/PKUHPC/SCOW/assets/125553919/2cc8b6e0-3eea-406c-89e3-c8211441a1e4)

2023-07-20 12:14 UTC, ZihanChen821 commented
> 地址切换未生效

集群里的desktopsDir设置了默认值导致，已修复

2023-07-20 12:14 UTC, ZihanChen821 commented
> 集群二只存在2个桌面 ![image](https://user-images.githubusercontent.com/125553919/254808537-6a04daad-3541-4c9a-a394-ba6e46f9fdce.png) 切换到集群一后，再切回集群二，会显示集群一其中一个桌面，接口返回是正确的 ![image](https://user-images.githubusercontent.com/125553919/254808790-4d570fbb-a096-46c8-b773-c807cd847f40.png) ![image](https://user-images.githubusercontent.com/125553919/254808899-2cc8b6e0-3eea-406c-89e3-c8211441a1e4.png) 刷新后显示正常

rowKey取的桌面ID 重复导致，已修复

2023-07-21 09:33 UTC, lyl-available approved these changes

2023-07-21 12:36 UTC, merged