feat(mis-web): 管理系统账户充值和租户充值允许负数
PKUHPC/SCOW pull request #725
Opened 2023-07-11 05:47 UTC by ZihanChen821

改动： 前端页面充值数值允许填负数，以实现错误充值的撤销功能

2023-07-11 06:40 UTC, ddadaal commented
检查http api，grpc api和数据库数据类型是否支持负数金额，增加后台测试负数充值额

2023-07-11 07:16 UTC, ZihanChen821 commented
> 检查http api，grpc api和数据库数据类型是否支持负数金额，增加后台测试负数充值额

http api：

![image](https://github.com/PKUHPC/SCOW/assets/130351655/7b13d75b-0a6c-47d7-a31c-41553ad75062)

![image](https://github.com/PKUHPC/SCOW/assets/130351655/4465cf57-8b7e-469c-9828-25f8b1194d91)

grpc: 使用Money，支持负数
![image](https://github.com/PKUHPC/SCOW/assets/130351655/19cecdd8-0cbf-4957-b155-9e75aced7407)
![image](https://github.com/PKUHPC/SCOW/assets/130351655/60a2994f-8322-46ad-957f-707a14b4b5da)
![image](https://github.com/PKUHPC/SCOW/assets/130351655/a31de8fa-f443-4d10-9c78-0ef87cf44cf1)

数据库：

![image](https://github.com/PKUHPC/SCOW/assets/130351655/8a5ead43-c108-4684-8fb0-766e9c38ae64)

![image](https://github.com/PKUHPC/SCOW/assets/130351655/a7cc08f4-85a6-4ec3-b707-0649c212ec5e)

![image](https://github.com/PKUHPC/SCOW/assets/130351655/3ee59cee-0bd5-4117-8d68-e1d72cb03e77)

![image](https://github.com/PKUHPC/SCOW/assets/130351655/a8f85a74-4317-456a-aa7b-55b47b817858)

2023-07-11 07:26 UTC, ddadaal submitted a review, later dismissed

2023-07-12 07:09 UTC, lyl-available commented
账户原本为正常状态，充值负数后余额小于0，账号未封锁

2023-07-12 08:30 UTC, lyl-available submitted a review, later dismissed

2023-07-12 09:26 UTC, ddadaal approved these changes
测试增加扣完余额会封锁的场景

2023-07-12 09:27 UTC, ddadaal requested changes
测试增加扣完余额会封锁的场景

2023-07-12 09:37 UTC, lyl-available commented
> 测试增加扣完余额会封锁的场景

这个已经测过了

2023-07-12 09:48 UTC, ddadaal commented
指加一个这个场景的测试用例

2023-07-12 15:10 UTC, ddadaal approved these changes

2023-07-14 03:14 UTC, merged