Feat(mis-server、mis-web): mis-web用户修改邮箱
PKUHPC/SCOW pull request #734
Opened 2023-07-14 03:45 UTC by OYX-1

![image](https://github.com/PKUHPC/SCOW/assets/74037789/6855a7e7-d7f1-4ff9-a6f9-e45e7f201ecb)
用户原邮箱直接展示且不可修改，用户填写符合规则的新邮箱后即可直接修改邮箱。

2023-07-14 06:19 UTC, ddadaal requested changes
这个API实际上修改了认证系统API，增加了一个新的capability以及新的URL。需要在文档 https://pkuhpc.github.io/SCOW/docs/integration/auth/impl 中介绍这个capability和API，以使得自定义认证系统的开发者能够实现这个功能。

2023-07-14 06:19 UTC, ddadaal commented on apps/auth/src/routes/changeEmail.ts
> +    "/email",
/user/email。因为邮箱是用户的属性，是用户资源的子资源，所以应该放在/user下。

2023-07-14 06:19 UTC, ddadaal commented on apps/mis-web/src/apis/api.ts
> +  changeDBEmail: apiClient.fromTypeboxRoute<typeof ChangeDBEmailSchema>("PATCH", "/api/profile/changeDBEmail"),
HTTP和gRPC API这两层修改email只应该有一个API。由mis-web在实现这个API时，在数据库以及认证系统中修改邮箱。

2023-07-14 06:19 UTC, ddadaal commented on apps/mis-web/src/pages/profile/index.tsx
> +          true ? (
true有什么意义？

2023-07-14 06:19 UTC, ddadaal commented on apps/mis-web/config.js
> +    ENABLE_CHANGE_EMAIL: capabilities.changeEmail,
不需要这个配置，不管认证系统能不能修改email，都应该给用户提供这个功能。mis-web修改了数据库的邮箱后，根据认证系统是否能修改email决定是否调用认证系统的修改email API。

2023-07-24 05:49 UTC, OYX-1 commented on apps/mis-web/config.js
> +    ENABLE_CHANGE_EMAIL: capabilities.changeEmail,
如果把数据库的邮箱改了，认证系统不允许修改邮箱，那么认证系统里邮箱和数据库里的邮箱会不一样呀。

2023-07-24 06:42 UTC, ddadaal commented on apps/mis-web/config.js
> +    ENABLE_CHANGE_EMAIL: capabilities.changeEmail,
这没办法。如果认证系统需要邮箱和SCOW的同学，就必须支持修改邮箱，不支持就办法。

2023-07-24 06:45 UTC, ddadaal requested changes

2023-07-24 06:45 UTC, ddadaal commented on apps/mis-server/src/services/user.ts
> +          user.email = oldEmail as string;
遇到错误要打log

2023-07-24 06:45 UTC, ddadaal commented on apps/mis-server/src/services/user.ts
> +      }, console)
libChangeEmail会接受一个logger对象，然后把调用认证系统API的log打在这个logger上。生产代码中log要打到logger上，不能使用console。看看其他API是怎么获取logger的

2023-07-24 06:45 UTC, ddadaal commented on apps/mis-web/config.js
> +    ENABLE_CHANGE_EMAIL: capabilities.changeEmail,
另外这个对话之前说的mis-web应该是mis-server

2023-07-24 09:26 UTC, ddadaal requested changes
加测试，包括认证系统修改邮箱（需要查看LDAP中是否正确修改）、mis-server的changeEmail API（只测试数据库是否修改）

2023-07-25 06:23 UTC, ddadaal requested changes

2023-07-25 06:23 UTC, ddadaal commented on .changeset/hip-ligers-admire.md
> +"@scow/grpc-api": minor
这是小功能，patch

2023-07-25 06:23 UTC, ddadaal commented on apps/auth/tests/ldap/ldap.test.ts
> +  expect(GetUserResp.json().user.mail).toEqual(newEmail);
现在这个测试用例就是去调了一下API，没有去检查结果，没有任何意义。要测试调用API后，LDAP中的用户的email信息是否真的被改了。

2023-07-25 06:23 UTC, ddadaal commented on apps/auth/tests/ldap/ldap.test.ts
> +  const GetUserResp = await server.inject({
局部变量camelCase命名法

2023-07-25 06:23 UTC, ddadaal commented on apps/mis-server/src/services/user.ts
> +      const LdapCapabilities = await getCapabilities(misConfig.authUrl);
局部变量camelCase命名

2023-07-25 07:15 UTC, ddadaal commented on apps/auth/tests/ldap/ldap.test.ts
> +  expect(GetUserResp.json().user.mail).toEqual(newEmail);
ok我的问题，我本来在找从LDAP里取用户信息的代码，从HTTP接口拿也可以

2023-07-25 07:16 UTC, ddadaal approved these changes

2023-07-25 09:38 UTC, lyl-available commented
这个功能在什么地方呀？

2023-07-25 10:59 UTC, OYX-1 commented
> 这个功能在什么地方呀？

![image](https://github.com/PKUHPC/SCOW/assets/74037789/07c90d8b-5131-4b1f-b641-bca778a6a4b7)

2023-07-25 11:16 UTC, lyl-available commented
![image](https://github.com/PKUHPC/SCOW/assets/125553919/9132ac15-ed1c-45df-92ba-7c526fa3038f)
邮箱格式不正确做成提示语了

2023-07-25 12:42 UTC, OYX-1 commented
> ![image](https://user-images.githubusercontent.com/125553919/255882617-9132ac15-ed1c-45df-92ba-7c526fa3038f.png) 邮箱格式不正确做成提示语了

已改

2023-07-27 06:22 UTC, lyl-available approved these changes

2023-07-27 15:08 UTC, ddadaal commented
准备好合并了的话，点击ready for review

2023-07-28 01:36 UTC, OYX-1 commented
> 准备好合并了的话，点击ready for review

okk

2023-07-28 16:13 UTC, merged