feat: 修改密码重构
PKUHPC/SCOW pull request #743
Opened 2023-07-17 07:26 UTC by tulvgengenr

test

2023-07-18 06:55 UTC, ddadaal requested changes

2023-07-18 06:55 UTC, ddadaal commented on .changeset/cold-squids-arrive.md
> +"@scow/lib-auth": major
minor

2023-07-18 06:55 UTC, ddadaal commented on apps/auth/src/auth/ldap/password.ts
> +export async function checkPasswordForAnyone(
checkPassword就行

2023-07-18 06:55 UTC, ddadaal commented on apps/auth/src/auth/ldap/password.ts
> +export async function modifyPasswordForAnyone(
modifyPassword就行

2023-07-18 11:05 UTC, ddadaal approved these changes

2023-07-24 10:58 UTC, lyl-available commented
当原密码输入错误时，既提示了原密码错误又提示了修改密码成功（实际未成功）
![image](https://github.com/PKUHPC/SCOW/assets/125553919/1d32cf11-465f-41b0-b07d-6ad3e1b08b57)

2023-07-25 02:45 UTC, lyl-available approved these changes

2023-07-25 06:17 UTC, ddadaal requested changes
ldap修改密码和检查密码这两个方法写测试用例

2023-07-25 07:17 UTC, ddadaal approved these changes

2023-07-25 13:08 UTC, merged