feat(mis-web): 用户列表优化
PKUHPC/SCOW pull request #750
Opened 2023-07-20 07:35 UTC by piccaSun

2023-07-24 06:40 UTC, ddadaal requested changes

2023-07-24 06:40 UTC, ddadaal commented on apps/mis-server/src/services/user.ts
> +        });
findAndCount出来的Count和单独`em.count`的结果是一样的。为什么要单独`em.count`一次？

2023-07-24 06:40 UTC, ddadaal commented on apps/mis-server/src/utils/users.ts
> +export const setPlatformUsers = (users) => {
users是什么类型？这个函数的函数名为“设置平台用户”，看起来像是一个修改操作，但是这个函数实际上是在把一个数据映射到另一个数据类型，修改函数名使得函数名更能体现这个函数做了什么。

2023-07-24 06:40 UTC, ddadaal commented on apps/mis-web/src/pageComponents/admin/AllUsersTable.tsx
> +  rangeSearchRole: string;
这个参数是不是只有三种可能取值？用union和字符串字面量的形式定义这个类型：`"PLATFORM_ADMIN" | "PLATFORM_FINANCE" | "ALL_USERS"`

2023-07-24 06:40 UTC, ddadaal commented on apps/mis-web/src/pageComponents/tenant/AdminUserTable.tsx
> +  const setFilteredData = (rangeSearchRole) => {
参数类型

2023-07-24 07:37 UTC, piccaSun commented on apps/mis-server/src/services/user.ts
> +        });
他们俩不一样
![image](https://github.com/PKUHPC/SCOW/assets/43978285/c9da5eee-ae63-46fe-8918-241718e49f39)
findAndCount出来的Count是带着idOrName查询条件的count
这个count是用来传给查询结果的表单，来表示页码信息的，em.count()是为了表示左上角括号里的总数

因为有总数不变又要让query带到tab下按照query显示结果的需求所以这个地方分别拿了totalCount和queryTotalCount

2023-07-24 07:41 UTC, ddadaal commented on apps/mis-server/src/services/user.ts
> +        });
ok

2023-07-24 09:22 UTC, piccaSun commented
上述意见已修改，请确认~

2023-07-24 11:04 UTC, ddadaal approved these changes

2023-07-25 03:40 UTC, lyl-available commented
平台用户列表的排序是按页来排序的

2023-07-25 06:45 UTC, piccaSun commented
> 

因为平台用户列表是后端分页，忘了将排序加到api查询中，所以排序只对第一页数据生效。修改api接口使其带有排序信息，点击排序时增加一次api查询

2023-07-26 02:53 UTC, piccaSun commented
新增平台管理-用户列表页面的后端排序，麻烦再确认一下~ @ddadaal 
![chrome-capture-2023-6-26](https://github.com/PKUHPC/SCOW/assets/43978285/015edbc1-5e68-426e-ba2b-fa6667a6f636)

2023-07-26 02:56 UTC, ddadaal requested changes

2023-07-26 02:56 UTC, ddadaal commented on protos/server/user.proto
> +  optional string sort_order = 4;
sort_order只有两种取值吧？field应该也是有具体取值范围的，都用enum限制。

2023-07-26 02:56 UTC, ddadaal commented on apps/mis-web/src/pages/api/admin/getPlatformRoleUsers.ts
> +    sortOrder: Type.Optional(Type.String()),
这里也是用正确的类型限制住可能的取值。

2023-07-26 03:21 UTC, piccaSun commented on protos/server/user.proto
> +  optional string sort_order = 4;
> sort_order只有两种取值吧？field应该也是有具体取值范围的，都用enum限制。

sort_order是只用到了两种取值，我改一下。
sort_field现在是要求与租户下的用户列表的排序一致，是userId, name和createTime。这个需要排序的列是不是以后也有可能经常发生变动啊？也要直接给具体范围吗？

2023-07-26 04:45 UTC, ddadaal commented on protos/server/user.proto
> +  optional string sort_order = 4;
变动了再改。给enum加新的取值是不影响兼容性的。

2023-07-26 12:00 UTC, piccaSun commented
已修改，请确认 @ddadaal

2023-07-26 12:19 UTC, ddadaal approved these changes

2023-07-27 07:18 UTC, lyl-available commented
排序结果还是有点问题
![image](https://github.com/PKUHPC/SCOW/assets/125553919/711de97b-725b-4a5a-a888-4633c7fb2426)

2023-07-27 08:41 UTC, piccaSun commented
@lyl-available 后端排序列名没有映射回数据库对应列名的字符串，已修改，请再确认一下😭

2023-07-28 01:17 UTC, piccaSun commented
不好意思，TAB切换的搜索逻辑想要优化重构一下，先转换成草稿
@lyl-available 不好意思先暂停测试一下

2023-07-30 15:14 UTC, piccaSun commented
重构租户管理前端分页和平台管理后端分页，实现搜索及角色切换后页码及排序信息重置
重构平台用户管理后端分页接口，每次切换角色时按角色进行表单信息的重新查询
不好意思提交的太晚了， @ddadaal  请有时间的时候确认

2023-07-30 15:24 UTC, ddadaal requested changes

2023-07-30 15:24 UTC, ddadaal commented on apps/mis-web/src/pageComponents/admin/AllUsersTable.tsx
> +    ) : setCurrentPlatformRole(undefined);
不是表达式的话用if直观一点

2023-07-30 15:24 UTC, ddadaal commented on apps/mis-web/src/pageComponents/admin/AllUsersTable.tsx
> +    countReload();
动名词词组：reloadAllUsers和reloadUserCounts

2023-07-30 15:24 UTC, ddadaal commented on apps/mis-web/src/pageComponents/admin/AllUsersTable.tsx
> +  }, []);
这个组件装载后就重新加载一次是必要的吗？

2023-07-30 15:32 UTC, ddadaal requested changes
突然发现另一个问题，GetUsers和GetAllUsers这两个接口有什么区别？能否合并为同一个GetUsers？

2023-07-30 15:32 UTC, ddadaal commented on protos/server/user.proto
> +}
这个enum只会在GetAllUsersRequest里用，所以可以直接放到GetAllUsersRequest里作为子enum

2023-07-30 15:47 UTC, piccaSun commented
> 突然发现另一个问题，GetUsers和GetAllUsers这两个接口有什么区别？能否合并为同一个GetUsers？
这。。我看功能上还是有区分的。GetAllUsers是单独拿的平台管理角色的用户列表。而且现在getUsers好像只用在了初始化显示用户列表的页面，应该除了读取全用户数据永远不涉及到query的部分？

2023-07-30 15:47 UTC, piccaSun commented
> 突然发现另一个问题，GetUsers和GetAllUsers这两个接口有什么区别？能否合并为同一个GetUsers？

 这。。我看功能上还是有区分的。GetAllUsers是单独拿的平台管理角色的用户列表。而且现在getUsers好像只用在了初始化显示用户列表的页面，应该除了读取全用户数据永远不涉及到query的部分？

2023-07-30 15:55 UTC, piccaSun commented on apps/mis-web/src/pageComponents/admin/AllUsersTable.tsx
> +  }, []);
没必要，只在setPalformRole和unsetPlatformRole的时候需要，我改一下~

2023-07-31 00:48 UTC, ddadaal commented
那之后把这两个API合并一下，这个PR就不管这个了。

2023-07-31 02:11 UTC, piccaSun commented
上述意见已修改，请确认 @ddadaal

2023-07-31 03:53 UTC, ddadaal approved these changes

2023-07-31 12:11 UTC, lyl-available approved these changes

2023-07-31 13:48 UTC, merged