feat(mis): 增加hook：jobPaid
PKUHPC/SCOW pull request #752
Opened 2023-07-20 09:54 UTC by tongchong

2023-07-21 06:33 UTC, ddadaal commented
作业付费不是一个具体的时刻。是指这个作业的信息被持久化到数据库了吗？

2023-07-21 06:42 UTC, tongchong commented
> 

对，执行完em.persist(pricedJob);  await em.flush();后 ，作业信息已经持久化到数据库了，是我的pr title描述有问题吗？

2023-07-21 06:51 UTC, ddadaal requested changes
hook名改为`jobSaved`。另外，目前的实现里调用callHook是在transactional块里面的，此时作业还没有写入到数据库里，离开transactional后em会自动commit，这时才把信息写入到数据库中。

2023-07-21 07:03 UTC, tongchong commented
> 离开transactional后em会自动commi

em.persist(pricedJob) 的数据也要等离开transactional后em自动commit吗？后面不是加了一个await em.flush(); 如果这样await em.flush();的意义是什么？作业的两条扣费记录肯定是等离开transactional后才commit。

2023-07-21 07:20 UTC, ddadaal commented
前面一个flush只保存了作业信息，但是计费的信息是离开了transational后才保存，两个charge和addJobCharge是不会flush的，会等着离开transactional后一起flush。实际上第一个em.flush()不应该存在，所有作业信息和计费信息应该在一次flush一个事务中完成，现在实际上是两个transaction。 @qhqhqhq

2023-07-21 07:26 UTC, tongchong commented
> 

我以为是特地这么写的，先保证把查询到的作业信息持久化到数据库，然后后续的两个charge和addJobCharge关系到slurm的封锁账户，可能会出错，放到后面一起执行

2023-07-21 07:28 UTC, qhqhqhq commented
> 前面一个flush只保存了作业信息，但是计费的信息是离开了transational后才保存，两个charge和addJobCharge是不会flush的，会等着离开transactional后一起flush。实际上第一个em.flush()不应该存在，所有作业信息和计费信息应该在一次flush一个事务中完成，现在实际上是两个transaction。 @qhqhqhq

这是之前导入作业的一个需求, 就是需要判断一下作业信息中是否存在不合法的数据比如mem_req过大, 然后导入数据库就会报错out of range, 这样之后的作业就都没法导入了, 所以在这里通过em.flush()判断一下作业是否能够导入, 如果不能导入, 就在log中提示, 然后跳过这条作业

2023-07-21 07:34 UTC, ddadaal commented
> > 前面一个flush只保存了作业信息，但是计费的信息是离开了transational后才保存，两个charge和addJobCharge是不会flush的，会等着离开transactional后一起flush。实际上第一个em.flush()不应该存在，所有作业信息和计费信息应该在一次flush一个事务中完成，现在实际上是两个transaction。 @qhqhqhq
> 
> 这是之前导入作业的一个需求, 就是需要判断一下作业信息中是否存在不合法的数据比如mem_req过大, 然后导入数据库就会报错out of range, 这样之后的作业就都没法导入了, 所以在这里通过em.flush()判断一下作业是否能够导入, 如果不能导入, 就在log中提示, 然后跳过这条作业

啊这……最好是手动写数据验证的逻辑，但是要是实在太麻烦了这样也行吧，写个注释在代码处。

2023-07-21 07:35 UTC, ddadaal commented
> > 
> 
> 我以为是特地这么写的，先保证把查询到的作业信息持久化到数据库，然后后续的两个charge和addJobCharge关系到slurm的封锁账户，可能会出错，放到后面一起执行

那就保持现在这个写法，在现在这个写法下，callHook应该放在紧接保存作业信息的flush之后

2023-07-21 07:52 UTC, qhqhqhq commented
> > > 
> > 
> > 
> > 我以为是特地这么写的，先保证把查询到的作业信息持久化到数据库，然后后续的两个charge和addJobCharge关系到slurm的封锁账户，可能会出错，放到后面一起执行
> 
> 那就保持现在这个写法，在现在这个写法下，callHook应该放在紧接保存作业信息的flush之后

这样会不会出问题, 因为之后的扣费过程也是可能报错导致整个事务回滚的

2023-07-21 07:53 UTC, ddadaal commented
保存作业成功，后面扣费出错，回滚是会导致保存的作业也回滚吗？

2023-07-21 07:54 UTC, qhqhqhq commented
是的

2023-07-21 07:55 UTC, tongchong commented
> 保存作业成功，后面扣费出错，回滚是会导致保存的作业也回滚吗？

这里使用jobSaved不一定保证save成功，只能保证肯定已经finish

2023-07-21 07:56 UTC, ddadaal commented
那还是先改一下整个作业保存扣费流程，改成对每个作业，先计算费用，再保存作业，再计费，计费执行完成后执行这个hook。

2023-07-24 00:44 UTC, ddadaal commented
#754 合并了，改一下hook调用位置

2023-07-24 07:36 UTC, ddadaal commented on apps/mis-server/src/tasks/fetch.ts
> +        }, logger);
现在这个位置实际上还是在计费结果进数据库之间就触发jobSaved了。在这个hook之前flush一次有什么不妥吗？@qhqhqhq

2023-07-24 07:44 UTC, qhqhqhq commented on apps/mis-server/src/tasks/fetch.ts
> +        }, logger);
其实现在把这个hook放在这里感觉还是会出问题，因为这一次事务是可能导入多条作业的（作业结束时间相同的作业），如果第一条作业导入后，执行了hook，在第二条作业导入时出现了问题，是会报错并且回滚的，也就是说第一条作业也会被回滚，这就导致最后作业实际并没有存入数据库，但还是触发了hook，所以感觉是不是把hook拿到事务外面会好一点？

2023-07-24 07:51 UTC, ddadaal commented on apps/mis-server/src/tasks/fetch.ts
> +        }, logger);
拿到事务外更好

2023-07-24 07:54 UTC, tongchong commented on apps/mis-server/src/tasks/fetch.ts
> +        }, logger);
那这个hook就改成一次性返回多个作业信息的hook

2023-07-25 06:16 UTC, ddadaal requested changes

2023-07-25 06:16 UTC, ddadaal commented on protos/hook/hook.proto
> +message HookJobInfo {
SavedJobInfo

2023-07-25 06:22 UTC, tongchong commented on protos/hook/hook.proto
> +message HookJobInfo {
我打算把 protos/server/job.proto 中的JobInfo提取到common中，新建一个ended_job.proto的公有proto文件，让fetch这里的hook返回的信息与apps/mis-server/src/services/job.ts中getJobs返回的作业信息一致

2023-07-26 01:21 UTC, ddadaal approved these changes

2023-07-26 01:21 UTC, merged