feat(mis): 在集群与分区信息页面，实现仅显示用户有使用权限的分区信息
PKUHPC/SCOW pull request #761
Opened 2023-07-26 02:04 UTC by piccaSun

2023-07-28 16:12 UTC, ddadaal requested changes

2023-07-28 16:12 UTC, ddadaal commented on apps/portal-server/src/services/config.ts
> +    },
这个API就是应该啥都不返回吗？

2023-07-28 16:12 UTC, ddadaal commented on apps/mis-web/src/pages/api/job/getBillingTable.ts
> +      allPartitionsSet.add(partitionStr);
首先，JSON.stringify(对象)出来的字符串的key的顺序不一定是一致的（ https://stackoverflow.com/questions/16167581/sort-object-properties-and-json-stringify ），这样写有可能是达不到去重的目的的。另外，序列化就是用来保存和传递消息的，不要用序列化来做逻辑。在这个地方，每个cluster中partition名字都是唯一的，可以使用`name`为根据对返回的数组进行去重。

2023-07-30 15:34 UTC, piccaSun commented on apps/portal-server/src/services/config.ts
> +    },
> 这个API就是应该啥都不返回吗？

这个API应该跟mis-server那边的是一致的，但是现在portal这边还没涉及到这个可见分区的需求，还没用到这个API，而且调度器接口可能也要变动，所以为了避免build configServiceServer的时候门户这边不写这个api会报错，我先TODO了一下。
是也跟mis一样给他补充完整比较好吗？

2023-07-30 15:40 UTC, ddadaal commented on apps/portal-server/src/services/config.ts
> +    },
对，先实现好，后面需要改的时候再改

2023-07-30 15:42 UTC, ddadaal commented on apps/portal-server/src/services/config.ts
> +    },
如果portal现在不需要这个功能，那么目前这个功能就是mis的，先创建一个新的只给mis用的API。如果后面portal要用了，再改到common里。

2023-08-02 11:50 UTC, piccaSun commented
1.修改protos及与调度器对应的getAvailablePartitions接口到mis下
   修改连接适配器服务方法为callOnAll（但是实际同样条件获取整个页面时间就稍稍缩短一点点）

2.修改页面连接方式SSR=> UseAsync
   但是在这个地方并没有新增API，因为原本GetBillingTableSchema也只是给这个用户集群分区显示页面使用的一个入口，并没有其他地方还用到这个schema，所以延续使用，只是在里面补充了一些接口信息。

3.修改去重方式为按集群下分区name去重

58环境下实现效果：
（后调整spin为在titile"分区信息"以下显示）
![chrome-capture-2023-7-2](https://github.com/PKUHPC/SCOW/assets/43978285/00ceb44b-ae85-424b-9500-713840f5196f)

@ddadaal 请确认

2023-08-03 02:48 UTC, ddadaal requested changes

2023-08-03 02:48 UTC, ddadaal commented on apps/mis-server/src/services/misConfig.ts
> +      return [{ clusterPartitions: wrappedResult } as any];
这里为何要as any？想办法去掉一下

2023-08-03 03:31 UTC, piccaSun commented on apps/mis-server/src/services/misConfig.ts
> +      return [{ clusterPartitions: wrappedResult } as any];
好像因为重新封装之后类型的构造找不到了没识别出来，那我再试试

2023-08-03 14:53 UTC, ddadaal commented on apps/mis-server/src/services/misConfig.ts
> +      return [{ clusterPartitions: wrappedResult } as any];
ts的类型系统是结构化的structural，也就是说如果两个类型的各个字段匹配，则这两个类型匹配。如果ts提示两个类型不匹配，首先应该看为什么不匹配，而不是用as强行转换。

这里类型系统就发现代码存在的问题，上一步的map的结果`wrappedResult`的类型实际上是`(ClusterPartitions | undefined)[]`，而不是你想要的`ClusterPartitions[]`，因为当`x.success`为falsy值（false | undefined)的时候，map出来的结果是undefined。你这里强转是有问题的，实际上是在掩盖x.success为false这个情况。这里不能简单的as，而是需要处理调用集群调度器失败的情况。

处理方式也很简单，打个log说调用哪个集群的时候失败，然后在返回结果的时候不返回这些undefined的结果就行。

2023-08-04 02:31 UTC, piccaSun commented on apps/mis-server/src/services/misConfig.ts
> +      return [{ clusterPartitions: wrappedResult } as any];
@ddadaal  我想再确认两点
1.是如果有失败还要不要返回？之前跟杨老师沟通调度器如果报错就是数据可能有问题要去解决错误，所以我直接在上面catch的时候扔出错误了
2.undefined是一个问题，但是我之前试过当我给x.success=false去配一个结果时并不能解决类型不匹配的问题
这个地方类型不匹配不是主要因为是在protobuf中定义的ClusterPartitions[ ]跟实际封装的{cluster: string, partitions:[]}[]不能匹配吗？但是在protobuf中没法直接使用map<string, repeated partitions>所以这个地方是不是最少需要一次断言？
![image](https://github.com/PKUHPC/SCOW/assets/43978285/30144ff8-fd3d-4eed-81b9-715da081d09e)

类似的地方还有AppSession的断言，这个地方的断言是不是同样的问题？
![image](https://github.com/PKUHPC/SCOW/assets/43978285/78be2575-eed8-4935-83ec-4b360fe095c4)

![image](https://github.com/PKUHPC/SCOW/assets/43978285/568aba95-00a6-40e6-bdc9-9d2cd3261a94)

2023-08-05 02:26 UTC, qhqhqhq commented on apps/mis-server/src/services/misConfig.ts
> +      return [{ clusterPartitions: wrappedResult } as any];
好的，我修改下callonall的返回值

2023-08-06 13:54 UTC, piccaSun commented on apps/mis-server/src/services/misConfig.ts
> +      return [{ clusterPartitions: wrappedResult } as any];
@ddadaal  不好意思是我对类型这块理解错了，已修改请确认

2023-08-07 11:20 UTC, ddadaal commented on apps/mis-server/src/services/misConfig.ts
> +      return [{ clusterPartitions: wrappedResult } as any];
#785 合并了，可以把这里的throw去掉了。

2023-08-07 12:40 UTC, piccaSun commented
上述问题已修改，增加前端页面发生错误时的文字展示,请确认 @ddadaal 
![image](https://github.com/PKUHPC/SCOW/assets/43978285/d9051584-d508-4d39-9acc-fb471058e2be)

2023-08-07 12:42 UTC, ddadaal approved these changes

2023-08-08 08:43 UTC, lyl-available commented
分区只有账户a_admin, 用户不属于a_admin依然显示分区信息
![image](https://github.com/PKUHPC/SCOW/assets/125553919/9c3c8146-4dd0-4180-92c3-eb0df5009a48)

![image](https://github.com/PKUHPC/SCOW/assets/125553919/4504f337-3310-4108-9964-a335b63c10c5)

2023-08-08 12:38 UTC, piccaSun commented
经确认，上述测试用户为lyl_test, 所属正常账户包含”a_a“,
将集群一可见分区compute指定账户a_admin可见，但是该用户仍能看到集群一分区compute信息的原因为
适配器端查询为字符串查找，查找结果"a_a"符合"a_admin"
上述问题需要slurm端修改
-------------------------------------------------------------------------------------
另外此PR原有查看dashboard下显示正常账户的逻辑缺乏账户没有封锁，只封锁账户内用户时的过滤，已修改

2023-08-09 08:27 UTC, lyl-available approved these changes

2023-08-09 12:40 UTC, merged