fix(mis-web): 对租户管理员增加账户管理的权限
PKUHPC/SCOW pull request #764
Opened 2023-07-26 07:42 UTC by OYX-1

之前租户管理员不能对其他账户进行添加用户、限额、封锁、设为管理员和移除用户等操作。
现在为租户管理员增加了这些权限：
![image](https://github.com/PKUHPC/SCOW/assets/74037789/024300df-3ef6-4f06-811a-6081eae2a5f9)
还有[issue335](https://github.com/PKUHPC/scow-internal-dev/issues/335)中的问题也不会出现了
![image](https://github.com/PKUHPC/SCOW/assets/74037789/c22e4263-273c-4703-9556-ef7a39598915)

2023-07-26 13:58 UTC, ddadaal requested changes

2023-07-26 13:58 UTC, ddadaal commented on apps/mis-web/src/pages/api/users/addToAccount.ts
> +    u.accountAffiliations.find((x) => x.accountName === accountName)?.role !== UserRole.USER ||
如果这个用户不存在于这个账户中，`u.accountAffiliations.find((x) => x.accountName === accountName)`为undefined，`u.accountAffiliations.find((x) => x.accountName === accountName)?.role`为`undefined`，此条件同样为true。

2023-07-27 05:44 UTC, OYX-1 commented on apps/mis-web/src/pages/api/users/addToAccount.ts
> +    u.accountAffiliations.find((x) => x.accountName === accountName)?.role !== UserRole.USER ||
嗯嗯，已改

2023-07-28 08:23 UTC, lyl-available approved these changes

2023-07-28 15:44 UTC, merged