feat(portal): 门户系统去除默认集群选择功能，新增集群选择排序以及记录上次选择集群功能
PKUHPC/SCOW pull request #767
Opened 2023-07-27 02:36 UTC by ZihanChen821

TODO

2023-07-27 15:15 UTC, ddadaal requested changes
- localStorage的项的key名应以SCOW开头，以和其他的key做区分，如`SCOW_DEFAULT_CLUSTER_ID`
- localStorage应只包含最基本的信息，比如这里localStorage里应该只包含id，不包含name

2023-07-27 15:15 UTC, ddadaal commented on apps/portal-web/src/layouts/DefaultCluster.tsx
> +export const useDefaultCluster = () => React.useContext(DefaultClusterContext);
默认集群的相关操作为何不放在DefaultClusterStore中，而定义这样一个Context？看起来这个Context和对应的Provider可以使用DefaultClusterStore来实现。

2023-07-28 01:26 UTC, ZihanChen821 commented on apps/portal-web/src/layouts/DefaultCluster.tsx
> +export const useDefaultCluster = () => React.useContext(DefaultClusterContext);
我这边的想法是把逻辑相关的 组件和 context聚合在一起了，感觉ClusterSelector组件基本上都会和这个defaultCluster绑定在一起使用，参考的是darkMode的实现。
如果要拆开的话，那就还是保持DefaultClusterStore只维护状态，组件单独放，每次使用的时候使用dynamic导入的形式把？

2023-07-31 03:50 UTC, ddadaal commented on apps/portal-web/src/layouts/DefaultCluster.tsx
> +export const useDefaultCluster = () => React.useContext(DefaultClusterContext);
darkMode用context是因为不想让lib-web依赖simstate，所以只能用context，在代码中的用直接用store代码会好看一点。

2023-07-31 03:52 UTC, ddadaal requested changes

2023-07-31 03:52 UTC, ddadaal commented on apps/portal-web/src/components/ClusterSelector.tsx
> +export const SingleClusterSelector = dynamic(() => Promise.resolve(SingleClusterSelectorUseDefault), { ssr: false });
为何要dynamic？这个组件必须要在浏览器端运行吗？

2023-07-31 04:23 UTC, ZihanChen821 commented on apps/portal-web/src/components/ClusterSelector.tsx
> +export const SingleClusterSelector = dynamic(() => Promise.resolve(SingleClusterSelectorUseDefault), { ssr: false });
如果没加的话，会有这个报错 
![image](https://github.com/PKUHPC/SCOW/assets/130351655/29dfa1d7-aab7-4c2c-aa40-d3eaa7e8d6c2)
我推测是因为，浏览器端从localStorage获取的defaultCluster值可能会与服务器端时的不一致导致的所以使用了dynamic。

2023-07-31 13:47 UTC, ddadaal commented on apps/portal-web/src/components/ClusterSelector.tsx
> +export const SingleClusterSelector = dynamic(() => Promise.resolve(SingleClusterSelectorUseDefault), { ssr: false });
这个警告不用管

2023-08-02 03:52 UTC, ddadaal approved these changes

2023-08-03 03:21 UTC, lyl-available commented
![image](https://github.com/PKUHPC/SCOW/assets/125553919/c5a858c7-adea-46b9-ac4e-ff280272dded)
集群名为中文或数字开头的排序是按什么来的？

2023-08-03 08:47 UTC, lyl-available commented
![image](https://github.com/PKUHPC/SCOW/assets/125553919/33df3518-886f-4756-8af9-f21a96e82db4)
桌面的默认集群没改，是集群二

2023-08-04 03:27 UTC, lyl-available approved these changes

2023-08-04 15:47 UTC, merged