feat: 交互式应用增加计算分区和软件应用版本的联动选择
PKUHPC/SCOW pull request #775
Opened 2023-07-31 06:48 UTC by OYX-1

之前在提交交互式应用时，选择分区后，CPU版本和GPU版本均会出现
![image](https://github.com/PKUHPC/SCOW/assets/74037789/a9d83fef-e8e6-4027-b19e-a729e955393c)
现在如果该分区只有CPU，那么只会出现CPU对应的版本
![image](https://github.com/PKUHPC/SCOW/assets/74037789/bd48689e-10ce-4bb1-b651-beed6496e56e)
如果该分区既有CPU又有GPU，那么会显示两个版本
![image](https://github.com/PKUHPC/SCOW/assets/74037789/6e418ad4-a41c-4011-a61b-d897446a6517)
用户配置部分：
用户在配置selectVersion时需要在select中加上gpuVersion项
![image](https://github.com/PKUHPC/SCOW/assets/74037789/e9c27b63-0001-4c13-ad3e-8b36123c057a)

2023-07-31 13:46 UTC, ddadaal requested changes

2023-07-31 13:46 UTC, ddadaal commented on apps/portal-web/src/pages/api/app/getAppMetadata.ts
> +  gpuVersion: Type.Optional(Type.Boolean()),
配置项名改为requiresGPU更清晰，表明这个应用版本**需要GPU**才能运行。

2023-07-31 13:46 UTC, ddadaal commented on apps/portal-web/src/pageComponents/app/LaunchAppForm.tsx
> +    if (item.name === "selectVersion") {
selectVersion不是一个特殊的配置项，不要特殊化处理这个配置。应该对所有select类型的attribute都这样处理：如果这个attribute的某些选项配置了requiresGPU，那么当用户切换分区时，这个attribute的可选的选项就要进行对应的修改。

2023-08-01 03:44 UTC, OYX-1 commented on apps/portal-web/src/pageComponents/app/LaunchAppForm.tsx
> +    if (item.name === "selectVersion") {
已改好

2023-08-02 07:52 UTC, ddadaal requested changes

2023-08-02 07:52 UTC, ddadaal commented on docs/docs/deploy/config/portal/apps/apps/relion/index.md
> +        # requireGPU: true
requireGPU为true, false和未配置分别是什么情况？在文档中写清楚。

2023-08-02 11:29 UTC, OYX-1 commented on docs/docs/deploy/config/portal/apps/apps/relion/index.md
> +        # requireGPU: true
已改好

2023-08-02 13:40 UTC, ddadaal commented on protos/portal/app.proto
> +  optional bool require_g_p_u = 3;
这个改成叫require_gpu就行

2023-08-03 02:01 UTC, OYX-1 commented on protos/portal/app.proto
> +  optional bool require_g_p_u = 3;
requireGPU里的GPU是缩写，一般缩写词都必须大写啊，例如“世贸组织”—WTO

2023-08-03 14:40 UTC, ddadaal requested changes

2023-08-03 14:40 UTC, ddadaal commented on protos/portal/app.proto
> +  optional bool require_g_p_u = 3;
但是GPU、CPU这些在计算机术语里基本已经成一个独立的单词了，可以直接用，gpu和g_p_u哪个可读性高一点？

2023-08-04 07:58 UTC, OYX-1 commented on protos/portal/app.proto
> +  optional bool require_g_p_u = 3;
嗯嗯，已改

2023-08-14 02:59 UTC, OYX-1 commented
@lyl-available 改好了，再试试

2023-08-14 06:30 UTC, lyl-available approved these changes

2023-08-14 09:55 UTC, merged