feat(auth): 全新 SCOW 登陆界面
PKUHPC/SCOW pull request #776
Opened 2023-07-31 08:14 UTC by Miracle575

# 新登陆界面样式
![image](https://github.com/PKUHPC/SCOW/assets/140392039/134ff1c0-a0dd-4ad3-9736-574a5272ed1b)
增加大背景图，并支持在  `dev/vagrant/config/ui.yaml` 修改背景图和背景色
![image](https://github.com/PKUHPC/SCOW/assets/140392039/aede6854-1eae-4ca7-a037-25bdedde4efd)

## 登录框
### 旧
![image](https://github.com/PKUHPC/SCOW/assets/140392039/58b3834b-14d9-4f0e-a86d-9e3615ed94c4)
### 新
![image](https://github.com/PKUHPC/SCOW/assets/140392039/e7bdbe79-c6ab-47c7-8c94-5e63bf1f7c97)
### 修改内容
1. 登录按钮大圆角改为小圆角
2. 密码框新增点击切换显示/隐藏密码

## 图标
### 旧版图标显示在登录框中
![image](https://github.com/PKUHPC/SCOW/assets/140392039/8be1fae3-d60b-44a2-b3d4-579014739fd2)
### 新版显示在页面左上角
![image](https://github.com/PKUHPC/SCOW/assets/140392039/1d0578e9-21b1-4164-b7ee-56262a684190)
并且新版支持在配置文件 `dev/vagrant/config/ui.yaml` 中修改图标为彩色或是白色
![image](https://github.com/PKUHPC/SCOW/assets/140392039/98cb2baa-3d83-4933-a454-f60f5bcf7c82)

## Powered By
### 旧版无 Powered By
### 新版显示在页面页面左下角
![image](https://github.com/PKUHPC/SCOW/assets/140392039/d52efcb1-c901-4bd1-a749-f07a6d14a741)

## slogan
### 旧版无 slogan
### 新版 slogan
![image](https://github.com/PKUHPC/SCOW/assets/140392039/19b18b98-eb2e-43b4-88ce-eac1a05dc348)

支持在  `dev/vagrant/config/ui.yaml` 修改 slogan 字体颜色和具体的内容
![image](https://github.com/PKUHPC/SCOW/assets/140392039/6ef3743c-9197-4bba-9fa3-d941ba9a8075)

2023-07-31 13:41 UTC, ddadaal requested changes
你改的是内置认证系统的登录节点，所以所有相关配置应该放在用于配置认证系统的auth.yml中，不是放在用于配置SCOW本身UI的ui.yaml中。SCOW支持第三方认证系统，所以认证系统的配置和部署实际上都是单独的服务。

2023-07-31 13:41 UTC, ddadaal commented on docs/docs/deploy/config/auth/config.md
> +  backgroundImage: "/public/assets/background.png"
1. [交互式作业配置图标](https://pkuhpc.github.io/SCOW/docs/deploy/config/portal/apps/configure-app-logo)已经使用过public目录下的文件了，这里的配置方式应该与已有的方式统一，也就是说，路径参数中不包含public。
2. 配置key也应该与已有的相统一，以path结尾，表示这是一个路径：`backgroundImagePath`。

2023-07-31 13:41 UTC, ddadaal commented on docs/docs/deploy/config/auth/config.md
> +  backgroundColor: "#9a0000"
背景色是fallback，在key中就写清楚：`backgroundFallbackColor`

2023-07-31 13:41 UTC, ddadaal commented on docs/docs/deploy/config/auth/config.md
> +  logoType: "true"
为什么是字符串的`"true"`和`"false"`？为什么指定是使用log.svg还是logo.dark.svg是使用true false？我知道在实现层面上是直接把这个配置传给了preferDark这个querystring，但是配置不应该依赖于实现。配置项设计应该清晰易懂，让用户很清晰地知道这个配置项的意思。用户只看logoType以及可以填写的值true和false，能知道这是什么意思吗？

另外实际上logo.svg和logo.dark.svg是分别用于亮色模式或者黑暗模式图片，不是彩图和白色

登录节点直接使用SCOW的logo配置就可以了： https://pkuhpc.github.io/SCOW/docs/deploy/config/customization/webui#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AF%BC%E8%88%AA%E6%A0%8Flogo

2023-07-31 13:41 UTC, ddadaal commented on docs/docs/deploy/config/auth/config.md
> +  sloganContentArr:
slogan部分配置的可以单独划一个object出来：

```yaml
slogan:
    color: ???
    title: ???
    texts: 
       - ???
       - ???
```

2023-08-01 05:47 UTC, Miracle575 commented on docs/docs/deploy/config/auth/config.md
> +  logoType: "true"
那这里我将 logoType 配置修改为 light 和 dark 两种。

另外关于这一点
> 登录节点直接使用SCOW的logo配置就可以了

需求中不需要给用户提供修改为自定义 logo 的功能，只需要在黑暗模式和亮色模式中能切换就行。我理解应该不需要去配置自定义 logo，只需要给 preferDark 传递的参数变一下就行？

2023-08-01 06:52 UTC, Miracle575 commented on docs/docs/deploy/config/auth/config.md
> +  backgroundColor: "#9a0000"
已修改

2023-08-01 06:53 UTC, Miracle575 commented on docs/docs/deploy/config/auth/config.md
> +  sloganContentArr:
已修改

2023-08-01 07:01 UTC, ddadaal commented on docs/docs/deploy/config/auth/config.md
> +  logoType: "true"
登录界面目前没有考虑黑暗和亮色模式吧？logoType让用户手动选就好了。

2023-08-01 07:03 UTC, Miracle575 commented on docs/docs/deploy/config/auth/config.md
> +  logoType: "true"
需求中是这么说的
> 提供默认图片和默认文字如下图所示，允许部署单位自行替换，考虑到替换的图片可能为浅色或者无图，SCOW LOGO也提供一份彩色版，字体颜色也支持修改；

也就是说背景图片会存在浅色或者无图等情况。所以希望 LOGO 也能切换。

2023-08-01 07:07 UTC, Miracle575 commented on docs/docs/deploy/config/auth/config.md
> +  backgroundImage: "/public/assets/background.png"
这个地方尝试使用了[交互式作业配置图标]( https://pkuhpc.github.io/SCOW/docs/deploy/config/portal/apps/configure-app-logo) 下[公共文件](https://pkuhpc.github.io/SCOW/docs/deploy/config/customization/public-files)的存放方式来存放背景图，但仍需要通过` /__public__/assets/background.png` 的路径才能访问到

2023-08-01 07:34 UTC, ddadaal commented on docs/docs/deploy/config/auth/config.md
> +  logoType: "true"
没有问题呀，背景图片是用户手动选的，所以使用哪个logo也是让用户通过`logoType`手动选嘛。

2023-08-01 07:35 UTC, ddadaal commented
登陆->登录

2023-08-02 13:40 UTC, ddadaal requested changes

2023-08-02 13:40 UTC, ddadaal commented on apps/auth/src/config/auth.ts
> +  }),
这个可以加一个`{ default: {} }`使slogan为可选配置

2023-08-02 13:40 UTC, ddadaal commented on docs/docs/deploy/config/auth/config.md
> +# auth 界面 ui 配置
文档中需表明每个配置是否为可选配置，默认值是什么

2023-08-02 13:40 UTC, ddadaal commented on docs/docs/deploy/config/auth/config.md
> +  # 登录界面背景图
强调相对于公共文件路径

2023-08-03 14:39 UTC, ddadaal requested changes

2023-08-03 14:39 UTC, ddadaal commented on apps/auth/config/auth.yml
> +  backgroundImagePath: "/__public__/assets/background.png"
你看看现在已经有的那个配置，是不包括__public__部分的，__public__部分是SCOW加的。因为用户需要关心的是他的文件相对于公共文件目录的相对路径，而具体怎么访问（即前面加__public__）是SCOW关心的

2023-08-04 15:44 UTC, ddadaal approved these changes

2023-08-09 06:32 UTC, lyl-available commented
![image](https://github.com/PKUHPC/SCOW/assets/125553919/187f9a3e-9138-48ca-9559-da4853a72189)
密码显示和隐藏按钮没出来

2023-08-09 08:55 UTC, lyl-available commented
logoType及slogan color修改未生效

2023-08-09 09:04 UTC, lyl-available commented
@ddadaal 设置的背景图如果比较小的话需要后台帮忙放大吗？（蓝框框是背景图）
![image](https://github.com/PKUHPC/SCOW/assets/125553919/1645133d-d7e8-4bbd-8f0a-b4543efee3c2)

2023-08-09 12:40 UTC, ddadaal commented
> @ddadaal 设置的背景图如果比较小的话需要后台帮忙放大吗？ ![image](https://user-images.githubusercontent.com/125553919/259392771-8c229511-105a-422d-b042-0b1b80408dda.png)

找得好。需要默认改成拉伸

2023-08-10 09:12 UTC, lyl-available approved these changes

2023-08-10 14:11 UTC, merged

2023-08-16 04:08 UTC, vanstriker commented
如何修改首页的功能是不是没有写到文档里面？

2023-08-16 05:37 UTC, Miracle575 commented
> 如何修改首页的功能是不是没有写到文档里面？

这部分的配置已经加在了文档中：https://pkuhpc.github.io/SCOW/docs/deploy/config/auth/config

2023-08-16 10:18 UTC, zhengkang2020 commented
logo 为什么不显示？

2023-08-16 11:40 UTC, Miracle575 commented
> 1、logo 为什么不显示？ ![image](https://user-images.githubusercontent.com/67989011/260978288-3aee4b1b-1b08-4da2-9691-2464c298b8b0.png)
> 
> 2、背景图片有大小要求吗？
> 
> 3、点击logo跳转到SCOW页面，这个能跳转到其他自定义页面吗？

1. 如果你是在本地的开发的话，是会显示不出来的。如果是已经部署了还是出现上述问题，可以把报错信息提供一下我们再进行排查
2. 背景图根据自身需要来，我们设置了 `background-size: cover` 来保证图片能铺满屏幕
3. 这个功能我们正在开发
@zhengkang2020

2023-08-17 03:34 UTC, zhengkang2020 commented
logo的日志是看auth吗？与下面的信息有没有关系?
```shell
[root@scow scow]# ./cli compose logs auth
INFO: Loaded plugins: []
scow-auth-1  | > @scow/auth@0.8.1 serve
scow-auth-1  | > node build/index.js
scow-auth-1  | {"level":30,"time":1692242616002,"pid":18,"hostname":"4927b6c98e82","version":{"commit":"1f92a08ad1cd07f9aa98dad1c037d9b0fd282555"},"msg":"Running @scow/auth"}
scow-auth-1  | {"level":30,"time":1692242616003,"pid":18,"hostname":"4927b6c98e82","config":{"HOST":"0.0.0.0","PORT":5000,"LOG_LEVEL":"info","LOG_PRETTY":false,"BASE_PATH":"/","AUTH_BASE_PATH":"/auth","MOCK_USERS":"","SSH_PRIVATE_KEY_PATH":"/root/.ssh/id_rsa","SSH_PUBLIC_KEY_PATH":"/root/.ssh/id_rsa.pub","EXTRA_ALLOWED_CALLBACK_HOSTNAMES":"","PUBLIC_PATH":"/__public__/"},"msg":"Loaded env config"}
```

```shell
scow-auth-1  | {"level":30,"time":1692242649746,"pid":18,"hostname":"4927b6c98e82","reqId":"req-16","msg":"Received end event. {\"messageID\":2,\"protocolOp\":101,\"controls\":[],\"log\":{},\"status\":0,\"matchedDN\":\"\",\"errorMessage\":\"\",\"referrals\":[],\"connection\":{\"connecting\":false,\"_hadError\":false,\"_parent\":null,\"_host\":null,\"_closeAfterHandlingError\":false,\"_readableState\":{\"objectMode\":false,\"highWaterMark\":16384,\"buffer\":{\"head\":null,\"tail\":null,\"length\":0},\"length\":0,\"pipes\":[],\"flowing\":true,\"ended\":false,\"endEmitted\":false,\"reading\":false,\"constructed\":true,\"sync\":false,\"needReadable\":true,\"emittedReadable\":false,\"readableListening\":false,\"resumeScheduled\":false,\"errorEmitted\":false,\"emitClose\":false,\"autoDestroy\":true,\"destroyed\":false,\"errored\":null,\"closed\":false,\"closeEmitted\":false,\"defaultEncoding\":\"utf8\",\"awaitDrainWriters\":null,\"multiAwaitDrain\":false,\"readingMore\":false,\"dataEmitted\":true,\"decoder\":null,\"encoding\":null},\"_events\":{\"end\":[null,null]},\"_eventsCount\":5,\"_writableState\":{\"objectMode\":false,\"highWaterMark\":16384,\"finalCalled\":false,\"needDrain\":false,\"ending\":false,\"ended\":false,\"finished\":false,\"destroyed\":false,\"decodeStrings\":false,\"defaultEncoding\":\"utf8\",\"length\":0,\"writing\":false,\"corked\":0,\"sync\":false,\"bufferProcessing\":false,\"writecb\":null,\"writelen\":0,\"afterWriteTickInfo\":null,\"buffered\":[],\"bufferedIndex\":0,\"allBuffers\":true,\"allNoop\":true,\"pendingcb\":0,\"constructed\":true,\"prefinished\":false,\"errorEmitted\":false,\"emitClose\":false,\"autoDestroy\":true,\"errored\":null,\"closed\":false,\"closeEmitted\":false},\"allowHalfOpen\":false,\"_sockname\":null,\"_pendingData\":null,\"_pendingEncoding\":\"\",\"server\":null,\"_server\":null},\"attributes\":[],\"notAttributes\":[],\"sentEntries\":0}"}
scow-auth-1  | {"level":30,"time":1692242649748,"pid":18,"hostname":"4927b6c98e82","reqId":"req-16","msg":"Disconnected LDAP connection."}
scow-auth-1  | {"level":30,"time":1692242649749,"pid":18,"hostname":"4927b6c98e82","reqId":"req-16","res":{"statusCode":200},"responseTime":12.675024032592773,"msg":"request completed"}
scow-auth-1  | {"level":30,"time":1692242653168,"pid":18,"hostname":"4927b6c98e82","reqId":"req-17","req":{"method":"GET","url":"/public/auth?callbackUrl=http%3A%2F%2Fhpc.xy-inv.com%2Fportal%2Fapi%2Fauth%2Fcallback","hostname":"hpc.xy-inv.com","remoteAddress":"172.21.0.7","remotePort":46184},"msg":"incoming request"}
scow-auth-1  | {"level":30,"time":1692242653174,"pid":18,"hostname":"4927b6c98e82","reqId":"req-17","res":{"statusCode":200},"responseTime":5.855875015258789,"msg":"request completed"}
scow-auth-1  | {"level":30,"time":1692242653227,"pid":18,"hostname":"4927b6c98e82","reqId":"req-18","req":{"method":"GET","url":"/public/assets/tailwind.min.css?","hostname":"hpc.xy-inv.com","remoteAddress":"172.21.0.7","remotePort":46198},"msg":"incoming request"}
scow-auth-1  | {"level":30,"time":1692242653229,"pid":18,"hostname":"4927b6c98e82","reqId":"req-18","res":{"statusCode":304},"responseTime":1.491642951965332,"msg":"request completed"}
scow-auth-1  | {"level":30,"time":1692242653303,"pid":18,"hostname":"4927b6c98e82","reqId":"req-19","req":{"method":"GET","url":"/public/assets/icons/eye-close.png?","hostname":"hpc.xy-inv.com","remoteAddress":"172.21.0.7","remotePort":46206},"msg":"incoming request"}
scow-auth-1  | {"level":30,"time":1692242653303,"pid":18,"hostname":"4927b6c98e82","reqId":"req-1a","req":{"method":"GET","url":"/public/assets/icons/eye.png?","hostname":"hpc.xy-inv.com","remoteAddress":"172.21.0.7","remotePort":46214},"msg":"incoming request"}

```

@Miracle575

2023-08-17 12:20 UTC, Miracle575 commented
> logo的日志是看auth吗？与下面的信息有没有关系?
> 
> ```shell
> [root@scow scow]# ./cli compose logs auth
> INFO: Loaded plugins: []
> scow-auth-1  | > @scow/auth@0.8.1 serve
> scow-auth-1  | > node build/index.js
> scow-auth-1  | {"level":30,"time":1692242616002,"pid":18,"hostname":"4927b6c98e82","version":{"commit":"1f92a08ad1cd07f9aa98dad1c037d9b0fd282555"},"msg":"Running @scow/auth"}
> scow-auth-1  | {"level":30,"time":1692242616003,"pid":18,"hostname":"4927b6c98e82","config":{"HOST":"0.0.0.0","PORT":5000,"LOG_LEVEL":"info","LOG_PRETTY":false,"BASE_PATH":"/","AUTH_BASE_PATH":"/auth","MOCK_USERS":"","SSH_PRIVATE_KEY_PATH":"/root/.ssh/id_rsa","SSH_PUBLIC_KEY_PATH":"/root/.ssh/id_rsa.pub","EXTRA_ALLOWED_CALLBACK_HOSTNAMES":"","PUBLIC_PATH":"/__public__/"},"msg":"Loaded env config"}
> ```
> 
> ```shell
> scow-auth-1  | {"level":30,"time":1692242649746,"pid":18,"hostname":"4927b6c98e82","reqId":"req-16","msg":"Received end event. {\"messageID\":2,\"protocolOp\":101,\"controls\":[],\"log\":{},\"status\":0,\"matchedDN\":\"\",\"errorMessage\":\"\",\"referrals\":[],\"connection\":{\"connecting\":false,\"_hadError\":false,\"_parent\":null,\"_host\":null,\"_closeAfterHandlingError\":false,\"_readableState\":{\"objectMode\":false,\"highWaterMark\":16384,\"buffer\":{\"head\":null,\"tail\":null,\"length\":0},\"length\":0,\"pipes\":[],\"flowing\":true,\"ended\":false,\"endEmitted\":false,\"reading\":false,\"constructed\":true,\"sync\":false,\"needReadable\":true,\"emittedReadable\":false,\"readableListening\":false,\"resumeScheduled\":false,\"errorEmitted\":false,\"emitClose\":false,\"autoDestroy\":true,\"destroyed\":false,\"errored\":null,\"closed\":false,\"closeEmitted\":false,\"defaultEncoding\":\"utf8\",\"awaitDrainWriters\":null,\"multiAwaitDrain\":false,\"readingMore\":false,\"dataEmitted\":true,\"decoder\":null,\"encoding\":null},\"_events\":{\"end\":[null,null]},\"_eventsCount\":5,\"_writableState\":{\"objectMode\":false,\"highWaterMark\":16384,\"finalCalled\":false,\"needDrain\":false,\"ending\":false,\"ended\":false,\"finished\":false,\"destroyed\":false,\"decodeStrings\":false,\"defaultEncoding\":\"utf8\",\"length\":0,\"writing\":false,\"corked\":0,\"sync\":false,\"bufferProcessing\":false,\"writecb\":null,\"writelen\":0,\"afterWriteTickInfo\":null,\"buffered\":[],\"bufferedIndex\":0,\"allBuffers\":true,\"allNoop\":true,\"pendingcb\":0,\"constructed\":true,\"prefinished\":false,\"errorEmitted\":false,\"emitClose\":false,\"autoDestroy\":true,\"errored\":null,\"closed\":false,\"closeEmitted\":false},\"allowHalfOpen\":false,\"_sockname\":null,\"_pendingData\":null,\"_pendingEncoding\":\"\",\"server\":null,\"_server\":null},\"attributes\":[],\"notAttributes\":[],\"sentEntries\":0}"}
> scow-auth-1  | {"level":30,"time":1692242649748,"pid":18,"hostname":"4927b6c98e82","reqId":"req-16","msg":"Disconnected LDAP connection."}
> scow-auth-1  | {"level":30,"time":1692242649749,"pid":18,"hostname":"4927b6c98e82","reqId":"req-16","res":{"statusCode":200},"responseTime":12.675024032592773,"msg":"request completed"}
> scow-auth-1  | {"level":30,"time":1692242653168,"pid":18,"hostname":"4927b6c98e82","reqId":"req-17","req":{"method":"GET","url":"/public/auth?callbackUrl=http%3A%2F%2Fhpc.xy-inv.com%2Fportal%2Fapi%2Fauth%2Fcallback","hostname":"hpc.xy-inv.com","remoteAddress":"172.21.0.7","remotePort":46184},"msg":"incoming request"}
> scow-auth-1  | {"level":30,"time":1692242653174,"pid":18,"hostname":"4927b6c98e82","reqId":"req-17","res":{"statusCode":200},"responseTime":5.855875015258789,"msg":"request completed"}
> scow-auth-1  | {"level":30,"time":1692242653227,"pid":18,"hostname":"4927b6c98e82","reqId":"req-18","req":{"method":"GET","url":"/public/assets/tailwind.min.css?","hostname":"hpc.xy-inv.com","remoteAddress":"172.21.0.7","remotePort":46198},"msg":"incoming request"}
> scow-auth-1  | {"level":30,"time":1692242653229,"pid":18,"hostname":"4927b6c98e82","reqId":"req-18","res":{"statusCode":304},"responseTime":1.491642951965332,"msg":"request completed"}
> scow-auth-1  | {"level":30,"time":1692242653303,"pid":18,"hostname":"4927b6c98e82","reqId":"req-19","req":{"method":"GET","url":"/public/assets/icons/eye-close.png?","hostname":"hpc.xy-inv.com","remoteAddress":"172.21.0.7","remotePort":46206},"msg":"incoming request"}
> scow-auth-1  | {"level":30,"time":1692242653303,"pid":18,"hostname":"4927b6c98e82","reqId":"req-1a","req":{"method":"GET","url":"/public/assets/icons/eye.png?","hostname":"hpc.xy-inv.com","remoteAddress":"172.21.0.7","remotePort":46214},"msg":"incoming request"}
> ```
> 

可以看一下是否启动了 portal-web，实际的 logo 资源请求发到了 portal-web。
可以根据 logo 的访问路径来判断访问的资源在什么位置。[相对路径|SCOW](https://pkuhpc.github.io/SCOW/docs/deploy/config/customization/basepath)

2023-08-18 02:13 UTC, zhengkang2020 commented
portal-web的日志如下，我这里如果要解决logo的问题，需要改动什么？另外日志为什么有个Error？

感谢回复！
```shell
[root@scow scow]# ./cli compose logs portal-web
INFO: Loaded plugins: []
scow-portal-web-1  |
scow-portal-web-1  |
scow-portal-web-1  | > @scow/portal-web@0.8.1 serve
scow-portal-web-1  | > node build/server/index.js
scow-portal-web-1  |
scow-portal-web-1  |
scow-portal-web-1  | Read dir config clusters of id hpc01 from /etc/scow/clusters/hpc01.yaml
scow-portal-web-1  | node:internal/deps/undici/undici:11576
scow-portal-web-1  |     Error.captureStackTrace(err, this);
scow-portal-web-1  |           ^
scow-portal-web-1  |
scow-portal-web-1  |
scow-portal-web-1  | TypeError: fetch failed
scow-portal-web-1  |     at Object.fetch (node:internal/deps/undici/undici:11576:11)
scow-portal-web-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
scow-portal-web-1  |     at async getCapabilities (/app/libs/auth/build/getCapabilities.js:24:19)
scow-portal-web-1  |     at async queryCapabilities (/app/apps/portal-web/config.js:37:12)
scow-portal-web-1  |     at async buildRuntimeConfig (/app/apps/portal-web/config.js:154:24)
scow-portal-web-1  |     at async module.exports (/app/apps/portal-web/next.config.js:32:25)
scow-portal-web-1  |     at async normalizeConfig (/app/node_modules/.pnpm/next@13.4.10_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/config-shared.js:153:12)
scow-portal-web-1  |     at async loadConfig (/app/node_modules/.pnpm/next@13.4.10_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/config.js:562:28)
scow-portal-web-1  |     at async Proxy.standaloneHandler (/app/node_modules/.pnpm/next@13.4.10_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next.js:260:44) {
scow-portal-web-1  |   cause: Error: connect ECONNREFUSED 172.22.0.9:5000
scow-portal-web-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
scow-portal-web-1  |     errno: -111,
scow-portal-web-1  |     code: 'ECONNREFUSED',
scow-portal-web-1  |     syscall: 'connect',
scow-portal-web-1  |     address: '172.22.0.9',
scow-portal-web-1  |     port: 5000
scow-portal-web-1  |   }
scow-portal-web-1  | }
scow-portal-web-1  |
scow-portal-web-1  |
scow-portal-web-1  | Node.js v18.17.1
scow-portal-web-1  | npm notice
scow-portal-web-1  | npm notice New minor version of npm available! 9.6.7 -> 9.8.1
scow-portal-web-1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.8.1>
scow-portal-web-1  | npm notice Run `npm install -g npm@9.8.1` to update!
scow-portal-web-1  | npm notice
scow-portal-web-1  |
scow-portal-web-1  |
scow-portal-web-1  | > @scow/portal-web@0.8.1 serve
scow-portal-web-1  | > node build/server/index.js
scow-portal-web-1  |
scow-portal-web-1  |
scow-portal-web-1  | Read dir config clusters of id hpc01 from /etc/scow/clusters/hpc01.yaml
scow-portal-web-1  | Running @scow/portal-web
scow-portal-web-1  | Version { commit: '1f92a08ad1cd07f9aa98dad1c037d9b0fd282555' }
scow-portal-web-1  | Server Runtime Config {
scow-portal-web-1  |   AUTH_EXTERNAL_URL: '/auth',
scow-portal-web-1  |   AUTH_INTERNAL_URL: 'http://auth:5000',
scow-portal-web-1  |   CLUSTERS_CONFIG: {
scow-portal-web-1  |     hpc01: {
scow-portal-web-1  |       displayName: 'hpc01',
scow-portal-web-1  |       loginNodes: [Array],
scow-portal-web-1  |       adapterUrl: '192.168.66.243:8999',
scow-portal-web-1  |       priority: 9007199254740991
scow-portal-web-1  |     }
scow-portal-web-1  |   },
scow-portal-web-1  |   PORTAL_CONFIG: {
scow-portal-web-1  |     jobManagement: true,
scow-portal-web-1  |     loginDesktop: {
scow-portal-web-1  |       enabled: true,
scow-portal-web-1  |       wms: [Array],
scow-portal-web-1  |       maxDesktops: 3,
scow-portal-web-1  |       desktopsDir: 'scow/desktops'
scow-portal-web-1  |     },
scow-portal-web-1  |     apps: true,
scow-portal-web-1  |     homeTitle: { defaultText: '', hostnameMap: {} },
scow-portal-web-1  |     homeText: { defaultText: 'XY-SCOW', hostnameMap: {} },
scow-portal-web-1  |     shell: true,
scow-portal-web-1  |     submitJobPromptText: '#此处参数设置的优先级高于页面其它地方，两者冲突时以此处为准',
scow-portal-web-1  |     submitJobDefaultPwd: 'scow/jobs/{{ name }}',
scow-portal-web-1  |     savedJobsDir: 'scow/savedJobs',
scow-portal-web-1  |     appJobsDir: 'scow/appData',
scow-portal-web-1  |     turboVNCPath: '/opt/TurboVNC',
scow-portal-web-1  |     appLastSubmissionDir: 'scow/apps'
scow-portal-web-1  |   },
scow-portal-web-1  |   DEFAULT_PRIMARY_COLOR: '#94070A',
scow-portal-web-1  |   MOCK_USER_ID: undefined,
scow-portal-web-1  |   UI_CONFIG: {
scow-portal-web-1  |     footer: { defaultText: '' },
scow-portal-web-1  |     primaryColor: { defaultColor: '#94070A' }
scow-portal-web-1  |   },
scow-portal-web-1  |   LOGIN_NODES: {},
scow-portal-web-1  |   SERVER_URL: 'portal-server:5000',
scow-portal-web-1  |   DEFAULT_HOME_TEXT: 'XY-SCOW',
scow-portal-web-1  |   HOME_TEXTS: {},
scow-portal-web-1  |   DEFAULT_HOME_TITLE: '',
scow-portal-web-1  |   HOME_TITLES: {},
scow-portal-web-1  |   SUBMIT_JOB_WORKING_DIR: 'scow/jobs/{{ name }}',
scow-portal-web-1  |   SCOW_API_AUTH_TOKEN: undefined,
scow-portal-web-1  |   SUBMIT_JOB_PROMPT_TEXT: '#此处参数设置的优先级高于页面其它地方，两者冲突时以此处为准'
scow-portal-web-1  | }
scow-portal-web-1  | Public Runtime Config {
scow-portal-web-1  |   ENABLE_CHANGE_PASSWORD: true,
scow-portal-web-1  |   ENABLE_SHELL: true,
scow-portal-web-1  |   ENABLE_JOB_MANAGEMENT: true,
scow-portal-web-1  |   ENABLE_LOGIN_DESKTOP: true,
scow-portal-web-1  |   ENABLE_APPS: true,
scow-portal-web-1  |   MIS_URL: '/mis',
scow-portal-web-1  |   CLUSTERS: [ { id: 'hpc01', name: 'hpc01' } ],
scow-portal-web-1  |   NOVNC_CLIENT_URL: '/vnc',
scow-portal-web-1  |   PASSWORD_PATTERN: '^(?=.*\\d)(?=.*[a-zA-Z])(?=.*[`~!@#\\$%^&*()_+\\-[\\];\',./{}|:"<>?]).{8,}$',
scow-portal-web-1  |   PASSWORD_PATTERN_MESSAGE: '必须包含字母、数字和符号，长度大于等于8位',
scow-portal-web-1  |   BASE_PATH: '/portal',
scow-portal-web-1  |   CLIENT_MAX_BODY_SIZE: '1G',
scow-portal-web-1  |   PUBLIC_PATH: '/__public__',
scow-portal-web-1  |   NAV_LINKS: undefined,
scow-portal-web-1  |   USER_LINKS: undefined,
scow-portal-web-1  |   VERSION_TAG: undefined
scow-portal-web-1  | }

```
@Miracle575

2023-08-18 03:11 UTC, Miracle575 commented
麻烦顺便提供一下 portal-server 的日志信息 @zhengkang2020

2023-08-18 03:16 UTC, zhengkang2020 commented
```shell
[root@scow scow]# ./cli compose logs portal-server
INFO: Loaded plugins: []
scow-portal-server-1  |
scow-portal-server-1  |
scow-portal-server-1  | > @scow/portal-server@0.8.1 serve
scow-portal-server-1  | > node build/index.js
scow-portal-server-1  |
scow-portal-server-1  |
scow-portal-server-1  | {"level":30,"time":1692323960693,"pid":18,"hostname":"4145c9c15ee5","version":{"commit":"1f92a08ad1cd07f9aa98dad1c037d9b0fd282555"},"msg":"Running @scow/portal-server"}
scow-portal-server-1  | {"level":30,"time":1692323960694,"pid":18,"hostname":"4145c9c15ee5","config":{"HOST":"0.0.0.0","PORT":5000,"LOG_LEVEL":"info","LOG_PRETTY":false,"PORTAL_BASE_PATH":"/portal","SSH_PRIVATE_KEY_PATH":"/root/.ssh/id_rsa","SSH_PUBLIC_KEY_PATH":"/root/.ssh/id_rsa.pub","DOWNLOAD_CHUNK_SIZE":3145728},"msg":"Loaded env config"}
scow-portal-server-1  | {"level":30,"time":1692323960699,"pid":18,"hostname":"4145c9c15ee5","msg":"Checking if root can login to hpc01 by login node login"}
scow-portal-server-1  | {"level":30,"time":1692323960809,"pid":18,"hostname":"4145c9c15ee5","msg":"Root can login to hpc01 by login node login"}
scow-portal-server-1  | {"level":30,"time":1692323961229,"pid":18,"hostname":"4145c9c15ee5","msg":"Copy scow-shell-file.sh to the /etc/profile.d/scow-shell-file.sh of the login node of cluster hpc01."}
scow-portal-server-1  | {"level":30,"time":1692323961236,"pid":18,"hostname":"4145c9c15ee5","msg":"Listening at 5000"}

```

2023-08-18 03:30 UTC, Miracle575 commented
初步判断可能是配置问题，可能需要提供一下相关的配置。可以尽可能提供 install.yaml，以及 config 目录下的一系列配置文件内容吗？ @zhengkang2020

2023-08-18 03:36 UTC, zhengkang2020 commented
install.yaml
```yaml
[root@scow scow]# cat install.yaml
# 整个系统的端口号。默认80
# port: 80

# 整个系统的部署路径。默认/
basePath: /

# SCOW的镜像的tag。默认：master
# imageTag: master

# 门户相关配置。默认不部署
# 如果不部署，请删除或者注释整个部分
portal:
#   # 门户路径相对于整个系统的部署路径。默认/
#   # 若设置则/开头，不要以/结尾.
#   # 如果BASE_PATH为/root1，PORTAL.BASE_PATH为/root2，那么最终访问门户系统的路径是/root1/root2
  basePath: /portal

#   # novnc web客户端镜像地址
#   # novncClientImage: ghcr.io/pkuhpc/novnc-client-docker:master

#   # 端口映射。如果不进行二次开发，请勿开放
#   # portMappings:
#   #   # portal-server的5000映射到。不填写则不映射
#   #   # portalServer: 127.0.0.1:7572

# 管理系统相关配置。默认不部署
# 如果不部署，请删除或者注释整个部分
mis:
#   # 门户系统路径相对于整个系统的部署路径。默认/
#   # 若设置则/开头，不要以/结尾.
#   # 如果BASE_PATH为/root1，PORTAL.BASE_PATH为/root2，那么最终访问管理系统的路径是/root1/root2
  basePath: /mis

#   # mysql数据库的镜像地址。默认为mysql:8
#   # mysqlImage: "mysql:8"

#   # 管理系统数据库的密码。如果部署管理系统，则必须配置
#   # 第一次启动管理系统时会使用此密码初始化管理系统数据库，之后如需修改需要手动在数据库中修改
  dbPassword: "myst!chang3this"

#   # 端口映射。如果不进行二次开发，请勿开放
#   # portMappings:
#   #   # 数据库的3306端口映射。不填写则不映射
#   #   db: 127:0.0.1:3306
#   #   # mis-serve的5000端口映射到。不填写则不映射
#   #   misServer: 127.0.0.1:7571

# 认证系统相关配置。可选，不配置为默认配置
# auth:
#   # redis镜像。默认为redis:alpine
#   redisImage: redis:alpine

#   # 端口映射。只对内置认证系统有效
#   # portMappings:
#   #   # redis的6379端口。不填写则不映射
#   #   # redis: 127.0.0.1:6379
#   #   # 认证系统的5000端口，不填写则不映射
#   #   # auth: 127.0.0.1:5001

#   # 自定义认证系统。默认使用内置认证系统
#   # 如果使用内置认证系统，将此部分注释掉
#   custom:
#     # 自定义认证系统镜像名。必填
#     # image: my-custom-auth:v1.0

#     # 端口映射。可选
#     # ports:
#     #   - "5000:5000"

#     # 更多挂载卷。可选
#     # 默认添加/etc/hosts:/etc/hosts和./config:/etc/scow
#     # volumes:
#     #   - "./myfile:/etc/myfile"

#     # 环境变量，可选。
#     # environment:
#     #   - DEBUG=log

# 日志相关配置
# log:
#   # 日志级别。默认info
#   # 可选：slient, error, warn, info, debug
#   level: info

#   # 是否输出更适合直接读的log。默认为false
#   # 如果为false，则输出json格式的日志。默认false
#   pretty: false

#   # fluentd日志收集服务配置。
#   # 将会使用fluent/fluent.conf作为配置文件
#   # 如果不使用，请注释整个部分
#   fluentd:
#     # fluentd镜像
#     image: fluentd:v1.14.0-1.0
#     # fluentd日志存放地点
#     logDir: /var/log/fluentd

# 网关配置
# gateway:
#   # 限制整个系统上传（请求）文件的大小。默认1G
#   # 可接受的格式为nginx的client_max_body_size可接受的值
#   uploadFileSizeLimit: 1G

#   # 限制后端服务发出响应的超时时间，默认60s
#   # 可接受的格式为nginx的proxy_read_timeout可接受的值
#   proxyReadTimeout: 60s

#   # 更多nginx配置
#   # 可接受的格式为nginx的server可接受的属性配置，例如可增加在当前系统nginx默认端口的服务
#   extra: >
#         location /extra {
#             proxy_pass http://extra-web:3000;
#             include includes/headers;
#             include includes/websocket;
#          }

# 插件配置
# plugins:
#   # 启用的插件
#   enabledPlugins: ["plugin1"]
```
auth.yaml

```yaml
[root@scow scow]# cat config/auth.yml
# auth 界面 ui 配置
ui:
  # 登录界面背景图，设置为""(空字符串)则无背景图
  # 可选配置，默认加载 install.yml 同级的 /public/assets 目录下的 background.png 作为背景图
  backgroundImagePath: "./assets/background.png"
  # 登录界面背景色，当背景图无法加载或者没有时，背景色起效
  # 可选配置，默认为 #9a0000
  backgroundFallbackColor: "#9a0000"
  # 登录界面 logo 图, light: 亮色模式下的 logo, dark: 黑暗模式下的 logo
  # 可选配置，默认为黑暗模式 logo
  logoType: "dark"

  # 登录界面 slogan 配置
  # 可选配置，默认右侧无 slogan
  slogan:
    # 登录界面 slogan 文字颜色
    # 可选配置，默认为白色字体
    color: "white"
    # 登录界面 slogan 标题
    # 可选配置，默认无 slogan 标题
    title: "开源算力中心门户和管理平台"
    # 多条 slogan 文本
    # 可选配置，默认 slogan 为空数组
    texts:
      - "图形化界面，使用方便"
      - "功能丰富，管理简单"
      - "一体化部署，开箱即用"
      - "标准化平台，支持算力融合"
      - "开源中立，独立自主"


authType: ldap
ldap:
  url: ldap://192.168.66.241
  bindDN: cn=Manager,ou=hpc,o=pku
  bindPassword: admin
  searchBase: "ou=hpc,o=pku"
  userFilter: "(uid=*)"
  addUser:
    userBase: "ou=People,ou=hpc,o=pku"
    userIdDnKey: uid
    # 把homeDir设置为共享存储上的用户的家路径
    homeDir: /data/home//{{ userId }}

    groupStrategy: newGroupPerUser
    newGroupPerUser:
      groupBase: "ou=Group,ou=hpc,o=pku"
      groupIdDnKey: cn
  attrs:
    uid: uid
    name: cn
    mail: mail

```

其他文件配置是默认的 @Miracle575

2023-08-18 03:37 UTC, Miracle575 commented
另外 docker ps 一下，看一下启动的容器服务 @zhengkang2020

2023-08-18 03:48 UTC, Miracle575 commented
可以通过我个人主页邮箱提供联系方式，可能交流方便一点 @zhengkang2020