fix(mis-web): 管理系统用户空间下分区信息中计量方式显示错误
PKUHPC/SCOW pull request #780
Opened 2023-08-02 13:20 UTC by piccaSun

### 问题

管理系统下用户空间的分区信息中没有显示正确的计量方式的文字描述字符串

![image](https://github.com/PKUHPC/SCOW/assets/43978285/0a166bc5-dfb9-4a06-a5e0-b078fe74523a)

此PR修改为与作业价格表中的计量方式显示一致，修改为计量方式文字及icon说明的形式
### 修改后

![image](https://github.com/PKUHPC/SCOW/assets/43978285/f0ac2b69-3926-4d28-b1ec-613dbf7df4ae)
![image](https://github.com/PKUHPC/SCOW/assets/43978285/233512c9-8efa-4ac6-b6d7-fbeeb079b9dc)

2023-08-02 13:36 UTC, ddadaal requested changes

2023-08-02 13:36 UTC, ddadaal commented on apps/mis-web/src/components/JobBillingTable.tsx
> +        </Space>
这些代码应该可以提个组件出来

2023-08-02 13:36 UTC, ddadaal commented on apps/mis-web/src/components/JobBillingTable.tsx
> +              </Popover>
这也是

2023-08-03 02:41 UTC, piccaSun commented
已修改，请确认 @ddadaal

2023-08-03 14:36 UTC, ddadaal requested changes
提了组件之后把现在已经有的这些重复部分也替换成组件

2023-08-04 01:38 UTC, piccaSun commented
> 提了组件之后把现在已经有的这些重复部分也替换成组件

commit中已经替换过了，包括跟 #774 可能有冲突也沟通过了

2023-08-04 15:35 UTC, merged