feat: 新增operation log server
PKUHPC/SCOW pull request #782
Opened 2023-08-04 03:43 UTC by ZihanChen821

// todo

2023-08-18 11:37 UTC, ddadaal requested changes

2023-08-18 11:37 UTC, ddadaal commented on apps/mis-web/src/pages/api/admin/changePassword.ts
> +        callLog(logInfo, OperationResult.SUCCESS);
callLog是async函数，即使不管结果，也要用await调用，否则调用log会乱。

2023-08-18 11:37 UTC, ddadaal commented on apps/portal-web/src/models/operationLog.ts
> +export const OperationType = {
operationType在portal和web中有重复，并且实际上已经在protobuf中定义过。可以在lib/operation-log中通过类型魔法，从protobuf生成的ts类型中提取出所有可能的OperationType，这样就不用重新定义一次了。

2023-08-21 01:50 UTC, ZihanChen821 commented on apps/mis-web/src/pages/api/admin/changePassword.ts
> +        callLog(logInfo, OperationResult.SUCCESS);
如果不希望callLog阻塞其他接口的逻辑，是否可以将callLog的async去掉，改为异步调用rpc call呢？

```typescript

export const createOperationLogClient = (
  config: AuditConfigSchema | undefined,
  logger: Logger | Console,
) => {
  const client = config && config.url
    ? new OperationLogServiceClient(config.url, ChannelCredentials.createInsecure())
    : undefined;

  if (!config || !client) {
    logger.debug("Operation Log Server disabled");
  }

  return {
    callLog: <TName extends OperationEvent["$case"]>({
      operatorUserId,
      operatorIp,
      operationTypeName,
      operationTypePayload,
      operationResult,
      logger,
    }: LogCallParams<TName>) => {

      if (!client) {
        logger.debug("Attempt to call Log %s with %o", operationTypeName, operationTypePayload);
        return;
      }

      asyncUnaryCall(client, "createOperationLog", {
        operatorUserId,
        operatorIp,
        operationResult,
        // @ts-ignore
        operationEvent: { $case: operationTypeName, [operationTypeName]: { ...operationTypePayload } },
      }).then(
        () => { logger.debug("Operation Log call completed"); },
        (e) => {
          logger.error(e, "Error when calling Operation Log");
        },
      );
    },
  };
};
```

2023-08-21 05:58 UTC, ZihanChen821 commented on apps/portal-web/src/models/operationLog.ts
> +export const OperationType = {
在lib/operation-log里这样定义，是否有要修改的呢

```typescript
type ExtractCases<T> = T extends { $case: infer U } ? U : never;

export type OperationType = ExtractCases<OperationLog["operationEvent"]>;

type OperationTypeEnum = { [K in OperationType]: K };

export const OperationType: OperationTypeEnum = {
  login: "login",
  logout: "logout",
  submitJob: "submitJob",
  endJob: "endJob",
  addJobTemplate: "addJobTemplate",
  deleteJobTemplate: "deleteJobTemplate",
  updateJobTemplate: "updateJobTemplate",
  shellLogin: "shellLogin",
  createDesktop: "createDesktop",
  deleteDesktop: "deleteDesktop",
  createApp: "createApp",
  createFile: "createFile",
  deleteFile: "deleteFile",
  uploadFile: "uploadFile",
  createDirectory: "createDirectory",
  deleteDirectory: "deleteDirectory",
  moveFileItem: "moveFileItem",
  copyFileItem: "copyFileItem",
  setJobTimeLimit: "setJobTimeLimit",
  createUser: "createUser",
  addUserToAccount: "addUserToAccount",
  removeUserFromAccount: "removeUserFromAccount",
  setAccountAdmin: "setAccountAdmin",
  unsetAccountAdmin: "unsetAccountAdmin",
  blockUser: "blockUser",
  unblockUser: "unblockUser",
  accountSetChargeLimit: "accountSetChargeLimit",
  accountUnsetChargeLimit: "accountUnsetChargeLimit",
  setTenantBilling: "setTenantBilling",
  setTenantAdmin: "setTenantAdmin",
  unsetTenantAdmin: "unsetTenantAdmin",
  setTenantFinance: "setTenantFinance",
  unsetTenantFinance: "unsetTenantFinance",
  tenantChangePassword: "tenantChangePassword",
  createAccount: "createAccount",
  addAccountToWhitelist: "addAccountToWhitelist",
  removeAccountFromWhitelist: "removeAccountFromWhitelist",
  accountPay: "accountPay",
  importUsers: "importUsers",
  setPlatformAdmin: "setPlatformAdmin",
  unsetPlatformAdmin: "unsetPlatformAdmin",
  setPlatformFinance: "setPlatformFinance",
  unsetPlatformFinance: "unsetPlatformFinance",
  platformChangePassword: "platformChangePassword",
  setPlatformBilling: "setPlatformBilling",
  createTenant: "createTenant",
  tenantPay: "tenantPay",
};

```

2023-08-21 06:30 UTC, ZihanChen821 commented on apps/portal-web/src/models/operationLog.ts
> +export const OperationType = {
采用了这样的方式定义是否可以

```typescript
// libs/operation-log

import { OperationLog } from "@scow/protos/build/audit/operation_log";

export enum OperationResult {
  UNKNOWN = 0,
  SUCCESS = 1,
  FAIL = 2,
};

type ExtractCases<T> = T extends { $case: infer U } ? U : never;

export type OperationType = ExtractCases<OperationLog["operationEvent"]>;

export type OperationTypeEnum = { [K in OperationType]: K };
```

目前还是需要在mis-web和portal-web里定义一个常量对象供schema使用（尝试在lib-operation-log里定义但是会有和proto里导入一样的报错）
````typescript
// src/models/operationLogs.ts
import { OperationTypeEnum } from "@scow/lib-operation-log";

export const OperationType: OperationTypeEnum = {
  login: "login",
  logout: "logout",
  submitJob: "submitJob",
  endJob: "endJob",
  addJobTemplate: "addJobTemplate",
  deleteJobTemplate: "deleteJobTemplate",
  updateJobTemplate: "updateJobTemplate",
  shellLogin: "shellLogin",
  createDesktop: "createDesktop",
  deleteDesktop: "deleteDesktop",
  createApp: "createApp",
  createFile: "createFile",
  deleteFile: "deleteFile",
  uploadFile: "uploadFile",
  createDirectory: "createDirectory",
  deleteDirectory: "deleteDirectory",
  moveFileItem: "moveFileItem",
  copyFileItem: "copyFileItem",
  setJobTimeLimit: "setJobTimeLimit",
  createUser: "createUser",
  addUserToAccount: "addUserToAccount",
  removeUserFromAccount: "removeUserFromAccount",
  setAccountAdmin: "setAccountAdmin",
  unsetAccountAdmin: "unsetAccountAdmin",
  blockUser: "blockUser",
  unblockUser: "unblockUser",
  accountSetChargeLimit: "accountSetChargeLimit",
  accountUnsetChargeLimit: "accountUnsetChargeLimit",
  setTenantBilling: "setTenantBilling",
  setTenantAdmin: "setTenantAdmin",
  unsetTenantAdmin: "unsetTenantAdmin",
  setTenantFinance: "setTenantFinance",
  unsetTenantFinance: "unsetTenantFinance",
  tenantChangePassword: "tenantChangePassword",
  createAccount: "createAccount",
  addAccountToWhitelist: "addAccountToWhitelist",
  removeAccountFromWhitelist: "removeAccountFromWhitelist",
  accountPay: "accountPay",
  importUsers: "importUsers",
  setPlatformAdmin: "setPlatformAdmin",
  unsetPlatformAdmin: "unsetPlatformAdmin",
  setPlatformFinance: "setPlatformFinance",
  unsetPlatformFinance: "unsetPlatformFinance",
  platformChangePassword: "platformChangePassword",
  setPlatformBilling: "setPlatformBilling",
  createTenant: "createTenant",
  tenantPay: "tenantPay",
};

export const OperationLog = Type.Object({
  operationLogId: Type.Number(),
  operatorUserId: Type.String(),
  operatorIp: Type.String(),
  operationCode: Type.String(),
  operationType: Type.Enum(OperationType),
  operationResult: Type.Enum(OperationResult),
  operationTime: Type.Optional(Type.String()),
  operationDetail: Type.String(),
});
export type OperationLog = Static<typeof OperationLog>;

2023-08-21 10:47 UTC, ddadaal commented on apps/mis-web/src/pages/api/admin/changePassword.ts
> +        callLog(logInfo, OperationResult.SUCCESS);
不可以，一样的道理，不管async调用就可能会造成log混乱。这里最好的解决方案应该是上MQ这些外部系统，但是目前我们懒得搞，正确>性能，宁愿牺牲一点性能也要保证结果是好追溯的。

2023-08-21 10:50 UTC, ddadaal commented on apps/portal-web/src/models/operationLog.ts
> +export const OperationType = {
这样可以，如果这个对象和proto里的有差错会报错吧。另外，把这个文件定义在lib-operation-log没问题，注意import的时候需要直接从`build`下import这个编译出来的js文件就行。

2023-08-22 01:11 UTC, ZihanChen821 commented on apps/portal-web/src/models/operationLog.ts
> +export const OperationType = {
好的，会报错的

2023-08-22 13:08 UTC, ddadaal approved these changes

2023-08-22 13:09 UTC, ddadaal commented
我觉得可以进了，但是现在进的话1.0就会带这个功能。明天确认一下1.0要不要这个功能。

2023-08-26 01:12 UTC, ddadaal commented
解决一下冲突

2023-08-28 01:18 UTC, ZihanChen821 commented
> 解决一下冲突

已解决

2023-08-28 11:30 UTC, merged