fix: 查询账户充值界面优化
PKUHPC/SCOW pull request #783
Opened 2023-08-04 07:32 UTC by OYX-1

# 之前的情况：
![image](https://github.com/PKUHPC/SCOW/assets/74037789/646b8ac5-a058-433d-9447-f11674dc5093)
![image](https://github.com/PKUHPC/SCOW/assets/74037789/9da6ec10-0810-498f-9312-df49f710229c)
# 现在的情况：
## 租户管理中，财务管理-充值记录页面修改，该页面功能为查询租户下账户的充值记录。
### 菜单栏名称修改为“账户充值记录”；
### 去掉充值对象租户账户二选一功能，只保留账户筛选项；
### 账户下拉框允许为空，为空时查询该租户下所有账户的充值记录；
![image](https://github.com/PKUHPC/SCOW/assets/74037789/84cbde97-1336-4cd0-bd10-fdc3e1e4b95d)
## 租户管理中增加一级菜单“充值记录”，页面功能为查询本租户的充值记录。
![image](https://github.com/PKUHPC/SCOW/assets/74037789/2ea6ba96-695e-4086-974d-122004a33af5)
## 修改平台管理中的充值记录页面：将租户查询条件修改为下拉框形式，且支持搜索和刷新租户列表
![image](https://github.com/PKUHPC/SCOW/assets/74037789/abe1f034-d3f4-413e-9d57-d1636b7a3123)

2023-08-04 16:20 UTC, ddadaal requested changes

2023-08-04 16:20 UTC, ddadaal commented on protos/server/charging.proto
> +  optional bool all_account = 5;
所以目前这个API需要覆盖以下四种情况的充值记录的查询：
1. 某个账户充值记录
2. 某个租户充值记录
3. 某个租户下所有账户的充值记录
4. 所有租户充值记录？

现在逻辑比较复杂了，目前这样的API设计不够直观。可以直接使用oneof和不同的message来区分不同情况

```proto
message GetPaymentRecordsRequest {
  google.protobuf.Timestamp start_time = 1;
  google.protobuf.Timestamp end_time = 2;
  
  message Account {
      string account_name = 1;
  }

  message Tenant {
     string tenant_name = 1;
  }
  
  message AccountsOfTenant {
    string tenant_name = 1;
  }
  
  message AllTenants { 
  }

  oneof target { 
    Account account = 3;
    Tenant tenant = 4;
    AccountsOfTenant accounts_of_tenant = 5;
    AllTenants all_tenants = 6;
  }
```
这样不管是你后面写逻辑，还是用这个API都会更清晰。

记得写注释，说明oneof每种情况是查询什么的。

另外，这是一个grpc api的breaking change，grpc api需要minor等级

2023-08-04 16:20 UTC, ddadaal commented on apps/mis-web/src/pageComponents/common/PaymentTable.tsx
> +  adminData: boolean;
`adminData`这个名字取得不好。什么admin？设置这个为true和false，具体对这个组件的行为有什么变化，从这个属性的名字上完全看不出来。

2023-08-04 16:20 UTC, ddadaal commented on apps/mis-web/src/pageComponents/common/PaymentTable.tsx
> +export enum nameType {
类型、枚举名要Pascal命名法

2023-08-04 16:20 UTC, ddadaal commented on apps/mis-web/src/pageComponents/common/PaymentTable.tsx
> +  showNameSearch?: nameType;
问题：
1. 这个组件还有几个prop属性也是以show开头，但是那几个属性都是boolean的。而这个以show开头的属性却不是boolean，破坏了一致性
2. 我看了一下代码，showNameSearch === NameType.Tenant的情况只有平台管理员的页面会触发吧。那这几个属性都是多余的。

简单的修改：
```ts
enum SearchType {
    // 选择账户
    Account = "Account',
    // 选择租户
    Tenant = "Tenant",
} 

interface Props {
    ...
    searchType: SearchType;
    // 去除showNameSearch和adminData
}

```

2023-08-07 07:34 UTC, OYX-1 commented on apps/mis-web/src/pageComponents/common/PaymentTable.tsx
> +  showNameSearch?: nameType;
没法这样改，是否为adminData区分获取记录的api，
showNameSearch我想区分的是是否展示下拉框，以及展示账户搜索还是租户搜索，不传的话就没有所有框
![image](https://github.com/PKUHPC/SCOW/assets/74037789/446a35a4-5d8f-46db-af00-41a68be153b3)

2023-08-07 07:37 UTC, OYX-1 commented on apps/mis-web/src/pageComponents/common/PaymentTable.tsx
> +  adminData: boolean;
这个变量我改成了isPlatform

2023-08-07 07:38 UTC, OYX-1 commented on protos/server/charging.proto
> +  optional bool all_account = 5;
嗯嗯，这个API情况挺多的

2023-08-07 07:51 UTC, OYX-1 commented on apps/mis-web/src/pageComponents/common/PaymentTable.tsx
> +  showNameSearch?: nameType;
已改好

2023-08-07 11:19 UTC, ddadaal requested changes

2023-08-07 11:19 UTC, ddadaal commented on apps/mis-web/src/pageComponents/common/PaymentTable.tsx
> +  whichSelect?: SearchType;
searchType比较好

2023-08-07 11:19 UTC, ddadaal commented on apps/mis-web/src/pages/api/admin/finance/payments.ts
> +      { $case:"tenant", tenant:{ tenantName:tenantName as string } } :
这个as是必须的吗？

2023-08-07 11:19 UTC, ddadaal commented on apps/mis-web/src/pages/api/finance/payments.ts
> +      { $case:"accountOfTenant", accountOfTenant:{ tenantName:user.tenant, accountName:accountName as string } } :
这个as是必须的吗？

2023-08-07 11:19 UTC, ddadaal commented on apps/mis-web/src/pageComponents/common/PaymentTable.tsx
> +    name: accountName ?? undefined,
accountName本来就可以是undefined的，`?? undefined`没有必要吧

2023-08-07 11:45 UTC, OYX-1 commented on apps/mis-web/src/pages/api/admin/finance/payments.ts
> +      { $case:"tenant", tenant:{ tenantName:tenantName as string } } :
不是，emmm好像是当时写代码时TS给我画红色波浪线

2023-08-07 11:50 UTC, OYX-1 commented on apps/mis-web/src/pageComponents/common/PaymentTable.tsx
> +    name: accountName ?? undefined,
已改好

2023-08-07 12:06 UTC, ddadaal approved these changes

2023-08-07 13:25 UTC, ddadaal requested changes
再看看isPlatform这个地方

2023-08-07 13:37 UTC, ddadaal commented on apps/mis-web/src/pageComponents/common/PaymentTable.tsx
> +  showNameSearch?: nameType;
我再次确认了一下这个PaymentTable的prop的所有取值方式，有如下几种：

| 查询目标 | `isPlatform` | `searchType` |
| -- | -- | -- |
| 账户管理员查询查询自己账户的 | `undefined` | `undefined` |
| 平台管理员查询所有租户的 | `true` | `tenant` | 
| 租户管理员查询租户本身 | `undefined` | `undefined` | 
| 租户管理员查询租户账户 | `undefined` | `account` | 

两个二者都是`undefined`的可以不考虑，那么可以确定`isPlatform`和`searchType`这两个选项实际上并没有组合关系，`isPlatform`为`true`时`searchType`一定是tenant，反之也是。那为什么还要设计两个属性？

从另一个角度看，这个组件需要支持那四种情况的查询，所以你可以仿照proto里这个API的设计，直接把这四个组件列举出来，这样如何使用这个组件会清晰很多。比如:

```
type SearchType =
  // 搜索某个账户
  | { type: "account"; accountName: string }
  // 搜索自己租户
  | { type: "ownTenant"; }
  // 搜索所有租户
  | { type: "allTenants" }
  // 搜索租户下的账户
  | { type: "accountOfOwnTenant", accountName: string }
```

2023-08-08 02:14 UTC, OYX-1 commented
> 再看看isPlatform这个地方

已删除

2023-08-08 14:36 UTC, ddadaal approved these changes

2023-08-11 07:36 UTC, lyl-available approved these changes

2023-08-11 11:59 UTC, merged