feat(auth): 新增 auth 可配置项
PKUHPC/SCOW pull request #808
Opened 2023-08-16 07:47 UTC by Miracle575

新增 auth 登录界面可配置项
1. 左下角Powered by SCOW中，SCOW增加跳转github链接：[https://github.com/PKUHPC/SCOW；](https://github.com/PKUHPC/SCOW%EF%BC%9B)
2. 左上角scow logo图片和跳转链接可配置，链接为空时不跳转；
3. 登录按钮颜色跟随主题色；
4. 页面的默认底色调整为#8C8C8C；
5. 缩放浏览器页面时，如果窗口过小导致无法显示全部内容时，将右侧的文字信息隐藏掉；
6. 登陆页面的所有可配置操作整理成文档添加到文档网站中配置章节https://icode.pku.edu.cn/SCOW/

2023-08-16 11:40 UTC, ddadaal requested changes

2023-08-16 11:40 UTC, ddadaal commented on dev/vagrant/config/auth.yml
> +  url: ldap://172.16.20.125
这个配置是vagrant开发集群下的配置，为什么要改？这个IP是什么地址

2023-08-16 11:40 UTC, ddadaal commented on apps/auth/src/config/auth.ts
> +    customLogoLink: Type.String({ description: "用户自定义点击 logo 跳转链接", default: "" }),
不要特殊处理空字符串！一个配置不设置（为undefined），和一个配置的值为空字符串，是两码事。这里的意思是用户可以不设置LOGO图片吧？如果用户可以不配置这两项，就把这两个配置设置为Optional。

2023-08-16 11:42 UTC, ddadaal requested changes

2023-08-16 11:42 UTC, ddadaal commented on apps/auth/src/config/auth.ts
> +  }),
logo配置是必须有的吗？应该有很多用户懒得配Logo相关的吧。增加Type.Optional或者设置默认值

2023-08-16 12:06 UTC, Miracle575 commented on apps/auth/src/config/auth.ts
> +    customLogoLink: Type.String({ description: "用户自定义点击 logo 跳转链接", default: "" }),
已改

2023-08-16 12:06 UTC, Miracle575 commented on apps/auth/src/config/auth.ts
> +  }),
已改

2023-08-16 14:32 UTC, ddadaal requested changes

2023-08-17 13:47 UTC, ddadaal requested changes

2023-08-17 13:47 UTC, ddadaal commented on apps/auth/src/config/auth.ts
> +export enum scowLogoType {
enum名字要Pascal，`ScowLogoType`

2023-08-17 14:00 UTC, ddadaal commented
功能可以先测了

2023-08-18 08:15 UTC, lyl-available commented
![image](https://github.com/PKUHPC/SCOW/assets/125553919/7c828607-9a6c-49e3-81a6-c99447458180)
默认的背景色没有变

2023-08-18 09:30 UTC, lyl-available approved these changes

2023-08-18 11:07 UTC, ddadaal approved these changes

2023-08-18 11:07 UTC, merged