fix(web): 用户、账户、作业称呼统一
PKUHPC/SCOW pull request #819
Opened 2023-08-21 12:26 UTC by OYX-1

## 统一展示用户和作业称呼
![image](https://github.com/PKUHPC/SCOW/assets/74037789/85890ae4-9c03-484a-beea-384a6f6f5a27)
![image](https://github.com/PKUHPC/SCOW/assets/74037789/02d4fb97-e888-4a28-8c32-240c4d8af328)
![image](https://github.com/PKUHPC/SCOW/assets/74037789/f91a8827-e515-4419-ab35-3609cd6d496e)

2023-08-22 13:03 UTC, ddadaal requested changes
称呼 -> 显示方式和名称

2023-08-22 13:03 UTC, ddadaal commented on apps/mis-web/src/pageComponents/accounts/AccountTable.tsx
> +          render={(_, r) => `${r.ownerName}（ID:${r.ownerId}）`}
ID:后面加空格

2023-08-22 13:03 UTC, ddadaal commented on apps/mis-web/src/pageComponents/accounts/AccountTable.tsx
> +          render={(_, r) => `${r.ownerName}（ID:${r.ownerId}）`}
要统一就统一完全，有的地方显示的是小写的`id: `，也改成大写的`ID: `

2023-08-23 02:27 UTC, OYX-1 commented on apps/mis-web/src/pageComponents/accounts/AccountTable.tsx
> +          render={(_, r) => `${r.ownerName}（ID:${r.ownerId}）`}
已修改

2023-08-23 10:11 UTC, ddadaal approved these changes

2023-08-23 10:11 UTC, merged