fix(mis-web): 修复账户添加用户提示语
PKUHPC/SCOW pull request #822
Opened 2023-08-22 06:24 UTC by OYX-1

## 之前：账户添加不属于本租户的用户时，页面提示为：
![image](https://github.com/PKUHPC/SCOW/assets/74037789/e7926ae9-e225-4e18-95d1-330e6cc8addd)
## 现在：
![image](https://github.com/PKUHPC/SCOW/assets/74037789/277c5531-5b5b-4082-ac0a-b7dd81d95d92)

2023-08-22 13:07 UTC, ddadaal requested changes

2023-08-22 13:07 UTC, ddadaal commented on apps/mis-web/src/pages/api/users/addToAccount.ts
> +        console.log("e", e.details);
去掉console.llog

2023-08-22 13:07 UTC, ddadaal commented on apps/mis-web/src/pages/api/users/addToAccount.ts
> +          return { 404: { code: "USER_ALREADY_EXIST_IN_OTHER_TENANT" as const } };
这个有可能是用户根本不存在，而不是存在在其他租户下，错误提示应该写得完整一点，”用户不存在或者已经属于其他租户“。另外，这种只是用来显示的错误，就不要在HTTP API层再处理一次了，把grpc api返回的code直接给前端来处理如何显示就行。

2023-08-23 02:01 UTC, OYX-1 commented on apps/mis-web/src/pages/api/users/addToAccount.ts
> +          return { 404: { code: "USER_ALREADY_EXIST_IN_OTHER_TENANT" as const } };
1.用户根本不存在的问题在账户添加用户请求之前就检查了：
![image](https://github.com/PKUHPC/SCOW/assets/74037789/968ded4c-c9d0-4ee5-ae85-4864898e02d0)
2.grpc api返回的code直接给前端来处理
grpc的code都一样，都是Status.NOT_FOUND
![image](https://github.com/PKUHPC/SCOW/assets/74037789/2e4e52f3-8323-4328-8c11-fd2797534431)
现在用details来区分Status.NOT_FOUND
![image](https://github.com/PKUHPC/SCOW/assets/74037789/505d9739-65d0-41f4-a14e-5777e565d1fc)
HTTP API

2023-08-23 11:49 UTC, ddadaal approved these changes

2023-08-23 11:49 UTC, ddadaal commented
解决一下冲突

2023-08-24 01:56 UTC, OYX-1 commented
> 解决一下冲突

OK了

2023-08-26 01:06 UTC, merged