feat(mis): 新增数据统计功能
PKUHPC/SCOW pull request #825
Opened 2023-08-24 08:14 UTC by ZihanChen821

// TODO

2023-11-12 01:55 UTC, ddadaal requested changes

2023-11-12 01:55 UTC, ddadaal commented on apps/mis-server/src/services/charging.ts
> +      const queryKey = `{get_top_charge_account:${startTime}:${endTime}:${topRank}`;
第一个{字符是专门这么设计的吗？

2023-11-12 01:55 UTC, ddadaal commented on apps/mis-server/src/tasks/clearQueryCache.ts
> +}
这个函数可以放在cachePlugin里，因为这个函数的功能是和cachePlugin有关的。相关的功能的代码尽量放在附近

2023-11-12 01:55 UTC, ddadaal commented on apps/mis-server/src/utils/cache.ts
> +  queryKey: string,
如果query有固定格式`key1:key2:key3"，那么把各个key组成固定的格式的职责由这个函数负责，或者定义一个负责生成query key的函数，然后这个函数调用。也就是说，这个函数的调用者只传string[]，具体如何把string[]解析为queryKey，调用者不关心。

2023-11-12 01:55 UTC, ddadaal commented on apps/mis-web/src/pageComponents/admin/StatisticCard.tsx
> +export default StatisticCard;
尽量不要用export default。export const StatisticCard就好

2023-11-12 01:55 UTC, ddadaal commented on apps/mis-web/src/pages/api/admin/getActiveUserCount.ts
> +     */
现在comment没有用了。之前因为schema是通过解析源代码生成的，comment也会读取。现在API都是运行时生成的，comment没有用了

2023-11-12 01:55 UTC, ddadaal commented on protos/server/job.proto
> +  optional uint32 top_rank = 3;
top_rank是指什么？top几？加个注释

2023-11-13 01:45 UTC, ZihanChen821 commented on apps/mis-server/src/services/charging.ts
> +      const queryKey = `{get_top_charge_account:${startTime}:${endTime}:${topRank}`;
属于笔误了，已删

2023-11-13 13:51 UTC, ddadaal approved these changes

2023-12-13 07:05 UTC, lyl-available commented
接口报错了
![image](https://github.com/PKUHPC/SCOW/assets/125553919/2c452450-e4b6-4a9a-86cb-e3a0daac01f2)
![image](https://github.com/PKUHPC/SCOW/assets/125553919/7abb0345-1bcb-4edf-9067-8320e8944a98)

2023-12-13 08:51 UTC, lyl-available commented
12月5日至12月13日，共创建用户7个
![image](https://github.com/PKUHPC/SCOW/assets/125553919/2edb2380-ebef-4d8a-a701-d687c3d047e6)
面板显示只有6个用户
![image](https://github.com/PKUHPC/SCOW/assets/125553919/ffd16d94-4a6d-4f31-9bd8-1567e225d0ba)
5号新创建的用户被计算到了4号
![image](https://github.com/PKUHPC/SCOW/assets/125553919/041b73da-a0c6-4831-aba5-962629d50d8a)

2023-12-20 03:56 UTC, lyl-available commented
![image](https://github.com/PKUHPC/SCOW/assets/125553919/ff988097-4731-4899-8647-095d0e488958)
活跃用户数计算的是所有用户操作频率

2023-12-21 06:10 UTC, lyl-available approved these changes

2023-12-25 13:04 UTC, ddadaal approved these changes

2023-12-25 13:12 UTC, ddadaal approved these changes

2023-12-25 13:12 UTC, merged