feat(web): react-typed-i18n国际化实现测试
PKUHPC/SCOW pull request #833
Opened 2023-08-30 10:21 UTC by piccaSun

2023-09-04 13:39 UTC, ddadaal requested changes

2023-09-04 13:39 UTC, ddadaal commented on apps/mis-web/src/utils/useI18nTranslateToString.ts
> +export default useI18nTranslateToString;
目前JS生态的共识是尽量少用export default，直接`export function useI18nTranslateToString()`就好

2023-09-04 13:39 UTC, ddadaal commented on apps/mis-web/src/utils/useI18nTranslateToString.ts
> +export default useI18nTranslateToString;
这两个函数可以直接写在src/i18n/index.ts里

2023-09-11 11:16 UTC, piccaSun commented
@ddadaal  

1[移动翻译函数至i18n/index.ts](https://github.com/PKUHPC/SCOW/pull/833/commits/a2a1a6210c045dc4a0daba9467d83803f4537d4d)中对之前的review意见做出了修改

2[从Cookies或header中获取语言id](https://github.com/PKUHPC/SCOW/pull/833/commits/eb77910e115d280b042a4bce26e04ddc8e5edb35)
变更了系统启动时从cookie中获取语言id，如果cookie语言不存在或违法从accept-header中获取

2[自定义配置文件中的国际化文本示例](https://github.com/PKUHPC/SCOW/pull/833/commits/987f4872eb0cf6c0ef3b908718b5d9f8610a3a39)
更改可自定义配置语言文本类型由string变更为string | i18nType
原则上不影响原有runtimePublic中的配置项
```

     # publicRuntimeConfig： 
    // 兼容原有系统的字符串形式的配置项
    PASSWORD_PATTERN_MESSAGE: typeof commonConfig.passwordPattern?.errorMessage === "string"
      ? commonConfig.passwordPattern?.errorMessage : commonConfig.passwordPattern?.errorMessage.i18n.default,
    #  在publicRuntimeConfig下新增  
      CUSTOM_I18N_CONFIG: {
      // 只记录i18n类型的配置项
      COMMON_PASSWORD_PATTERN_MESSAGE: typeof commonConfig.passwordPattern?.errorMessage === "string"
        ? undefined : commonConfig.passwordPattern?.errorMessage,
    },
```
页面调用时，如果碰到原有字符串判定逻辑仍然使用publicConfig.PASSWORD_PATTERN_MESSAGE
在显示文字时通过checkI18nValue()函数新增显示判定
页面显示时需useEffect监听当前国际化语言id的变化

以上的问题请确认

关于第三点，目前placeholder里面的显示只是最简单基础的一项，common.yaml文件中也要求必须配置
比如说有一些需要如没有配置就显示默认值的情况，Type.Union下试了一下不太好实现
实际上配置项的情况各种各样，感觉让原有配置项兼容string | i18nType的形式不如再增加一个只有i18n类型的配置项实现起来逻辑更简单？
另外第三点的页面渲染问题，每个页面都要useEffect追加监听也略显繁琐，这是我理解错了吗有更简单明了的实现办法嘛？

2023-09-11 11:42 UTC, ddadaal requested changes

2023-09-11 11:42 UTC, ddadaal commented on libs/web/src/utils/getLanguageCookie.ts
> +    return cookies.language;
检查cookie中的language值是否合法

2023-09-11 11:42 UTC, ddadaal commented on libs/web/src/utils/getLanguageCookie.ts
> +    return cookies.language;
整个流程是，先从cookie或者header中获取已经有的值，然后检查获取到的值是否合法

2023-09-11 11:42 UTC, ddadaal commented on libs/config/src/common.ts
> +    ]),
目前应该所有可以配置国际化的名字的配置项都是`(string | { i18n: { cn: string ...} }}`这个类型，所以可以定义一处然后所有地方都用

2023-09-11 11:42 UTC, ddadaal commented on libs/config/src/type.ts
> +}
为何要单独定义？下面代码有问题吗？

```ts
const I18nStringSchema = Type.Union([
    Type.String({ }),
    Type.Object({ i18n: Type.Object({ default: Type.String(), ... } })
]);
```

2023-09-11 11:42 UTC, ddadaal commented on libs/web/src/utils/getLanguageCookie.ts
> +    return cookies.language;
把默认语言、可以接受的语言全部定义为常量（数组常量），这样以后修改起来方便一些

2023-09-12 14:33 UTC, ddadaal commented
(4) 可以使用类型系统更精确地确定返回值：
```ts
  RUNTIME_I18N_CONFIG_TEXTS: {
    passwordPatternMessage: I18nStringType | undefined,
    test: I18nStringType;
  }


export const getRuntimeI18nConfigText = <TKey extends RuntimeI18nConfigKeys>(
  languageId: string, key: TKey,
): ((typeof publicConfig.RUNTIME_I18N_CONFIG_TEXTS)[TKey]) extends (I18nStringType)
  ? (string) : string | undefined => {

  const i18nConfigText = publicConfig.RUNTIME_I18N_CONFIG_TEXTS[key];

  if (!i18nConfigText) {
    return undefined as any;
  }

  return getI18nConfigCurrentText(i18nConfigText, languageId);
};

const a = getRuntimeI18nConfigText("zh-CN", "passwordPatternMessage"); // string | undefined
const b = getRuntimeI18nConfigText("zh-CN", "test"); // string

```

2023-09-14 13:19 UTC, piccaSun commented
@ddadaal 
[cluster, app等配置文件国际化处理](https://github.com/PKUHPC/SCOW/pull/833/commits/2af38688dbee608c13e37d484ca67751feaa0f78)
[登录页面i18n](https://github.com/PKUHPC/SCOW/pull/833/commits/a1254f8d25b1e966725d0fca7f30aa30b68a3306)
涉及到具体实施方案和逻辑处理的地方麻烦确认

2023-09-15 10:20 UTC, lyl-available commented
![image](https://github.com/PKUHPC/SCOW/assets/125553919/877348db-de37-44cc-84d5-15964f5fb729)
漏了一项

2023-09-15 10:35 UTC, lyl-available commented
管理系统-未结束作业，门户-桌面页面打开后会自动登出

2023-09-15 10:38 UTC, lyl-available commented
![image](https://github.com/PKUHPC/SCOW/assets/125553919/88d2ddd2-7ddd-48a4-b885-29edf78ce2b3)
账户列表这部分区域切换成英文后会不停闪动

2023-09-15 13:36 UTC, piccaSun commented
> 管理系统-未结束及结束作业列表，门户-桌面，门户-作业列表，管理系统-导入用户等页面打开后会自动退出登录

最新分支本地没有复现这个问题，之后在部署环境下再确认

2023-09-16 02:05 UTC, ddadaal requested changes

2023-09-16 02:05 UTC, ddadaal commented on apps/auth/src/utils/loginI18nTexts.ts
> +};
为了之后的添加语言以及文本的扩展性，auth也参考web的做法，专门创建一个i18n目录，每个语言一个文件，之后在index.js建立一个语言到语言文本的字典。

2023-09-16 02:05 UTC, ddadaal commented on libs/web/src/utils/libWebI18nTexts.ts
> +export const libWebZhCn = {
和auth一样的，参考lib-web组织目录结构

2023-09-16 02:05 UTC, ddadaal commented on libs/web/src/utils/i18n.ts
> +      return i18nConfigText.i18n.default;
这样就不用switch case判断语言了，方便增加语言

2023-09-16 06:52 UTC, piccaSun commented
@ddadaal  
不好意思，操作日志部分还是跟别的地方国际化有一些不一样[管理系统操作日志显示国际化](https://github.com/PKUHPC/SCOW/pull/833/commits/bfcf5336017315cd5c399291f63b3f7da0c30ca8)，麻烦审核
有一个问题是getOperationDetail是在web端api-schema中完成的，这个地方需要读一次operationEvent才能在前端使用t函数，这个类型实在有点复杂，所以用了Type.Any()，api-response也用了一次断言
麻烦看一下这里可以更好的处理一下嘛？

2023-09-16 08:53 UTC, lyl-available commented
![image](https://github.com/PKUHPC/SCOW/assets/125553919/12741d20-b7c1-483b-951c-6c880c150237)
zhang账户消费记录部分字段未翻译

2023-09-16 09:04 UTC, lyl-available commented
创建用户，2次密码输入不一致的error没了，前面confirm password有部分被遮挡
![image](https://github.com/PKUHPC/SCOW/assets/125553919/3989725f-2f05-4543-898e-528a072c784a)

2023-09-16 11:47 UTC, ddadaal requested changes

2023-09-16 11:47 UTC, ddadaal commented on apps/mis-web/src/models/operationLog.ts
> +  operationEvent: Type.Optional(Type.Any()),
可以使用unsafe定义这个类型：https://github.com/sinclairzx81/typebox#unsafe-types

```ts
export const TypeA = Type.Object({
  a: Type.Unsafe<{ b: string }>(),
});

let a: Static<typeof TypeA>;

a.a.b // string

```

我看了下，整个OperationLog实际上不会在运行时被调用。这个对象本身（非其类型）只在GetOperationLogsSchema中作为response的类型被使用，但是实际上运行时不会检查响应的类型。所以可以使用Unsafe的方法直接定义这个Schema的200的返回值类型：`200: Type.Unsafe<{ 实际上的类型 }>();` ，然后删除OperationLog，直接用ts定义OperationLog类型即可。操作日志相关的类型可以从`@scow/protos/build/audit/operation_log`中获取

2023-09-17 08:32 UTC, piccaSun commented
操作日志暂时不做修改的话，其他部分已修改，麻烦审核 @ddadaal 
@piccaSun
[整理auth和libWeb文本到cn和en](https://github.com/PKUHPC/SCOW/pull/833/commits/2fd27581021d61525a4ae464846cf16e931cce89)
[直接返回翻译函数](https://github.com/PKUHPC/SCOW/pull/833/commits/e2ade554be4e7fe9bb8251fb2fe875160935b440)

2023-09-17 09:56 UTC, lyl-available commented
管理系统-已完成作业详情中，集群名展示的是中文配置
![image](https://github.com/PKUHPC/SCOW/assets/125553919/4ff9002f-cf7a-465e-8944-186a4bc7522d)
管理系统-未完成作业列表，点击详情，页面500
![image](https://github.com/PKUHPC/SCOW/assets/125553919/b6c78c78-78aa-4258-abb4-8a491097882c)

2023-09-17 11:46 UTC, piccaSun commented
@lyl-available 
结束作业详情页和未结束作业详情页的集群名的国际化配置遗漏
解说详情集群没有按照语言id去读取对应文本，已修复
未结束作业中集群名由于类型的变化导致react渲染页面出错，已修复
辛苦！请确认！

2023-09-17 14:22 UTC, ddadaal requested changes

2023-09-17 14:22 UTC, ddadaal commented on apps/mis-web/src/utils/config.ts
> +  return getI18nConfigCurrentText(i18nConfigText, languageId);
用getI18nText实现这个函数

2023-09-17 14:22 UTC, ddadaal commented on apps/mis-web/src/utils/config.ts
> +  return getI18nConfigCurrentText(i18nConfigText, languageId);
用getI18nText实现这个函数

2023-09-17 14:24 UTC, ddadaal requested changes

2023-09-17 14:24 UTC, ddadaal commented on libs/web/src/utils/i18n.ts
> +      return i18nConfigText.i18n.default;
继续：不要用switch case判断语言

2023-09-17 14:55 UTC, piccaSun commented on apps/mis-web/src/utils/config.ts
> +  return getI18nConfigCurrentText(i18nConfigText, languageId);
> 用getI18nText实现这个函数

用getI18nText实现时没法像getRuntimeI18nConfigText和getSeverI18nConfigText去有效的校验Key
所以现在其实没使用到getI18nText
当出现多层嵌套的对象时，也是先获取对象直接去使用了getI18nConfigCurrentText
是说都用泛用性的getI18nText不严格校验参数的Key值了吗？

2023-09-18 07:06 UTC, lyl-available commented
1、选中集群后切换语言，已选中的标签未翻译
![image](https://github.com/PKUHPC/SCOW/assets/125553919/32b678b0-389f-4231-8d5d-3841b43fa3e0)
2、模式切换未翻译
![image](https://github.com/PKUHPC/SCOW/assets/125553919/39d60ac3-893d-41e0-96f5-bce6a30f134b)
3、切换语言时，集群信息部分未翻译，需刷新后才显示正常
![image](https://github.com/PKUHPC/SCOW/assets/125553919/a8a185ca-10c1-4213-8447-3c80110856f3)

2023-09-18 10:31 UTC, piccaSun commented
@lyl-available 
上述问题已修改，请确认
另外主题模式语言，管理系统可见分区上方截图集群名称没有显示的bug一同修改了，请确认

2023-09-18 12:35 UTC, ddadaal commented on apps/mis-web/src/utils/config.ts
> +  return getI18nConfigCurrentText(i18nConfigText, languageId);
这三个函数逻辑实际上是一样的，而getI18nText是最通用的函数，另外两个是getI18nText的当object是RUNTIME_I18N_CONFIG_TEXTS或者SERVER_I18N_CONFIG_TEXTS的特例，所以可以用getI18nText实现这两个函数。如下：
```ts
export const getRuntimeI18nConfigText2 = <TKey extends RuntimeI18nConfigKeys>(
  key: TKey,
  languageId: string,
) => {
  return getI18nText(publicConfig.RUNTIME_I18N_CONFIG_TEXTS, key, languageId);
};

export const getServerI18nConfigText2 = <TKey extends ServerI18nConfigKeys>(
  key: TKey,
  languageId: string,
) => {
  return getI18nText(runtimeConfig.SERVER_I18N_CONFIG_TEXTS, key, languageId);
};


```

2023-09-18 13:35 UTC, piccaSun commented on apps/mis-web/src/utils/config.ts
> +  return getI18nConfigCurrentText(i18nConfigText, languageId);
好的，我以为是不再单独分getRuntimeI18nConfigText和getServerI18nConfigText2直接都用getI18nText来实现，那我修改一下

2023-09-18 14:07 UTC, piccaSun commented
@ddadaal 
已修改使用通用的getI18nText函数，请确认

2023-09-19 06:17 UTC, lyl-available commented
图片验证码及opt验证配置为true时，登录页面显示异常
![image](https://github.com/PKUHPC/SCOW/assets/125553919/a5d4c73b-a0a8-436f-bb7a-9f40d31f26d7)

2023-09-25 12:27 UTC, ddadaal requested changes
在apps/cli/assets/config下的配置文件示例中，在每个支持国际化文本的配置项上加注释“此文本支持国际化”，如下：

```yaml
# 主页标题
homeTitle:
  # 默认文本
  # 此文本支持国际化
  defaultText: "Super Computing on Web"
```

2023-09-25 12:27 UTC, ddadaal commented on apps/auth/package.json
> +    "react-typed-i18n": "^2.3.0"
不要^，SCOW的package.json中的依赖版本都确定为具体的版本

2023-09-25 13:37 UTC, piccaSun commented
@ddadaal  上述意见已修改，请确认~

2023-09-25 15:55 UTC, ddadaal approved these changes

2023-09-25 15:55 UTC, merged