feat(mis): 管理员查看账户消费记录
PKUHPC/SCOW pull request #839
Opened 2023-09-05 10:02 UTC by piccaSun

// TODO  filter

2023-09-07 14:43 UTC, ddadaal requested changes

2023-09-07 14:43 UTC, ddadaal commented on apps/mis-server/src/services/charging.ts
> +      let searchParam = {};
这个变量可以定义类型，看看em.find的第一个参数类型是什么

2023-09-07 14:43 UTC, ddadaal commented on protos/server/charging.proto
> +}
这几个message单独存在意义不大，但是由于有两个Request都要用，应该放在外面，所以可以给这几个message价格后缀`Target`，表明这几个message是什么意思。

2023-09-07 15:55 UTC, piccaSun commented
@ddadaal  上述问题已修改，请确认

2023-09-10 08:44 UTC, ddadaal approved these changes

2023-09-11 08:10 UTC, lyl-available commented
![image](https://github.com/PKUHPC/SCOW/assets/125553919/5719ff80-ad1f-441e-8338-1479140557cd)
按账户搜索不起作用

2023-09-12 02:40 UTC, lyl-available commented
租户管理搜索其他账户记录的时候会返回403
![image](https://github.com/PKUHPC/SCOW/assets/125553919/afbfa012-c9d1-4f46-a6ad-91d89eab8cc0)

2023-09-12 03:43 UTC, piccaSun commented
修复账户搜索
修复权限问题, 原来漏掉了开放账户查询的权限给租户及平台的权限
上述问题已修改，请确认 @lyl-available

2023-09-12 07:10 UTC, lyl-available commented
选择账户，返回该账户的消费记录
![image](https://github.com/PKUHPC/SCOW/assets/125553919/a1630c6b-ca38-4513-beb4-95cde5c6bb4f)
点击搜索，返回的还是全部数据
![image](https://github.com/PKUHPC/SCOW/assets/125553919/a131e35f-e9f2-43be-8c3c-dc693fabda46)

2023-09-13 09:09 UTC, piccaSun commented
账户消费列表按类型进行过滤时，也需要同时获取新的总数和金额合计
现在修改api增加类型查询参数，类型也通过后端进行查询
这个新增逻辑请确认
@lyl-available  @ddadaal

2023-09-13 13:49 UTC, ddadaal requested changes

2023-09-13 13:49 UTC, ddadaal commented on apps/mis-server/tests/charging/charging.test.ts
> +it("returns charge records", async () => {
这几种测试用例之间没什么关系，拆成多个测试用例比较好

2023-09-13 14:35 UTC, ddadaal commented
@lyl-available 可以测功能

2023-09-14 02:57 UTC, lyl-available commented
当请求时间为13号到13号时，应该筛选的是13号当天的记录，目前开始和结束时间都是一样的
![image](https://github.com/PKUHPC/SCOW/assets/125553919/852a2515-5b4c-43cf-be05-6c2c889c215e)

2023-09-14 06:24 UTC, piccaSun commented
时间指定搜索时没有精确指定日期的起始时间，已修改，请确认 @lyl-available

2023-09-14 08:06 UTC, lyl-available commented
当用户有多个账户时，点击不同账户的消费记录，返回的均为第一个账户的数据，需再次点击搜索才返回正常
![image](https://github.com/PKUHPC/SCOW/assets/125553919/00e7c798-b428-4c5f-b3f2-b6f05df6e0d1)

2023-09-14 09:13 UTC, piccaSun commented
充值列表和消费列表在账户管理下切换账户名是setQuery变量名错误，已修改，请确认 @lyl-available

2023-09-14 09:44 UTC, lyl-available approved these changes

2023-09-14 13:17 UTC, piccaSun commented on apps/mis-server/tests/charging/charging.test.ts
> +it("returns charge records", async () => {
已拆分修改请确认 @ddadaal

2023-09-14 13:18 UTC, piccaSun commented on apps/mis-server/src/services/charging.ts
> +      ];
@ddadaal  因为不单独判断会提示不可迭代，所以写成了 ...(misConfig.customChargeTypes || [])的形式，请确认

2023-09-14 13:52 UTC, ddadaal approved these changes

2023-09-14 13:52 UTC, merged