fix(auth): auth登录成功后，重定向回mis和portal时加上一个登录标记
PKUHPC/SCOW pull request #850
Opened 2023-09-11 03:04 UTC by ZihanChen821

//TODO

2023-09-11 09:57 UTC, ddadaal commented
可以用referer header来判断来源吗？

2023-09-12 02:42 UTC, ZihanChen821 commented
> 可以用referer header来判断来源吗？

![image](https://github.com/PKUHPC/SCOW/assets/130351655/8d5fb4b1-5c3e-4888-a39d-d2f8c9682644)
是可以的

2023-09-12 12:56 UTC, ddadaal requested changes

2023-09-12 12:56 UTC, ddadaal commented on apps/portal-web/src/pages/api/auth/callback.ts
> +  const isFromLogin = req.headers?.referer?.indexOf(runtimeConfig.AUTH_EXTERNAL_URL + "/public/auth") !== -1;
判断是否存在用includes

2023-09-13 13:42 UTC, ddadaal approved these changes

2023-09-13 13:42 UTC, merged