fix(lib-operation-log): 修改作业时限操作日志内容展示修复及创建操作日志错误捕获 bug 修复
PKUHPC/SCOW pull request #852
Opened 2023-09-12 06:40 UTC by ZihanChen821

2023-09-12 12:58 UTC, ddadaal requested changes

2023-09-12 12:58 UTC, ddadaal commented on apps/mis-web/src/models/operationLog.ts
> +      return `设置作业(ID: ${logPayload.jobId})时限 ${Math.abs(logPayload.limitMinutes)} 分钟`;
这里出现了这个问题，是因为这里logPayload的类型没有推断出来吗？

2023-09-13 01:44 UTC, ZihanChen821 commented on apps/mis-web/src/models/operationLog.ts
> +      return `设置作业(ID: ${logPayload.jobId})时限 ${Math.abs(logPayload.limitMinutes)} 分钟`;
是的， 这里修改了下， 先不取logPayload, 在每个case里获取该对象就有类型推断了

2023-09-13 13:42 UTC, ddadaal approved these changes

2023-09-13 13:42 UTC, merged