feat(portal-web): 门户系统登录节点连接shell时url参数不显示登录节点名称只显示登录节点地址
PKUHPC/SCOW pull request #867
Opened 2023-09-20 02:14 UTC by piccaSun

2023-09-20 10:50 UTC, ddadaal requested changes
读取集群配置时需要检查是否每个登录节点节点地址均不相同。在libs/config/src/cluster.ts的getClusterConfigs中进行这个检查

2023-09-20 11:05 UTC, piccaSun commented
> 读取集群配置时需要检查是否每个登录节点节点地址均不相同。在libs/config/src/cluster.ts的getClusterConfigs中进行这个检查

这个之前用name做判断的时候也没有检查过。。
一直是对相同的name和address没有特殊限定
要在这加上这个逻辑吗？

2023-09-21 15:25 UTC, ddadaal requested changes
文档（https://pkuhpc.github.io/SCOW/docs/deploy/config/cluster-config）里提示用户所有集群的所有登录节点地址均应该不相同

2023-09-21 15:25 UTC, ddadaal commented on libs/config/src/cluster.ts
> +      throw new Error("loginNodes must NOT have duplicate addresses");
提示说清楚，是所有集群的登录地址均不能相同。`login node address must be unique across all clusters and all login nodes."

2023-09-22 04:47 UTC, piccaSun commented
> 文档（[https://pkuhpc.github.io/SCOW/docs/deploy/config/cluster-config）里提示用户所有集群的所有登录节点地址均应该不相同](https://pkuhpc.github.io/SCOW/docs/deploy/config/cluster-config%EF%BC%89%E9%87%8C%E6%8F%90%E7%A4%BA%E7%94%A8%E6%88%B7%E6%89%80%E6%9C%89%E9%9B%86%E7%BE%A4%E7%9A%84%E6%89%80%E6%9C%89%E7%99%BB%E5%BD%95%E8%8A%82%E7%82%B9%E5%9C%B0%E5%9D%80%E5%9D%87%E5%BA%94%E8%AF%A5%E4%B8%8D%E7%9B%B8%E5%90%8C)

已追加并修改提示语言，请确认 @ddadaal

2023-09-22 12:57 UTC, ddadaal approved these changes

2023-09-22 12:57 UTC, merged