实现跨集群传输模块
PKUHPC/SCOW pull request #872
Opened 2023-09-22 06:00 UTC by tulvgengenr

test

2023-09-23 12:56 UTC, ddadaal requested changes

2023-09-23 12:56 UTC, ddadaal commented on docs/docs/deploy/config/portal/transfer-cross-clusters.md
> +crossClusterFilesTransfer:
crossClusterFileTransfer

2023-09-23 12:56 UTC, ddadaal commented on libs/config/src/cluster.ts
> +  }),
整个选项有个空对象的default值或者是optional的，否则现有所有配置文件都会报错

2023-09-23 12:56 UTC, ddadaal commented on protos/portal/file.proto
> +message StartFilesTransferRequest {
所有文件传输的用词都修改为FileTransfer

2023-09-23 12:56 UTC, ddadaal commented on apps/portal-web/src/utils/file.ts
> +export const redirectToDashboard = (router) => {
类型NextRouter

2023-09-23 12:56 UTC, ddadaal commented on apps/portal-web/src/pages/files/fileTransfer.tsx
> +    redirectToDashboard(router);
按照react的规范，组件可能会被render多次，所以render函数本身应该是无副作用的。这里redirectToDashboard执行时会调用router.redirect产生副作用，不规范。如果一定跳转，查看Redirect组件的实现（ apps/mis-web/src/components/Redirect.tsx ）。这里可以渲染一个错误页面。

2023-09-23 12:56 UTC, ddadaal commented on apps/portal-web/src/pages/api/file/terminateFilesTransfer.ts
> +      code: Type.Literal("SCOW-SYNC-TERMINATE_CMD_FAILED"),
分割词组都用下划线

2023-09-23 12:56 UTC, ddadaal commented on apps/portal-web/src/pageComponents/filemanager/ClusterFileTable.tsx
> +          path={path ? path : ""}
path ?? ""

2023-09-25 12:13 UTC, ddadaal requested changes

2023-09-25 12:13 UTC, ddadaal commented on apps/portal-server/src/services/file.ts
> +      if (!keyConfiged) {
configed -> configured，别偷懒，单词打完，注意代码可读性

2023-09-25 15:55 UTC, ddadaal approved these changes

2023-09-25 16:49 UTC, tulvgengenr commented on apps/portal-server/src/services/file.ts
> +          await loggedExec(ssh, logger, true, genKeyCmd, []);
遇到了一个bug，希望在shell中执行的命令是" -N \"\" "，如果以array的形式传入{”-N“, "\"\""}，loggedExec函数会调用types的shell-quote库的quote方法，该方法会自动加上单引号，导致在shell中执行的命令为" -N '\"\"' "。解决方法只能在loggedExec中做特判，但是这很违背代码的封装，所以我将“-N \“\””添加到了传入的command中，该command不会被quote解析。
代码如下：
const genKeyArgs = [
  "-t", "rsa",
  "-b", "4096",
  "-C", "for scow-sync",
  "-f", privateKeyPath,
];
// eslint-disable-next-line quotes
const genKeyCmd = `ssh-keygen -N ""`;

2023-09-26 13:19 UTC, ddadaal commented on apps/portal-server/src/services/file.ts
> +          await loggedExec(ssh, logger, true, genKeyCmd, []);
可以

2023-10-16 08:14 UTC, lyl-available commented
![image](https://github.com/PKUHPC/SCOW/assets/125553919/31457200-f1e3-4edf-904b-2096844160d5)
两边的框框置顶对齐吧，这样看着不太好看

2023-10-16 08:20 UTC, lyl-available commented
点击目录会跳转到仪表盘
![image](https://github.com/PKUHPC/SCOW/assets/125553919/931ff992-9f95-4c78-a0bd-a653bde775c2)

2023-10-16 09:35 UTC, lyl-available commented
文件传输成功没有提示，当目标文件夹存在同名文件时传输不成功同样没有提示 @vanstriker @xuekai00 麻烦看下需不需要加一下

2023-10-17 03:24 UTC, lyl-available commented
已经传输过的文件被删除后就无法再次传输

2023-10-17 08:03 UTC, lyl-available commented
点击文件夹后，上方显示路径会一直叠加
![image](https://github.com/PKUHPC/SCOW/assets/125553919/82ad12e0-8237-4959-8dbc-dfa6073338e2)

2023-10-17 09:25 UTC, lyl-available commented
集群一传输节点配置为false后依然可以传输文件
![image](https://github.com/PKUHPC/SCOW/assets/125553919/bbfd96a2-3059-46de-ac8f-52cec2ca07f8)
![image](https://github.com/PKUHPC/SCOW/assets/125553919/d99635df-d38b-4cd9-969a-26015611e1b3)

2023-10-19 07:07 UTC, lyl-available commented
选中文件后，传输按钮生效
![image](https://github.com/PKUHPC/SCOW/assets/125553919/e55b847c-7ce7-477b-b7c2-b42e25ca8933)
另起一个页面，删除该选中的文件，传输按钮依然生效
![image](https://github.com/PKUHPC/SCOW/assets/125553919/2e29c9bf-250b-4e53-a4d6-9457c78b9216)

2023-10-19 07:34 UTC, lyl-available commented
文件夹访问未做权限控制
![image](https://github.com/PKUHPC/SCOW/assets/125553919/7932c8db-ab47-492e-a5fc-0e7c08dcb2ed)

2023-10-26 01:36 UTC, lyl-available approved these changes

2023-10-26 16:02 UTC, ddadaal approved these changes

2023-10-26 16:02 UTC, merged