feat(mis-web): 管理系统用户可见分区追加优化
PKUHPC/SCOW pull request #882
Opened 2023-10-08 08:43 UTC by piccaSun

2023-10-09 12:59 UTC, ddadaal approved these changes

2023-10-17 09:31 UTC, piccaSun commented
@ddadaal  此issue再次追加以下两个优化。麻烦再次审核一下变更的部分https://github.com/PKUHPC/SCOW/pull/882/commits/430e9d58223bbd58c9f38bbc6f40ebbee7ceea3e

1.集群下，用户可见分区查询报错时不展示错误，只展示正常可以使用的可见分区
2.有些用户的分区数量很大，在集群展示分区时增加集群分区表格的手动折叠功能，提取集群名进行折叠，表格内不再展示集群名，集群分区表格增加y轴最大显示范围800

显示效果如下
![可见集群分区](https://github.com/PKUHPC/SCOW/assets/43978285/28d9c81f-6a5a-4088-92a4-ae86bfa0439a)
![9400d52e-6587-4c55-bb1c-62e71ed2e60c](https://github.com/PKUHPC/SCOW/assets/43978285/fb51a15a-d2a1-4e73-9a37-3d6ba87d56c2)
![87ea6633-c0cd-446e-b3b4-9b0443f4c9e5](https://github.com/PKUHPC/SCOW/assets/43978285/f6d7df1f-c8da-4c5a-913e-643c8cf473b0)

2023-10-17 12:54 UTC, ddadaal requested changes

2023-10-17 12:54 UTC, ddadaal commented on protos/server/config.proto
>  }
这个API修改破坏了原来的这个接口，建议

1. 不修改原来的接口，而是新增一个GetAvailablePartitionsForCluster接口
2. 将原来的接口标记为deprecated，不推荐使用
    - 给rpc增加注释，说deprecate了，推荐使用另一个接口
    - 看看这个方法 https://stackoverflow.com/questions/43275832/how-to-mark-rpc-as-deprecated
4. 在下一个API的major版本中移除原来这个接口

2023-10-18 08:14 UTC, piccaSun commented on protos/server/config.proto
>  }
@ddadaal 
这个issue实际上前端也随着API的破坏性修改发生了重大的架构变化
请问这种情况前端对应不同API版本要遵循什么策略？
是否还要在当前版本根据调用不同的接口支持重定向到新旧两个前端？

2023-10-18 12:02 UTC, ddadaal commented on protos/server/config.proto
>  }
SCOW的前端后端可以认为都是一起升级的，前端可以直接对最新的API写就好。

2023-10-19 10:38 UTC, piccaSun commented on protos/server/config.proto
>  }
已修改请确认。
在已过时的message和api中加入deprecated。
修改后虽然build时候没有报出明显的Warning，generated中可以确认到变化
![image](https://github.com/PKUHPC/SCOW/assets/43978285/62a21b3d-ae64-4e01-b495-9ca8bde4924b)

2023-10-20 10:31 UTC, lyl-available approved these changes

2023-10-20 14:58 UTC, merged