impl
PKUHPC/SCOW pull request #891
Opened 2023-10-13 12:02 UTC by piccaSun

// TODO：确认OperationLog,适配器更新后联调

2023-10-19 12:54 UTC, ddadaal requested changes
这个功能可以不增加新的调度器接口，而完全由SCOW完全使用已有的调度器接口实现吗？

2023-10-19 12:54 UTC, ddadaal commented on .changeset/cold-moons-bathe.md
> +新增 submitFileAsJob 接口，连接 slurm 调度器，直接提交文件 sbatch 执行
修改说法，后端不一定是slurm调度器。改成“直接把文件作为作业提交调度器执行"

2023-10-19 12:54 UTC, ddadaal commented on .changeset/proud-seahorses-repeat.md
> +新增文件管理下提交任意文件直接作为作业文本 sbatch 执行的功能
注意说法，”直接作为作业文本提交调度器执行“

2023-10-19 12:54 UTC, ddadaal commented on libs/protos/scheduler-adapter/package.json
> +    "generate": "rimraf generated && buf generate --template buf.gen.yaml https://github.com/PKUHPC/scow-scheduler-adapter-interface.git#branch=add_job_submit_file_as_job_proto",
SCOW主线代码里不能出现这种使用调度器接口仓库的非master分支的情况。这个PR应该等新的调度器接口发布后才合并。

2023-10-19 16:30 UTC, piccaSun commented on libs/protos/scheduler-adapter/package.json
> +    "generate": "rimraf generated && buf generate --template buf.gen.yaml https://github.com/PKUHPC/scow-scheduler-adapter-interface.git#branch=add_job_submit_file_as_job_proto",
好的，这个是打算全部review、测试完没有问题再把scow-slurm-interface那边合并到主分支,然后再修改scow这边generate的调度器适配器仓库

2023-10-19 16:38 UTC, piccaSun commented
> 这个功能可以不增加新的调度器接口，而完全由SCOW完全使用已有的调度器接口实现吗？

因为原有调度器接口是在提交作业时，获得所有提交作业的参数，然后调度器自己执行类似下方的脚本拼接
```
	scriptString += "#SBATCH " + "-A " + in.Account + "\n"
	scriptString += "#SBATCH " + "--partition=" + in.Partition + "\n"
```
所以如果想使用旧的接口，需要scow逐句解析出任意文件的对应各个参数，跟杨老师一起商量了一下最后新增了调度器的接口

2023-10-19 16:46 UTC, piccaSun commented
changeset文字已修改，请确认 @ddadaal

2023-10-20 15:07 UTC, ddadaal commented
OK，那可以保留这个API。如果功能测试没有问题了，去接口的仓库提交PR，先把接口合并后再来合并这个。

2023-10-22 10:39 UTC, piccaSun commented
> OK，那可以保留这个API。如果功能测试没有问题了，去接口的仓库提交PR，先把接口合并后再来合并这个。

好的，那请 @lyl-available 先测试，我在测试的时候先更新一下测试用的调度器适配器

2023-10-25 10:41 UTC, lyl-available commented
测试通过

2023-10-26 09:26 UTC, piccaSun commented
修改提交成功后的返回值，使其包含提交成功的作业ID，文字与提交作业成功的显示文字保持一致
62集群下测试效果如下：
![image](https://github.com/PKUHPC/SCOW/assets/43978285/86890eec-5f3a-418c-ab7c-2f5d7bd6c91a)

2023-10-26 09:29 UTC, lyl-available approved these changes

2023-10-26 09:50 UTC, piccaSun commented
@ddadaal 
功能测试已结束，调度器适配器接口已通过pr合并到主分支，已经修改回scow下面的调度器适配器接口仓库地址为主分支地址。
但是slurm调度器这边忘了通知杨老师，调度器还没有将这个新增接口合并到调度器的主分支。

2023-11-03 09:22 UTC, piccaSun commented
调度器适配器接口修改后62部署环境与slurm联调没有问题，等待调度器适配器接口仓库版本更新后修改buf-generate
提交成功时
![image](https://github.com/PKUHPC/SCOW/assets/43978285/3c32c64e-7a14-4ec4-a8f8-2d185871c2a9)
![image](https://github.com/PKUHPC/SCOW/assets/43978285/711c368d-17ef-48e1-9740-77a203f611d0)
提交失败时
![image](https://github.com/PKUHPC/SCOW/assets/43978285/92c14396-a206-4108-be06-02edaac5c69c)

2023-11-06 01:39 UTC, piccaSun commented
@ddadaal  已更新scow-scheduler-adapter-interface版本号至v1.2.0

2023-11-06 12:04 UTC, ddadaal requested changes

2023-11-06 12:04 UTC, ddadaal commented on apps/portal-server/src/services/job.ts
> +      }).catch((e) => {
需要处理不支持这个接口的旧版本适配器的情况。

https://jgf29kqp7z.feishu.cn/docx/MDqrdUBM3ogujcxT4DKcbpmmnwg?theme=LIGHT&contentTheme=DARK#MqYFdhA3TobRbfxtkPbcQ5zQngc

2023-11-09 13:52 UTC, ddadaal requested changes

2023-11-09 13:52 UTC, ddadaal commented on apps/portal-server/src/utils/clusters.ts
> +      scheduleApiVersion = { major: 1, minor: 1, patch: 0 };
接口不存在默认是1.0.0，因为1.1.0是要求实现这个接口的。

2023-11-09 13:52 UTC, ddadaal commented on apps/portal-server/src/utils/clusters.ts
> +  comparedVersion: ApiVersion): Promise<void> {
这个函数可以通用非常好，但是还是设计复杂了，目前只需要确认获取到的版本大于等于要求的版本即可。第二个参数可以命名为minVersion，更贴切

2023-11-09 13:52 UTC, ddadaal commented on apps/portal-server/src/utils/clusters.ts
> +    }
如果甚至都获取不到版本，报错。

2023-11-09 13:52 UTC, ddadaal commented on apps/portal-server/src/utils/clusters.ts
> +      scheduleApiVersion = { major: 1, minor: 1, patch: 0 };
接口服务不存在是指VersionService不存在吗？那也是认为是1.0.0。不需要区分

2023-11-09 13:52 UTC, ddadaal commented on apps/portal-server/src/utils/clusters.ts
>    const client = getSchedulerAdapterClient(c.adapterUrl);
我不太确认这个client对象是否能保存起来一直用，但是portal-server其他地方都是当场使用getSchedulerAdapterClient获取新的client对象的，这里没必要单独缓存一次。

2023-11-09 13:52 UTC, ddadaal commented on apps/portal-server/src/utils/clusters.ts
> +    const compareResult = compareSemVersion(comparedVersion, scheduleApiVersion);
现在只要判断版本是否>=就可以了。以后需要的话以后再说吧

2023-11-09 13:52 UTC, ddadaal commented on apps/portal-server/src/utils/clusters.ts
> +// export async function checkScowSchedulerApiVersion(client: SchedulerAdapterClient): Promise<void> {
没太看懂这个函数是在做什么……SCOW只需要管要调用的集群的调度器版本，不需要管SCOW自己的版本

2023-11-10 03:46 UTC, piccaSun commented on apps/portal-server/src/utils/clusters.ts
> +// export async function checkScowSchedulerApiVersion(client: SchedulerAdapterClient): Promise<void> {
已删除注释掉的代码部分

2023-11-10 03:46 UTC, piccaSun commented on apps/portal-server/src/utils/clusters.ts
> +    const compareResult = compareSemVersion(comparedVersion, scheduleApiVersion);
已修改为在本函数下直接判断调度器api版本是否大于等于最低要求版本，请确认

2023-11-10 03:48 UTC, piccaSun commented on apps/portal-server/src/utils/clusters.ts
> +      scheduleApiVersion = { major: 1, minor: 1, patch: 0 };
是的。已修改为服务或接口不存在都认为版本为1.0.0,请确认

2023-11-10 03:49 UTC, piccaSun commented on apps/portal-server/src/utils/clusters.ts
> +      scheduleApiVersion = { major: 1, minor: 1, patch: 0 };
已修改为1.0.0

2023-11-10 03:49 UTC, piccaSun commented on apps/portal-server/src/utils/clusters.ts
> +    }
已修改为报错。

2023-11-10 03:49 UTC, piccaSun commented on apps/portal-server/src/utils/clusters.ts
> +  comparedVersion: ApiVersion): Promise<void> {
已修改，请确认

2023-11-10 03:58 UTC, piccaSun commented
修改上述意见（调度器暂未实现VersionService服务暂未联调）
判断版本不符合要求时前端报错如下
![提交失败](https://github.com/PKUHPC/SCOW/assets/43978285/d727ecbc-1f1b-470b-8c85-6f890d746776)
后台提示详细错误信息
![后台报错](https://github.com/PKUHPC/SCOW/assets/43978285/c482335a-fbde-4cea-9cd7-52f9d2f51215)

2023-11-10 14:06 UTC, piccaSun commented on apps/portal-server/src/utils/clusters.ts
>    const client = getSchedulerAdapterClient(c.adapterUrl);
这个这次没有修改，只是因为获取的是对应集群的适配器版本所以函数写在获取集群适配器服务客户端的同一个文件下了。
我看server端一般都是调用下方23行的getAdapterClient()
![image](https://github.com/PKUHPC/SCOW/assets/43978285/a3722122-e0e8-4a1a-8f3b-1ea44618e68d)

2023-11-11 10:05 UTC, ddadaal approved these changes

2023-11-11 10:07 UTC, merged