fix(mis): 管理系统消费记录页面加载过慢或无法打开
PKUHPC/SCOW pull request #900
Opened 2023-10-20 13:44 UTC by piccaSun

### 做了什么

修改获取消费记录页面分页方式为后端分页
在getChargeRecord的api接口中增加查询参数page, pageSize, 返回值中增加totalCount
在实体ChargeRecord中添加（time, tenantName，accountName, type）的复合索引query_info

修改前
生产环境十万多条数据量的时候出现页面无法打开的情况

修改后
本地测试2000万+的数据，除offset直接跳转到200万+页码以后需要40秒以上
其他查询条件基本控制在10~15秒左右
![image](https://github.com/PKUHPC/SCOW/assets/43978285/9a4a9855-8e65-4372-bdaf-be702e8aa9a3)

2023-10-20 15:04 UTC, ddadaal requested changes

2023-10-20 15:04 UTC, ddadaal commented on protos/server/charging.proto
> +  optional uint64 page_size = 10;
给这个接口加分页实际上改变了这个接口的行为，应该被认为是一个破坏性更新。新建一个GetPaginatedChargeRecords API吧。

2023-10-20 15:04 UTC, ddadaal commented on protos/server/charging.proto
>    optional common.Money total = 2;
可以考虑把计算总额单独拆成一个API，这样每次查列表的时候不需要单独再计算一次总额。由前端分别调用不同的API获得不同的数据

2023-10-22 11:50 UTC, piccaSun commented on protos/server/charging.proto
>    optional common.Money total = 2;
> 可以考虑把计算总额单独拆成一个API，这样每次查列表的时候不需要单独再计算一次总额。由前端分别调用不同的API获得不同的数据

1.之前的接口计算总数和总额都是随着条件变化的
后端分页的话即使页码变更也需要重新发送请求，那总数和总额都应该获取最新的一次请求结果
2.目前遇到的问题是发现两千万级数据COUNT和SUM的mysql聚合查询响应很慢，接近10秒
如果每次都要发送请求，我觉得那COUNT最好不要和SUM分开查询
这个是不是新增一个返回总额的请求反而响应会变慢啊？

2023-10-22 11:53 UTC, piccaSun commented on protos/server/charging.proto
> +  optional uint64 page_size = 10;
> 给这个接口加分页实际上改变了这个接口的行为，应该被认为是一个破坏性更新。新建一个GetPaginatedChargeRecords API吧。

https://jgf29kqp7z.feishu.cn/wiki/wikcnwLufSSo9yvRJwtcZRqgPxg
以前API版本号中提到增加optional request参数算兼容性API
现在是只要API有改动就算破坏性，就需要增加@deprecated吗？

2023-10-23 11:43 UTC, ddadaal commented on protos/server/charging.proto
> +  optional uint64 page_size = 10;
不能只看是否增加optional参数，还要看API的语义是否改变。本来这个API是返回所有信息，但是现在传同样的参数（不设置分页信息）变成只返回一页内容，这也是一种breaking change。

2023-10-23 11:51 UTC, ddadaal commented on protos/server/charging.proto
>    optional common.Money total = 2;
拆开主要优化的是不改条件而只改页数的情况，这种情况应该是多数吧？改条件了查询慢了也就慢了。
查询总数确实是会变慢的，因为分页查的话，查到limit条记录就结束了，要总额需要把所有符合条件的记录都找出来。
这个功能如果很容易出现大量数据的话，查询某一页就不返回total了，只返回对应页数的记录。然后再计算总额中再返回total。这也是很多列表查询场景常用的优化做法。

2023-10-26 05:48 UTC, piccaSun commented on protos/server/charging.proto
>    optional common.Money total = 2;
@ddadaal  已修改，请确认。已更新重构后的上方说明。

2023-10-26 16:01 UTC, ddadaal approved these changes

2023-11-07 11:15 UTC, lyl-available commented
无功能性问题，但是带上账号或者消费类型筛选条件后，如：账号管理-消费记录页面，翻页和查询的时候，接口返回会有点慢

2023-11-07 11:15 UTC, lyl-available approved these changes

2023-11-07 11:21 UTC, piccaSun commented
> 无功能性问题，但是带上账号或者消费类型筛选条件后，如：账号管理-消费记录页面，翻页和查询的时候，接口返回会有点慢

实际确认了一下测试环境，有的数据是因为即使只单纯做翻页，但是数据id已经到4000万以上的情况，那么只是做翻页查询也需要很长时间，数据库sql查询也需要15秒以上，这个目前不进一步优化数据存储感觉不太好解决
@ddadaal 
![image](https://github.com/PKUHPC/SCOW/assets/43978285/2ead6ae3-1ecd-4712-b542-2e9f203c54a5)

2023-11-07 13:26 UTC, ddadaal approved these changes

2023-11-07 13:26 UTC, ddadaal commented
冲突

2023-11-07 14:52 UTC, piccaSun commented
> 冲突

已解决冲突，请确认

2023-11-07 15:03 UTC, merged