feat(mis): 增加定时同步scow与适配器用户及账户封锁状态的功能
PKUHPC/SCOW pull request #913
Opened 2023-10-26 09:24 UTC by tongchong

2023-10-30 11:04 UTC, ddadaal requested changes

2023-10-30 11:04 UTC, ddadaal commented on apps/mis-server/src/bl/block.ts
> +      blockedUserAccounts.push([ua.user.getProperty("userId"), ua.account.getProperty("accountName")]);
这里可以用`.user.$.userId`吗？上面用populate应该推出类型了。

2023-10-30 12:29 UTC, tongchong commented on apps/cli/assets/config/mis.yaml
> +periodicSynchronizeStatus:
好的，我改成periodicSyncUserAccountBlockStatus，之前缩减是因为参考fetchJob，加了账户用户后参数太长了

2023-10-30 12:29 UTC, tongchong commented on apps/mis-server/src/bl/block.ts
> +      blockedUserAccounts.push([ua.user.getProperty("userId"), ua.account.getProperty("accountName")]);
可以的，我改了

2023-10-30 12:31 UTC, ddadaal approved these changes

2023-11-02 07:30 UTC, lyl-available approved these changes

2023-11-02 13:45 UTC, merged