feat(web): 允许用户指定系统语言
PKUHPC/SCOW pull request #935
Opened 2023-10-31 14:14 UTC by piccaSun

### 做了什么

在`common.yml`中增加必填配置项`systemLanguage`
```
# 设置系统语言
systemLanguage:
  # 对象类型
  # 可选，默认为true。
  # 如果true，则SCOW在用户未手动选择语言时，自动根据cookie, header等判断语言，如判断失败使用default语言
  # 如果为false，则SCOW首次进入系统时使用配置的默认语言
  autoDetect: true
  # 默认语言，必须设置。类型必须为当前系统合法语言["zh_cn"，"en"]的枚举值
  default: "zh_cn"

# 设置系统语言，字符串类型
# 类型必须为当前系统合法语言["zh_cn"，"en"]的枚举值
# 若设置此类型，SCOW直接使用此语言，不允许用户再进行语言切换
# systemLanguage: "zh_cn"
```

1.当配置为字符串类型时 `systemLanguage: "zh_cn"`
隐藏语言切换器，进入系统后设置语言cookie为“zh_cn”不再变更，系统一直使用中文显示

2.当配置为对象类型
```
systemLanguage:
  autoDetect: false
  default: "zh_cn"
```
显示语言切换器，但是进入SCOW系统的初始语言不再判断cookie或浏览器偏好，而为配置的"zh_cn"
系统默认语言也为“zh_cn”

3.当配置为对象类型
```
systemLanguage:
  autoDetect: true 或不配置此项时
  default: "zh_cn"
```
显示语言切换器，进入SCOW系统时的初始语言优先判断cookie或浏览器偏好，当二者皆不存在或不合法时，使用配置的语言
"zh_cn"

**systemLanguage没有配置时，系统报错，无法启动**
![image](https://github.com/PKUHPC/SCOW/assets/43978285/494cecd8-4dbe-4c26-9643-7bb0560e0c4e)

**systemLanguage为对象但没有配置default时，系统报错，无法启动**
![image](https://github.com/PKUHPC/SCOW/assets/43978285/24f73dc0-8d6f-4277-b486-01da1e153b90)

**systemLanguage为对象，或systemLanguage为字符串时，配置的语言不在系统合法语言列表的枚举值中时，系统报错，无法启动**
![image](https://github.com/PKUHPC/SCOW/assets/43978285/3d23c593-1316-454d-99ea-b311c170663a)

2023-11-01 13:03 UTC, ddadaal commented on apps/mis-web/src/layouts/BaseLayout.tsx
> +  };
如果不使用国际化，应该直接忽略cookie。因为在不使用国际化的情况下，_app.tsx里的执行`getInitialLanguage`时没有考虑cookie，所以这里不需要额外设置cookie，因为反正cookie也不会被使用

2023-11-01 13:06 UTC, ddadaal commented on libs/server/src/systemLanguage.ts
> +    (systemLanguageConfig.autoDetect || typeof systemLanguageConfig.autoDetect === "undefined") &&
直接systemLanguageConfig.autoDetect

2023-11-01 13:11 UTC, ddadaal commented on apps/mis-web/src/pages/_app.tsx
> +  const initialLanguage = getInitialLanguage(extra.languageCookie, systemLanguageConfig);
这里可以在后端（getInitialProps）就把这个函数调用了，决定第一次执行所需要的语言ID传给前端把，不需要专门把initialLanguage传到前端。

2023-11-01 13:12 UTC, ddadaal commented on libs/config/src/common.ts
> +      autoDetect: Type.Optional(Type.Boolean({ description: "是否跟随系统进行语言选择" })),
Type.Boolean({ description: "", default: true })，这样这个属性在代码中不会是undefined的，而且用户可以知道默认值为true，方便编程。

2023-11-01 13:12 UTC, ddadaal commented on libs/config/src/common.ts
> +        { description: "系统默认语言" }),
这里也通过default设置默认语言为zh_cn

2023-11-01 13:13 UTC, ddadaal commented on libs/config/src/common.ts
> +  systemLanguage: Type.Union([
整个default也可以设置一个default值为`{}`，因为默认值是{}所以会自动采用Object这个类型

2023-11-01 13:20 UTC, piccaSun commented on apps/mis-server/tests/charging/charging.test.ts
> +it.skip("returns charge records with query of tenant", async () => {
是的，merge了master之后我就改过来。

2023-11-02 09:36 UTC, piccaSun commented
除昨天沟通过的Type.Union中的一个值设定default会有strict mode报错，相关问题没有修改外
其他修改意见已修改，请确认。
@ddadaal

2023-11-02 14:33 UTC, ddadaal requested changes

2023-11-02 14:33 UTC, ddadaal commented on apps/mis-web/src/layouts/BaseLayout.tsx
> +  }, [systemLanguageConfig.isUsingI18n, systemLanguageConfig.autoDetect]);
不管就行了，没必要非得把它删掉😂

2023-11-02 14:33 UTC, ddadaal commented on docs/docs/deploy/config/customization/custom-system-language.md
> +```
文档这里有点奇怪，不配置等同于上面那个配置就可以了，这里的或者可以不写。

2023-11-02 14:40 UTC, piccaSun commented on apps/auth/config/common.yaml
> +#   # 默认语言，当systemLanguage为对象类型时必须设置。
如果配置为对象是不是autoDetect可以不配但是default必须得配置啊？
还是说用户就写个  systemLanguage： 
什么值都不写这样也可以？

2023-11-02 14:48 UTC, piccaSun commented on apps/mis-web/src/layouts/BaseLayout.tsx
> +  }, [systemLanguageConfig.isUsingI18n, systemLanguageConfig.autoDetect]);
不删掉的话SSR读语言ID去显示配置项的国际化时候需要多一重校验
`getServerCurrentLanguageId(req: IncomingMessage | undefined, systemLanguageConfig: SystemLanguageConfig): string { ... }`
那我把这个判断逻辑挪到这个函数里🤦‍

2023-11-02 15:12 UTC, ddadaal commented on apps/mis-web/src/layouts/BaseLayout.tsx
> +  }, [systemLanguageConfig.isUsingI18n, systemLanguageConfig.autoDetect]);
能拿到`systemLanguageConfig`就好办，就一开始就用这个判断就可以了。
```ts
export function getServerCurrentLanguageId(req: IncomingMessage | undefined,
  systemLanguageConfig: SystemLanguageConfig): string {
  # 如果不用autoDetect，就直接返回defaultLanguage
  if (!systemLanguageConfig.autoDetect) {
    return systemLanguageConfig.defaultLanguage;
  }

  const cookies = parseCookies({ req });

  if (cookies && cookies.language) {
    const currentCookieLang = cookies.language;
    if (Object.values(SYSTEM_VALID_LANGUAGES).includes(currentCookieLang)) {
      return currentCookieLang;
    }
  }

  return systemLanguageConfig.defaultLanguage;
};

```

2023-11-02 15:16 UTC, piccaSun commented on apps/mis-web/src/layouts/BaseLayout.tsx
> +  }, [systemLanguageConfig.isUsingI18n, systemLanguageConfig.autoDetect]);
这个地方不能这样吧。。。
```
 # 如果不用autoDetect，就直接返回defaultLanguage
  if (!systemLanguageConfig.autoDetect) {
    return systemLanguageConfig.defaultLanguage;
  }
```
当autoDetect为false,第一次可以这样判断。但是当用户没有切出系统可是又手动更换了语言的时候，这个时候SSR当前语言应该从cookie读。。不能去读 systemLanguageConfig.defaultLanguage吧...?

2023-11-02 15:32 UTC, piccaSun commented on apps/auth/config/common.yaml
> +#   # 默认语言，当systemLanguage为对象类型时必须设置。
已修改，请确认

2023-11-02 15:32 UTC, piccaSun commented on docs/docs/deploy/config/customization/custom-system-language.md
> +```
已修改，请确认

2023-11-05 14:17 UTC, piccaSun commented on apps/mis-web/src/layouts/BaseLayout.tsx
> +  }, [systemLanguageConfig.isUsingI18n, systemLanguageConfig.autoDetect]);
如果不删除cookie的话
有可能有以下情况,cookie中保存了en，systemLanguage: {autoDetect: false, default: "zh_cn"}
第一次进入系统因为使用InitialLanguage会选择显示的文字为中文，但是如果用户还没有切换语言，但是需要SSR读取语言ID匹配配置项文本的中文的时候，如门户首页HomeText,HomeTitle，这个时候语言id不能从i18n获取，如果不删除原有的cookie,读到的就会是en
我觉得删除的话是最简单的，清空了之前的cookie，但是之后用户再手动进行语言切换的时候还是可以set新的cookie进来

2023-11-06 02:39 UTC, piccaSun commented on apps/mis-web/src/layouts/BaseLayout.tsx
> +  }, [systemLanguageConfig.isUsingI18n, systemLanguageConfig.autoDetect]);
补充一下如果不删除逻辑，简单处理`!systemLanguage.autoDetect`时语言切换不能正常显示门户首页配置的homeTitle国际化的示例
```
# 主页标题
homeTitle:
  defaultText:
    i18n:
      default: "超算平台"
      en: "Super Computing on Web"
      zh_cn: "超算平台"
```
![门户不变](https://github.com/PKUHPC/SCOW/assets/43978285/0c87ee1a-4d65-4fa1-bd05-d8c846e815e7)

2023-11-06 12:01 UTC, ddadaal commented on apps/mis-web/src/layouts/BaseLayout.tsx
> +  }, [systemLanguageConfig.isUsingI18n, systemLanguageConfig.autoDetect]);
删除cookie确实没什么问题，但是问题出在不删cookie为什么会出问题，因为理想情况下，所有前端显示用的国际化文本**都应该使用hook或者基于hook的Localized组件来获取具体需要显示的内容**，而这个hook方案是不依赖于cookie的。不删cookie出现了问题说明不是所有的文本都是通过hook来的，这可能会为未来的开发埋坑。

我看了下，代码里门户的dashboard和提交作业中出现了直接在getServerSideProps里通过cookie获取文本，这和其他使用国际化文本的地方通过hook的方式不一样。这是必要的吗？如果把这两个地方也改成使用hook，会影响功能吗？如果不影响，那最好也改成hook，以确保所有使用国际化文本的地方都使用同一个方式，减少未来的可能出现的行为不一致的问题。

2023-11-07 03:34 UTC, piccaSun commented
已修改配置名称为autoDetectWhenUserNotSet，统一修改前后端获取语言信息逻辑，修改文档
关于dashboard和提交作业的SSR处理的问题，昨天看漏了，他们两个也是ServerRuntimeConfig的配置，所以如果不更改配置逻辑目前还是只能保留SSR形式，请确认
@ddadaal

2023-11-07 13:26 UTC, ddadaal approved these changes

2023-11-09 10:08 UTC, lyl-available commented
配置autoDetectWhenUserNotSet为false，默认语言为zh_cn:
![image](https://github.com/PKUHPC/SCOW/assets/125553919/c2464fe2-960d-484a-bf65-da3e981bd46c)
cookie中无语言信息:
![image](https://github.com/PKUHPC/SCOW/assets/125553919/c5c075c9-2542-49e8-ba19-f5e55cd1d438)
平台语言会随着浏览器配置变化而变化，而不是直接读取默认语言中文
![image](https://github.com/PKUHPC/SCOW/assets/125553919/d488ee8b-2018-4ef4-adcc-e57360398a84)

2023-11-09 10:20 UTC, lyl-available commented
配置autoDetectWhenUserNotSet为true，默认语言为en，cookie中无语言信息:
![image](https://github.com/PKUHPC/SCOW/assets/125553919/1d9d67f3-04da-4dd4-b95d-03b4856c128d)
平台语言会随着默认语言的变化而变化，而不是读取浏览器配置语言中文：
![image](https://github.com/PKUHPC/SCOW/assets/125553919/7b6ca456-7959-45d5-969b-b5381d9ddc2b)

2023-11-09 12:41 UTC, piccaSun commented
@lyl-available  
第一个问题是因为62环境的配置项名称autoDetectWhenUserNotSet写错了， 因为是可选配置所以系统最后读取了默认值，
实际上读取结果autoDetectWhenUserNotSet：true, 初始语言随浏览器偏好"en"变化符合预期

第二个问题是因为浏览器偏好判断出了问题，系统配置的简体中文字符串zh_cn与HTTP语言请求信息的字符串zh-CN不一致，语言偏好第一顺位以后切断字符时包含了比例，所以第二顺位的zh判断也失败了，但是第一个问题中的en判断正常。此处问题已修改请确认。

2023-11-10 04:41 UTC, lyl-available approved these changes

2023-11-10 14:34 UTC, piccaSun commented
无关性能修改，因为lib/config下的type.ts下保存的只有i18n相关的类型及常量，为避免歧义修改文件名为i18n.ts，修改对应导入路径。修改后本地build正常，系统运行正常；62环境系统运行正常。

2023-11-11 10:08 UTC, ddadaal commented
冲突

2023-11-12 10:52 UTC, piccaSun commented
> 冲突

已解决冲突，请确认 @ddadaal

2023-11-13 13:46 UTC, merged