feat(portal-web): 门户系统文件管理新增文件编辑功能
PKUHPC/SCOW pull request #942
Opened 2023-11-02 02:49 UTC by Miracle575

# 文件编辑功能

## 1. 文件管理中文件列表操作列，对于文件（除图片类型）显示编辑按钮
![image](https://github.com/PKUHPC/SCOW/assets/140392039/a28dac8c-0569-4941-b022-5b98b25f18f8)

## 2. 可编辑文件大小可配置
在 `portal.yaml` 中新增配置项：
```yaml
# 文件编辑大小限制
# 可接受的格式为nginx的client_max_body_size可接受的值
# fileEditSize: "1m"
```
默认可编辑文件大小为 1m

对超过可编辑大小的文件操作列编辑按钮置灰，鼠标悬浮提供 tooltip

2023-11-02 13:44 UTC, ddadaal requested changes
文件编辑是个大功能点，monaco-editor是个比较重量级的东西，建议参考shell，把文件编辑做成一个单独的页面。

2023-11-02 13:44 UTC, ddadaal commented on apps/cli/assets/config/portal.yaml
> +# fileEditSize: "1m"
文件编辑是个大功能点，后续可能会有更多的配置项，现在先单独开一个object，用于以后扩展更多的配置项

```yaml
fileEdit:
   sizeLimit: ???
```

2023-11-02 13:44 UTC, ddadaal commented on apps/portal-web/src/utils/languageMap.ts
> +export default languageMap;
不鼓励使用export default，直接export要export的东西，import { languageMap }就可以了

2023-11-08 06:47 UTC, Miracle575 commented on apps/cli/assets/config/portal.yaml
> +# fileEditSize: "1m"
最后还是考虑使用 modal 框来实现，并合并了预览和编辑的逻辑。现在文件编辑的状态逻辑比较复杂，需要测试介入一下

2023-11-08 11:33 UTC, ddadaal requested changes

2023-11-08 11:33 UTC, ddadaal commented on renovate.json
> +        "monaco-editor"
为什么要关闭更新呢，按现在这个方案monaco-editor的文件是编译时复制的，没有版本依赖的问题。

2023-11-08 11:33 UTC, ddadaal commented on libs/config/src/portal.ts
> +    }, { description: "文件编辑功能" }),
preview和edit本身可以设置一个{}的default

2023-11-09 13:44 UTC, ddadaal approved these changes

2023-11-15 08:50 UTC, lyl-available commented
点击show more，页面会卡死
![image](https://github.com/PKUHPC/SCOW/assets/125553919/045c9ddd-bc82-436a-baa5-5e084609031e)

2023-11-16 07:07 UTC, lyl-available approved these changes

2023-11-16 13:12 UTC, merged