fix(web): 优化web端tabl展示效果
PKUHPC/SCOW pull request #943
Opened 2023-11-02 09:43 UTC by tongchong

2023-11-03 12:01 UTC, ddadaal requested changes
这个PR是用来优化UI的，如果要默认限制用户名账户等，需要另开一个PR做。

2023-11-03 15:32 UTC, tongchong commented on apps/cli/assets/config/mis.yaml
因为原本默认是没有限制的，但slurm适配器那边，是不允许大写，且一样有字符串长度的限制，大概在60~80的样子，产品那边希望给用户、账户默认init的配置就加上长度，以及字符串内容类型的限制，这样可以减少超长字符，减少特殊情况下的报错，比方说先创建了一个带大写字母的用户，但是创建成功以后，无法提交作业

2023-11-03 16:17 UTC, ddadaal commented on apps/cli/assets/config/mis.yaml
单开一个PR做这个事情，这个PR只改UI

2023-11-04 02:10 UTC, tongchong commented on apps/cli/assets/config/mis.yaml
好的，我将限制输入的，如配置文件、max等设置，单独另开一个PR

2023-11-06 11:29 UTC, ddadaal approved these changes

2023-11-06 11:29 UTC, merged