feat(web): 所有显示集群的地方，按配置优先级进行顺序优化
PKUHPC/SCOW pull request #944
Opened 2023-11-03 03:13 UTC by piccaSun

### 做了什么

在之前的性能优化中已经完成了门户系统和管理系统publicRuntimeConfig.CLUSTERS中的集群为按配置优先级顺序排序
本PR内实现serverRuntimeConfig.CLUSTERS_CONFIG也按照配置的集群优先级进行排序

### 页面UI变化
1. 管理系统下作业价格表相关页面的展示
2. 门户系统下创建桌面时，如果默认集群没有可以创建桌面的登录节点，那么按照集群优先级顺序查找可以使用的集群并自动选择

2023-11-03 13:18 UTC, ddadaal requested changes
javascript遍历object的key时，其得到的顺序不一定是插入顺序（参考： https://stackoverflow.com/a/5525820 ）。在现在的情况下想解决这个问题，最简单的方式我认为是加一个CLUSETER_LIST的config，其值为排序好的集群ID的数组。代码中所有需要列出所有数组的时候，通过CLUSTER_LIST遍历集群ID，然后通过CLUSTERS拿信息。改动可能有点大，但是为了严格一点还是这样做吧。

2023-11-08 08:28 UTC, piccaSun commented
已修改请确认 @ddadaal

2023-11-08 10:55 UTC, ddadaal requested changes

2023-11-08 10:55 UTC, ddadaal commented on .changeset/four-falcons-obey.md
这个PR没有改配置格式，不需要单独创建一个config给用户介绍改了啥

2023-11-08 12:17 UTC, piccaSun commented on .changeset/four-falcons-obey.md
> 这个PR没有改配置格式，不需要单独创建一个config给用户介绍改了啥

已删除，请确认

2023-11-08 12:52 UTC, ddadaal approved these changes

2023-11-08 12:52 UTC, merged