feat(portal): 在适配器为 K8S 的时候，提交作业页面增加输入框：镜像地址
PKUHPC/SCOW pull request #954
Opened 2023-11-07 05:57 UTC by tongchong

### 配置：
 ```yaml title="config/clusters/XXX.yml"
# # 是否为K8S集群，默认为false，为true时将在提交作业页面增加镜像url输入框
# K8S: true  
```

若K8S设置为true，则在页面中展示：
<img width="320" alt="1699336507561" src="https://github.com/PKUHPC/SCOW/assets/25954437/1a980baa-dfad-415f-aecd-8f200ab3b740">

2023-11-07 13:15 UTC, ddadaal requested changes

2023-11-07 13:15 UTC, ddadaal commented on libs/config/src/cluster.ts
> +  K8S: Type.Boolean({ description: "是否为K8S集群", default: false }),
不要增加这个配置，而是SCOW自己通过适配器调度器的接口知道这个集群的类型是什么，然后再做相应处理

2023-11-13 06:24 UTC, tongchong commented on libs/config/src/cluster.ts
> +  K8S: Type.Boolean({ description: "是否为K8S集群", default: false }),
好的，我就在 feat: 增加获取集群信息的接口 GetClusterInfo 中增加一个type [PKUHPC/scow-scheduler-adapter-interface/pull/16]

2023-11-15 12:28 UTC, ddadaal commented on protos/portal/job.proto
> +  optional string extra_options = 18;
extra_options需要留有扩展性，应该是map<string, string>用来存放更多的数据

2023-11-16 01:50 UTC, tongchong commented on protos/portal/job.proto
> +  optional string extra_options = 18;
适配器那边的接口，使用的是 repeated string extra_options = 15;  我将proto/portal/job.proto也与其统一，改为string[]

2023-11-16 13:20 UTC, ddadaal approved these changes

2023-11-16 13:20 UTC, ddadaal commented
后续如果有必要，把extra_options改成map<string, string>的字段，同时修改SCOW API。

2023-11-19 15:20 UTC, tongchong commented
我把把extra_options改成map<string, string>的字段，因为需要记录到模板中。适配器那边暂时不动。

2023-11-23 13:55 UTC, ddadaal approved these changes

2024-09-05 06:54 UTC, closed without merging