feat(portal): 提交作业和提交交互式应用时显示可用分区
PKUHPC/SCOW pull request #977
Opened 2023-11-14 10:08 UTC by piccaSun

2023-12-04 11:25 UTC, ddadaal requested changes

2023-12-05 02:42 UTC, piccaSun commented
@ddadaal  上述问题已修改，请确认

2023-12-05 10:35 UTC, ddadaal requested changes

2023-12-06 03:17 UTC, piccaSun commented on .changeset/four-timers-protect.md
> +"@scow/mis-web": minor
@ddadaal  已确认，不需要到major，根据API版本变动升级到minor就可以了

2023-12-06 11:58 UTC, ddadaal approved these changes

2023-12-06 11:58 UTC, ddadaal commented on .changeset/four-timers-protect.md
> +"@scow/mis-web": minor
不是 我本来的意思是patch😂确认了是minor也行

2023-12-06 12:44 UTC, piccaSun commented
grpc-api的版本Level无需与scow一致，所以经确认修改功能上等级为patch

2024-06-19 03:16 UTC, lyl-available approved these changes

2024-06-19 10:47 UTC, ddadaal approved these changes

2024-06-19 10:47 UTC, merged