feat:添加外部自定义认证系统
PKUHPC/SCOW pull request #979
Opened 2023-11-16 02:54 UTC by Miracle575

添加外部自定义认证系统

2023-11-30 13:53 UTC, ddadaal requested changes

2024-01-09 08:12 UTC, Miracle575 commented on apps/cli/assets/install.yaml
> +#     imageConfig:
旧版本中此处有个配置已经为 image，如果这里将 imageConfig 改为 image 会导致重名

```
#     # 兼容老版本
#     # 定义认证系统镜像名。必填
#     # image: my-custom-auth:v1.0
```

2024-01-09 08:17 UTC, Miracle575 commented on apps/mis-server/src/config/env.ts
> +  AUTH_URL: str({ desc: "认证系统 URL", default: "" }),
此处在 cli 设置环境变量时如果没有配置 AUTH_URL 则传递 "",所以默认一定是 ""

```
addService("mis-server", {
      image: scowImage,
      ports: config.mis.portMappings?.misServer ? { [config.mis.portMappings.misServer]: 5000 } : {},
      environment: {
        "SCOW_LAUNCH_APP": "mis-server",
        "DB_PASSWORD": config.mis.dbPassword,
        AUTH_URL: config.auth.custom?.external?.url ?? "",
        ...serviceLogEnv,
      },
      volumes: {
        "/etc/hosts": "/etc/hosts",
        "./config": "/etc/scow",
        "~/.ssh": "/root/.ssh",
      },
    });
```

2024-01-09 08:20 UTC, Miracle575 commented on apps/mis-server/src/services/tenant.ts
> +        const createdInAuth = await createUser(config.AUTH_URL || misConfig.authUrl,
> config.AUTH_URL || misConfig.authUrl出现太多次了，应该在config目录下每个文件中新增一个`const authUrl`变量取这个值，其他所有需要使用authUrl的都使用这里定义的authUrl。

在config目录下每个文件中新增一个`const authUrl`变量。这个config目录是指哪个？

2024-01-10 10:57 UTC, ddadaal commented on apps/cli/assets/install.yaml
> +#     imageConfig:
老版本配置最终会deprecate，当老版本配置deprecate后这里就会不一致了。可以让已有的image变成一个string | object的union，然后在读取配置的时候验证

2024-01-10 11:01 UTC, ddadaal requested changes

2024-01-10 11:01 UTC, ddadaal commented on apps/mis-server/src/services/tenant.ts
> +        const createdInAuth = await createUser(config.AUTH_URL || misConfig.authUrl,
这里没写清楚。可以新建一个mis-server/src/config/index.ts文件，里面存放从各个配置里读取并计算出来的配置，如`authUrl`

2024-01-13 14:11 UTC, ddadaal requested changes
冲突

2024-01-13 14:11 UTC, ddadaal commented on apps/cli/src/config/install.ts
> +      type: Type.Enum(AuthCustomType, { description: "自定义认证系统类型", default: AuthCustomType.image }),
当前为了兼容老版本，这个type可以设置为Optional。通过有没有设置type判断应该用老版本的配置还是用新版本的配置，可以简化读取配置时的逻辑。并且在读取配置的时候，如果发现用的老版本，应该提示用户当前配置方案已经过时。参考其他读取配置文件的逻辑。

2024-01-13 14:11 UTC, ddadaal commented on docs/docs/integration/auth/use.md
> +    # 兼容老版本,image 在老版本中为字符串
在这里声明，下列配置是老版本的配置，已过时，未来将会删除

2024-01-15 10:42 UTC, ddadaal approved these changes

2024-01-15 10:43 UTC, merged