feat: 门户仪表盘删除之前的配置标题和文字，增加平台队列状态展示
PKUHPC/SCOW pull request #987
Opened 2023-11-20 02:56 UTC by OYX-1

2023-11-21 13:31 UTC, ddadaal requested changes
这个PR最好把设计图里的顶部的logo以及表格的标题文本加上，不然看着首页很奇怪，用户第一眼看不能一眼反应过来是这些是什么数据

2023-11-21 13:31 UTC, ddadaal commented on libs/protos/scheduler-adapter/package.json
> +    "generate": "rimraf generated && buf generate --template buf.gen.yaml https://github.com/PKUHPC/scow-scheduler-adapter-interface.git",
指定需要的接口版本

2023-11-21 13:31 UTC, ddadaal commented on apps/portal-web/package.json
> +    "recharts": "^2.10.1",
- 不能使用^，和其他依赖一样使用指定版本
- 试试 https://ant-design-charts.antgroup.com/ ，和antd风格更搭

2023-11-21 13:31 UTC, ddadaal commented on apps/portal-web/src/pageComponents/dashboard/InfoPanes.tsx
布局需要一些改进：

1. 让各个InfoPane占满整个宽度，使各个InfoPane之间用固定的padding隔开，而不是固定InfoPane的宽度一堆空隙，这样现在PR的截图里看着比较空
2. 可以给InfoPane设置minWidth和maxWidth，使得在宽度低的情况下自动换行，并保证InfoPane在小宽度下不至于太小（minWidth）在大宽度下不至于太大（maxWidth）
3. 为什么第一个InfoPane没有用Container包裹？

2023-11-21 13:31 UTC, ddadaal commented on apps/portal-web/src/pageComponents/dashboard/InfoPane.tsx
> +`;
这些风格有必要吗？默认的不可吗？因为ant-design自己是有自己的设计风格的，我们自己改没什么必要，反而破坏了风格统一性

2023-11-21 13:31 UTC, ddadaal commented on apps/portal-web/src/pageComponents/dashboard/InfoPane.tsx
> +  color: #999;
这个颜色考虑了暗色模式吗？

2023-11-21 13:31 UTC, ddadaal commented on apps/portal-web/src/pageComponents/dashboard/InfoPanes.tsx
> +  notAvailable:"#c04851",
这些颜色可以使用antd提供的颜色吗？ https://ant.design/docs/spec/colors-cn

2023-11-23 03:29 UTC, OYX-1 commented on apps/portal-web/src/pageComponents/dashboard/InfoPane.tsx
> +  color: #999;
![image](https://github.com/PKUHPC/SCOW/assets/74037789/f9410ea5-33ca-4284-b02d-0fb886ce6791)
是这样配置吗？
theme.token里感觉没有什么合适的颜色，还是直接黑白最清晰

2023-11-23 03:32 UTC, OYX-1 commented on apps/portal-web/package.json
> +    "recharts": "^2.10.1",
我看mis-web是使用的recharts，需要改吗？

2023-11-23 12:58 UTC, ddadaal commented on apps/portal-web/src/pageComponents/dashboard/InfoPane.tsx
> +  color: #999;
配置是这样的，简单来说就是用antd的theme提供的颜色，不要自己写颜色

2023-11-23 13:02 UTC, ddadaal commented on apps/portal-web/src/pageComponents/dashboard/InfoPanes.tsx
记得改完之后要更新一下PR的描述，贴上最新的效果图。

2023-11-23 13:55 UTC, ddadaal commented on apps/portal-web/package.json
> +    "recharts": "^2.10.1",
mis-web用了recharts吗？我看package.json没有？

2023-11-24 01:41 UTC, OYX-1 commented on apps/portal-web/package.json
> +    "recharts": "^2.10.1",
[feat(mis): 新增数据统计功能](https://github.com/PKUHPC/SCOW/pull/825)
![image](https://github.com/PKUHPC/SCOW/assets/74037789/d5cf47c9-4e28-4b4c-aa08-e65ade090008)
在这个PR里，还没测试

2023-11-24 03:48 UTC, OYX-1 commented
> 这个PR最好把设计图里的顶部的logo以及表格的标题文本加上，不然看着首页很奇怪，用户第一眼看不能一眼反应过来是这些是什么数据

表格标题漏了，已加。
![image](https://github.com/PKUHPC/SCOW/assets/74037789/e8f2ab20-b995-432e-9db1-906a4ed0b46a)
顶部的logo，这个若淼老师和薛老师说去掉呀

2023-11-24 07:17 UTC, OYX-1 commented on apps/portal-web/src/pageComponents/dashboard/InfoPanes.tsx
已更新

2023-11-24 09:21 UTC, ddadaal commented on apps/portal-web/package.json
> +    "recharts": "^2.10.1",
那就用recharts吧。

2023-11-24 09:22 UTC, ddadaal commented
好的，没看到这个评论。按设计图为准。

2023-11-27 12:32 UTC, ddadaal approved these changes

2023-12-13 02:26 UTC, lyl-available commented
这里文字显示有问题了
![image](https://github.com/PKUHPC/SCOW/assets/125553919/7ebe8584-6219-4648-a983-0484b7f81bd5)

2023-12-18 06:40 UTC, lyl-available approved these changes

2023-12-18 09:08 UTC, ddadaal approved these changes

2023-12-18 09:08 UTC, merged