feat: 添加issue模板
PKUHPC/SCOW pull request #997
Opened 2023-11-23 08:28 UTC by lingbozeng

添加issue模板：bug模板和feature模板

2023-11-23 12:44 UTC, ddadaal requested changes

2023-11-23 12:44 UTC, ddadaal commented on .changeset/mighty-hotels-glow.md
这个就没必要加changeset了，和SCOW本身无关的

2023-11-24 02:15 UTC, lingbozeng commented on .changeset/mighty-hotels-glow.md
changeset已撤销

2023-11-24 09:13 UTC, ddadaal approved these changes

2023-11-24 11:29 UTC, merged